abi/fns/vers versioning based on glibc version
ziglang/zig pull request #10036
Opened 2021-10-26 13:20 UTC by mjonaitis1

Fixes: #7667

This PR introduces versioning for symbol mapping files (abi.txt, fns.txt, vers.txt) which are used to generate stub shared libraries when compiling for glibc targets. 

These files are now stored under lib/libc/glibc/symbols/{GLIBC_VERSION} where {GLIBC_VERSION} is the version of glibc. Currently, I have generated these files from glibc 2.23 up to glibc 2.33.

update_glibc tool is also changed in this PR. Now it accepts a third argument - glibc version that will be updated or used to create new directory under lib/libc/glibc/symbols.

2021-11-01 12:44 UTC, Mantelijo commented
@marler8997 @andrewrk so generally, what are your thoughts for this to go through? Should I try to change these files from ASCII to binary format?

2021-11-01 18:05 UTC, marler8997 commented
Status quo seems fine.  An additional change to reduce the uncompressed size using a "sparse format" feel like a "nice to have".

2021-11-01 19:04 UTC, marler8997 commented
Another thing to consider is that if we design a compact binary format for these files, then it would reduce the memory needed to load them.  So we would save:

1. a little space in the released archive
2. a couple megabytes in an installed instance of zig
3. a couple megabytes of RAM when we have to load these files

One question I have is, when does Zig need to load these files?  Is it only when we need to build glibc?

2021-11-01 19:26 UTC, andrewrk commented
> generally, what are your thoughts for this to go through? Should I try to change these files from ASCII to binary format?

It seems likely this change can land unmodified, at first glance it looks great. I haven't given it a full review yet - sorry for the delay. At least I can tell you that I won't tag 0.9.0 before this lands. Deal?

> One question I have is, when does Zig need to load these files? Is it only when we need to build glibc?

Correct!

2021-11-09 01:01 UTC, andrewrk requested changes
Thanks @mjonaitis1 for your patience on getting this reviewed. I finally had a deeper look into this today and I have some guidance on how to get this landed.

As it stands now, this is a nice proof-of-concept that the problem can be fixed, by modeling the data more accurately - taking into account the fact that symbols can migrate between libraries over versions.

However rather than introducing N copies of the data, one for each glibc version, let's rework the data layout in glibc.zig to support encoding this data properly, and likewise rework the encoding of fns.txt, abi.txt, vers.txt to being one dataset that encodes this information rather than being N datasets, one per glibc version.

I have some suggestions for how to go about this:
 * Start a brand new git repository which collects the .abilist files from the entire history of the glibc project (or as far back as it is practical to go). In this new repository, there would be a copy of the data per glibc version checked into the repo, namespaced into directories by version.
 * Move the tools/update_glibc.zig script to this new repository as well. Whenever glibc has an update, we can copy .abilist files into the repository under version directory, and re-run the script to compile the information into our singular dataset, which can be then copied over to the main ziglang/zig repository.
 * Let's switch to a binary encoding of the data and aim for compactness.

Here is some brainstorming on the encoding:

The lists of things that we have:

 * list of glibc versions  (44)
   - we can use u64 bitsets to describe a set of glibc versions.
 * list of glibc libraries  (7)
   - we can use u8 bitsets to describe a set of glibc libraries.
 * list of targets         (20)
   - we can use u32 bitsets to describe a set of targets. E.g. the first 20 bits of the u32 correspond to the list of targets; 12 bits unused.
 * list of glibc symbols (3970)

With that in mind, here is an idea to store the data. The list of glibc libraries is implied.

- list of glibc versions
- list of targets
- for each glibc symbol:
  - null-terminated string name
  - list of inclusions that describes where this symbol can be found. each inclusion is:
    - u32 set of targets that this inclusion applies to
      - use 1 of these bits to tell whether this is the last inclusion in the list
    - u64 set of glibc versions that this inclusion applies to
    - u8 set of glibc libraries that this inclusion applies to

With an average of 1.5 inclusions per symbol (which looks like a conservative estimate), this comes out to 75 KB for the entire dataset ( `13 * 3970 * 1.5`), plus the bytes need to store the symbol names exactly once. I think this will be a worthwhile investment, as this is a great deal smaller than 2.1 MiB, improving not only installation size on disk, but also performance when this data needs to be loaded by the compiler.

2021-11-22 16:38 UTC, mjonaitis1 commented
I have created this new repo here: https://github.com/mjonaitis1/zig-glibc-abilist. Please note that `update_glibc.zig` still has old `abi/fns/vers` functionality - it can be removed later once we are sure about this new encoding. 

Now my question is what is the best approach to integrate this new format reader into zig's `/src/glibc.zig` source? One approach that I am currently trying out is adding `glibc_symbols_reader.zig` from the repo provided above into `/src/glibc_symbols_reader.zig` and loading it in `/src/glibc.zig:loadMetaData`, the structure might need some rework, but this might work.

What are your thoughts?

2021-11-25 02:25 UTC, andrewrk commented
@mjonaitis1 apologies - I only just now saw this update today. Exciting work, I will dedicate my main task slot tomorrow to this.

2021-11-25 02:34 UTC, andrewrk commented
I played with it a little bit-

Looks like the symbols file that gets generated is 102 KB. That's great! Looks like my estimate was off by 25 KB but that's peanuts. Pretty nice that `xz` is able to reduce the size further down to 21 KB.

> One approach that I am currently trying out...

The approach that you outlined here sounds perfectly reasonable to me :+1: 

Thanks for doing this!

2021-11-25 11:51 UTC, mjonaitis1 commented
While I was trying to do a sample implementation in zig's `src/glibc.zig` I encountered an issue: with this new binary format we are losing some important information like what are the default versions for symbol that are available for specific target in specific library. This new binary format with inclusions collects all the information from pre-selected list of glibc versions (at the moment glibc 2.23-2.33), each inclusion is a summed up information of all targets and all versions available for a specific symbol. Now the problem is that a symbol can have different default versions on different targets. 

Example: dlopen symbol. In binary inclusion format, this is the information I have:
```
Symbol: dlopen in libdl
         Available versions: GLIBC_2.0 GLIBC_2.1 GLIBC_2.2 GLIBC_2.2.5 GLIBC_2.3 GLIBC_2.4 GLIBC_2.16 GLIBC_2.17
         Available targets: aarch64-linux-gnu aarch64_be-linux-gnu s390x-linux-gnu arm-linux-gnueabi armeb-linux-gnueabi arm-linux-gnueabihf armeb-linux-gnueabihf sparc-linux-gnu sparcel-linux-gnu sparcv9-linux-gnu mips64el-linux-gnuabi64 mips64-linux-gnuabi64 mips64el-linux-gnuabin32 mips64-linux-gnuabin32 mipsel-linux-gnueabihf mips-linux-gnueabihf mipsel-linux-gnueabi mips-linux-gnueabi x86_64-linux-gnu x86_64-linux-gnux32 i386-linux-gnu powerpc64le-linux-gnu powerpc64-linux-gnu powerpc-linux-gnueabi powerpc-linux-gnueabihf
```
In glibc-2.33 abilist file for libdl `sysdeps/unix/sysv/linux/x86_64/64/libdl.abilist` we have this:
```
GLIBC_2.2.5 dlopen F
```

But in `sysdeps/unix/sysv/linux/aarch64/libdl.abilist` for the same glibc-2.33 we have this:
```
GLIBC_2.17 dlopen F
```
If I target, let's say, glibc-2.17 and x86_64-linux-gnu - zig will build stub libdl with dlopen@GLIBC_2.17 which is actually not available in libdl on x86_64-linux-gnu. But since there is no per symbol per target information - there is no way to tell that. 

I tried to brainstorm a solution ([a8842aa](https://github.com/mjonaitis1/zig-glibc-abilist/commit/a8842aa415299c46d61273d65504d360feddcfce)) for this and I thought about having a "maximum" version for each library for each target. That way I could check which maximum version is available for a specific library for specific target, but this actually does not help as there might be a lot of overlapping versions in library but default versions for symbol might be different. 

So I think the only viable solution would be to actually have as many inclusions for each symbol as there are targets, where each inclusion is a bitset of available versions and library information. But this would drastically increase the symbols file size: `25(targets) x 9(u64bitset for versions  + u8 for lib) * 4100(roughly the number of symbols+duplications where symbol changes library)` which is `~900KB`. However, I am not exactly sure if this is the best approach.

2021-11-26 07:08 UTC, LemonBoy commented
Keep #8896 and #8714 in mind too, there's some more cases that need to be addressed.

2021-12-13 09:24 UTC, andrewrk commented
Closing in favor of  #10330

2021-12-13 09:24 UTC, closed without merging