C backend: implement ?void
ziglang/zig pull request #10071
Opened 2021-10-31 18:49 UTC by rainbowbismuth

Since there is no type in C that can take up zero bytes in a struct, I've implemented "?void" as a simple `bool` instead of something like `typedef struct { bool is_null; } zig_Q_void;` This requires some special casing, but I figure simpler generated code is better.

2021-10-31 19:01 UTC, g-w1 commented
What about generating `?struct {}`, also zero bytes. Maybe instead of checking if it is void, check if the type is zero bytes?

2021-10-31 19:12 UTC, rainbowbismuth commented
Excellent point, I will try that.

2021-10-31 19:55 UTC, rainbowbismuth commented on src/type.zig
> +                if (index == 0) {
I misunderstood what this function does, I think it would be better to change `abiSize()` directly

2021-11-01 18:51 UTC, andrewrk requested changes
Thanks for the patch! I see a couple of cross-compilation bugs that should be trivial to resolve.

2021-11-01 18:51 UTC, andrewrk commented on src/type.zig
> +                return self.structFieldOffset(self.structFieldCount(), target);
Looks like you meant to do this: 

```suggestion
                return self.structFieldOffset(field_count, target);
```

2021-11-01 18:51 UTC, andrewrk commented on src/codegen/c.zig
> +                if (payload_type.abiSize(builtin.target) == 0) {
Be sure to pass in the target that is chosen to build for, not the host target that the compiler is running on! Look for `const target = ` elsewhere in this file. I see other instances of `builtin.target` in this patch too.

2021-11-02 13:59 UTC, rainbowbismuth commented
Thanks for the pointers Andrew :)

2021-11-02 16:45 UTC, merged