add support for compiling Objective-C++ code
ziglang/zig pull request #10096
Opened 2021-11-04 06:57 UTC by slimsag

Prior to this change, calling `step.addCSourceFiles` with Obj-C++ file extensions (`.mm`) would result in an error due to Zig not being aware of that extension. Clang supports an `-ObjC++` compilation mode flag, but it was only possible to use if you violated standards and renamed your `.mm` Obj-C++ files to `.m` (Obj-C) to workaround Zig being unaware of the extension.

This change makes Zig aware of `.mm` files so they can be compiled, enabling compilation of projects such as [Google's Dawn WebGPU implementation](https://dawn.googlesource.com/dawn/) using only a `build.zig` file.

Helps hexops/mach#21

Signed-off-by: Stephen Gutekanst <stephen@hexops.com>

2021-11-04 17:18 UTC, kubkon commented
Wow, cool! Out of curiosity, does ObjC++ link fine with zld?

2021-11-05 04:44 UTC, slimsag commented
@kubkon Yep! So far so good, Dawn has ~5.5k lines of ObjC++ across ~20 files and it links and runs that just fine without complaint. I did run into #10103 but it's not related to ObjC++

2021-11-05 20:02 UTC, kubkon requested changes
The changes look great. I just have one tiny request: would you be able to add some basic standalone tests that are enabled on macOS with SDK present only (we have a flag for that `-Denable-macos-sdk`)? The test would then link against some frameworks or what not, unless you think this is unnecessary.

2021-11-05 20:07 UTC, slimsag commented
I'd be very happy to do that! I dug around a bit and it seems like I would basically need to add a directory [like this one](https://github.com/ziglang/zig/tree/master/test/standalone/link_frameworks) ("standalone test") with something like a hello-world ObjC++ file called from Zig, plus maybe linking a framework in? Does that sound about right?

2021-11-05 20:10 UTC, kubkon commented
> I'd be very happy to do that! I dug around a bit and it seems like I would basically need to add a directory [like this one](https://github.com/ziglang/zig/tree/master/test/standalone/link_frameworks) ("standalone test") with something like a hello-world ObjC++ file called from Zig, plus maybe linking a framework in? Does that sound about right?

Yep, sounds right. And then in `standalone.zig` you can enable it only in the presence of macOS SDK (I don't think the test would make much sense on a different platform).

2021-11-21 04:18 UTC, slimsag commented
@kubkon PTAL - I rebased against `master` and added a standalone test (I based it on the existing `objc` standalone test, just adapted it for ObjC++)

2021-11-21 08:48 UTC, kubkon commented
> @kubkon PTAL - I rebased against `master` and added a standalone test (I based it on the existing `objc` standalone test, just adapted it for ObjC++)

Thanks @slimsag! Just an FYI that in terms of the failing macOS CI, that's my doing and I'll fix ASAP :-)

2021-11-21 20:07 UTC, kubkon commented
@slimsag if you rebase against master, macOS CI should be green again :-)

2021-11-22 03:29 UTC, slimsag commented
Done! 🤞

2021-11-22 07:44 UTC, merged