Added an explicit type for the termios constants
ziglang/zig pull request #10266
Opened 2021-12-03 14:07 UTC by ZapAnton

Adds the `tcflag_t` type to the termios constants.
This is made to allow bitwise operations on the termios
constants without an integer cast, e.g.:

```zig
var raw = try std.os.tcgetattr(std.os.STDIN_FILENO);
raw.lflag &= std.os.linux.ECHO | std.os.linux.ICANON;
```
instead of

```zig
var raw = try std.os.tcgetattr(std.os.STDIN_FILENO);
raw.lflag &= ~@intCast(u32, std.os.linux.ECHO | std.os.linux.ICANON);
```

Contributes to https://github.com/ziglang/zig/issues/10181

2021-12-03 21:07 UTC, andrewrk requested changes
Thanks for the PR. Please search for these symbols in the project; there are other matching definitions for OpenBSD and macOS that also need to be updated.

2021-12-04 08:24 UTC, ZapAnton commented
Done

2021-12-04 08:53 UTC, andrewrk approved these changes

2021-12-04 21:24 UTC, merged

2021-12-04 21:25 UTC, andrewrk commented
Thanks!