stage2: make tests/behaviour/void.zig work with c backend
ziglang/zig pull request #10401
Opened 2021-12-23 18:45 UTC by mattyhall

* fix initialisation of void* fields of structs (initialises to NULL rather than {})
* don't generate fields where the type does not have codegen bits
* in airAlloc generate a void* local if the element type does not have codegen bits

2021-12-24 00:40 UTC, andrewrk commented
the CI failure will be fixed by running `zig fmt` on your changes :)

2021-12-24 14:46 UTC, mattyhall commented
Whoops, thanks! I'm not sure why the new failure has happened unfortunately :(

2021-12-26 21:26 UTC, andrewrk requested changes

2021-12-26 21:26 UTC, andrewrk commented on src/codegen/c.zig
> +                .Pointer => return writer.writeAll("NULL"),
This is supposed to produce a pointer whose address is 0xaa bytes, not 0 bytes.

2021-12-26 21:26 UTC, andrewrk commented on src/codegen/c.zig
> +    }
There should be no local variable allocated in this case. See the `airAlloc` function in the LLVM backend for inspiration.

2021-12-27 22:42 UTC, andrewrk commented
Nice work!

2021-12-27 22:42 UTC, merged