std: expose `ChildProcess`'s `exec` function
ziglang/zig pull request #10436
Opened 2021-12-29 00:37 UTC by nektro

found this as a cleaner solution than exposing `collectOutputPosix` and `collectOutputWindows` separately.

`spawnAndWait` alone does not solve this use case since it does not collect any output

2021-12-30 02:39 UTC, daurnimator commented
If we're renaming this method, can we please move away from "exec" as a name? It suggests that the current process will be replaced.

See https://github.com/ziglang/zig/issues/5853

2021-12-30 02:59 UTC, nektro commented
what name should be used instead? i dont see any consensus.

fwiw i also disagree with the premise of the issue. exec is simply short for execute. perhaps run would be better?

2021-12-30 03:02 UTC, daurnimator commented
> what name should be used instead?

I think `spawn` seems the best suggestion in there; and it has precedence via e.g. `posix_spawn` in C.

2021-12-30 03:10 UTC, nektro commented
`spawn` is already a method and does something different

2022-05-11 02:24 UTC, andrewrk requested changes
I agree with @daurnimator - this is a breaking change to rename a function which has an accepted proposal to avoid "exec" as the name, so the breaking change should follow this guidance.

Also, this is a breaking change that I'm not sure what the motivation is. Can I see an example of what didn't work very well without this breaking change?

2022-05-26 22:41 UTC, closed without merging