Add tests for std.Thread.Condition and std.Thread.Semaphore
ziglang/zig pull request #10728
Opened 2022-01-29 19:42 UTC by naeu

Fixes #10636

2022-01-29 19:48 UTC, ominitay requested changes

2022-01-29 19:48 UTC, ominitay commented on lib/std/Thread/Condition.zig
> +    }
```suggestion
test "Thread.Condition" {
    if (builtin.single_threaded) {
        return error.ZigSkipTest;
    }
```

2022-01-29 19:48 UTC, ominitay commented on lib/std/Thread/Semaphore.zig
> +    }
```suggestion
test "Thread.Semaphore" {
    if (builtin.single_threaded) {
        return error.ZigSkipTest;
    }
```

2022-01-29 20:28 UTC, ominitay commented
Apologies, should have been `SkipZigTest`, I shuffle words a lot

2022-01-29 20:32 UTC, naeu commented
No worries, updated.

2022-01-30 10:00 UTC, merged

2022-01-30 12:42 UTC, ominitay commented
Congrats on your first contribution :)

2022-02-03 17:40 UTC, naeu commented
In case it's worth fixing, [there's a branch](https://github.com/naeu/zig/commits/thread-test-fix) to make these tests more robust and avoid spurious wakes in the condition test.