Add compiler-rt functions for f80
ziglang/zig pull request #10738
Opened 2022-01-31 00:09 UTC by Vexu

No tests but I have fuzzed them against hw a bit, might not work correctly for big-endian, and forcing f80 to be 16 bytes on x86 also seems to have some issues.

2022-01-31 10:08 UTC, matu3ba requested changes
structure looks good, but I havent looked into the logical details of impl yet as this is still marked as draft.

mostly nits on some missing explanations and mask stuff (easy to introduce typos)

2022-01-31 10:08 UTC, matu3ba commented on lib/std/math.zig
> +    _pad: u32 = undefined,
It would be nice, if somewhere the device specific behavior could be linked.

2022-01-31 10:13 UTC, matu3ba commented
I think you can test this in a more structured manner with [the table from wikipedia](https://en.wikipedia.org/wiki/Extended_precision#x86_extended_precision_format). For the trunc stuff the musl libc tests are usually a great source, but in this case you could just use the test cases for Softfloat: http://www.jhauser.us/arithmetic/TestFloat.html

2022-02-04 19:57 UTC, Vexu commented
> What's the merge checklist?

For little-endian non-i386 I just need to double check the `normalize_f80` function and address matu3ba's review.
The i386 issues are caused by stage1 using `LLVMABISizeOfType`/`LLVMABIAlignmentOfType` instead of `type->abi_size`/`type->abi_align` which causes mismatches in `get_llvm_type` when `f80` is used in a struct.

For big-endian rendering literals is still broken but that shouldn't block this.

And it wouldn't hurt to add some tests, I'll try generating some based on x86 hw implementation.

2022-02-04 19:59 UTC, Vexu commented on lib/std/special/compiler_rt/compareXf2.zig
> +    return __lexf2(a, b);
This is just to match the other `__neXf2` functions, the caller is supposed to compare the result to `0`.

2022-02-04 19:59 UTC, Vexu commented on lib/std/special/compiler_rt/compareXf2.zig
> +    return __lexf2(a, b);
Same as the other.

2022-02-04 20:02 UTC, Vexu commented on lib/std/special/compiler_rt/compareXf2.zig
> +    // If either a or b is NaN, they are unordered.
It is referencing NaN comparisons which are always unordered.
```
NaN != NaN == true
NaN == NaN == false
NaN > NaN == false
NaN >= NaN == false
NaN < NaN == false
NaN <= NaN == false
```

2022-02-04 20:05 UTC, Vexu commented on lib/std/special/compiler_rt/compareXf2.zig
> +    if (@boolToInt(a_rep.exp == b_rep.exp) & @boolToInt(a_rep.fraction == b_rep.fraction) != 0) {
This function is supposed to match hardware which compares bit for bit equality.

2022-02-04 20:12 UTC, Vexu commented on lib/std/special/compiler_rt/trunc_f80.zig
> +            // Round to nearest
Not sure, copied it from the `truncXfYf2` function.

2022-02-06 01:57 UTC, merged