stage 1: improve error message if error union is cast to payload
ziglang/zig pull request #10770
Opened 2022-02-02 20:20 UTC by SebastianKeller

kristoff-it mentioned that this error message could be improved.
Most often the code is missing a 'try'. The error message should reflect that.

before:

```
./src/main.zig:6:24: error: expected type '[]const u8', found '@typeInfo(@typeInfo(@TypeOf(getValue)).Fn.return_type.?).ErrorUnion.error_set![]const u8'
    printValue(getValue());
```
after:

```
./src/main.zig:6:24: error: Can not convert error union to payload type. Missing 'try'?
Expected type '[]const u8', found '@typeInfo(@typeInfo(@TypeOf(getValue)).Fn.return_type.?).ErrorUnion.error_set![]const u8'
    printValue(getValue());
```

code
```zig
const std = @import("std");
var gpa = std.heap.GeneralPurposeAllocator(.{}){};

pub fn main() anyerror!void {
    printValue(getValue());
}

fn printValue(str: []const u8) void {
    std.debug.print("{s}", .{str});
}

fn getValue() ![]const u8 {
    return try gpa.allocator().dupe(u8, "test");
}
```

2022-02-04 19:39 UTC, Vexu requested changes
Needs a test case in `test/compile_errors.zig` so that it isn't forgotten in stage2.

Adding a similar error for `?T to T` should also be pretty simple with `consider using '.?', 'orelse' or 'if'` as the hint.

2022-02-04 19:39 UTC, Vexu commented on src/stage1/ir.cpp
> +                buf_sprintf("Can not convert error union to payload type. Missing 'try'?\nExpected type '%s', found '%s'",
```suggestion
                buf_sprintf("cannot convert error union to payload type. consider using `try`, `catch`, or `if`. expected type '%s', found '%s'",
```
No newlines in error messages, we should probably have a separate hint message type for suggestions but that can be an improvement in stage2.

2022-02-05 23:57 UTC, SebastianKeller commented
Hi Vexu, thanks for the feedback! I've changed the message, added the `?T -> T` case and updated the `compile_errors.zig`.

2022-02-07 09:40 UTC, Vexu approved these changes

2022-02-10 01:35 UTC, merged