[std.mem] bytesAsValue for byte-aligned packed structs
ziglang/zig pull request #10941
Opened 2022-02-20 11:24 UTC by motiejus

Currently `bytesAsValue` works with only word-aligned structs;
technically, when `@sizeOf(T) == @divExact(@bitSizeOf(T))`.

This diff makes it possible to use non-word-aligned packed structs with
`bytesAsValue`, though still requires them to be byte-aligned
(non-byte-aligned packed structs may be the next step).

2022-02-20 14:11 UTC, motiejus commented
re. drone-ci failures: this command seems to have worked for me:

```
$ ./build/zig build -Dtarget=arm-linux-musleabihf
<...>
$ file zig-out/bin/zig
zig-out/bin/zig: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, with debug_info, not stripped
$ 
```

2022-02-20 14:23 UTC, Vexu commented
The test you added passes without changing the `@sizeOf`, do you have a test case that doesn't currently pass?

> re. drone-ci failures: this command seems to have worked for me:

It is caused by a broken commit in master, don't know why the CI is using master instead of your branch.

2022-02-20 14:43 UTC, motiejus commented
> The test you added passes without changing the `@sizeOf`, do you have a test case that doesn't currently pass?

This is a mixup, thanks for noticing. Will do so likely tomorrow.

2022-02-20 22:23 UTC, motiejus commented
> > The test you added passes without changing the `@sizeOf`, do you have a test case that doesn't currently pass?
> 
> This is a mixup, thanks for noticing. Will do so likely tomorrow.

Updated. It wasn't easy to find a packed struct that satisfies the assertion; I would love to learn more about ([in `@sizeOf` docs](https://ziglang.org/documentation/master/#sizeOf)) though:

```
This size may contain padding bytes. 
```

2022-02-21 10:25 UTC, motiejus commented
Changing `asBytes` to assume byte-aligned data fails to compile stage1, as there are some non-byte-aligned structs. So `asBytes` cannot be changed as-is. I also spent an hour or so mirroring the change to `asBytes`, to no avail.

I will leave this PR to `bytesAsValue` alone and file an issue for `asBytes` to discuss it further.

2022-05-11 21:22 UTC, andrewrk requested changes

2022-05-11 21:22 UTC, andrewrk commented on lib/std/mem.zig
> +test "bytesAsValue works with non-word-aligned structs" {
Please use a different word than "word" which is ambiguous.

2022-05-11 21:22 UTC, andrewrk commented on lib/std/mem.zig
> +    assert(@sizeOf(padded) != @divExact(@bitSizeOf(padded), 8));
This assertion trips on latest master:

```
$ ./stage1/bin/zig test test.zig 
Test [1/1] test "example"... thread 2925231 panic: reached unreachable code
/home/andy/Downloads/zig/lib/std/debug.zig:260:14: 0x206aab in std.debug.assert (test)
    if (!ok) unreachable; // assertion failure
             ^
/home/andy/Downloads/zig/build-release/test.zig:7:11: 0x2076de in test "example" (test)
    assert(@sizeOf(padded) != @divExact(@bitSizeOf(padded), 8));
          ^
```

2022-05-11 21:22 UTC, andrewrk commented on lib/std/mem.zig
> +    _ = bytesAsValue(padded, &[3]u8{ 0, 0, 0 });
The test should write through the pointer and then observe an expected outcome

2022-05-12 02:14 UTC, motiejus commented
I think I no longer want to do this, because:
- we cannot make a symmetric change to `asBytes` (most importantly).
- this is only for stage1 (at the time I did not test stage2).
- I am adding the assertion to my packed structs: `@sizeOf(S) * 8 == @bitSizeOf(S)` and life is easy.

2022-05-12 02:14 UTC, closed without merging