stage2: peer type resolution *[N]T and *[M]T to []const T
ziglang/zig pull request #10973
Opened 2022-02-22 21:37 UTC by mitchellh

This makes the given test pass without causing any additional tests to fail.

This doesn't cause any existing behavior tests to fail, but I think there are still some more complex peer resolution cases that this isn't 100% correct for that future skipped behavior tests will keep ironing out. Still, this moves the needle forward.

2022-02-22 21:59 UTC, mitchellh commented
If this looks good I'll prob keep plugging away at peer type resolution bugs.

2022-02-22 22:30 UTC, mitchellh commented on src/Sema.zig
> +        return Type.ptr(sema.arena, info.data);
My other idea for this was to add a `toConstSlice` function to `Type` which would basically do this.

2022-02-23 12:24 UTC, Vexu requested changes

2022-02-23 16:10 UTC, mitchellh commented on src/Sema.zig
> +        info.data.mutable = false;
Oops, I had a todo for this. Yes, I’m missing the `make_slice_const` logic that stage1 has. I’ll fix this.

2022-02-23 16:41 UTC, Vexu approved these changes

2022-02-24 06:50 UTC, merged