stage2: Do not strip by default for wasm
ziglang/zig pull request #11456
Opened 2022-04-17 16:42 UTC by Luukdegram

For wasm, we do not wish to strip by default, as it also strips away useful sections such as the 'name' section. This section provides functions with names, which can be used during debugging. Other tools also use this information to generate code (such as WAT).
DWARF info is out-of-scope for this PR, so we do strip debug info by default for wasm still.

Fixes #11420

2022-04-17 22:11 UTC, andrewrk requested changes
I'm a bit concerned with the changed definition of the meaning of `strip` with this change - I think `strip` should continue to mean "there is no debug info and no symbol table" and the `hasDebugInfo` function should continue to mean "there is no point to ever turning off strip for this target".

Perhaps this could be solved by adding exceptions for WebAssembly specifically rather than changing the meaning of `strip`? i think `hasDebugInfo` should return `true` for WebAssembly since `strip` will destroy some useful debug information (the name section).

2022-04-17 22:38 UTC, Luukdegram commented
> I'm a bit concerned with the changed definition of the meaning of `strip` with this change - I think `strip` should continue to mean "there is no debug info and no symbol table" and the `hasDebugInfo` function should continue to mean "there is no point to ever turning off strip for this target".
> 
> Perhaps this could be solved by adding exceptions for WebAssembly specifically rather than changing the meaning of `strip`? i think `hasDebugInfo` should return `true` for WebAssembly since `strip` will destroy some useful debug information (the name section).

I’m not convinced this changes the definition of `strip`. Passing the strip flag will correctly remove the symbol table (as well as debug info) for Wasm now, where previously it was always being removed as `strip` was always set to true when targeting Wasm. I do, however, agree that `hasDebugInfo` should return true for Wasm, but that pulls in std.debug which hasn’t implemented anything for Wasm just yet. I figured that would be a better fit for a seperate PR. (But perhaps they’re too dependent on eachother). 

Would you mind specifying on what we could apply the exceptions for Wasm?

2022-04-17 22:45 UTC, andrewrk commented
> but that pulls in std.debug which hasn’t implemented anything for Wasm just yet

This is where I suggest to make the exception for Wasm - in the std.debug code next to where it checks strip.

2022-04-17 22:46 UTC, Luukdegram commented
> > but that pulls in std.debug which hasn’t implemented anything for Wasm just yet
> 
> 
> 
> This is where I suggest to make the exception for Wasm - in the std.debug code next to where it checks strip.

Gotcha, let's go with that! Thanks for the input.

2022-04-18 11:32 UTC, Luukdegram commented
Superseded by #11461

2022-04-18 11:32 UTC, closed without merging