fixing unintended behaviour for #11455
ziglang/zig pull request #11459
Opened 2022-04-18 08:41 UTC by OfekShochat

2022-04-18 11:17 UTC, luehmann commented
Hi @OfekShochat, I think it would make sense to add tests for this. You can take a look the pull-request I opened before I saw yours.

2022-04-18 13:10 UTC, OfekShochat commented
Ok will do! Busy right now though, might take some time

2022-04-22 14:38 UTC, daurnimator requested changes
Make sure you add a test case of a key that needs escaping in json.

2022-04-22 14:38 UTC, daurnimator commented on lib/std/json.zig
> +                    try out_stream.writeAll(Field.name);
This is not correct; it may need escaping.

2022-05-16 22:09 UTC, andrewrk commented
* CI tests failing
 * Conflicts with master branch
 * No activity for 28 days

Please open a fresh PR if you would like to continue this effort.

2022-05-16 22:09 UTC, closed without merging