Sema: Fix array concatenation at comptime
ziglang/zig pull request #11512
Opened 2022-04-24 13:35 UTC by sin-ack

This allows the following code to now compile properly:

```zig
export fn _start() void {
    _ = doTheTest("bar");
}

fn doTheTest(comptime s: [*:0]const u8) [*:0]const u8 {
        return "foo" ++ s;
}
```

2022-04-28 15:26 UTC, Vexu approved these changes
Could you add a behavior test for this?

2022-04-29 03:44 UTC, andrewrk requested changes
Behavior test please!

2022-04-29 03:44 UTC, andrewrk commented on src/Sema.zig
> +            const rhs_single_ptr = rhs_ty.zigTypeTag() == .Pointer and rhs_ty.isSinglePointer();
```suggestion
            const lhs_single_ptr = lhs_ty.isSinglePointer();
            const rhs_single_ptr = rhs_ty.isSinglePointer();
```

2022-04-29 23:13 UTC, sin-ack commented
Behavior test added.

2022-04-29 23:19 UTC, andrewrk approved these changes
Thanks for the behavior test!

2022-04-30 02:53 UTC, merged