compiler_rt: Move mem implementations from c.zig
ziglang/zig pull request #11747
Opened 2022-05-28 13:46 UTC by Luukdegram

This moves functions that LLVM generates calls to, to the compiler_rt implementation itself, rather than c.zig.
This is a prerequisite for native backends to link with compiler-rt and also allows native backends to generate calls to `memcpy` and the like.

2022-05-28 18:57 UTC, andrewrk approved these changes

2022-05-29 17:08 UTC, Luukdegram commented
Converting to Draft as this seems to cause some OOM issues in our own CI (zinc).

2022-05-30 18:11 UTC, Luukdegram commented
From my local testing, it seems to OOM when we're targetting Linux-musl. Will do more research on why that could happen. Considering the exports are weak, they should simply get resolved to musl's versions.

2022-06-20 12:32 UTC, kubkon requested changes

2022-06-20 14:01 UTC, Luukdegram commented on lib/compiler_rt/mem.zig
> +        @export(memset, .{ .name = "memset", .linkage = common.linkage });
Good call, will do this once this PR actually works :)

2022-09-01 02:53 UTC, andrewrk commented
Rather than OOM, it looks like the CI hit the 4 hour time limit. Perhaps did these changes result in and endless loop happening somewhere?

2022-09-01 04:52 UTC, Luukdegram commented
> Rather than OOM, it looks like the CI hit the 4 hour time limit. Perhaps did these changes result in and endless loop happening somewhere?
> 
> Also I'm marking this as ready-for-review because the only blocker is CI tests passing, correct?

My bad, I forgot to update this PR after I had done more investigation.
Locally compiling tests for each MIPS target in the testing matrix seems to take an additional 10 mins compared to master, but they do indeed eventually finish (and pass the tests). This does feel like there's some looping going on. Unfortunately, I haven't been able to figure out yet where this happens and more importantly, prevent it from happening.

2022-09-18 19:46 UTC, andrewrk commented
@Luukdegram could you please rebase this on latest master?

2022-09-21 09:08 UTC, Luukdegram commented
Rebased and seems it passes all tests. Though, it did seem to increase CI time compared to the few successful CI runs after the latest run of this PR. I suppose we want to investigate that further before merging.

2022-09-21 17:05 UTC, andrewrk commented
I wouldn't use CI time as a metric for performance. It can be affected by many things such as how many jobs are running simultaneously. If a performance issue is suspected, better to measure directly.

2022-09-21 17:33 UTC, andrewrk requested changes
Let's put compiler-rt on the linker line only once. This PR makes it on the linker line twice. Was that intentional, @kubkon?

2022-09-21 17:39 UTC, kubkon commented
> Let's put compiler-rt on the linker line only once. This PR makes it on the linker line twice. Was that intentional, @kubkon?

Not at all. No idea as to why this happened. We should delete the second commit.

2022-09-21 17:39 UTC, Luukdegram commented
> Let's put compiler-rt on the linker line only once. This PR makes it on the linker line twice. Was that intentional, @kubkon?

We tried that to see what the impact would be. I however reverted that in 423560c. Admittedly, the commit message should've included that.

2022-09-21 18:10 UTC, Luukdegram commented
I went ahead and cleaned up the commits.

2022-09-21 18:11 UTC, andrewrk commented
So did you test this combination?
* Compiler-rt on the linker line only once
* Compiler-rt in the adjusted location (towards the end)

2022-09-21 18:13 UTC, kubkon commented
> So did you test this combination?
> 
>     * Compiler-rt on the linker line only once
> 
>     * Compiler-rt in the adjusted location (towards the end)

compiler-rt before or after libc will have an impact on the final produced artifact btw. Depending on which one goes first, we might use a symbol from either compiler-rt or libc for some primitive like `memcpy`.

2022-09-21 18:54 UTC, andrewrk commented
The intention is that zig provides compiler-rt as "low priority" symbols. Any symbols explicitly provided by the user, or the system libc, should override.

2022-09-21 19:27 UTC, Luukdegram commented
This PR holds true to that intention. As we define the symbols as weak, the user can explicitly override the symbols by providing strong ones instead. When linked with libc, the compiler-rt symbols do not overwrite the libc symbols as libc is on the linker line first (both status quo, and after this PR) and weak symbols do not overwrite other weak symbols.

2022-09-21 19:33 UTC, kubkon commented
This is true up to the user defining competing symbols as strong. Otherwise, we have competition of libc vs compiler-rt or other library on our hands, so we probably should strive to put `libcompiler_rt.a` after every other static lib.

2022-09-21 19:33 UTC, kubkon commented
Anyhow, unless you want to try it out in this PR, I'd handle this separately in another PR.

2022-10-17 22:12 UTC, merged