Correct the init function to use initLocked() for initializing std.event.Lock.
ziglang/zig pull request #11953
Opened 2022-06-28 18:27 UTC by kaihlavirta

#### Fixes issue #11924 
#### init funcion used init() to initialize a std.event.Lock. std.event.Lock does not have init() function. Corrected to initLocked().

2022-06-29 12:05 UTC, Vexu requested changes

2022-06-29 12:05 UTC, Vexu commented on lib/std/event/group.zig
> +                .lock = Lock.initLocked(),
Looking at the commit which caused this a31d9f92f282a878836a3ecac5a48d5f4037868c, the lock is supposed to be initiated in an unlocked state:
```suggestion
                .lock = .{},
```

Also, could you apply the same change to `std.event.Locked` as mentioned in the issue?

2022-06-30 20:25 UTC, kaihlavirta commented
Updated :
* lib/std/event/group.zig
* lib/std/event/locked.zig

to use `.lock = .{}` instead of `.lock = Lock.init()` or `.lock = Lock.initLocked()`

2022-06-30 21:09 UTC, merged

2022-07-01 10:51 UTC, haolian9 commented
should tests in [here](https://github.com/kaihlavirta/zig/blob/6b260f7968c21edad80f67b38441bb2d174ec29f/lib/std/event/group.zig#L125) be enabled?

2022-07-01 11:20 UTC, Vexu commented
They could be enabled if they were fixed but evented IO is not being tested in the CI currently due to stage1 memory usage.