fix error message importing file starting with module root path
ziglang/zig pull request #11976
Opened 2022-07-01 10:22 UTC by LordMZTE

closes #9537

2022-07-01 12:02 UTC, Vexu requested changes
This logic was directly ported from stage1, have you checked whether this happens with it?

2022-07-01 12:02 UTC, Vexu commented on src/Module.zig
> +        mem.indexOfAny(u8, &.{resolved_path[resolved_root_path.len]}, "/\\") == null)
```suggestion
        std.fs.path.isSep(resolved_path[resolved_root_path.len]))
```

2022-07-01 13:12 UTC, LordMZTE commented
Doesn't seem to happen in stage1, but I didn't really debug it in stage1. Maybe there's something missing in my attempt to reproduce this.

2022-07-17 13:12 UTC, LordMZTE commented
Hmm, I'm not sure why, but for some reason, the code to reproduce this compiles just fine on my branch. I doubt that this is caused by my changes though.

2022-07-17 18:01 UTC, kcbanner commented
I wonder if it's OS related? I have only tried my repro steps from #9537 on Windows, I'm not sure which OS you are testing with

2022-07-17 18:23 UTC, LordMZTE commented
Sorry, I should've clarified that I can reproduce this on master. I'm just very confused why my changes would make the code compile, so my guess is that my branch might be based off of an old revision of the master branch where this was broken for some reason.

2022-07-27 15:17 UTC, merged