Implement EmulationableRunStep for linker tests
ziglang/zig pull request #12059
Opened 2022-07-09 15:51 UTC by Luukdegram

Implements a new step that can run and compare the output for foreign binaries that will be run through emulation when enabled (or directly on the host when non-foreign binary). When disabled, it will skip running the binary and produce a warning instead. Said warning can be hidden by either setting the option manually in `build.zig` on the step, or passing `-Dhide-foreign-warnings`. This option is automatically added when creating the step.

The main goal of this step is to help us test the various linkers and we want to run it for multiple targets. This is especially useful when cross-compiling for ELF and MachO as they support more than a single architecture. For this reason, a handy function was appended to `CheckObjectStep` called `runAndCompare` that will automatically create this step and provide the artifact that was used for the original step. 

This PR does not yet update all the current linker tests to use this new step.

2022-07-10 07:54 UTC, kubkon requested changes
I will review the actual code more thoroughly later, but two things that immediately come to mind: 1) would you mind enabling linker tests in the Linux CI now, and 2) could you remove the if-macos check from `test/link.zig` so that we run MachO tests regardless of the host?

2022-07-10 08:58 UTC, rohlem commented
Minor non-functional bikeshedding, I think "[emulatable](https://en.wiktionary.org/wiki/emulatable)" is a more common term.

2022-07-10 12:52 UTC, Luukdegram commented
> Minor non-functional bikeshedding, I think "[emulatable](https://en.wiktionary.org/wiki/emulatable)" is a more common term.

Good call, thanks!

2022-07-12 13:01 UTC, kubkon requested changes
Looks great, thanks @Luukdegram! I have only one suggested change. However, for the future, I was thinking maybe we could somehow re-use the code between `RunStep` and `EmulatableRunStep` since there's a lot of overlap.

2022-07-12 16:16 UTC, Luukdegram commented
> Looks great, thanks @Luukdegram! I have only one suggested change. However, for the future, I was thinking maybe we could somehow re-use the code between `RunStep` and `EmulatableRunStep` since there's a lot of overlap.

Rather than waiting for the future, I went ahead and changed the logic to share the overlapping parts of the steps.

2022-07-24 18:55 UTC, kubkon approved these changes
LGTM!

2022-07-25 04:33 UTC, merged