compiler_rt: Update Windows ABI for float<->int conversion routines
ziglang/zig pull request #12071
Opened 2022-07-10 17:01 UTC by topolarity

Resolves #12063

Starting with LLVM 14, the Libcalls to these functions are now lowered using a `Vector(2, u64)` instead of the standard ABI for i128 integers on Windows, so our compiler-rt implementation needs to be updated to expose the same ABI

Relevant LLVM revision: https://reviews.llvm.org/D110413

2022-07-10 19:43 UTC, andrewrk commented
Great work - really appreciate your help with the LLVM stuff lately :pray:

2022-07-10 19:53 UTC, andrewrk requested changes
I believe the failure is due to codegen/llvm.zig emitting explicit calls to compiler_rt functions in the cases where LLVM will fail to properly do so - meaning that this function signature must be adjusted in codegen.cpp and codegen/llvm.zig to match.

Are you up for those changes too? Let me know if you want some help.

2022-07-10 19:53 UTC, andrewrk commented on lib/compiler_rt/fixdfti.zig
> +const v128 = @import("std").meta.Vector(2, u64);
```suggestion
const v128 = @Vector(2, u64);
```

2022-07-10 19:53 UTC, andrewrk commented on lib/compiler_rt/fixdfti.zig
> +    @export(fixdfti_fn, .{ .name = "__fixdfti", .linkage = common.linkage });
Suggest to follow the pattern of `want_aeabi `, `want_ppc_abi `, `gnu_f16_abi ` and make it look like this:

```suggestion
    if (common.windows_i128_abi) {
        @export(__fixdfti_windows_x86_64, .{ .name = "__fixdfti", .linkage = common.linkage });
    } else {
        @export(__fixdfti, .{ .name = "__fixdfti", .linkage = common.linkage });
    }
```

The comment body can go into the doc comments for `windows_i128_abi` in common.zig.

2022-07-10 20:26 UTC, topolarity commented
> Great work - really appreciate your help with the LLVM stuff lately 🙏

Happy to lend a hand! These are fun bugs to chase for now 🐞

2022-07-10 20:27 UTC, topolarity commented
> I believe the failure is due to codegen/llvm.zig emitting explicit calls to compiler_rt functions in the cases where LLVM will fail to properly do so - meaning that this function signature must be adjusted in codegen.cpp and codegen/llvm.zig to match.

Very good point - should have thought of our explicitly-lowered calls.

Let me take a stab and see how far I can get. I'll reach out if it gets hairy.

2022-07-11 01:15 UTC, andrewrk approved these changes

2022-07-11 03:53 UTC, merged