CMake: Improve usage of `llvm-config` (esp. for consistent static/shared linking)
ziglang/zig pull request #12136
Opened 2022-07-16 02:01 UTC by topolarity

This commit reworks the LLVM/Clang/LLD discovery process for CMake.

The biggest changes are that:
  1. We search for `llvm-config` from most preferred directory to least, skipping any candidate that is the wrong version, or that doesn't support the requested link mode ("static" or "shared")
  2. `-DZIG_PREFER_CLANG_CPP_DYLIB` has been renamed to `-DZIG_SHARED_LLVM`, to better align with `-DZIG_STATIC_LLVM`.
  3. We only search for LLVM and LLD in the same directory where LLVM was located.
  4. We use `llvm-config` to find include directories
  5. LLVM's link mode is forwarded to Clang, so that they are both linked either statically or dynamically
  6. We use `--static-libs` when querying `--system-libs` from llvm-config, so that this will include libz and other dependencies for statically linking LLD
 
I believe (6) may resolve #12069

2022-07-16 02:04 UTC, topolarity commented
IIUC, `-DZIG_PREFER_CLANG_CPP_DYLIB` is used for Homebrew, so let me know if we need to keep the old name to avoid thrash for users

2022-07-16 02:44 UTC, topolarity commented
Any extra steps I need to take to make sure this doesn't break zig-bootstrap? Or will the CI already cover that?

2022-07-16 07:14 UTC, BratishkaErik commented
I have only shared libraries, and before bc1c5e222f1d43c04123567d7f88b18415163e16 it worked fine.
`cmake -DZIG_SHARED_LLVM=true ..`
Output:
```-- The C compiler identification is GNU 11.3.0
-- The CXX compiler identification is GNU 11.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring zig version 0.10.0-dev.3013+e867127a6
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMBinaryFormat.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMBitstreamReader.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMRemarks.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMCore.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMBitReader.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMDebugInfoCodeView.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMMC.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMMCParser.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMTextAPI.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMObject.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMDebugInfoDWARF.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMProfileData.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMAnalysis.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMBitWriter.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMTransformUtils.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMAggressiveInstCombine.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMInstCombine.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMScalarOpts.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMTarget.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMFuzzMutate.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMFileCheck.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMInterfaceStub.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMAsmParser.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMIRReader.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMCodeGen.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMSelectionDAG.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMDebugInfoMSF.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMAsmPrinter.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMMIRParser.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMGlobalISel.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMDWARFLinker.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMExtensions.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMFrontendOpenACC.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMFrontendOpenMP.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMInstrumentation.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMLinker.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMVectorize.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMipo.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMObjCARCOpts.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMCoroutines.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMCFGuard.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMPasses.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMLTO.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMMCDisassembler.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMMCA.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMObjectYAML.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMOption.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMDebugInfoGSYM.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMDebugInfoPDB.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMSymbolize.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMDWP.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMOrcShared.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMOrcTargetProcess.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMRuntimeDyld.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMExecutionEngine.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMInterpreter.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMJITLink.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMMCJIT.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMOrcJIT.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMXCoreInfo.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMXCoreDesc.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMXCoreCodeGen.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMXCoreDisassembler.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMAVRInfo.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMAVRDesc.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMAVRCodeGen.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMAVRAsmParser.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMAVRDisassembler.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMWebAssemblyInfo.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMWebAssemblyUtils.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMWebAssemblyDesc.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMWebAssemblyCodeGen.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMWebAssemblyAsmParser.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMWebAssemblyDisassembler.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMSystemZInfo.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMSystemZDesc.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMSystemZCodeGen.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMSystemZAsmParser.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMSystemZDisassembler.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMRISCVInfo.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMRISCVDesc.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMRISCVCodeGen.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMRISCVAsmParser.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMRISCVDisassembler.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMSparcInfo.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMSparcDesc.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMSparcCodeGen.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMSparcAsmParser.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMSparcDisassembler.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMAArch64Info.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMAArch64Utils.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMAArch64Desc.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMAArch64CodeGen.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMAArch64AsmParser.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMAArch64Disassembler.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMMSP430Info.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMMSP430Desc.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMMSP430CodeGen.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMMSP430AsmParser.a
llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMMSP [...]

2022-07-16 07:18 UTC, topolarity commented
Thanks for the report. I'll look into it.

Can you also share the output before this change, for comparison?

2022-07-16 07:23 UTC, BratishkaErik commented
> Thanks for the report. I'll look into it.
> 
> Can you also share the output before this change, for comparison?

`cmake -DZIG_PREFER_CLANG_CPP_DYLIB=true ..`
Output:
```
-- The C compiler identification is GNU 11.3.0
-- The CXX compiler identification is GNU 11.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring zig version 0.10.0-dev.3013+e867127a6
-- Found llvm: /usr/lib/llvm/14/lib64/libLLVM-14.so (Required is at least version "14")
-- Found clang: /usr/lib/llvm/14/lib64/libclang-cpp.so (Required is at least version "14")
-- Found lld: /usr/lib64/liblldMinGW.so;/usr/lib64/liblldELF.so;/usr/lib64/liblldCOFF.so;/usr/lib64/liblldWasm.so;/usr/lib64/liblldMachO.so;/usr/lib64/liblldCommon.so (Required is at least version "14")
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Configuring done
-- Generating done
-- Build files have been written to: /home/bratishkaerik/zig/build
```

2022-07-16 10:14 UTC, kamidev commented
I tried this on M1 Mac and successfully built stage1 and stage2 without the zlib-workaround. Behavior tests worked as well.

However, building stage3 currently crashes. This started to happen on master too, today. So it may be unrelated.

2022-07-16 10:49 UTC, BratishkaErik commented
> I tried this on M1 Mac and successfully built stage1 and stage2 without the zlib-workaround. Behaviour tests worked as well.
> 
> However, building stage3 currently crashes. This started to happen on master too, today. So it may be unrelated.

Do you mean https://github.com/ziglang/zig/issues/12069? IDK how but I can build stage1 without this workaround (both static and shared zlib installed) (IIUC llvm-config can't choose between static and shared form on affected systems?)

2022-07-16 13:36 UTC, kamidev commented
> > I tried this on M1 Mac and successfully built stage1 and stage2 without the zlib-workaround. Behaviour tests worked as well.
> > However, building stage3 currently crashes. This started to happen on master too, today. So it may be unrelated.
> 
> Do you mean #12069? IDK how but I can build stage1 without this workaround (both static and shared zlib installed) (IIUC llvm-config can't choose between static and shared form on affected systems?)

Yes, #12069. Interesting! I had this problem on ARM Mac and Intel Mac, other people reported it on Arch Linux and NixOS. What are you running?

2022-07-16 13:45 UTC, BratishkaErik commented
> > > I tried this on M1 Mac and successfully built stage1 and stage2 without the zlib-workaround. Behaviour tests worked as well.
> > > However, building stage3 currently crashes. This started to happen on master too, today. So it may be unrelated.
> > 
> > Do you mean #12069? IDK how but I can build stage1 without this workaround (both static and shared zlib installed) (IIUC llvm-config can't choose between static and shared form on affected systems?)
> 
> Yes, #12069. Interesting! I had this problem on ARM Mac and Intel Mac, other people reported it on Arch Linux and NixOS. What are you running?
> 
> 

Gentoo Linux, tried https://packages.gentoo.org/packages/sys-libs/zlib (shared library) with `static-libs` flag disabled and enabled (i.e without and with static library), in second case (both shared and static) — with and without -DZIG_STATIC_ZLIB=On

2022-07-16 14:43 UTC, topolarity commented
> I tried this on M1 Mac and successfully built stage1 and stage2 without the zlib-workaround. Behaviour tests worked as well.
> 
> However, building stage3 currently crashes. This started to happen on master too, today. So it may be unrelated.

The stage 3 problems may be related to https://github.com/ziglang/zig/pull/12133. I have to rework that PR a bit, but it'd be helpful to know if it makes any difference for you as-is

2022-07-16 15:39 UTC, BratishkaErik commented
`cmake ..`: works fine
`cmake -DZIG_SHARED_LLVM=On ..`: works fine
`cmake -DZIG_STATIC_LLVM=On ..`:
```
-- The C compiler identification is GNU 11.3.0
-- The CXX compiler identification is GNU 11.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring zig version 0.10.0-dev.3024+47c58cba5
CMake Error at cmake/Findllvm.cmake:25 (message):
  LLVM 14.x found at /usr/lib/llvm/14/bin/llvm-config does not support
  linking as shared library
Call Stack (most recent call first):
  CMakeLists.txt:111 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/bratishkaerik/zig/build/CMakeFiles/CMakeOutput.log".
```

Notice:
> LLVM 14.x found at /usr/lib/llvm/14/bin/llvm-config does not support
  linking as shared library

But it surely does. It's a bit confusing.

2022-07-16 15:54 UTC, topolarity commented
Thanks for the helpful reports!

Can you share the output of `/usr/lib/llvm/14/bin/llvm-config --link-shared`?

2022-07-16 15:58 UTC, BratishkaErik commented
> Thanks for the helpful reports!
> 
> Can you share the output of `/usr/lib/llvm/14/bin/llvm-config --link-shared`?

```sh
```
Empty

2022-07-16 16:16 UTC, BratishkaErik commented on cmake/Findllvm.cmake
> +        COMMAND ${LLVM_CONFIG_EXE} --libs ${STATIC_OR_SHARED_LINK}
```suggestion
        COMMAND ${LLVM_CONFIG_EXE} --libs all ${STATIC_OR_SHARED_LINK}
```

2022-07-16 17:29 UTC, topolarity commented
> > LLVM 14.x found at /usr/lib/llvm/14/bin/llvm-config does not support
> > linking as shared library
> 
> But it surely does. It's a bit confusing. Besides this, thank you so much!
The commit just pushed should report the error received from llvm-config. Would you mind trying it once more?

2022-07-16 17:34 UTC, BratishkaErik commented
> > > LLVM 14.x found at /usr/lib/llvm/14/bin/llvm-config does not support
> > > linking as shared library
> > 
> > 
> > But it surely does. It's a bit confusing. Besides this, thank you so much!
> 
> The commit just pushed should report the error received from llvm-config. Would you mind trying it once more?

`cmake ..`:  works and builds fine
`cmake -DZIG_SHARED_LLVM=On ..`: works and builds fine
`cmake -DZIG_STATIC_LLVM=On ..`:
```
-- The C compiler identification is GNU 11.3.0
-- The CXX compiler identification is GNU 11.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring zig version 0.10.0-dev.3024+47c58cba5
CMake Error at cmake/Findllvm.cmake:25 (message):
  LLVM 14.x found at /usr/lib/llvm/14/bin/llvm-config does not support
  linking as shared library ("llvm-config: error: missing:
  /usr/lib/llvm/14/lib64/libLLVMBinaryFormat.a

  llvm-config: error: missing:
  /usr/lib/llvm/14/lib64/libLLVMBitstreamReader.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMRemarks.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMCore.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMBitReader.a

  llvm-config: error: missing:
  /usr/lib/llvm/14/lib64/libLLVMDebugInfoCodeView.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMMC.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMMCParser.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMTextAPI.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMObject.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMDebugInfoDWARF.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMProfileData.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMAnalysis.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMBitWriter.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMTransformUtils.a

  llvm-config: error: missing:
  /usr/lib/llvm/14/lib64/libLLVMAggressiveInstCombine.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMInstCombine.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMScalarOpts.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMTarget.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMFuzzMutate.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMFileCheck.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMInterfaceStub.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMAsmParser.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMIRReader.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMCodeGen.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMSelectionDAG.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMDebugInfoMSF.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMAsmPrinter.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMMIRParser.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMGlobalISel.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMDWARFLinker.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMExtensions.a

  llvm-config: error: missing:
  /usr/lib/llvm/14/lib64/libLLVMFrontendOpenACC.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMFrontendOpenMP.a

  llvm-config: error: missing:
  /usr/lib/llvm/14/lib64/libLLVMInstrumentation.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMLinker.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMVectorize.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMipo.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMObjCARCOpts.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMCoroutines.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMCFGuard.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMPasses.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMLTO.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMMCDisassembler.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMMCA.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMObjectYAML.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMOption.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMDebugInfoGSYM.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMDebugInfoPDB.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMSymbolize.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMDWP.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMOrcShared.a

  llvm-config: error: missing:
  /usr/lib/llvm/14/lib64/libLLVMOrcTargetProcess.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMRuntimeDyld.a

  llvm-config: error: missing:
  /usr/lib/llvm/14/lib64/libLLVMExecutionEngine.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMInterpreter.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMJITLink.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMMCJIT.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMOrcJIT.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMXCoreInfo.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMXCoreDesc.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMXCoreCodeGen.a

  llvm-config: error: missing:
  /usr/lib/llvm/14/lib64/libLLVMXCoreDisassembler.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMAVRInfo.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMAVRDesc.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMAVRCodeGen.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMAVRAsmParser.a

  llvm-config: error: missing:
  /usr/lib/llvm/14/lib64/libLLVMAVRDisassembler.a

  llvm-config: error: missing:
  /usr/lib/llvm/14/lib64/libLLVMWebAssemblyInfo.a

  llvm-config: error: missing:
  /usr/lib/llvm/14/lib64/libLLVMWebAssemblyUtils.a

  llvm-config: error: missing:
  /usr/lib/llvm/14/lib64/libLLVMWebAssemblyDesc.a

  llvm-config: error: missing:
  /usr/lib/llvm/14/lib64/libLLVMWebAssemblyCodeGen.a

  llvm-config: error: missing:
  /usr/lib/llvm/14/lib64/libLLVMWebAssemblyAsmParser.a

  llvm-config: error: missing:
  /usr/lib/llvm/14/lib64/libLLVMWebAssemblyDisassembler.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMSystemZInfo.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMSystemZDesc.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMSystemZCodeGen.a

  llvm-config: error: missing:
  /usr/lib/llvm/14/lib64/libLLVMSystemZAsmParser.a

  llvm-config: error: missing:
  /usr/lib/llvm/14/lib64/libLLVMSystemZDisassembler.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMRISCVInfo.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMRISCVDesc.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMRISCVCodeGen.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMRISCVAsmParser.a

  llvm-config: error: missing:
  /usr/lib/llvm/14/lib64/libLLVMRISCVDisassembler.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMSparcInfo.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMSparcDesc.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMSparcCodeGen.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVMSparcAsmParser.a

  llvm-config: error: missing:
  /usr/lib/llvm/14/lib64/libLLVMSparcDisassembler.a

  llvm-config: error: missing: /usr/lib/llvm/14/lib64/libLLVM [...]

2022-07-16 19:20 UTC, topolarity commented
That error message should have said "LLVM 14.x found at /usr/lib/llvm/14/bin/llvm-config does not support linking as a **static** library". Fixed now

Regarding the failure itself: Are the files reported missing present elsewhere in `/usr/lib/llvm/14/`, and `llvm-config` is just failing to find them? Were you able to build Zig with statically-linked LLVM before?

If not, then CMake might just be correctly informing you that there is no static version of LLVM that it can find to link against.

2022-07-16 19:32 UTC, BratishkaErik commented
> That error message should have said "LLVM 14.x found at /usr/lib/llvm/14/bin/llvm-config does not support linking as a **static** library". Fixed now

Oh! Now I can sleep in peace :)

> Regarding the failure itself: Are the files reported missing present elsewhere in `/usr/lib/llvm/14/`, and `llvm-config` is just failing to find them? Were you able to build Zig with statically-linked LLVM before?

Only shared. https://github.com/ziglang/zig/pull/12136#issuecomment-1186105829

2022-07-17 00:53 UTC, topolarity commented
Pushed a change to build `libzigcpp` as a shared library, based on a discussion with @kubkon

This is the first time we'll be building and installing a shared library as part of the Zig build process, so hopefully I got all of the details right (especially `rpath`). If anyone is able to give things another quick test, I'd greatly appreciate it

2022-07-17 01:43 UTC, BratishkaErik commented
> Pushed a change to build `libzigcpp` as a shared library, based on a discussion with @kubkon
> 
> This is the first time we'll be building and installing a shared library as part of the Zig build process, so hopefully I got all of the details right (especially `rpath`). If anyone is able to give things another quick test, I'd greatly appreciate it

Stage1 `cmake -DZIG_SHARED_LLVM=On .. && make -j8 -l7`: builds and workds fine
Stage2 `./zig build -p stage2 -Dstatic-llvm=false -Denable-llvm=true`:
```zig
warning: FileNotFound: /home/bratishkaerik/zig/build/zigcpp/libzigcpp.a
thread 25859 panic: attempt to unwrap error: FileNotFound
/home/bratishkaerik/zig/lib/std/process.zig:373:46: 0x5654b62bed41 in std.process.getEnvVarOwned (zig1)
        const result = os.getenv(key) orelse return error.EnvironmentVariableNotFound;
                                             ^
/home/bratishkaerik/zig/lib/std/process.zig:373:46: 0x5654b62bed41 in std.process.getEnvVarOwned (zig1)
        const result = os.getenv(key) orelse return error.EnvironmentVariableNotFound;
                                             ^
/home/bratishkaerik/zig/lib/std/process.zig:373:46: 0x5654b62bed41 in std.process.getEnvVarOwned (zig1)
        const result = os.getenv(key) orelse return error.EnvironmentVariableNotFound;
                                             ^
/home/bratishkaerik/zig/lib/std/os.zig:3068:19: 0x5654b62d5019 in std.os.readlinkZ (zig1)
        .INVAL => return error.NotLink,
                  ^
/home/bratishkaerik/zig/lib/std/zig/system/NativeTargetInfo.zig:419:26: 0x5654b655d5d8 in std.zig.system.NativeTargetInfo.glibcVerFromSO (zig1)
        error.NotLink => return error.GnuLibCVersionUnavailable,
                         ^
/home/bratishkaerik/zig/lib/std/os.zig:2749:19: 0x5654b62463c0 in std.os.mkdiratZ (zig1)
        .EXIST => return error.PathAlreadyExists,
                  ^
/home/bratishkaerik/zig/lib/std/os.zig:2709:9: 0x5654b6246276 in std.os.mkdirat (zig1)
        return mkdiratZ(dir_fd, &sub_dir_path_c, mode);
        ^
/home/bratishkaerik/zig/lib/std/fs.zig:1327:9: 0x5654b6246186 in std.fs.Dir.makeDir (zig1)
        try os.mkdirat(self.fd, sub_path, default_new_dir_mode);
        ^
/home/bratishkaerik/zig/lib/std/os.zig:2749:19: 0x5654b62463c0 in std.os.mkdiratZ (zig1)
        .EXIST => return error.PathAlreadyExists,
                  ^
/home/bratishkaerik/zig/lib/std/os.zig:2709:9: 0x5654b6246276 in std.os.mkdirat (zig1)
        return mkdiratZ(dir_fd, &sub_dir_path_c, mode);
        ^
/home/bratishkaerik/zig/lib/std/fs.zig:1327:9: 0x5654b6246186 in std.fs.Dir.makeDir (zig1)
        try os.mkdirat(self.fd, sub_path, default_new_dir_mode);
        ^
/home/bratishkaerik/zig/lib/std/os.zig:2749:19: 0x5654b62463c0 in std.os.mkdiratZ (zig1)
        .EXIST => return error.PathAlreadyExists,
                  ^
/home/bratishkaerik/zig/lib/std/os.zig:2709:9: 0x5654b6246276 in std.os.mkdirat (zig1)
        return mkdiratZ(dir_fd, &sub_dir_path_c, mode);
        ^
/home/bratishkaerik/zig/lib/std/fs.zig:1327:9: 0x5654b6246186 in std.fs.Dir.makeDir (zig1)
        try os.mkdirat(self.fd, sub_path, default_new_dir_mode);
        ^
/home/bratishkaerik/zig/lib/std/os.zig:2749:19: 0x5654b62463c0 in std.os.mkdiratZ (zig1)
        .EXIST => return error.PathAlreadyExists,
                  ^
/home/bratishkaerik/zig/lib/std/os.zig:2709:9: 0x5654b6246276 in std.os.mkdirat (zig1)
        return mkdiratZ(dir_fd, &sub_dir_path_c, mode);
        ^
/home/bratishkaerik/zig/lib/std/fs.zig:1327:9: 0x5654b6246186 in std.fs.Dir.makeDir (zig1)
        try os.mkdirat(self.fd, sub_path, default_new_dir_mode);
        ^
/home/bratishkaerik/zig/lib/std/os.zig:2749:19: 0x5654b62463c0 in std.os.mkdiratZ (zig1)
        .EXIST => return error.PathAlreadyExists,
                  ^
/home/bratishkaerik/zig/lib/std/os.zig:2709:9: 0x5654b6246276 in std.os.mkdirat (zig1)
        return mkdiratZ(dir_fd, &sub_dir_path_c, mode);
        ^
/home/bratishkaerik/zig/lib/std/fs.zig:1327:9: 0x5654b6246186 in std.fs.Dir.makeDir (zig1)
        try os.mkdirat(self.fd, sub_path, default_new_dir_mode);
        ^
/home/bratishkaerik/zig/lib/std/os.zig:1680:23: 0x5654b6535810 in std.os.openatZ (zig1)
            .NOENT => return error.FileNotFound,
                      ^
/home/bratishkaerik/zig/lib/std/fs.zig:1076:13: 0x5654b623f8b6 in std.fs.Dir.openFileZ (zig1)
            try os.openatZ(self.fd, sub_path, os_flags, 0);
            ^
/home/bratishkaerik/zig/lib/std/fs.zig:1003:9: 0x5654b623bd0e in std.fs.Dir.openFile (zig1)
        return self.openFileZ(&path_c, flags);
        ^
/home/bratishkaerik/zig/src/Cache.zig:539:22: 0x5654b623d6da in Cache.Manifest.populateFileHash (zig1)
        const file = try fs.cwd().openFile(ch_file.path.?, .{});
                     ^
/home/bratishkaerik/zig/src/Cache.zig:476:21: 0x5654b622940d in Cache.Manifest.hit (zig1)
                    return err;
                    ^
/home/bratishkaerik/zig/src/Compilation.zig:2130:13: 0x5654b6321549 in Compilation.update (zig1)
            return err;
            ^
/home/bratishkaerik/zig/src/main.zig:3294:5: 0x5654b62b13ed in main.updateModule (zig1)
    try comp.update();
    ^
/home/bratishkaerik/zig/src/main.zig:2985:21: 0x5654b620c84b in main.buildOutputType (zig1)
        else => |e| return e,
                    ^
/home/bratishkaerik/zig/src/main.zig:219:9: 0x5654b61b8e23 in main.mainArgs (zig1)
        return buildOutputType(gpa, arena, args, .{ .build = .Exe });
        ^
???:?:?: 0x5654b61ba7ab in ??? (/home/bratishkaerik/zig/src/stage1/stage1.cpp)
/home/bratishkaerik/zig/src/stage1.zig:48:43: 0x5654b61b8938 in main (zig1)
        stage2.mainArgs(gpa, arena, args) catch unreachable;
                                          ^
error: zig...
error: The following command terminated unexpectedly:
/home/bratishkaerik/zig/build/zig build-exe /home/bratishkaerik/zig/src/main.zig -lc /home/bratishkaerik/zig/build/zigcpp/libzigcpp.a /usr/lib/llvm/14/lib64/libclang-cpp.so.14 /usr/lib64/liblldMinGW.so /usr/lib64/liblldELF.so /usr/lib64/liblldCOFF.so /usr/lib64/liblldWasm.so /usr/lib64/liblldMachO.so /usr/lib64/liblldCommon.so /usr/lib/llvm/14/lib64/libLLVM-14.so /usr/lib/gcc/x86_64-pc-linux-gnu/11.3.0/libstdc++.a -lunwind --cache-dir /home/bratishkaerik/zig/zig-cache --global-cache-dir /home/bratishkaerik/.cache/zig --name zig --pkg-begin build_options /home/bratishkaerik/zig/zig-cache/options/0ghZFRJv5yPSIQOmN7jArYzqIPaxipxNPztZSGsd95d9FUsuBk1sFGWFiIl23teH --pkg-end -I /usr/include -fno-build-id --enable-cache
error: the following build command failed with exit code 6:
/home/bratishkaerik/zig/zig-cache/o/9e99760733e35b737bbb023007fc4485/build /home/bratishkaerik/zig/build/zig /home/bratishkaerik/zig /home/bratishkaerik/zig/zig-cache /home/bratishkaerik/.cache/zig -p stage2 -Dstatic-llvm=false -Denable-llvm=true
```

2022-07-17 03:09 UTC, BratishkaErik commented
```diff
diff --git a/build.zig b/build.zig
index 31347f8e7..414c54a8d 100644
--- a/build.zig
+++ b/build.zig
@@ -534,10 +534,10 @@ fn addCmakeCfgOptionsToExe(
     exe: *std.build.LibExeObjStep,
     use_zig_libcxx: bool,
 ) !void {
-    exe.addObjectFile(fs.path.join(b.allocator, &[_][]const u8{
+    exe.addLibraryPath(fs.path.join(b.allocator, &[_][]const u8{
         cfg.cmake_binary_dir,
         "zigcpp",
-        b.fmt("{s}{s}{s}", .{ exe.target.libPrefix(), "zigcpp", exe.target.staticLibSuffix() }),
+        b.fmt("{s}{s}{s}", .{ exe.target.libPrefix(), "zigcpp", exe.target.dynamicLibSuffix() }),
     }) catch unreachable);
     assert(cfg.lld_include_dir.len != 0);
     exe.addIncludePath(cfg.lld_include_dir);
```

ZIG_SKIP_INSTALL_LIB_FILES doesn't skip `lib/libzigcpp.so`, only `lib/std`, maybe it can be renamed to ZIG_SKIP_INSTALL_STD_LIB ?

2022-07-17 05:40 UTC, BratishkaErik commented
```diff
diff --git a/build.zig b/build.zig
index 31347f8e7..07d0b5766 100644
--- a/build.zig
+++ b/build.zig
@@ -331,8 +331,29 @@ pub fn build(b: *Builder) !void {
                 b.addSearchPrefix(cfg.cmake_prefix_path);
             }

+            const zigcpp_lib_name = fs.path.join(b.allocator, &[_][]const u8{
+                cfg.cmake_binary_dir,
+                "zigcpp",
+                b.fmt("{s}{s}{s}", .{ exe.target.libPrefix(), "zigcpp", exe.target.dynamicLibSuffix() }),
+            }) catch unreachable;
+
+            exe.addObjectFile(zigcpp_lib_name);
+            test_cases.addObjectFile(zigcpp_lib_name);
             try addCmakeCfgOptionsToExe(b, cfg, exe, use_zig_libcxx);
             try addCmakeCfgOptionsToExe(b, cfg, test_cases, use_zig_libcxx);
+
+            switch (exe.target.getOs().tag) {
+                .macos => {
+                    exe.addRPath("@loader_path/../lib");
+                    test_cases.addRPath("@loader_path/../lib");
+                },
+                else => {
+                    exe.addRPath("$ORIGIN/../lib");
+                    test_cases.addRPath("$ORIGIN/../lib");
+                },
+            }
+
+            b.installLibFile(zigcpp_lib_name, b.fmt("{s}{s}{s}", .{ exe.target.libPrefix(), "zigcpp", exe.target.dynamicLibSuffix() }));
         } else {
             // Here we are -Denable-llvm but no cmake integration.
             try addStaticLlvmOptionsToExe(exe);
@@ -534,11 +555,6 @@ fn addCmakeCfgOptionsToExe(
     exe: *std.build.LibExeObjStep,
     use_zig_libcxx: bool,
 ) !void {
-    exe.addObjectFile(fs.path.join(b.allocator, &[_][]const u8{
-        cfg.cmake_binary_dir,
-        "zigcpp",
-        b.fmt("{s}{s}{s}", .{ exe.target.libPrefix(), "zigcpp", exe.target.staticLibSuffix() }),
-    }) catch unreachable);
     assert(cfg.lld_include_dir.len != 0);
     exe.addIncludePath(cfg.lld_include_dir);
     addCMakeLibraryList(exe, cfg.clang_libraries);
```

2022-07-17 07:01 UTC, BratishkaErik commented on CMakeLists.txt
> +    set(RPATH_BASE @loader_path)
```suggestion
    set(RPATH_BASE @executable_path)
```

2022-07-17 09:48 UTC, BratishkaErik commented
Everything from https://github.com/ziglang/zig/wiki/Building-Zig-From-Source builds and works fine:

> Remember! For Option B, these libraries must be produced by zig cc / zig c++ - not by your system C/C++ compiler. If you are annoyed by this, welcome to the club.

Well, I can't reproduce this, stage1-from-prebuilt builds and works fine
(and somehow Option B weighs 2,8 megabytes less than Option A, both stripped and with -Drelease=true)

2022-07-17 21:00 UTC, topolarity commented
@BratishkaErik Thanks for all of the thorough testing, I really appreciate it.

Pushed support for stage2 (+3)

Most important difference w.r.t. your change is that I did not make RPATH configurable. `libzigcpp.so` exposes no public API whatsoever, so I don't think we should support installing this system library directories. Willing to hear arguments to the contrary, though.

2022-07-18 10:24 UTC, BratishkaErik commented
```sh
scanelf: rpath_security_checks(): Security problem NULL DT_RUNPATH in zigcpp/libzigcpp.so
```
I guess libzigcpp.so doesn't need RPATH?

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 2ae8e3d18..6dcd76d6c 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -907,6 +907,7 @@ endif()

 set_target_properties(zigcpp PROPERTIES
     COMPILE_FLAGS ${EXE_CFLAGS}
+    SKIP_BUILD_RPATH On
 )

 target_link_libraries(zigcpp LINK_PUBLIC
```

2022-07-18 15:21 UTC, topolarity commented
> I guess libzigcpp.so doesn't need RPATH?

Good catch! Updated now, thank you.

2022-07-19 22:24 UTC, andrewrk requested changes
Thanks for looking into this. What a complete mess.

I think the root problem here is that dynamically linked LLVM+Clang does not mix with statically linked LLD.

I don't really see a way to link properly when the system wants us to link dynamically against LLVM and Clang but then only provides static LLD libraries. This just seems like we're hitting C++ undefined behavior.

> Pushed a change to build `libzigcpp` as a shared library, based on a discussion with @kubkon

I'd like to avoid this; this code has no reason to be a dynamic library and making it such will only cause problems. What problem is this solving?

2022-07-19 23:59 UTC, topolarity commented
> I think the root problem here is that dynamically linked LLVM+Clang does not mix with statically linked LLD.
> 
> I don't really see a way to link properly when the system wants us to link dynamically against LLVM and Clang but then only provides static LLD libraries. This just seems like we're hitting C++ undefined behavior.

I haven't quite managed to grok the common recommendation not to "mix" static/shared libraries, to be honest - At the end of the day, static libraries are just (collections of) object files, and saying not to mix them with shared libraries would suggest it's also wrong to mix object files with shared libraries - But that's a linker's entire job.

The concrete problem I've seen is not C++ UB - It's that this part of the C standard (http://port70.net/~nsz/c/c11/n1570.html#6.2.2p2) no longer holds up when statically linking the same objects (e.g. `libstdc++.a`) into multiple shared libraries, since the dynamic linker is not capable of noticing/fixing the duplication.

I'm also no expert in C++ or linkers. There's a high chance there's more complexity I'm missing here, so I'm all ears if any of the above is wrong.

> What a complete mess.

Tell me about it 😰

2022-07-20 00:05 UTC, topolarity commented
> I'd like to avoid this; this code has no reason to be a dynamic library and making it such will only cause problems. What problem is this solving?

Same as the LLD situation basically - There are concerns about mixing shared/static stepping on C++ UB, but I don't personally have a specific bug/standard I can point to that says why this would have to be shared

Happy to revert, if you'd prefer. My priority is that we don't statically link `libstdc++` into multiple shared libraries and we don't mix library versions/ABIs

2022-07-21 18:47 UTC, andrewrk commented
> The concrete problem I've seen is not C++ UB - It's that this part of the C standard (http://port70.net/~nsz/c/c11/n1570.html#6.2.2p2) no longer holds up when statically linking the same objects (e.g. `libstdc++.a`) into multiple shared libraries, since the dynamic linker is not capable of noticing/fixing the duplication.

This is indeed the concrete problem that I am thinking of (which you have addressed in #12085), and that is my mistake for confusing things by saying "C++ UB". I think that I have gotten this problem mixed up with the [Static Initialization Order Fiasco](https://en.cppreference.com/w/cpp/language/siof).

> Same as the LLD situation basically - There are concerns about mixing shared/static stepping on C++ UB, but I don't personally have a specific bug/standard I can point to that says why this would have to be shared. Happy to revert, if you'd prefer. 

I am firmly convinced that making these files dynamically linked is the wrong way to go, and would indeed request a revert on that particular change.

> My priority is that we don't statically link `libstdc++` into multiple shared libraries and we don't mix library versions/ABIs

I share this priority with you.

2022-07-21 19:03 UTC, topolarity commented
Great, sounds like a plan. Thanks for the input - I needed a Core Team POV on this one.

2022-07-24 16:49 UTC, voroskoi commented
Sorry for coming late to the party, but unlike master this branch does not work with guix, does not find the clang include dir and libs. They have different hash than llvm include dirs, so I have no idea how to handle this. Does it work with nixos?

2022-07-25 17:39 UTC, topolarity commented
> Sorry for coming late to the party, but unlike master this branch does not work with guix, does not find the clang include dir and libs. They have different hash than llvm include dirs, so I have no idea how to handle this. Does it work with nixos?

Thanks for the heads up - I've relaxed the way we look for Clang so that it respects `CMAKE_LIBRARY_PATH` (as well as `CMAKE_PREFIX_PATH`), even if this isn't where we found LLVM. I think this is enough to get things operational on Nix-like OS's again

2022-07-26 15:10 UTC, voroskoi commented
This one works indeed, thanks. Only #12153 left, but as far as I understand Andrew that stays this way for a while.

2022-07-26 18:41 UTC, merged

2022-07-26 18:42 UTC, andrewrk commented
Thank you @topolarity, this looks like it was an ordeal in order to implement. I think this is the best we can do with what we've got. That `while (1)` in cmake is terrifying but seems like the right call :shrug: 

Really appreciate your diligence on this one.

2024-05-14 23:20 UTC, beholders-eye commented on cmake/Findllvm.cmake
> +    unset(LLVM_CONFIG_EXE CACHE)
What's the goal here, why unset LLVM_CONFIG_EXE, what if we want to `-DLLVM_CONFIG_EXE=<some/path/to/llvm-config>` ?