build.zig: Try harder to find "config.h"
ziglang/zig pull request #12133
Opened 2022-07-16 00:32 UTC by topolarity

Now that we're building stage3 frequently, I noticed that stage2 can't auto-locate config.h.

This change makes `build.zig` try a little harder to find the `config.h` from CMake: It will check for "build"/"stage1" directories that might contain the file.

More importantly, it will warn the user if it could not be located:
```
$ ./stage2/bin/zig build -Dlog -Denable-llvm --zig-lib-dir lib --prefix $(pwd)/stage3 --search-prefix ~/local/llvm13-release
warning: config.h could not be located automatically. Consider providing it explicitly via "-Dconfig_h"
```

2022-07-16 09:16 UTC, Vexu commented
Previous discussion: https://github.com/ziglang/zig/pull/11501#pullrequestreview-959579630

2022-07-16 14:54 UTC, topolarity commented
Thanks for the context @Vexu - I'll to rework this one, clearly.

I wonder if copying the `config.h` into the installation during the build would be acceptable? This way Zig would inherit its build settings from the Zig building it.

2022-07-19 23:01 UTC, andrewrk requested changes
I don't really think config.h belongs in the installation of Zig. Although I admit it's mostly personal taste, if you produce an installation of Zig using Zig without going through stage1, then no config.h is produced. It seems like, therefore, a canonical installation of Zig does not include config.h.

Is there something wrong with the recommended way to handle stage1, stage2, and stage3 installations side-by-side by running commands directly from the cmake build directory, or by passing `-Dconfig_h` with the `zig build` commands?

2022-07-19 23:52 UTC, topolarity commented
I share your preference actually 👌 

> Is there something wrong with the recommended way to handle stage1, stage2, and stage3 installations side-by-side by running commands directly from the cmake build directory, or by passing -Dconfig_h with the zig build commands?

I think this behavior is perfectly fine with the warning added. Let me scale back the change to just that.

2022-07-29 18:38 UTC, merged