WIP: Fix #9184
ziglang/zig pull request #12148
Opened 2022-07-17 06:42 UTC by yujiri8

I'm new to this. Am I going about it the right way, not changing the API of fmtIntSizeDec and fmtIntSizeBin themselves? I'm confused about the API, is this how it's meant to be used?
```zig
const std = @import("std");
const fmt = std.fmt;
const debug = std.debug;
const io = std.io;

pub fn main() !void {
    var stdout = io.getStdOut().writer();
    try fmt.fmtIntSizeBin(10000).format("", fmt.FormatOptions{.width = 12, .alignment = .Center}, stdout);
    // debug.print("{s}", .{result});
}
```

(It currently prints `9.765625    KiB     `. I assume the intended behavior would be to put no space inbetween the number and `KiB` and center the concanetation?)

2022-07-17 07:13 UTC, Vexu requested changes
The float value and the plain `B` suffix are still being written directly to the writer. Instead everything should be written into a `std.io.fixedBufferStream` backed by the buffer on stack and then the `fbs.getWritten()` should be written into the original writer using `formatBuf`.

2022-07-17 07:13 UTC, Vexu commented on lib/std/fmt.zig
> +                return formatBuf(buf[0..2], options, writer);
```suggestion
                return formatBuf("0B", options, writer);
```

2022-07-17 07:13 UTC, Vexu commented on lib/std/fmt.zig
> +            var buf: [1000]u8 = undefined;
The worst case for `formatFloatDecimal` seems to be 32 bytes + 3 bytes for the suffix.

2022-07-18 00:24 UTC, yujiri8 commented
Using fixedBufferStream now. This almost works, but the tests are failing with:
```
./lib/std/fmt.zig:1662:13: error: expected type 'std.io.NullWriter', found '@typeInfo(@typeInfo(@TypeOf(std.fmt.formatSizeImpl(1000).f)).Fn.return_type.?).ErrorUnion.error_set'
            try format_fn(self.data, fmt, options, writer);
            ^
./lib/std/fmt.zig:461:32: note: called from here
        return try value.format(actual_fmt, options, writer);
                               ^
./lib/std/fmt.zig:181:23: note: called from here
        try formatType(
                      ^
./lib/std/fmt.zig:1893:11: note: called from here
    format(counting_writer.writer(), fmt, args) catch |err| switch (err) {};
          ^
./lib/std/fmt.zig:1900:40: note: called from here
    const size = math.cast(usize, count(fmt, args)) orelse return error.OutOfMemory;
                                       ^
./lib/std/testing.zig:201:42: note: called from here
    const result = try std.fmt.allocPrint(allocator, template, args);
                                         ^
./test.zig:10:26: note: called from here
    try testing.expectFmt("", "{d}", .{fmt.fmtIntSizeDec(42)});
                         ^
./test.zig:7:21: note: called from here
pub fn main() !void {
                    ^
./lib/std/io/fixed_buffer_stream.zig:16:38: note: 'error.NoSpaceLeft' not a member of destination error set
        pub const WriteError = error{NoSpaceLeft};
                                     ^
```
Replacing every usage of `try` in the function with `catch unreachable` solves it, but I don't think that's correct since it was using try before when calling formatFloatDecimal. Meanwhile my own test case like this works fine:
```zig
const std = @import("std");
const fmt = std.fmt;
const debug = std.debug;
const io = std.io;
const testing = std.testing;

pub fn main() !void {
    debug.print("{s: ^20}", .{fmt.fmtIntSizeDec(18446744073709551615)});
    // try testing.expectFmt("", "{d}", .{fmt.fmtIntSizeDec(42)});
}
```
It seems to be only testing.expectFmt that doesn't like it.

2022-07-19 06:57 UTC, yujiri8 commented
Updated! The tests pass now and testing.expectFmt seems to work. Thanks for your help!

2022-07-19 07:28 UTC, Vexu approved these changes
Could you add  a new test for alignment and width like was done in #10361?

2022-07-21 06:28 UTC, yujiri8 commented
Done! Four new test cases.

2022-07-21 15:41 UTC, merged