CMakeLists.txt: fix linking with ld
ziglang/zig pull request #12153
Opened 2022-07-17 19:55 UTC by voroskoi

Fix for the error below:
ld: liblldELF.a(OutputSections.cpp.o): undefined reference to symbol 'deflate'
ld: libz.so.1: error adding symbols: DSO missing from command line

ld recently changed to only link with explicitly defined targets

2022-07-17 19:57 UTC, voroskoi commented
Wait, zig also fails.

2022-07-17 20:06 UTC, voroskoi commented
OK, works for me :-)

2022-07-17 21:37 UTC, topolarity commented
This change overlaps with #12136 , but I'm inclined to think this fix is better because it doesn't rely on llvm-config.

The flaw with the other change is that when llvm-config corresponds to a shared-library (only) installation of LLVM, it will not report libz as a build-time dependency. It links to libz at run-time not build time.

However, on some systems LLD is provided only as a static library which does need libz at build-time. As far as I know, there's no equivalent to `llvm-config` for LLD and it doesn't come with `pkg-config` files on my system either, so I think the best we can do is just hardcode this dependency.

2022-07-18 05:18 UTC, voroskoi commented
Hi,

Sorry, I was not aware of that PR.

Are there any systems out there with `lld` installed, but `llvm` not? Isn't it safe to assume that `llvm-config` is available?

On the other hand I hardly think of a system without `libz`, so linking would just work. Maybe we could add a `--disable-link-zlib` flag to let users disable linking?

2022-07-18 06:34 UTC, topolarity commented
Sorry, let me clarify:

If your LLVM installation only includes shared libraries, "llvm-config --link-static --system-libs" fails. On the other hand, "llvm-config --link-shared --system-libs" always (correctly) reports no build-time link dependencies because for a shared library, `libz` isn't needed at build-time, only run-time.

The issue is that if LLD is being linked as a static library, it will have build-time dependencies (-lz) and llvm-config won't be able to report them.

2022-07-19 22:30 UTC, andrewrk requested changes
> However, on some systems LLD is provided only as a static library which does need libz at build-time. As far as I know, there's no equivalent to llvm-config for LLD and it doesn't come with pkg-config files on my system either, so I think the best we can do is just hardcode this dependency.

Hmm I'm not satisfied with this. I'd like to work with upstream to solve this in a more satisfying way. Let's let this problem fester until we can get upstream to cooperate with us on helping downstream applications link properly.

In the meantime, building zig with everything static works fine. Let's coordinate with package maintainers and LLVM on getting system-integration working properly.

The root problem here is LLD not being provided as a dynamically linked library along with LLVM and Clang, would you agree?

2022-07-26 18:41 UTC, andrewrk commented
I believe this has been addressed by #12136.

2022-07-26 18:41 UTC, closed without merging

2022-07-26 19:12 UTC, voroskoi commented
No, #12136 does not fix this, at least not for me, but I understand that my solution is not the right one. Shall I open a bug report for this?

2022-07-26 19:25 UTC, andrewrk commented
Can you share what happens when you try to build master branch now?

2022-07-26 19:44 UTC, voroskoi commented
Here is my guix.scm, I run `guix shell -m guix.scm` to create the profile.
```
[I] ⋊> ~/c/zig on master ◦ cat guix.scm                                                                                                                           /gnu/store/vrw5zvpb1dx6688j5xv7nbfq51bj4dzp-profile
;; What follows is a "manifest" equivalent to the command line you gave.
;; You can store it in a file that you may then pass to any 'guix' command
;; that accepts a '--manifest' (or '-m') option.

(concatenate-manifests
  (list (specifications->manifest
          (list "zig@0.10"
                "llvm@14"
                "lld@14"
                "clang@14"
                "zls"))
        (package->development-manifest
          (specification->package "zig"))))

```

Next step:
```
[I] ⋊> ~/c/z/build on master ◦ cmake .. -DCMAKE_BUILD_TYPE=Release                                                                                                /gnu/store/vrw5zvpb1dx6688j5xv7nbfq51bj4dzp-profile
-- The C compiler identification is GNU 10.3.0
-- The CXX compiler identification is GNU 10.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /gnu/store/vrw5zvpb1dx6688j5xv7nbfq51bj4dzp-profile/bin/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /gnu/store/vrw5zvpb1dx6688j5xv7nbfq51bj4dzp-profile/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring zig version 0.10.0-dev.3326+7a09bce23
-- Found llvm: -lLLVMWindowsManifest;-lLLVMXRay;-lLLVMLibDriver;-lLLVMDlltoolDriver;-lLLVMCoverage;-lLLVMLineEditor;-lLLVMXCoreDisassembler;-lLLVMXCoreCodeGen;-lLLVMXCoreDesc;-lLLVMXCoreInfo;-lLLVMX86TargetMCA;-lLLVMX86Disassembler;-lLLVMX86AsmParser;-lLLVMX86CodeGen;-lLLVMX86Desc;-lLLVMX86Info;-lLLVMWebAssemblyDisassembler;-lLLVMWebAssemblyAsmParser;-lLLVMWebAssemblyCodeGen;-lLLVMWebAssemblyDesc;-lLLVMWebAssemblyUtils;-lLLVMWebAssemblyInfo;-lLLVMVEDisassembler;-lLLVMVEAsmParser;-lLLVMVECodeGen;-lLLVMVEDesc;-lLLVMVEInfo;-lLLVMSystemZDisassembler;-lLLVMSystemZAsmParser;-lLLVMSystemZCodeGen;-lLLVMSystemZDesc;-lLLVMSystemZInfo;-lLLVMSparcDisassembler;-lLLVMSparcAsmParser;-lLLVMSparcCodeGen;-lLLVMSparcDesc;-lLLVMSparcInfo;-lLLVMRISCVDisassembler;-lLLVMRISCVAsmParser;-lLLVMRISCVCodeGen;-lLLVMRISCVDesc;-lLLVMRISCVInfo;-lLLVMPowerPCDisassembler;-lLLVMPowerPCAsmParser;-lLLVMPowerPCCodeGen;-lLLVMPowerPCDesc;-lLLVMPowerPCInfo;-lLLVMNVPTXCodeGen;-lLLVMNVPTXDesc;-lLLVMNVPTXInfo;-lLLVMMSP430Disassembler;-lLLVMMSP430AsmParser;-lLLVMMSP430CodeGen;-lLLVMMSP430Desc;-lLLVMMSP430Info;-lLLVMMipsDisassembler;-lLLVMMipsAsmParser;-lLLVMMipsCodeGen;-lLLVMMipsDesc;-lLLVMMipsInfo;-lLLVMLanaiDisassembler;-lLLVMLanaiCodeGen;-lLLVMLanaiAsmParser;-lLLVMLanaiDesc;-lLLVMLanaiInfo;-lLLVMHexagonDisassembler;-lLLVMHexagonCodeGen;-lLLVMHexagonAsmParser;-lLLVMHexagonDesc;-lLLVMHexagonInfo;-lLLVMBPFDisassembler;-lLLVMBPFAsmParser;-lLLVMBPFCodeGen;-lLLVMBPFDesc;-lLLVMBPFInfo;-lLLVMAVRDisassembler;-lLLVMAVRAsmParser;-lLLVMAVRCodeGen;-lLLVMAVRDesc;-lLLVMAVRInfo;-lLLVMARMDisassembler;-lLLVMARMAsmParser;-lLLVMARMCodeGen;-lLLVMARMDesc;-lLLVMARMUtils;-lLLVMARMInfo;-lLLVMAMDGPUTargetMCA;-lLLVMAMDGPUDisassembler;-lLLVMAMDGPUAsmParser;-lLLVMAMDGPUCodeGen;-lLLVMAMDGPUDesc;-lLLVMAMDGPUUtils;-lLLVMAMDGPUInfo;-lLLVMAArch64Disassembler;-lLLVMAArch64AsmParser;-lLLVMAArch64CodeGen;-lLLVMAArch64Desc;-lLLVMAArch64Utils;-lLLVMAArch64Info;-lLLVMOrcJIT;-lLLVMMCJIT;-lLLVMJITLink;-lLLVMInterpreter;-lLLVMExecutionEngine;-lLLVMRuntimeDyld;-lLLVMOrcTargetProcess;-lLLVMOrcShared;-lLLVMDWP;-lLLVMSymbolize;-lLLVMDebugInfoPDB;-lLLVMDebugInfoGSYM;-lLLVMOption;-lLLVMObjectYAML;-lLLVMMCA;-lLLVMMCDisassembler;-lLLVMLTO;-lLLVMPasses;-lLLVMCFGuard;-lLLVMCoroutines;-lLLVMObjCARCOpts;-lLLVMipo;-lLLVMVectorize;-lLLVMLinker;-lLLVMInstrumentation;-lLLVMFrontendOpenMP;-lLLVMFrontendOpenACC;-lLLVMExtensions;-lLLVMDWARFLinker;-lLLVMGlobalISel;-lLLVMMIRParser;-lLLVMAsmPrinter;-lLLVMDebugInfoMSF;-lLLVMSelectionDAG;-lLLVMCodeGen;-lLLVMIRReader;-lLLVMAsmParser;-lLLVMInterfaceStub;-lLLVMFileCheck;-lLLVMFuzzMutate;-lLLVMTarget;-lLLVMScalarOpts;-lLLVMInstCombine;-lLLVMAggressiveInstCombine;-lLLVMTransformUtils;-lLLVMBitWriter;-lLLVMAnalysis;-lLLVMProfileData;-lLLVMDebugInfoDWARF;-lLLVMObject;-lLLVMTextAPI;-lLLVMMCParser;-lLLVMMC;-lLLVMDebugInfoCodeView;-lLLVMBitReader;-lLLVMCore;-lLLVMRemarks;-lLLVMBitstreamReader;-lLLVMBinaryFormat;-lLLVMTableGen;-lLLVMSupport;-lLLVMDemangle (Required is at least version "14") 
-- Found clang: /gnu/store/vrw5zvpb1dx6688j5xv7nbfq51bj4dzp-profile/lib/libclang-cpp.so.14 (Required is at least version "14") 
-- Found lld: /gnu/store/vrw5zvpb1dx6688j5xv7nbfq51bj4dzp-profile/lib/liblldMinGW.a;/gnu/store/vrw5zvpb1dx6688j5xv7nbfq51bj4dzp-profile/lib/liblldELF.a;/gnu/store/vrw5zvpb1dx6688j5xv7nbfq51bj4dzp-profile/lib/liblldCOFF.a;/gnu/store/vrw5zvpb1dx6688j5xv7nbfq51bj4dzp-profile/lib/liblldWasm.a;/gnu/store/vrw5zvpb1dx6688j5xv7nbfq51bj4dzp-profile/lib/liblldMachO.a;/gnu/store/vrw5zvpb1dx6688j5xv7nbfq51bj4dzp-profile/lib/liblldCommon.a (Required is at least version "14") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/voroskoi/code/zig/build
```

Build log:
```
[I] ⋊> ~/c/z/build on master ◦ make install                                                                                                                       /gnu/store/vrw5zvpb1dx6688j5xv7nbfq51bj4dzp-profile
[  0%] Building CXX object CMakeFiles/zigcpp.dir/src/zig_llvm.cpp.o
[  1%] Building CXX object CMakeFiles/zigcpp.dir/src/zig_llvm-ar.cpp.o
[  1%] Building CXX object CMakeFiles/zigcpp.dir/src/zig_clang.cpp.o
[  2%] Building CXX object CMakeFiles/zigcpp.dir/src/zig_clang_driver.cpp.o
[  2%] Building CXX object CMakeFiles/zigcpp.dir/src/zig_clang_cc1_main.cpp.o
[  3%] Building CXX object CMakeFiles/zigcpp.dir/src/zig_clang_cc1as_main.cpp.o
[  3%] Building CXX object CMakeFiles/zigcpp.dir/src/windows_sdk.cpp.o
[  4%] Linking CXX static library zigcpp/libzigcpp.a
[  4%] Built target zigcpp
[  4%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3e/source/8086/f128M_isSignalingNaN.c.o
[  5%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3e/source/8086/extF80M_isSignalingNaN.c.o
[  5%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3e/source/8086/s_commonNaNToF128M.c.o
[  6%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3e/source/8086/s_commonNaNToExtF80M.c.o
[  6%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3e/source/8086/s_commonNaNToF16UI.c.o
[  7%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3e/source/8086/s_commonNaNToF32UI.c.o
[  7%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3e/source/8086/s_commonNaNToF64UI.c.o
[  8%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3e/source/8086/s_f128MToCommonNaN.c.o
[  8%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3e/source/8086/s_extF80MToCommonNaN.c.o
[  9%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3e/source/8086/s_f16UIToCommonNaN.c.o
[  9%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3e/source/8086/s_f32UIToCommonNaN.c.o
[ 10%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3e/source/8086/s_f64UIToCommonNaN.c.o
[ 10%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3e/source/8086/s_propagateNaNF128M.c.o
[ 11%] Buildin [...]

2022-07-26 19:50 UTC, andrewrk commented
Hmm, for me the "Found llvm" part says:

```
-- Found llvm: -lLLVM-14;-lrt;-ldl;-lpthread;-lm;-lz;-ltinfo;-lxml2 (Required is at least version "14") 
```

I'm not sure why yours does not have these. Can you share the output of `llvm-config --shared-mode` ?

2022-07-26 20:02 UTC, andrewrk commented
I'm not sure we can solve this problem downstream; we are trying our best to learn what the system wants us to do, and the system is crapping its pants

2022-07-26 20:17 UTC, topolarity commented
@voroskoi For reference, https://github.com/ziglang/zig/issues/12069 is the issue you're looking for.

That's probably the right place to stay subscribed until a proper solution comes into place

2022-07-27 13:18 UTC, voroskoi commented
OK, thanks.