use ws2_32 posix like function signatures for std.c
ziglang/zig pull request #12217
Opened 2022-07-24 13:24 UTC by arBmind

Fixes #10934

* fixes issues with different size types

2022-10-12 18:37 UTC, andrewrk requested changes
Thanks for the patch. I have one request before merging-

2022-10-12 22:37 UTC, arBmind commented on lib/std/os/windows/ws2_32.zig
> +pub const posixLike = struct {
Okay, to do that I copied all the posix like functions of ws2_32 api to c.zig and changed the formatting a match the c equivalents.

Also realized that I moved too many functions to posixLike (as they were mentioned in winsock documentation) that are not part of c.zig.

2023-04-09 15:22 UTC, andrewrk commented
std.c is for the C library, not for ws2_32. Please see #15223 for a resolution of this issue. The std.os code should be modified to call std.windows.ws2_32 on windows rather than going through std.c.

2023-04-09 15:22 UTC, closed without merging

2023-04-09 15:40 UTC, andrewrk commented
Sendto issue addressed in #15225.