optimize std.fs.Dir.makeOpenPath for the case that the path already exists
ziglang/zig pull request #12475
Opened 2022-08-18 10:56 UTC by joedavis

Updates std.fs.Dir.makeOpenPath (and its iterable counterpart) to use a single syscall in most cases (100% of the time on Windows).

openDirAccessMaskW is updated to take an additional configuration option, which toggles between FILE_OPEN_IF and FILE_OPEN to support this.

Resolves #12474

2022-08-18 11:46 UTC, joedavis commented
Looks like the build is failing on Windows CI. Once I’m back at my computer I’ll take a look and see what discrepancy there is with my local setup.

2022-08-18 17:34 UTC, kubkon requested changes

2022-08-18 17:34 UTC, kubkon commented on lib/std/fs.zig
>              0,
I might be off here, but my hunch tells me you want `FILE_ATTRIBUTE_NORMAL` if creating a dir, `0` otherwise.

2022-08-18 17:34 UTC, kubkon commented on lib/std/fs.zig
>              0,
Oh yep, Windows docs confirm it [ZwCreateFile](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-zwcreatefile):

> [in] FileAttributes

> Specifies one or more FILE_ATTRIBUTE_XXX flags, which represent the file attributes to set if you create or overwrite a file. The caller usually specifies FILE_ATTRIBUTE_NORMAL, which sets the default attributes. For a list of valid FILE_ATTRIBUTE_XXX flags, see the [CreateFile](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfilea) routine in the Microsoft Windows SDK documentation. If no file is created or overwritten, FileAttributes is ignored.

2022-08-20 07:44 UTC, nektro requested changes

2022-08-20 07:44 UTC, nektro commented on lib/std/fs.zig
> +        }
should be `return self.openDir(...) catch ...` and do `makePath()` on `FileNotFound` only

2022-08-20 07:44 UTC, nektro commented on lib/std/fs.zig
> +        }
same as above

2022-09-01 01:57 UTC, andrewrk commented
Hello - I have attempted to rebase this against master branch on your behalf in order to re-run the failing CI checks. However you have disabled "allow maintainers to push to this branch". So please re-open this PR against master branch after addressing the review feedback and failing CI tests.

2022-09-01 01:57 UTC, closed without merging