Fix crash when carriage return is encountered in multiline string
ziglang/zig pull request #12661
Opened 2022-08-28 10:33 UTC by moosichu

Taking guidance from: ziglang/zig-spec#38, carriage returns are now allowed preceding line-feeds when found in doc-comments or multiline strings. The CRLF is also only interpreted as a newline in this case. However - they are otherwise rejected when found in any other context except when used as plain whitespace.

This resolves #11414.

2022-08-28 10:42 UTC, Vexu requested changes
Needs a test, you'll have to use string literals in `test/compile_errors.zig`.

2022-10-15 14:01 UTC, andrewrk commented
CI checks are failing

2022-10-22 08:51 UTC, moosichu commented
Yeah - I haven't had the time to address those test issues for the the past while, but should hopefully be able to at the end of this week if that's ok :) Sorry for the delay on this one!

2022-12-11 19:02 UTC, moosichu commented
Just resolved the merge conflicts that I saw had cropped-up (hopefully :crossed_fingers:)

2023-01-03 10:55 UTC, Vexu approved these changes

2023-02-19 12:14 UTC, merged