Scan from line start when finding tag in tokenizer
ziglang/zig pull request #12692
Opened 2022-08-30 23:08 UTC by moosichu

This resolves a crash that can occur for invalid bytes like carriage
returns that are valid characters when not parsed from within literals.

There are potentially other edge cases this could resolve as well, as
the calling code for this function didn't account for any potential
'pending_invalid_tokens' that could be queued up by the tokenizer from
within another state.

This PR resolves #12674 and will unblock #12661.

#12449 could later simplify this when implemented, however this was a super simple change and fixes a known crash.

2022-08-31 08:21 UTC, Vexu commented
`tokenSlice` is quite heavily used so if this only affects `.invalid` tokens then it should only be called for them.

2022-09-05 07:58 UTC, moosichu commented
Only just found some time to get around to this! Good shout, that change has been pushed.

2022-10-30 00:15 UTC, andrewrk requested changes
Thanks for this improvement. Needs a unit test before being merged - especially because there is already discussion about wanting to remove the workaround, in which case we would want to make sure it doesn't break!

2022-10-30 10:31 UTC, moosichu commented
#12661 Already supercedes this anyway, so if you are happy with that (especially because it has tests) I don't think this needs to be merged. This was mainly intended as a low-risk workaround for a known crash, whereas #12661 actually fixes the issue by adhering to the spec.

Will close this for now! Mainly becuase any tests for this would be made redundant anyway.

2022-10-30 10:31 UTC, closed without merging