rvalue_noresult need add type resultloc case
ziglang/zig pull request #12764
Opened 2022-09-07 06:22 UTC by kkHAIKE

fix https://github.com/ziglang/zig/issues/12555

my first PR...😊
zig is great project.

2022-09-07 06:46 UTC, kkHAIKE commented
oh no, other bad case..
```
xxx(while (gen()) |x| b: {
    if (x == 0) break :b true;
} else false);
```

2022-09-08 09:24 UTC, Vexu requested changes
Needs a behavior test.

2022-09-08 10:06 UTC, Vexu commented
I don't know how that should be solved, I'd have to fix it myself to be able to help.

2022-09-10 05:00 UTC, kkHAIKE commented
@Vexu done. 😊

2022-09-10 14:22 UTC, Vexu requested changes

2022-09-10 14:22 UTC, Vexu commented on src/AstGen.zig
> +pub const ResultLocTag = enum {
```suggestion
pub const ResultLocTag = std.meta.Tag(ResultLoc);
```
I don't want this kind of repetition.

2022-09-10 14:22 UTC, Vexu commented on src/AstGen.zig
> +    /// otherwise it's work like none.
I don't understand what this does based on this comment. And why is it only in the then-scope?

2022-09-10 14:22 UTC, Vexu commented on test/compile_errors.zig
> +        const case = ctx.obj("issue 12455 while with switch", .{});
I'd prefer this be in a separate file like most other compile error tests.

2022-09-10 14:22 UTC, Vexu commented on test/behavior.zig
> +    _ = @import("behavior/bugs/11816_12551_12555.zig");
Please put this with the other `/bugs/`.

2022-09-10 14:22 UTC, Vexu commented on src/AstGen.zig
> +                    }
```suggestion
                    block_gz.setBreakResultLoc(prev_break_result_loc.only_break.unwrap());
```

2022-09-14 15:39 UTC, Vexu requested changes

2022-09-14 15:39 UTC, Vexu commented on src/AstGen.zig
> +    /// and only the `break` operands are the result values of loops.
```suggestion
    /// Used for loop bodies in which the result location only applies to
    /// the operands of break expressions.
```

2022-09-14 15:39 UTC, Vexu commented on src/AstGen.zig
> +                }
I think modifying the block's break result loc might lead to incorrect behavior with nested breaks like:
```zig
break :loop {
    if (cond) break :loop something;
}
```
Assigning `block_gz.break_result_loc` to a variable and then unwrapping if needed should avoid any issues.

2022-09-15 08:38 UTC, kkHAIKE commented
@Vexu OMG, i take quite a long way round. i make new PR for the new simple way.https://github.com/ziglang/zig/pull/12850

i'm so sorry for wasting your time.

2022-09-15 08:39 UTC, closed without merging