Properly handle --name with folder separators
ziglang/zig pull request #12932
Opened 2022-09-22 18:09 UTC by yujiri8

For #10501. Basic use case:
```
# (in build/)
stage3/bin/zig build-exe --name hello/a <source file>
```
Outputs to `hello/a`, or if `hello` doesn't exist, fails with `error: unable to open output directory 'hello': FileNotFound`

2022-10-11 16:22 UTC, Vexu requested changes
This doesn't seem like it would handle `--name foo/bar -fno-emit-bin -femit-h`, maybe it'd be better to do this check where `root_name` is declared or alternative where the `--name` flag is handled?

2022-10-13 11:32 UTC, Vexu commented
> created an empty folder `foo`

The point was that if such folder does not exist the compiler will exit with `error: FileNotFound`.

Also the usage text states that this isn't supposed to be a file path:
```
  --name [name]             Override root name (not a file path)
```

2022-10-13 15:14 UTC, yujiri8 commented
> Also the usage text states that this isn't supposed to be a file path:

So are you not supposed to be able to pass a file path as the --name? Or do you just mean I should update the usage text?

2022-10-13 15:58 UTC, Vexu commented
> So are you not supposed to be able to pass a file path as the --name?

That's how I understand it.

2022-10-15 01:45 UTC, yujiri8 commented
I guess then my whole PR was misguided and all that's needed is a better error message :/ I will get back to this

2022-10-15 02:18 UTC, yujiri8 commented
How about this change?

2022-10-15 02:30 UTC, yujiri8 commented
Mm, I wonder if there is a case with --pkg-begin that's still problematic...

2022-10-15 02:35 UTC, yujiri8 commented
So it allows package names with folder separators, but as it doesn't seem to result in any output files being written to subfolders, is this problematic behavior? I feel like it shouldn't be.

2022-10-17 11:04 UTC, Vexu commented
The name given to `--pkg-begin` does not interact with the filesystem in any way so it is not affected by this.

2022-10-17 11:06 UTC, merged