sema: load the correct AST in addFieldErrNote
ziglang/zig pull request #12951
Opened 2022-09-24 09:12 UTC by schmee

The enum we want to get the fields from might not be declared in the same file as the block we are analyzing, so we should get the AST from the decl's file instead.

Closes #12950.

2022-09-24 09:50 UTC, Vexu requested changes
`failWithInvalidComptimeFieldStore` does the same mistake, could you fix that too?

2022-09-24 09:50 UTC, Vexu commented on src/Sema.zig
> +    _ = block;
Remove the parameter instead.

2022-09-24 09:50 UTC, Vexu commented on test/cases/compile_errors/unhandled_enum_value_in_switch_with_enum_declared_in_other_file.zig
> +// :1361:19: note: enum 'math.Order' declared here
Use `:?:?:` so that this test doesn't break every time `math.zig` is slightly altered.

2022-09-26 07:19 UTC, schmee commented
@Vexu thanks for the reivew, updated 👍

2022-09-26 10:58 UTC, merged