std.c: fix incorrect return types
ziglang/zig pull request #12999
Opened 2022-09-28 16:52 UTC by alichraghi

Closes #12964

2022-09-28 20:46 UTC, matu3ba commented
Source https://pubs.opengroup.org/onlinepubs/009604499/functions/posix_spawnattr_destroy.html and https://pubs.opengroup.org/onlinepubs/009696699/functions/posix_spawn_file_actions_destroy.html

Only possible error value is
```
[EINVAL]
    The value specified by file_actions is invalid.
```

This is missing the usage fixups and on the `os/darwin.zig` side something like
```zig
posix_spawn_file_actions_destroy(..) catch |err| switch (err) {
    INVAL => unreachable,
} 
```
as convention is `Resource allocation may fail; resource deallocation must succeed.`.

2022-09-29 06:47 UTC, alichraghi commented
[`posix_spawn` uses `system` functions](https://ziglang.org/documentation/master/std/src/os/posix_spawn.zig#L50). which means it uses `c/darwin.zig`. if we want to use ziggified 

`posix_spawn_file_actions_destroy`, then `os.system` must be patched
```diff
pub const system = if (@hasDecl(root, "os") and root.os != @This())
    root.os.system
else if (builtin.link_libc or is_windows)
    std.c
else switch (builtin.os.tag) {
    .linux => linux,
    .wasi => wasi,
++  .macos, .watchos, .ios, .tvos => darwin,
    .uefi => uefi,
    else => struct {},
};
```
or just import and use `darwin` in `posix_spawn.zig`

2022-10-03 10:29 UTC, Vexu requested changes

2022-10-03 10:29 UTC, Vexu commented on lib/std/os/posix_spawn.zig
> +            }
If this is not expected to return any error then it'd be better to just make the else prong `unreachable`, see `std.os.munmap` for an example of this.

2022-10-13 11:21 UTC, merged