all: rename i386 to x86
ziglang/zig pull request #13101
Opened 2022-10-07 17:55 UTC by alichraghi

Closes #4663

2022-10-10 01:20 UTC, The-King-of-Toasters commented on tools/generate_linux_syscalls.zig
> +            // abi is always x86
epic grep fail

2022-11-03 14:57 UTC, Vexu requested changes

2022-11-03 14:57 UTC, Vexu commented on lib/std/zig/fmt.zig
> +    try std.testing.expect(isValidId("x86"));
Don't change this test.

2022-11-03 14:57 UTC, Vexu commented on lib/std/coff.zig
> +    X86 = 0x14c,
This shouldn't be changed.

2022-11-03 14:57 UTC, Vexu commented on lib/std/net/url.zig
> +pub fn main() void {
What's this doing here?

2022-11-03 15:01 UTC, Vexu commented
The CI failure should be fixed by running `tools/update_glibc.zig`.

2022-11-03 17:59 UTC, alichraghi commented
running `zig run tools/update_glibc.zig -- lib/libc/glibc/ .` didn't change anything

2022-11-03 18:10 UTC, Vexu commented
> ```
> //! This script updates the .c, .h, .s, and .S files that make up the start
> //! files such as crt1.o. Not to be confused with
> //! https://github.com/ziglang/glibc-abi-tool/ which updates the `abilists`
> //! file.
> ```

My bad.

2022-11-03 19:09 UTC, alichraghi commented
still failing but i think it's easy to fix. will try tomorrow

2022-11-04 07:03 UTC, alichraghi commented
hmm new error is so weird. `addIncludePath("test")` is there and `zig(2|3) translate-c test/behavior/translate_c_macros.h` successed

2022-11-04 14:42 UTC, Vexu commented
> hmm new error is so weird. `addIncludePath("test")` is there and `zig(2|3) translate-c test/behavior/translate_c_macros.h` successed

The issue was that it was looking for the wrong include directory which can be fixed by renaming it, but doing so makes me question the correctness of the abilist change.

2022-11-05 03:59 UTC, alichraghi commented
CI is green! let's merge this faster because it get conflicts everyday

2022-11-05 06:34 UTC, merged