stage2: implement packetStuctToInt for more types
ziglang/zig pull request #13124
Opened 2022-10-10 14:33 UTC by GethDW

Hopefully this implementation is correct. I'll happily add some tests given some hints on how/where to add tests for comptime evaluation.

2022-10-10 15:53 UTC, Vexu commented
Duplicate of #12849 which doesn't compile or handle vectors but has tests. If you add tests and the reverse direction and it compiles then I'll merge this over that.

2022-10-11 14:02 UTC, topolarity requested changes

2022-10-11 14:02 UTC, topolarity commented on src/value.zig
> +        const elem_size = @intCast(usize, elem_ty.abiSize(target));
Also see [this comment](https://github.com/ziglang/zig/pull/12947#discussion_r979143189) regarding the indexing on big-endian

2022-10-11 14:42 UTC, GethDW commented on test/behavior/bitcast.zig
> +    try expect(@bitCast(Int, S{}) == comptime @bitCast(Int, S{}));
Thanks, I'd convinced myself that it was already runtime.

2022-10-12 08:52 UTC, andrewrk commented
typo in the commit message
```diff
-packet
+packed
```

2022-10-18 11:05 UTC, merged