compiler_rt: update memcpy to compare usizes at a time
ziglang/zig pull request #13264
Opened 2022-10-22 18:12 UTC by nektro

cc @mikdusan noticed this improving stage2 compilation performance of stage3 by slightly more than 2x on macOS when using our own implementation

> libSystem.memcpy: 299.05 seconds
> memcpy.zig: 996.01 seconds
> memcpy_usize.zig: 443.22 seconds

2022-10-22 18:14 UTC, nektro commented
`memmove` can be modified to call this function

`memcpy` can be modified to use this same optimization

2022-10-22 19:44 UTC, Jarred-Sumner commented
Couldn't this use SIMD to go in chunks of 16/32 and copy that way? Should be straightforward with @Vector

2022-10-22 20:27 UTC, topolarity commented on lib/compiler_rt/memcpy.zig
> +    var dw = @ptrCast([*]usize, @alignCast(@alignOf(usize), d));
Is this alignCast correct?

Seems like it would depend on the alignment of `d + len`

2022-10-22 23:48 UTC, andrewrk requested changes
Thanks @nektro.

> Couldn't this use SIMD to go in chunks of 16/32 and copy that way? Should be straightforward with `@vector`

Yes, it should do that.

Another related issue is #1018 so that multiple copies of memcpy can be shipped and the best one depending on runtime cpu feature detection can be swapped in.

Any compiler_rt symbol improvement such as this must come with benchmark results and a clear guide for how the results can be reproduced.

2022-10-23 20:51 UTC, rohlem commented
Uhm, both the title and the code comment mention "comparing" usizes - that should read "copying", right?
Although 4 people have already looked at this, so maybe I'm bugging.

2022-10-23 21:01 UTC, nektro commented
no @rohlem you're right

2022-10-24 13:04 UTC, pqflx3 commented on lib/compiler_rt/memcpy.zig
> +    n = (len - off) / 8;
quick question: should `8` be `wsize`?

2022-10-24 17:14 UTC, nektro commented on lib/compiler_rt/memcpy.zig
> +    n = (len - off) / 8;
yep

2022-12-10 21:33 UTC, closed without merging