crypto.sha2: Use intrinsics for SHA-256 on x86-64 and AArch64
ziglang/zig pull request #13272
Opened 2022-10-23 07:05 UTC by topolarity

There's probably plenty of room to optimize these further in the future, but for the moment this gives ~3x improvement on Intel x86-64 processors, ~5x on AMD x86-64, and ~10x on M1 AArch64 Macs.

These extensions are very new. Most processors prior to 2020 do not support them.

P.S. @kubkon I haven't fixed the CPU features for LLVM in stage2 yet, but at least this gives you something to play with until that's sorted 🙂

2022-10-23 08:39 UTC, joachimschmidt557 commented
In future it would be nice if we use inline assembly instead of LLVM intrinsics to enable the self-hosted backends to use these features too.

2022-10-23 16:44 UTC, topolarity commented
> In future it would be nice if we use inline assembly instead of LLVM intrinsics to enable the self-hosted backends to use these features too.

Good point! Switched to inline asm for this PR.

In general, I think inline assembly can interact very differently with the optimizer versus intrinsics, but in this case it's actually a 20% win for x86-64: Intel is over 1 GB/s now (4x improvement vs. master)

2022-10-23 16:57 UTC, topolarity commented
Eugh... Intel x86-64 loves the new inline assembly, but AMD hates it:

```
intrinsics: 66870 us (1568.08 MB/s)
inline asm: 251760 us (416.50 MB/s)
```

I'll go digging through the assembly and see if I can figure out why.

2022-10-23 17:02 UTC, kubkon commented
> Eugh... Intel x86-64 loves the new inline assembly, but AMD hates it:
> 
> ```
> intrinsics: 66870 us (1568.08 MB/s)
> inline asm: 251760 us (416.50 MB/s)
> ```
> 
> I'll go digging through the assembly and see if I can figure out why.

What about arm64? Comparable, or ahead, or behind? If the latter, that's bad timing as I wanted to start testing it out in zld repo.

2022-10-23 17:03 UTC, topolarity commented
> What about arm64? Comparable, or ahead, or behind? If the latter, that's bad timing as I wanted to start testing it out in zld repo.

arm64 on my M1 mac is about the same (<5% delta)

2022-10-23 17:04 UTC, kubkon commented
> > What about arm64? Comparable, or ahead, or behind? If the latter, that's bad timing as I wanted to start testing it out in zld repo.
> 
> arm64 on my M1 mac is about the same (<5% delta)

Awesome! Thanks for confirming!

2022-10-23 17:22 UTC, kubkon commented
Is there any trick to building any of this locally? On my M1Pro I am getting:

```
error: <inline asm>:2:1: instruction requires: sha2
sha256h.4s v2, v1, v3
```

2022-10-24 05:41 UTC, Jarred-Sumner commented
not sure if helpful but I have a script that benches SHA hashing comparing BoringSSL's implementation to Zig's implementation

This is for an old build of Zig without this PR's changes `0.10.0-dev.2822+b79884eaf` on a Ryzen machine

```
[SHA256]

     zig: 3.292s
  boring: 518.223ms
     evp: 518.25ms
  evp in: 518.228ms
```

https://github.com/Jarred-Sumner/bun/blob/dea7cb14bdf0446fcb8a0750fe86b2056a7c3be0/src/sha.zig#L173-L230

2022-10-24 06:30 UTC, andrewrk commented
@kubkon what does `zig build-exe --show-builtin` output for you?

2022-10-24 06:59 UTC, kubkon commented
> @kubkon what does `zig build-exe --show-builtin` output for you?

```
pub const cpu: std.Target.Cpu = .{                                                                                                                                                                                                                                                                                                                   
    .arch = .aarch64,                                                                                                                                                                                                                                                                                                                                
    .model = &std.Target.aarch64.cpu.apple_a14,                                                                                                                                                                                                                                                                                                      
    .features = std.Target.aarch64.featureSet(&[_]std.Target.aarch64.Feature{                                                                                                                                                                                                                                                                        
        .aes,                                                                                                                                                                                                                                                                                                                                        
        .aggressive_fma,                                                                                                                                                                                                                                                                                                                             
        .alternate_sextload_cvt_f32_pattern,
        .altnzcv,
        .am,
        .arith_bcc_fusion,
        .arith_cbz_fusion,
        .ccdp,
        .ccidx,
        .ccpp,
        .complxnum,
        .contextidr_el2,
        .crc,
        .crypto,
        .disable_latency_sched_heuristic,
        .dit,
        .dotprod,
        .el2vmsa,
        .el3,
        .flagm,
        .fp16fml,
        .fp_armv8,
        .fptoint,
        .fullfp16,
        .fuse_address,
        .fuse_adrp_add,
        .fuse_aes,
        .fuse_arith_logic,
        .fuse_crypto_eor,
        .fuse_csel,
        .fuse_literals,
        .jsconv,
        .lor,
        .lse,
        .lse2,
        .mpam,
        .neon,
        .nv,
        .pan,
        .pan_rwv,
        .pauth,
        .perfmon,
        .predres,
        .ras,
        .rcpc,
        .rcpc_immo,
        .rdm,
        .sb,
        .sel2,
        .sha2,
        .sha3,
        .specrestrict,
        .ssbs,
        .tlb_rmi,
        .tracev8_4,
        .uaops,
        .v8_1a,
        .v8_2a,
        .v8_3a,
        .v8_4a,
        .v8a,
        .vh,
        .zcm,
        .zcz,
        .zcz_gp,
    }),
};
```

2022-10-24 13:29 UTC, kubkon approved these changes
Stellar work! Thanks @topolarity!

2022-10-25 04:07 UTC, daurnimator commented
Doesn't this make it impossible to do sha256 at comptime?

2022-10-25 18:08 UTC, jedisct1 commented
For hash functions, comptime-support can indeed be an important thing to have.

That leaves us with either dynamic dispatch (which doesn't match the rest, and the plan to eventually do it), or, as you pointed out, a way to check if the function is called at comptime or not.

Doing this, even with a hack as a starter, sounds like a much better route that duplicating every function to have a comptine variant.

2022-10-28 01:02 UTC, andrewrk commented
```
pub fn isComptime() bool {
    var t = true;
    var a: u8 = 0;
    var b: u16 = 0;
    const x = if (t) a else b;
    return @TypeOf(x) == u8;
}
```

2022-10-28 13:06 UTC, jedisct1 commented
That's a nice trick!

2022-10-28 22:05 UTC, andrewrk commented
> CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
> Please set them or make sure they are set and tested correctly in the CMake files:
> ZSTD

Hmm not sure what's up with the CI failures - I don't understand why this would be happening in this branch but not master branch.

2022-10-28 22:28 UTC, topolarity commented
> Are you sure this is rebased against master branch? 

Oops, I thought CI merged the PR branch into master automatically, but I see now that this doesn't apply changes to the CI script itself. 

Just pushed a proper rebase - should be ready for review/merge assuming it passes.

2022-10-29 00:01 UTC, andrewrk requested changes

2022-10-29 00:18 UTC, andrewrk commented
Re: the CI failures, I think

`!isComptime() and comptime std.Target.x86.featureSetHas(builtin.cpu.features, .sha)`

has to be changed to 

`comptime std.Target.x86.featureSetHas(builtin.cpu.features, .sha) and !isComptime()`

 See #6768 for more details.

2022-10-29 00:39 UTC, topolarity commented
Thanks for the review! Yep, #6768 took me by surprise.

Should be all fixed up now :+1:

2022-10-29 01:05 UTC, andrewrk approved these changes

2022-10-29 07:31 UTC, merged

2023-11-10 16:38 UTC, xcaptain commented
> > Doesn't this make it impossible to do sha256 at comptime?
> 
> Good point, I hadn't thought of that. Yeah, it breaks comptime evaluation for SHA-256.
> 
> Without #868 (or a related hack), the only way to fix that is to create a separate comptime method that users call at comptime. That means it's viral, too: Any function that calls SHA-256 must split into a comptime and runtime version, as well as their callers and so on.

I don't think it's necessary to add another comptime method. I made some changes like below and run 

```shell
zig test lib/std/std.zig --zig-lib-dir lib
```

![image](https://github.com/ziglang/zig/assets/4054836/e4cda677-9a55-4e2e-ab81-507e2f3071d7)

The tests built and passed. The hash functions should already support running at comptile time, no need to add another one, am I right?