mingw: add _vscprintf from upstream
ziglang/zig pull request #13759
Opened 2022-12-03 19:15 UTC by kcbanner

This allows x86 to build again: https://github.com/ziglang/zig/issues/13733

I pulled in `_vscprintf.c` file from the mingw64 repo, and exported the symbol. The history of that file in that repo has more info on why it needs to exist. I'm not sure what the `_vscprintf replaced by emu` comment referred to, as the commit adding that didn't add an emulated version. I may be missing some context here.

That being said, the test suite run with an x86-windows-gnu zig immediately segfaults so there may be more problems to address with x86:

```
LLVM Emit Object... Segmentation fault at address 0x3c
???:?:?: 0x76ca1708 in ??? (???)
???:?:?: 0x76ca174a in ??? (???)
C:\cygwin64\home\kcbanner\kit\zig\lib\std\Progress.zig:229:21: 0xdbd5d3 in refreshWithHeldLock (zig.exe.obj)
                info.wAttributes,
                    ^
C:\cygwin64\home\kcbanner\kit\zig\lib\std\Progress.zig:117:45: 0xc67e84 in end (zig.exe.obj)
            self.context.refreshWithHeldLock();
                                            ^
C:\cygwin64\home\kcbanner\kit\zig\src\Compilation.zig:2398:33: 0xca2fca in update (zig.exe.obj)
    defer main_progress_node.end();
                                ^
C:\cygwin64\home\kcbanner\kit\zig\src\Compilation.zig:5424:31: 0xdb7a6f in buildOutputFromZig (zig.exe.obj)
    try sub_compilation.update();
                              ^
C:\cygwin64\home\kcbanner\kit\zig\src\Compilation.zig:3420:22: 0xdba5cd in processOneJob (zig.exe.obj)
                &comp.libc_static_lib,
                     ^
C:\cygwin64\home\kcbanner\kit\zig\src\Compilation.zig:3092:30: 0xca5a4f in performAllTheWork (zig.exe.obj)
            try processOneJob(comp, work_item);
                             ^
C:\cygwin64\home\kcbanner\kit\zig\src\Compilation.zig:2401:31: 0xca1a24 in update (zig.exe.obj)
    try comp.performAllTheWork(main_progress_node);
                              ^
C:\cygwin64\home\kcbanner\kit\zig\src\main.zig:3376:20: 0xccef77 in updateModule (zig.exe.obj)
    try comp.update();
                   ^
C:\cygwin64\home\kcbanner\kit\zig\src\main.zig:3991:21: 0xbe9234 in cmdBuild (zig.exe.obj)
        updateModule(gpa, comp, .none) catch |err| switch (err) {
                    ^
C:\cygwin64\home\kcbanner\kit\zig\src\main.zig:261:24: 0xbbe13f in mainArgs (zig.exe.obj)
        return cmdBuild(gpa, arena, cmd_args);
                       ^
C:\cygwin64\home\kcbanner\kit\zig\src\stage1.zig:56:24: 0xd2ed6c in main (zig.exe.obj)
        stage2.mainArgs(gpa, arena, args) catch unreachable;
```

2022-12-10 00:56 UTC, andrewrk commented
Currently we have no patches against mingw-w64, and merging this branch would add a patch. I hope @mstorsjo doesn't mind if we ping him here and ask for a suggestion. Hi Martin - can you help us understand what `i386 _vscprintf replaced by emu` means here?

2022-12-20 22:45 UTC, mstorsjo commented
> Currently we have no patches against mingw-w64, and merging this branch would add a patch. I hope @mstorsjo doesn't mind if we ping him here and ask for a suggestion. Hi Martin - can you help us understand what `i386 _vscprintf replaced by emu` means here?

Sorry, I missed following up on this one (I had meant to do that much much sooner).

In most cases, functions are commented out from def files, because we don't want to link against the function from the DLL, but we provide a statically linked version of the function instead. This can either be because of missing functionality (e.g. msvcrt.dll functions that aren't C99 compliant), or for compatibility reasons. So the comments "replaced by emu" means "replaced with a statically linked reimplementation/stub/wrapper" (the word "emu" is somewhat vague/misleading here).

For the case of `_vscprintf`, it's because there are older versions of msvcrt.dll (on Windows 2000 and earlier, iirc) that lack this function. So instead of linking directly against it (and you get an executable that refuses to load on older versions of Windows), the import library provides a statically linked function (which tries to dynamically load the real one - and if unavailable, it falls back on a less efficient reimplementation of the same functionality). See e.g. https://github.com/mingw-w64/mingw-w64/commit/dd72602ea5. Since `_vscprintf` has been available since XP, and none of the other architectures (x86_64, arm, arm64) were available before XP, this compatibility kludge is only needed on i386 - on other architectures, the statically linked helper function is omitted, and the def file ends up containing the function so that it is linked directly.

For such functions, it's quite important to follow the logic in mingw-w64-crt's Makefile.am about which library the static functions go into. Originally most such static helper functions were in `libmingwex.a`, but over time, we've moved more and more of them to e.g. `libmsvcr*.a`. E.g. for the case of UCRT, we might want to link against the CRT's version of a function, while we might want to statically link a reimplementation when using the older legacy msvcrt.dll. If the statically linked functions are in `libmingwex.a`, they get used in all cases, while if they're in e.g. `libmsvcrt-os.a`, they only get used when using msvcrt.dll as CRT, but not for UCRT.

2022-12-28 09:25 UTC, andrewrk requested changes
Thanks @mstorsjo! That all makes a lot of sense.

Based on this information I can confidently review this PR now.

2022-12-28 09:25 UTC, andrewrk commented on lib/libc/mingw/lib-common/msvcrt.def.in
> +_vscprintf
Omit this change and then this PR is ready to be merged.

I tested this locally already.

2022-12-28 19:31 UTC, andrewrk commented
I also noticed that the file did not get properly copied from mingw-w64 v10.0.0 so I'm going to close this and open a fresh PR:

```diff
$ gd -w
diff --git a/lib/libc/mingw/stdio/_vscprintf.c b/lib/libc/mingw/stdio/_vscprintf.c
index a33547213..b859b9a2a 100644
--- a/lib/libc/mingw/stdio/_vscprintf.c
+++ b/lib/libc/mingw/stdio/_vscprintf.c
@@ -15,7 +15,7 @@ static int __cdecl emu_vscprintf(const char * __restrict__ format, va_list argli
 {
     char *buffer, *new_buffer;
     size_t size;
-    int ret = -1;
+    int ret;
 
     /* if format is a null pointer, _vscprintf() returns -1 and sets errno to EINVAL */
     if (!format) {
```

I'm guessing you grabbed this from master branch. We'll need to wait until mingw-w64 tags a new release before updating files beyond v10.0.0.

2022-12-28 19:31 UTC, closed without merging

2022-12-28 19:35 UTC, andrewrk commented
7350f0d9b5aecaf98998bc6591a649d9a7b7091f