Replace SipHash-1-3 with AEGIS128L MAC for the Cache
ziglang/zig pull request #13805
Opened 2022-12-07 13:54 UTC by jedisct1

The MAC function of AEGIS is much faster than SipHash-1.3 (~4 times faster on current Intel/ARM CPUs).

Should give a slight speedup when compiling large projects.

2022-12-08 05:43 UTC, lin72h commented
Very interesting, Thanks for working on this. Just curious, is it possible to extend the digest to 160 bit output, and use it as a SHA1 replacement? If so, does the strength of AEGIS can be used as git hashing purpose?

2022-12-08 10:19 UTC, jedisct1 commented
As specified, the output can only be 128 bits. An ad-hoc construction to get 256 bits would be to add 2x2 or 2x3 blocks of the state, but that wouldn't be compatible with the specification.

Still, AEGIS could be turned into a variable-length MAC. Absorb the input, then an empty block, encrypt a counter and use the resulting ciphertext as the MAC. But that would also require a proper specification before it gets in the Zig standard library.

That being said, `git` already supports SHA-256 (try `git init --object-format=sha256`).

2022-12-08 10:26 UTC, jedisct1 commented
[Ponteil](https://github.com/jedisct1/ponteil) is an example of an experimental AEGIS-based XOF. I would personally use it, but this is not something that can go into a standard library either, and even less something to use in Git (considering the fact that even getting the Git ecosystem to use SHA-256 seems to be a real challenge).

2022-12-08 12:01 UTC, lin72h commented
Ponteil seems to be the thing I'm asking for. Thanks. Like you said, it's impossible for the git ecosystem to switch even from sha1 to sha256, but the new [got](http://gameoftrees.org/) from the OpenBSD community, could switch to any hashing algorithm if there's a true performance advantage there.

2022-12-08 12:57 UTC, jedisct1 commented
It doesn't, since I don't have access to such CPUs.

So, there's still room for making it even faster.

2022-12-08 14:40 UTC, jedisct1 commented
Not a lot, TBH. AEGIS requires shifting the whole state by 128 bits, so keeping everything in 256 or 512 bits registers may be tricky.

2022-12-08 14:52 UTC, lin72h commented
If I remember correctly, AVX512 have 128bit rotation by combining 2 adjacent  64b registers. Really like the idea to reuse the primitive like gimli

2022-12-10 01:01 UTC, andrewrk requested changes
Nice, thank you for exploring this!

2022-12-10 01:01 UTC, andrewrk commented on src/main.zig
> +pub const side_channels_mitigations = .none;
What is this doing here? I don't see that this is read anywhere.

2022-12-10 01:03 UTC, andrewrk commented
> It doesn't, since I don't have access to such CPUs.

Good news- the CI server in fact does have the vaes feature and I'd be happy to get you set up with a user account so you can try it out.

2022-12-10 12:10 UTC, jedisct1 commented on src/main.zig
> +pub const side_channels_mitigations = .none;
This is to play well with https://github.com/ziglang/zig/pull/13739 - For the compiler itself, we can prioritize performance over side channels mitigations.

2022-12-12 16:00 UTC, jedisct1 commented on src/main.zig
> +pub const side_channels_mitigations = .none;
The global has been removed.

2022-12-12 16:33 UTC, lin72h commented
Good to know AVX2 also can do that. The AVX512 version  are [_mm512_maskz_shldv_epi64](https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#text=_mm512_maskz_shldv_epi64&ig_expand=6371,6317) [_mm512_maskz_shrdv_epi64](https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#text=_mm512_maskz_shrdv_epi64&ig_expand=6371)

2022-12-13 03:49 UTC, andrewrk commented
One more thing I want to check before merging this- unfortunately the performance of "baseline" matters to us since that is most commonly the CPU feature set that is targeted 

How does this hash perform compared to status quo on x86_64 baseline and aarch64 baseline? Each of these can be measured simply by passing an explicit `-target` parameter, like this: `-target x86_64-linux` or `-target aarch64-linux`

2022-12-13 08:22 UTC, jedisct1 commented
Damn, yes, until we get a proper way to do dynamic dispatch, we're limited to `baseline` performance.

And unfortunately, on `baseline`, AEGIS performs much worse than SipHash, that remains the fastest option

```text
   siphash128-1-3:       4505 MiB/s
   aegis-128l mac:        822 MiB/s
```

Closing, then. Something to possibly consider again once we can do dynamic dispatch.

2022-12-13 08:22 UTC, closed without merging

2022-12-13 09:58 UTC, jedisct1 commented
Or if we could use a secret key, that would allow usage of universal hash functions, that are provably secure and fast even on `baseline`.

2022-12-13 18:30 UTC, jedisct1 commented
@lin72h Here's an attempt at [a VAES/AVX2 implementation](https://github.com/jedisct1/aegis-vaes).

Unfortunately, it's actually slower than with 128-bit registers, due to the low throughput of `_mm256_permute2x128_si256()`. I don't think a Zig version would be different.

Can you think of a more efficient way of doing this?

As you pointed out, things may be better with AVX512, though.

2022-12-13 22:58 UTC, jedisct1 commented
Update: found a trick to avoid permutations. Stay tuned :)

2022-12-14 04:46 UTC, lin72h commented
@jedisct1 every exciting. This feature could be a top feature on the next release note

2022-12-14 04:50 UTC, lin72h commented
@andrewrk I think zig's **main** x86 target should be Intel haswell+, because it also mean all the AMD zen+ will be supported too.  And It's hard to find a cloud provider with a pre-haswell VM in the current Market.

Keep new feature like this away from merging in order to maintain the **baseline** x86(without AVX2) performance will make everything mediocre not great as it should be

2022-12-14 04:55 UTC, andrewrk commented
We have to care about other CPU architectures, too: RISC-V, ARM, and even virtual machines such as WebAssembly. For the purposes of choosing a cache hash algorithm, modern x86_64 and baseline x86_64 can be thought of merely as two more architectures in this list that must be considered. Consider it a weighted average with higher weights given to those ISAs that are more commonly used.

2022-12-14 04:59 UTC, lin72h commented
I understand your concern to make zig really shine as a cross platform solution. But for this PR, the AES is well-supported, I think this is the reason why Frank picked it for the first place. Arm, RISCV, even microcontroller(The [new IoT standard](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwiiiKCPqfj7AhVKM94KHWULB9wQFnoECAwQAQ&url=https%3A%2F%2Fgithub.com%2Fproject-chip%2Fconnectedhomeip&usg=AOvVaw1gNTiNJaSTngzW-P4tbPg_) requires AES.

2022-12-14 08:23 UTC, jedisct1 commented
@lin72h Hashing files is a just tiny part of what the compiler does.

Certainly, having a faster hash function would be good, but the status quo is fine; it's decently fast on all platforms, The performance of the zig compiler on baseline is certainly not "mediocre".

An AES-based function (or even a CLMUL-based one) can still be selected at comptime if the compiler is specifically built for an architecture that supports acceleration.

An alternative would be to use a universal hash function such as vhash or [sthash](https://github.com/jedisct1/rust-sthash), that are provably secure, are very fast on all platforms, but really require a secret key.

2022-12-14 14:42 UTC, jedisct1 commented
@lin72h clhash is great, but is slow without hardware carryless multiplication. Incidentally, CPUs with hardware carryless multiplication are the same as those with AES acceleration.

This is also a universal hash function, that requires a secret key to not immediately break in an adversarial context. Furthermore, clash's output is only 64 bits, which doesn't make it collision-resistant.

Also check out [umash](https://github.com/backtrace-labs/umash).

2022-12-14 14:58 UTC, lin72h commented
Great, Thanks for the link. I got some night reading material tonight

2022-12-15 00:18 UTC, andrewrk commented
> An alternative would be to use a universal hash function such as vhash or [sthash](https://github.com/jedisct1/rust-sthash), that are provably secure, are very fast on all platforms, but really require a secret key.

I'm confused, what exactly do you mean by require a secret key? From whom is the secret being kept? How about a hard-coded (fixed, publicly-known, not secret) random string of bytes for the secret key?

2022-12-15 10:25 UTC, jedisct1 commented
@andrewrk What I mean here is a random secret key, generated when the cache is created.

If the key is public, anyone can trivially create files causing collisions. This is a concern when importing git submodules and for the future package manager.

2022-12-15 11:30 UTC, andrewrk commented
OK I understand the threat model now. Attacker could create malicious code that hashes the same as a popular library, and then if victim compiles the attacker's code, it could remain active due to a false positive cache hit even after the victim has deleted the attacker's code and replaced it with the intended package.

Let us explore this option then. There is already an abstraction that can be used for reading/writing a small file which can be used to store the secret key:

https://github.com/ziglang/zig/blob/077b003c50065a8b193dcad793ca5c4474222af6/src/Cache.zig#L930-L952