expose VcpkgRoot so that build script can call exe.addVcpkgPath
ziglang/zig pull request #13924
Opened 2022-12-13 12:16 UTC by Jack-Ji

2022-12-13 12:19 UTC, fabioarnold commented
Maybe add a test to LibExeObjStep.zig like this so it doesn't break in the future again?

```
test "addVcpkgPaths" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();

    var builder = try Builder.create(
        arena.allocator(),
        "test",
        "test",
        "test",
        "test",
    );
    defer builder.destroy();

    var exe = builder.addExecutable("not_an_executable", "/not/an/executable.zig");
    exe.addVcpkgPaths(.dynamic) catch |err| {
        if (err != error.VcpkgNotFound) {
            return err;
        }
    };
}
```

2022-12-13 12:34 UTC, Jack-Ji commented
> Maybe add a test to LibExeObjStep.zig like this so it doesn't break in the future again?
> 
> ```
> test "addVcpkgPaths" {
>     var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
>     defer arena.deinit();
> 
>     var builder = try Builder.create(
>         arena.allocator(),
>         "test",
>         "test",
>         "test",
>         "test",
>     );
>     defer builder.destroy();
> 
>     var exe = builder.addExecutable("not_an_executable", "/not/an/executable.zig");
>     exe.addVcpkgPaths(.dynamic) catch |err| {
>         if (err != error.VcpkgNotFound) {
>             return err;
>         }
>     };
> }
> ```

Good idea, it's done [2193fe4](https://github.com/ziglang/zig/pull/13924/commits/2193fe49bf71475c0358e0d6a7c8721e2abb28d3)

2022-12-13 22:00 UTC, fabioarnold commented on lib/std/build/LibExeObjStep.zig
> +test "addVcpkgPaths" {
```suggestion
test "addVcpkgPaths" {
    if (builtin.os.tag == .wasi) return error.SkipZigTest;

```
Sorry, missed the skip for wasi.

2022-12-13 23:18 UTC, andrewrk requested changes
I don't think this test is particularly valuable because it's only testing package not found. I'm ok with merging this without a new test, but if we're going to add tests for vcpkg then I think it should be a proper integration test which is out of scope for this PR.

2022-12-14 00:13 UTC, Jack-Ji commented
OK, I think I understand your concern. Should I make a new clean PR, or change this one directly? @andrewrk

2022-12-14 00:19 UTC, merged