Optimize access of array member in a structure.
ziglang/zig pull request #13972
Opened 2022-12-16 08:49 UTC by shwqf

This change adds a simple pattern match for a short AIR sequence of 'struct_field_ptr -> load -> array_elem_val', and generates same LLVM IR as the sequence of 'struct_field_ptr -> ptr_elem_ptr -> load'.

Although this change will still generate CallInst of Memcpy, LLVM will successfully identify the CallInst as dead code and eliminate it, preventing unuseful memcpy of the array field.

Resolves https://github.com/ziglang/zig/issues/13938

2022-12-16 13:52 UTC, matu3ba commented on test_io_uring_renameat_old
> +hello
What is this?

2022-12-16 14:39 UTC, Vexu commented
It is good to fix things like this but doing it in `llvm.zig` means that it either has to be implemented for every backend or that it needs to be reimplemented in an earlier stage of the compiler.

2022-12-16 16:03 UTC, shwqf commented on test_io_uring_renameat_old
> +hello
.....mistake

2022-12-16 16:09 UTC, shwqf commented
> It is good to fix things like this but doing it in `llvm.zig` means that it either has to be implemented for every backend or that it needs to be reimplemented in an earlier stage of the compiler.



> It is good to fix things like this but doing it in `llvm.zig` means that it either has to be implemented for every backend or that it needs to be reimplemented in an earlier stage of the compiler.

I am familiar with LLVM, so I changed llvm.zig first. I will try to optimize it in Sema.zig tomorrow.

2022-12-16 16:12 UTC, Vexu commented
> I am familiar with LLVM, so I changed llvm.zig first. I will try to optimize it in Sema.zig tomorrow.

Note that it is not a blocker for this PR since the other backends (besides maybe the C backend) are not ready for use.

2022-12-16 16:16 UTC, shwqf commented
> > I am familiar with LLVM, so I changed llvm.zig first. I will try to optimize it in Sema.zig tomorrow.
> 
> Note that it is not a blocker for this PR since the other backends (besides maybe the C backend) are not ready for use.

lol, it would be great if we have a LLVM-like pipeline for AIR

2022-12-16 16:50 UTC, IntegratedQuantum commented
> Although this change will still generate CallInst of Memcpy, LLVM will successfully identify the CallInst as dead code and eliminate it

Does that also work in debug mode?
Because if it doesn't and the debug performance is still 10000 times worse, then this PR wouldn't help me(being the author of #13938) since I want to be able to test my program in debug mode.

2022-12-17 05:03 UTC, shwqf commented
> > Although this change will still generate CallInst of Memcpy, LLVM will successfully identify the CallInst as dead code and eliminate it
> 
> Does that also work in debug mode? Because if it doesn't and the debug performance is still 10000 times worse, then this PR wouldn't help me(being the author of #13938) since I want to be able to test my program in debug mode.

Now it can

2022-12-19 08:18 UTC, matu3ba commented
Can you rebase on top of master and run zig fmt? It fails:
```
-- Install configuration: "Debug"
+ echo Looking for non-conforming code formatting...
Looking for non-conforming code formatting...
+ stage3-debug/bin/zig fmt --check .. --exclude ../test/cases/ --exclude ../build-debug
../src/codegen/llvm.zig
Error: Process completed with exit code 1.
```

2022-12-20 08:03 UTC, shwqf commented
> Can you rebase on top of master and run zig fmt? It fails:
> 
> ```
> -- Install configuration: "Debug"
> + echo Looking for non-conforming code formatting...
> Looking for non-conforming code formatting...
> + stage3-debug/bin/zig fmt --check .. --exclude ../test/cases/ --exclude ../build-debug
> ../src/codegen/llvm.zig
> Error: Process completed with exit code 1.
> ```

fixed

2022-12-20 14:40 UTC, Vexu approved these changes

2022-12-22 21:34 UTC, andrewrk requested changes
Thank you for sending this enhancement.

In the future, I want to implement #13265. This will make the LLVM backend no longer use the LLVM IR builder API and instead output bitcode directly. Under such circumstances, we will not have access to these C++ APIs, or this SSA structure that LLVM creates. This patch takes us further away from that goal, and so I request that the optimization be done without doing either of these things:

 * Introducing new C++ code
 * Depending on more of LLVM's API surface area

2022-12-23 03:12 UTC, shwqf commented
> Thank you for sending this enhancement.
> 
> In the future, I want to implement #13265. This will make the LLVM backend no longer use the LLVM IR builder API and instead output bitcode directly. Under such circumstances, we will not have access to these C++ APIs, or this SSA structure that LLVM creates. This patch takes us further away from that goal, and so I request that the optimization be done without doing either of these things:
> 
> * Introducing new C++ code
> * Depending on more of LLVM's API surface area

The new C++ code is for removing useless memcpy in debug mode, LLVM can optimize it automatically in release mode.  We at least need to introduce 'LLVMInstructionEraseFromParent' for this small optimization.

2022-12-23 08:56 UTC, Vexu commented
> * Introducing new C++ code
> 
> * Depending on more of LLVM's API surface area

One possible but slightly harder solution would be to implement this in AstGen.

2022-12-23 14:36 UTC, shwqf commented
> > * Introducing new C++ code
> > * Depending on more of LLVM's API surface area
> 
> One possible but slightly harder solution would be to implement this in AstGen.

I tried but I found AST is untyped.

2022-12-23 15:15 UTC, Vexu commented
Types are not needed to fix this, field access can result in a pointer via `field_ptr` and array access can take a pointer with `elem_ptr` and then turn it into a value using `load`. The issue is that currently AstGen uses `field_val` and `elem_val` and then relies on LLVM to fix it.

2022-12-23 16:09 UTC, shwqf commented
> Types are not needed to fix this, field access can result in a pointer via `field_ptr` and array access can take a pointer with `elem_ptr` and then turn it into a value using `load`. The issue is that currently AstGen uses `field_val` and `elem_val` and then relies on LLVM to fix it.

How can we tell if a field is a **slice** or an **array**?

My first implementation is in AstGen as you suggest, statg3 cannot be compiled.

2022-12-23 16:55 UTC, Vexu commented
`elem_ptr` works for all indexable types including arrays and slices.

2022-12-25 04:35 UTC, shwqf commented
I got COVID, too tired to continue to finish AstGen version. 

I remove the redundant C++ code, now this PR only work in non-Debug mode.

@Vexu @matu3ba @andrewrk

2023-05-11 07:01 UTC, matu3ba commented
Can you rebase on top of master? The tests fail at Autodoc before llvm, so that should fix them.

2023-05-11 11:52 UTC, matu3ba commented
I think you need to apply `zig fmt`:
```
+ echo Looking for non-conforming code formatting...
+ stage3-debug/bin/zig fmt --check .. --exclude ../test/cases/ --exclude ../build-debug
Looking for non-conforming code formatting...
../lib/std/c/darwin.zig
Error: Process completed with exit code 1.
```

2023-05-12 06:04 UTC, merged