Use aligned_alloc instead of malloc for aligned memory allocation.
ziglang/zig pull request #14090
Opened 2022-12-27 19:58 UTC by kimshrier

The code in lib/std/heap.zig uses malloc for a memory allocation that needs to be aligned to the requirements of std.c.max_align_t.  Malloc makes no guarantee about the alignment of memory that it returns.  The existing code does a run-time check to make sure that the proper alignment has been achieved and panics if it is not properly aligned.

The means that memory allocation at this point in the code works by accident.  This is something I would think is undesirable.

There is a standard memory allocation function, aligned_alloc, that does exactly what is needed.  The only caveat is that the length of the allocated memory needs to be a multiple of the alignment.  Behavior is undefined if this is not true.  That is the reason that I adjust the value of len if it isn't already a multiple of the alignment.

2022-12-27 20:34 UTC, matu3ba commented
> There is a standard memory allocation function, aligned_alloc, that does exactly what is needed. The only caveat is that the length of the allocated memory needs to be a multiple of the alignment. Behavior is undefined if this is not true. That is the reason that I adjust the value of len if it isn't already a multiple of the alignment.

From https://en.cppreference.com/w/c/memory/aligned_alloc:
```
Passing a size which is not an integral multiple of alignment or an alignment which is not valid or not supported by the implementation causes the function to fail and return a null pointer (C11, as published, specified undefined behavior in this case, this was corrected by DR 460). Removal of size restrictions to make it possible to allocate small objects at restrictive alignment boundaries (similar to [alignas](https://en.cppreference.com/w/c/language/_Alignas)) has been proposed by [n2072](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n2072.htm).
```
As I understand it, the unnecessary UB has been fixed in C17 in https://www.open-std.org/jtc1/sc22/wg14/www/docs/n2244.htm#dr_460.

2022-12-27 20:43 UTC, matu3ba reviewed
The FreeBSD stuff, which feels like belongs into a separate PR with proper explanations.

> Malloc makes no guarantee about the alignment of memory that it returns.

From https://en.cppreference.com/w/c/memory/malloc:
"If allocation succeeds, returns a pointer that is suitably aligned for any object type with [fundamental alignment](https://en.cppreference.com/w/c/language/object#Alignment)."

>  The existing code does a run-time check to make sure that the proper alignment has been achieved and panics if it is not properly aligned.

How is aligned_alloc different other than returning NULL?

2022-12-27 20:43 UTC, matu3ba commented on lib/std/heap.zig
> +    // of the allignment.
s/allignment/alignment

2022-12-27 20:43 UTC, matu3ba commented on lib/std/heap.zig
> +    const adjustedLen = if (len % @alignOf(std.c.max_align_t) == 0) len else (len + (@alignOf(std.c.max_align_t) - (len % @alignOf(std.c.max_align_t))));
s/adjustedLen/adjusted_len

2022-12-27 20:43 UTC, matu3ba commented on CMakeLists.txt
> +if(CMAKE_SYSTEM_NAME STREQUAL "FreeBSD" AND ZIG_STATIC)
This FreeBSD stuff belongs into another PR or the PR should explain the fix properly with problem, fix and outcome.

2022-12-28 10:39 UTC, LemonBoy commented
The `raw_c_allocator` is/was meant to be a thin wrapper over `malloc` and `free`, to be used in cases where you're confident not to need weird alignments and hit that assertion. `c_allocator` is the real deal and, as specified in #6385, it uses `posix_memalign` where available or tries to emulate it using the plain old overallocating `malloc` trick (which is exactly what `aligned_alloc` does, see [musl's implementation](https://git.musl-libc.org/cgit/musl/tree/src/malloc/mallocng/aligned_alloc.c?h=v1.2.2) ).

2022-12-28 18:18 UTC, kimshrier commented
The problem is that this assertion is being hit 100% of the time when running the stage3 compiler on FreeBSD.

A simple command showing the problem.
```
$ stage3/bin/zig build -h
thread 189880 panic: incorrect alignment
/home/kim/Projects/zig/from_github/zig/lib/std/heap.zig:185:65: 0x5a3d8e in rawCAlloc (zig)
    const ptr = @alignCast(@alignOf(std.c.max_align_t), c.malloc(len));
                                                                ^
/home/kim/Projects/zig/from_github/zig/lib/std/mem/Allocator.zig:86:34: 0x6053d7 in allocAdvancedWithRetAddr__anon_6134 (zig)
    return self.vtable.alloc(self.ptr, len, ptr_align, ret_addr);
                                 ^
/home/kim/Projects/zig/from_github/zig/lib/std/mem/Allocator.zig:192:41: 0x727bb5 in alignedAlloc__anon_40268 (zig)
    return self.allocAdvancedWithRetAddr(T, alignment, n, @returnAddress());
                                        ^
/home/kim/Projects/zig/from_github/zig/lib/std/array_list.zig:380:67: 0x72d9af in ensureTotalCapacityPrecise (zig)
                const new_memory = try self.allocator.alignedAlloc(T, alignment, new_capacity);
                                                                  ^
/home/kim/Projects/zig/from_github/zig/lib/std/array_list.zig:356:51: 0x6047dd in ensureTotalCapacity (zig)
            return self.ensureTotalCapacityPrecise(better_capacity);
                                                  ^
/home/kim/Projects/zig/from_github/zig/lib/std/array_list.zig:391:60: 0x5a4114 in ensureUnusedCapacity (zig)
            return self.ensureTotalCapacity(self.items.len + additional_count);
                                                           ^
/home/kim/Projects/zig/from_github/zig/lib/std/array_list.zig:229:48: 0x5a0309 in appendSlice (zig)
            try self.ensureUnusedCapacity(items.len);
                                               ^
/home/kim/Projects/zig/from_github/zig/lib/std/fs/path.zig:679:39: 0x61c463 in resolvePosix (zig)
                try result.appendSlice(component);
                                      ^
/home/kim/Projects/zig/from_github/zig/lib/std/fs/path.zig:458:28: 0x6289f6 in resolve (zig)
        return resolvePosix(allocator, paths);
                           ^
/home/kim/Projects/zig/from_github/zig/src/Module.zig:4978:35: 0x8b26fc in importFile (zig)
        cur_pkg_dir_path, cur_file.sub_file_path, "..", import_string,
                                  ^
/home/kim/Projects/zig/from_github/zig/src/Compilation.zig:3457:42: 0x9ac7e8 in workerAstGenFile (zig)
                break :blk mod.importFile(file, import_path) catch continue;
                                         ^
/home/kim/Projects/zig/from_github/zig/src/ThreadPool.zig:87:39: 0x7b9181 in runFn (zig)
            @call(.auto, func, closure.arguments);
                                      ^
/home/kim/Projects/zig/from_github/zig/src/ThreadPool.zig:126:28: 0x7468d0 in worker (zig)
            runFn(&run_node.data);
                           ^
/home/kim/Projects/zig/from_github/zig/lib/std/Thread.zig:393:13: 0x95211a in callFn__anon_86509 (zig)
            @call(.auto, f, args);
            ^
/home/kim/Projects/zig/from_github/zig/lib/std/Thread.zig:666:30: 0x74723c in entryFn (zig)
                return callFn(f, args_ptr.*);
                             ^
???:?:?: 0x80c623839 in ??? (???)
???:?:?: 0x0 in ??? (???)
Abort trap (core dumped)
```

It looks like the zig function alignedAlloc in std/mem/Allicator.zig is calling self.allocAdvancedWithRetAddr which calls self.rawAlloc which calls self.vtable.alloc.  It looks to me that the alloc function pointed to in self.vtable should not be rawCAlloc.  Is this where the fix should be made?  What would be the appropriate function to use here?

2022-12-28 20:23 UTC, Vexu commented
> The problem is that this assertion is being hit 100% of the time when running the stage3 compiler on FreeBSD.

There is a check in `main.zig` that selects between `c_allocator` and `raw_c_allocator`, it sounds like FreeBSD should force `c_allocator`.
https://github.com/ziglang/zig/blob/7350f0d9b5aecaf98998bc6591a649d9a7b7091f/src/main.zig#L165-L170

2022-12-29 09:23 UTC, LemonBoy commented
What's the `sizeof` and `alignof` (using GCC/Clang) of `max_align_t` on FreeBSD?

2022-12-29 10:38 UTC, The-King-of-Toasters commented
It's `32` and `16` on x86_64 and aarch64.

2022-12-29 11:54 UTC, LemonBoy commented
Eh, that's weird. If the alignment and size of `std.c.max_align_t` match the C counterpart I'd expect the `malloc`-d pointer to be 0x10 aligned and the `aligncast` to succeed.

2022-12-30 03:19 UTC, andrewrk requested changes

2022-12-30 03:19 UTC, andrewrk commented on src/main.zig
> +        }
please add a comment explaining why this is done

2022-12-30 03:26 UTC, closed without merging