langref: fix unclosed and lonely tag
ziglang/zig pull request #14250
Opened 2023-01-09 16:40 UTC by Techatrix

Previously the number of `<p>` and `</p>` where not the same.
Line 5588 has no closing tag and there is a lone tag on line 9414.

2023-01-09 19:16 UTC, andrewrk commented
The CI runs tidy on the lang ref, we should figure out why this wasn't caught by it

2023-01-10 05:16 UTC, tato commented
> A p element's end tag may be omitted if the p element is immediately followed by an address, article, aside, blockquote, details, div, dl, fieldset, figcaption, figure, footer, form, h1, h2, h3, h4, h5, h6, header, hgroup, hr, main, menu, nav, ol, p, pre, section, table, or ul element, or if there is no more content in the parent element and the parent element is an HTML element that is not an a, audio, del, ins, map, noscript, or video element, or an autonomous custom element.

https://html.spec.whatwg.org/multipage/syntax.html#syntax-tag-omission

2023-01-10 05:28 UTC, andrewrk requested changes

2023-01-10 05:28 UTC, andrewrk commented on doc/langref.html.in
>        {#syntax#}@Type{#endsyntax#} is not available for {#link|Functions#}.
```suggestion
<p>
      {#syntax#}@Type{#endsyntax#} is not available for {#link|Functions#}.
      </p>
```

2023-01-10 23:02 UTC, merged