wasm: implement float operations with compiler-rt
ziglang/zig pull request #14668
Opened 2023-02-17 16:39 UTC by Techatrix

This implements the majority of floating-point operations on the native webassembly backend by either calling into compiler-rt or directly emitting instructions if available.
Prior to this, operations on `f16` were implemented using a round trip to `f32` (which is why I had to change the archive test).

2023-02-17 16:59 UTC, Luukdegram commented
Nice work! I like what you did with building the operands programmatically. I’ll do a proper review this weekend.

2023-02-18 14:04 UTC, Luukdegram requested changes

2023-02-19 19:39 UTC, Techatrix commented on src/arch/wasm/CodeGen.zig
> +fn buildTrunc(func: *CodeGen, operand: WValue, wanted_ty: Type, given_ty: Type) InnerError!WValue {
I got confused with the `trunc` field in `FloatOp` thanks to ZLS's highlighting.

2023-02-19 22:45 UTC, Techatrix commented on src/arch/wasm/CodeGen.zig
> -            try func.addTag(.f64_promote_f32);
Using `f64_promote_f32` when casting `f16` to `f64` was also faster when i tested it.

This is how I implemented all float casts.

| given | wanted | instructions  |
|-------|--------|---------------|
|  f16  |  f32   | __extendhfsf2 |
|  f16  |  f64   | __extendhfsf2, f64_promote_f32 |
|  f16  |  f80   | __extendhfxf2 |
|  f16  |  f128  | __extendhftf2 |
|  f32  |  f64   | f64_promote_f32 |
|  f32  |  f80   | f64_promote_f32, __extenddfxf2 |
|  f32  |  f128  | f64_promote_f32, __extenddftf2 |
|  f64  |  f80   | __extenddfxf2 |
|  f64  |  f128  | __extenddftf2 |
|  f80  |  f128  | __extendxftf2 |
|  f32  |  f16   | __truncsfhf2 |
|  f64  |  f16   | f32_demote_f64, __truncsfhf2 |
|  f80  |  f16   | __truncxfhf2 |
|  f128 |  f16   | __trunctfhf2 |
|  f64  |  f32   | f32_demote_f64 |
|  f80  |  f32   | __truncxfdf2, f32_demote_f64 |
|  f128 |  f32   | __trunctfdf2, f32_demote_f64 |
|  f80  |  f64   | __truncdfxf2 |
|  f128 |  f64   | __truncdftf2 |
|  f128 |  f80   | __truncxftf2 |

2023-02-21 08:05 UTC, Luukdegram requested changes
Thank you for taking the time to verify Wasm instruction vs compiler-rt call. Apologies for the nitpicking but I think this is almost ready to be merged with just those last changes.

ps: If you rebase on top of master instead of merging master into your branch we can keep the commit history clean :)

2023-02-21 08:05 UTC, Luukdegram commented on src/arch/wasm/CodeGen.zig
> +        current_ty = Type.f64;
I find this pattern quite error-prone and hard to read. I think keeping the very original code with only the `TODO` branch updated to make use of the dynamic compiler-rt call keeps it much more clear. e.g:
```zig
fn fpext(func: *CodeGen, operand: WValue, given: Type, wanted: Type) InnerError!WValue {
    const given_bits = given.floatBits(func.target);
    const wanted_bits = wanted.floatBits(func.target);

    if (wanted_bits == 64 and given_bits == 32) {
        try func.emitWValue(operand);
        try func.addTag(.f64_promote_f32);
        return WValue{ .stack = {} };
    } else if (given_bits == 16) {
        // call __extendhfsf2(f16) f32
        const f32_result = try func.callIntrinsic(
            "__extendhfsf2",
            &.{Type.f16},
            Type.f32,
            &.{operand},
        );

        if (wanted_bits == 32) {
            return f32_result;
        }
        if (wanted_bits == 64) {
            try func.addTag(.f64_promote_f32);
            return WValue{ .stack = {} };
        }
    }

     // put the dynamic call to compiler-rt here
}
```

Repeating some code to keep it clear is always a winner compared to trying to be clever in my books.

2023-02-21 08:05 UTC, Luukdegram commented on src/arch/wasm/CodeGen.zig
> +        current_ty = Type.f32;
Same as above, let's keep the original code (pre-PR) with just the `TODO` replaced with the dynamic compiler-rt call.

2023-02-21 08:05 UTC, Luukdegram commented on src/arch/wasm/CodeGen.zig
> -            try func.addTag(.f64_promote_f32);
Thank you for verifying, much appreciated!

2023-02-25 06:47 UTC, Luukdegram approved these changes

2023-03-01 08:00 UTC, andrewrk commented
I disagree with using a compiler-rt function when there is a directly supported wasm operation. If the compiler-rt function is faster than the native operation, that is a problem with the wasm runtime being used. Zig is not in the business of caring about which wasm runtimes are being used. It only cares about outputting semantically correct wasm code. How did you check if it was "faster" anyway? Are you sure that there isn't a runtime in existence where the native operation performs better?

2023-03-01 08:53 UTC, Techatrix commented
> I disagree with using a compiler-rt function when there is a directly supported wasm operation. 

Maybe I am misunderstanding what is being meant by "directly supported wasm operation" but as an example, there is no single wasm instruction that computes f16 addition or a logarithm on any float size. If there an instruction is available like f32 multiplication or f64 square root, the code-gen i wrote will use them instead of calling into compiler-rt functions.

> If the compiler-rt function is faster than the native operation, that is a problem with the wasm runtime being used. Zig is not in the business of caring about which wasm runtimes are being used. It only cares about outputting semantically correct wasm code. How did you check if it was "faster" anyway? Are you sure that there isn't a runtime in existence where the native operation performs better?

If i recall correctly, the discussion that I had with Luukdegram was not about whether or not to use a native wasm instruction instead of compiler-rt, but instead about whether it would be beneficial to use certain wasm instructions so that we can use a different but faster compiler-rt function.

One of them was using  `__extendhfsf2` followed by a `f64.promote_f32` instead of directly using `__extendhfdf2` to convert a f16 to f64. If needed, I can elaborate on that but in short, `__extendhfdf2` has a few more instructions than `__extendhfsf2` than could avoided by using `f64.promote_f32` which was turned out to be faster. Of course less instructions doesn't necessarily mean faster and different wasm runtimes may behave differently, but it doesn't sound like this is what you were referring to when  you disagreed, right?

2023-03-07 10:12 UTC, Luukdegram commented
> I disagree with using a compiler-rt function when there is a directly supported wasm operation. If the compiler-rt function is faster than the native operation, that is a problem with the wasm runtime being used. Zig is not in the business of caring about which wasm runtimes are being used. It only cares about outputting semantically correct wasm code. How did you check if it was "faster" anyway? Are you sure that there isn't a runtime in existence where the native operation performs better?

As @Techatrix mentioned, this PR always prioritizes native Wasm instructions over compiler-rt. It only falls back to a compiler-rt call when such instruction does not exist (e.g. f16->f32 uses compiler-rt, whereas f32->f64 uses a native Wasm instruction). Does this clear up any confusion? I'd like to see this merged but won't take any action unless you're satisfied with the chosen solution also.

2023-04-07 16:22 UTC, Luukdegram commented
Thank you for your patience, my break took a bit long than originally anticipated. Great work, I'm confident in the solution that was implemented so will give this a merge.

2023-04-07 16:22 UTC, merged