Linker: -z<arg> should be equivalent to -z <arg>
ziglang/zig pull request #14680
Opened 2023-02-19 21:57 UTC by jedisct1

`lld` accepts both syntaxes, but we were rejecting (and, before 3f7e9ff597a3514bb1c4f1900027c40682ac9f13, ignoring) the former.

In particular, `cargo-zigbuild` was broken since Rust unconditionally [adds](https://github.com/rust-lang/rust/blame/7aa413d59206fd511137728df3d9e0fd377429bd/compiler/rustc_codegen_ssa/src/back/linker.rs#L761) `-znoexecstack` (not `-z noexecstack`) on non-Windows platforms.

2023-02-19 22:59 UTC, andrewrk requested changes
Thanks!

Found a bug.

Related: #14663

2023-02-19 22:59 UTC, andrewrk commented on src/main.zig
> +                    var z_arg = mem.trimLeft(u8, arg, "-z");
`mem.trimLeft` would additionally strip the 'z' from "-zzoo" resulting in "oo".

```suggestion
                    var z_arg = arg[2..];
```

2023-02-20 16:15 UTC, merged

2023-02-21 08:01 UTC, motiejus commented
I tried to do this before, but was given a good question by @Luukdegram here: https://github.com/ziglang/zig/pull/11669#issuecomment-1133006342

... and then changed Go to do the right (/documented) thing instead. Should we consider fixing cargo-zigbuild instead?

2023-02-21 13:28 UTC, jedisct1 commented
@motiejus Not a big fan of having multiple ways to do the same thing either. But being compatible with `lld`, especially for quirks that are widely used in the wild, is probably not a bad thing. It makes it easier to use `zig cc` as a drop-in replacement for `clang`, and can only encourage adoption.

`-znoexecstack` doesn't come from `cargo-zigbuild` but from Rust itself. So, `cargo-zigbuild` would have to implement a hack that parses and rewrite `-z` linker flags. Given how trivial and non-intrusive supporting this directly in Zig is, I'd rather fix it as that layer, rather than adding a hack to one specific 3rd-party tool.

2023-02-21 13:37 UTC, motiejus commented
> `-znoexecstack` doesn't come from `cargo-zigbuild` but from Rust itself. So, `cargo-zigbuild` would have to implement a hack that parses and rewrite `-z` linker flags.

I meant fix the source where the flag is added before passed to cargo-zigbuild.

> Given how trivial and non-intrusive supporting this directly in Zig is, I'd rather fix it as that layer, rather than adding a hack to one specific 3rd-party tool.

I guess there isn't much of an advantage to keep it "correct" as, say, with UBSAN. I think it's a good fight not to fight.

2023-02-21 13:41 UTC, jedisct1 commented
> I meant fix the source where the flag is added before passed to cargo-zigbuild.

That would be fixing Rust. May be more difficult than Go.

But Rust probably isn't the only application out there using this syntax.