std.process.Child: implement maxrss on Darwin
ziglang/zig pull request #15050
Opened 2023-03-22 18:29 UTC by tjog

Notably the Darwin (XNU) kernel the maxrss field is number of bytes and not kilobytes (kibibytes) like other platforms (e.g. Linux, BSD).

This is my first PR, although very small in scope, feel welcome to give input.

Fixes #14957

2023-03-23 03:22 UTC, tjog commented
Turns out iOS does not match the OSX implementation ([other GH issue](https://github.com/nodejs/node/issues/44332)):

- OSX: https://github.com/apple/darwin-xnu/blob/2ff845c2e033bd0ff64b5b6aa6063a1f8f65aa32/bsd/man/man2/getrusage.2#L95
- iOS: https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/getrusage.2.html 

Will get a simulator up for .ios, .watchos, .tvos  to verify the archived man paged still applies to those.

2023-03-23 19:51 UTC, tjog commented
Turns out the archived page is wrong. Darwin is consistent across apple platforms for `rusage`, at least if you are to believe the Swift GH repo: https://github.com/apple/swift/blob/dfcc4fce9883ac9989eef9893651a780bad88cb4/lib/Basic/Unix/TaskQueue.inc#L60-L63

I verified this on iOS simulator (see code block below). One complication is that on iOS the first wait4 call is always interrupted leaving garbage values in rusage. However, the second time around it succeeds. Discovered through how [Swift](https://github.com/apple/swift/blob/dfcc4fce9883ac9989eef9893651a780bad88cb4/lib/Basic/Unix/TaskQueue.inc#L599-L619) uses `wait4`. MacOS does not need the retry. It always succeeds on the first `wait4`. 

But, `fork` and `posix_spawn` is not available on other Apple platforms than iOS and MacOS. From what I gather online the iOS sandbox should block all attempts to create a subprocess anyway. Only jailbroken iOS devices which do not have this restriction would succeed. The only argument against not setting iOS as `can_spawn=false` are using fork as a way to detect if the device is jailbroken or not. I have no clue how common this is though.

The fact fork works in iOS simulator is odd, maybe the sandbox is disabled for performance reasons.

I still think the best option is to set these other Darwin targets as unable to spawn and generate compile errors. This will allow reverting back to switch cases for `getMaxRss` and `rusage_init`. A single platform `.macos` is also cleaner than the `is_darwin` version. Will do this and await input.

For completeness, here is the C code ran through Xcode that verifies iOS also returns maxrss in bytes. The same code was run on MacOS by compiling with clang (no Xcode project was created).

<details>
<summary>
Code and results from macOS and iOS simulator, `wait4` perror is logged once for iOS simulator but never for macOS.
</summary>

```c
#include <assert.h>
#include <sys/errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/wait.h>
#include <sys/resource.h>

int main(int argc, char * argv[]) {
    pid_t pid = fork();
    if (pid == 0) {
        // Child process
        size_t mem_size = (20 * 1024 * 1024); // Allocate 20MB of memory
        // maxrss results:
        // (MB granularity to ensure underlying allocator always grabs
        //  different amount of pages):
        // mem_size    macOS       iOS
        // 1MB       1417216   2273280
        // 4MB       4571136   5455872
        // 10MB     10862592  11714560
	// 20MB     21348352  22167552
        char* mem = malloc(mem_size);
        if (mem == NULL) {
            perror("malloc");
            exit(1);
        }
        // Use the memory to ensure it's not optimized away
        for (size_t i = 0; i < mem_size; i++) {
            mem[i] = i % 256;
        }
        sleep(1); // simulate some work
        free(mem);
        printf("Child exiting\n");
        exit(0);
    } else if (pid > 0) {
        // Parent process
        // From Swift example https://github.com/apple/swift/blob/dfcc4fce9883ac9989eef9893651a780bad88cb4/lib/Basic/Unix/TaskQueue.inc#L599-L619
        int Status = 0;
        struct rusage Usage;
        for (;;) {
            // NOTE: only succeeds second time for iOS, need for loop
            const pid_t pidFromWait = wait4(pid, &Status, 0, &Usage);
            
            if (pidFromWait == pid)
                break;
            assert(pidFromWait == -1 &&
                   "Did not pass WNOHANG, should only get pidToWaitFor or -1");
            if (errno == ECHILD || errno == EINVAL)
                exit(1);
            else {
                perror("wait4");
            }
        }
        int exit_status = WEXITSTATUS(Status);
        printf("Child process terminated with status %d\n", exit_status);
        printf("User time used: %ld.%06d s\n", Usage.ru_utime.tv_sec, Usage.ru_utime.tv_usec);
        printf("System time used: %ld.%06d s\n", Usage.ru_stime.tv_sec, Usage.ru_stime.tv_usec);
        printf("Max RSS: %ld\n", Usage.ru_maxrss);
    } else {
        // Fork failed
        perror("fork");
        exit(1);
    }
}
```
</details>

2023-03-23 20:16 UTC, kubkon commented
> Turns out iOS does not match the OSX implementation ([related node GH issue](https://github.com/nodejs/node/issues/44332), [and libuv solution PR](https://github.com/libuv/libuv/pull/3721)):
> 
>     * OSX: https://github.com/apple/darwin-xnu/blob/2ff845c2e033bd0ff64b5b6aa6063a1f8f65aa32/bsd/man/man2/getrusage.2#L95
> 
>     * iOS: https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/getrusage.2.html
> 
> 
> Will get a simulator up for .ios, .watchos, .tvos to verify the archived man paged still applies to those.

For the future, official Apple OSS distributions can be found here: https://github.com/apple-oss-distributions

2023-03-23 20:26 UTC, kubkon requested changes
Nice work! I've got a couple nits and then i think we can go ahead and merge it. When it comes to iOS and other Apple platforms, I don't think anyone would want to spawn a child process using this API for the reasons you mentioned. I believe that for those platforms Apple prescribes you use their frameworks more than anything else. Having said that even if you could spawn a child with this API and it didn't work, we can always revisit later for better iOS support (and other Apple platforms).

2023-03-23 20:26 UTC, kubkon commented on lib/std/child_process.zig
> +            if ((builtin.os.tag == .linux or is_darwin) and self.request_resource_usage_statistics) {
I think a switch here will be more readable here than a long `if` statement like this. Something like

```zig
if (self.request_resource_usage_statistics) {
    switch (builtin.os.tag) {
        .linux => { },
        .macos, .ios => { },
        else => { },
    }
}
```

2023-03-23 20:26 UTC, kubkon commented on lib/std/child_process.zig
> +        const rusage_init = if (builtin.os.tag == .linux or is_darwin)
Please use a `switch` statement here

```zig
switch (builtin.os.tag) {
    .linux => { },
    .macos, .ios => { },
    else => { },
}
```

2023-03-23 21:14 UTC, tjog commented
Updated with your comments in mind! Did not split the switch cases since they share the same implementation.

2023-03-24 06:24 UTC, kubkon approved these changes
Looks great, thanks!

2023-03-24 06:25 UTC, kubkon commented
Can you resolve conflicts with the master branch please?

2023-03-24 20:43 UTC, tjog commented
Rebased and resolved! @kubkon

2023-03-25 02:20 UTC, merged