std: freebsd update proposal.
ziglang/zig pull request #15071
Opened 2023-03-25 12:43 UTC by devnexen

adding getentropy and cpuset_(get/set)affinity calls.

2023-04-14 17:33 UTC, mikdusan requested changes

2023-04-14 17:33 UTC, mikdusan commented on lib/std/c/freebsd.zig
> +};
copying the os macro calc lets `CPU_SETSIZE` work with non-multiples of `64` (bits per long):
```zig
__bits: [(CPU_SETSIZE + (@bitSizeOf(c_long) - 1)) / @bitSizeOf(c_long)]c_long
```

2023-04-14 23:53 UTC, mikdusan approved these changes

2023-04-18 11:52 UTC, devnexen commented
cc @Vexu 🙂

2023-04-18 11:59 UTC, merged