add linker -wrap flag
ziglang/zig pull request #15097
Opened 2023-03-28 06:36 UTC by zachcheu

This passes `-wrap` through to the old.

Test
```
> cat wrap_example.c foo.c
#include <stdio.h>
extern int foo();
extern int __real_foo();

int __wrap_foo() {
    printf("wrap foo\n");
    return 0;
}

int __real_foo(){
    printf("real foo\n");
    return 0;
}

int main () {
    printf("foo:");foo();
    printf("wrapfoo:");__wrap_foo();
    printf("realfoo:");__real_foo();
    return 0;
}
#include <stdio.h>
int foo() {
    printf("foo\n");
    return 0;
}

> ./zig2 cc wrap_example.c foo.c  -Wl,-wrap,foo -o main

> ./main
foo:wrap foo
wrapfoo:wrap foo
realfoo:foo
```

2023-03-28 09:44 UTC, motiejus approved these changes
cc @kubkon 

This is causing annoyance in Uber's Go Monorepo. If you agree this is a simple-enough change, can we get it landed?

2023-03-30 06:43 UTC, kubkon commented on src/main.zig
> +                    mem.eql(u8, arg, "--wrap"))
Good catch about `-Wl,-wrap` being implicitly handled in the loop - I missed that.

Re the latter, `zig build-exe` does not understand `-Wl` flag and should handle an explicit `-wrap` flag.

2023-03-30 06:46 UTC, kubkon requested changes

2023-03-31 23:34 UTC, zachcheu commented on src/main.zig
> +                    mem.eql(u8, arg, "--wrap"))
Is this what you mean by supporting `zig build-exe`?
```
> ./zig2 build-exe -lc main.c foo.c -wrap foo

> ./main
foo:wrap foo
wrapfoo:wrap foo
realfoo:foo
```

2023-04-07 16:53 UTC, andrewrk commented
hi @zachcheu, I'm sorry for confusing you - I added a commit to the branch and force pushed, and then set to auto-merge once the CI tests passed. It looks like you attempted to push some other work after that just now, but ran into git troubles.

I can take it from here. Are you OK with that?

2023-04-07 17:09 UTC, zachcheu commented
No worries. Feel free to take it from here. Thanks!

2023-04-07 23:58 UTC, merged