Build: restore color support
ziglang/zig pull request #15168
Opened 2023-04-04 07:48 UTC by perillo

Commit 986a30e37 (integrate the build runner and the compiler server) removed the std.Build.color field, because build steps are no longer supposed to interact with stderr directly.

However this change have same issues:
  - The build system still use colors, in the dumpBadGetPathHelp function and std.Build.Step.dump method.  They create a new TTYConfig, ignoring the user preference.
  - A custom build step may still want to use colors. An example is ziglings. It uses a custom Run step, since it needs additional actions not supported by std.Build.RunStep, and it wants to use colors to improve user experience.

Add a new ttyconf field to std.Build, and, in the create function, initialize it using std.debug.detectTTYConfig.

Change lib/build_runner.zig to update the Build.ttyconf field, after the builder has been configured.

Rename the tty_config variable to ttyconf, for consistency.

2023-04-04 09:14 UTC, Vexu approved these changes

2023-10-19 00:16 UTC, andrewrk requested changes

2023-10-19 00:16 UTC, andrewrk commented on lib/std/Build.zig
> +ttyconf: debug.TTY.Config,
This is a public API so let's make the name match the type:

```suggestion
tty_config: debug.TTY.Config,
```

2024-01-16 09:18 UTC, andrewrk commented
Closing abandoned pull request.

2024-01-16 09:18 UTC, closed without merging