std.c: adding freebsd's kinfo_proc type.
ziglang/zig pull request #15523
Opened 2023-04-30 13:56 UTC by devnexen

2023-05-01 02:40 UTC, andrewrk requested changes

2023-05-01 02:40 UTC, andrewrk commented on lib/std/c/freebsd.zig
> +pub const segsz_t = if (builtin.cpu.arch.ptrBitWidth() == 32) i32 else i64;
```suggestion
pub const vm_size_t = usize;
pub const segsz_t = usize;
```

2023-05-01 02:40 UTC, andrewrk commented on lib/std/c/freebsd.zig
> +    u_kproc: kinfo_proc,
```suggestion
    stats: pstats,
    kproc: kinfo_proc,
```

zig std lib convention is to erase prefixes like this on all fields.

2023-05-01 02:40 UTC, andrewrk commented on lib/std/c/freebsd.zig
> +    std.debug.assert(@sizeOf(kinfo_proc) == KINFO_PROC_SIZE);
```suggestion
    assert(@sizeOf(kinfo_proc) == KINFO_PROC_SIZE);
```

2023-05-08 21:52 UTC, devnexen commented
cc @Vexu 🙂

2023-05-09 09:04 UTC, merged