std.ChildProcess: fix EBADF when explicitly passing cwd as working directory
ziglang/zig pull request #15592
Opened 2023-05-05 19:37 UTC by LordMZTE

closes #9688

This fixes a bug where `ChildProcess.spawn` would try to call `fchdir` with `AT_FDCWD` causing an EBADF error to occur when `ChildProcess.cwd_dir` is set to `std.fs.cwd()`.

2023-05-05 23:55 UTC, squeek502 commented
Worth noting that this is not the only place `AT.FDCWD` can cause problems (e.g. I know `os.fstat` has the same issue but the fix there is much less clear), and I'm unsure about exactly where this type of thing should be accounted for. For example, this same issue could be fixed by doing

```zig
if (dirfd == AT.FDCWD) return;
```

in `std.os.fchdir` instead. Note that this alternate fix would also avoid `EBADF` when doing something like:

```zig
test {
    const cwd = fs.cwd();
    try cwd.setAsCwd();
}
```

whereas the implementation in this PR would still hit `EBADF` in that case.

2023-05-06 08:06 UTC, LordMZTE commented
Right. Let's see if the maintainers would prefer this fix.

2023-10-19 00:20 UTC, andrewrk requested changes
Let's please do the fix suggested by @squeek502

2023-10-19 06:05 UTC, LordMZTE commented
Got it, I'll open this as a new PR as this one is getting pretty outdated and contains a redundant commit.

2023-10-19 06:05 UTC, closed without merging