Implement access and faccessat with W_OK on Windows
ziglang/zig pull request #15697
Opened 2023-05-13 21:27 UTC by notcancername

2023-07-25 17:56 UTC, andrewrk requested changes

2023-07-25 17:56 UTC, andrewrk commented on lib/std/c/windows.zig
> +// pub const R_OK = 1;
???

2023-10-19 02:44 UTC, andrewrk requested changes
Instead of adding logic to the posix compatibility layer, I think you should add support for these in `std.fs.Dir.accessW`.

related:
* #6600
* #5019

2023-12-24 01:13 UTC, closed without merging

2023-12-24 01:13 UTC, notcancername commented
Closing as I am not personally invested enough here.