Build: Fix bug causing ReleaseSmall to fail on Windows
ziglang/zig pull request #15756
Opened 2023-05-18 09:56 UTC by xEgoist

closes: #13405

Due to the change in default behavior of ReleaseSmall (#13067), debug info (pdb here) are stripped by default. However because `Compile.create` defaults to null, `producesPdbFile` will report true for
`lib/std/Build/Step/InstallArtifact.zig` 
https://github.com/ziglang/zig/blob/378264d404e71da878f9e6934c045ad64193877f/lib/std/Build/Step/InstallArtifact.zig#L33

Because of this, this only affects `zig build` and not `zig build-exe`. After this, a simple program compiled with  `ReleaseSmall` will successfully compile and won't try to copy/produce the pdb file.

Of course, this still allows the user to choose not to strip the build and will produce a pdb file.

2023-05-18 10:09 UTC, davidgm94 commented
Couldn't it be possible to imitate the ReleaseFast code path for stripping? As far as I understand, this only happens with ReleaseSmall, but by using ReleaseFast the binary is stripped too and the bug doesn't happen. There has to be some place in the code where the ReleaseFast stripping is handled gracefully. Otherwise we risk introducing here a very hidden branch in an unexpected place that could cause some trouble. That's my opinion and obviously I could be missing some details or misinterpreting something since I am not that aware of the compiler internals.

2023-05-18 10:23 UTC, xEgoist commented
> Couldn't it be possible to imitate the ReleaseFast code path for stripping? As far as I understand, this only happens with ReleaseSmall, but by using ReleaseFast the binary is stripped too and the bug doesn't happen. There has to be some place in the code where the ReleaseFast stripping is handled gracefully. Otherwise we risk introducing here a very hidden branch in an unexpected place that could cause some trouble. That's my opinion and obviously I could be missing some details or misinterpreting something since I am not that aware of the compiler internals.

I don't think the current/intended behavior of ReleaseFast is to strip the binaries, but i could also be wrong or misinterpreting what you said :smile:. 

Linux:
```sh
~/Projects/zigProjects/bench
Zig-Shell ❯ zig build -Doptimize=ReleaseFast

~/Projects/zigProjects/bench 6s
Zig-Shell ❯ file zig-out/bin/bench          
zig-out/bin/bench: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, with debug_info, not stripped
```
Windows builds also produces pdb.

2023-05-18 10:28 UTC, davidgm94 commented
Ok I take back what I said then. Apologies :)

2023-05-18 14:55 UTC, xEgoist commented
Seems like CI is failing on `debug.zig` "manage resources correctly" ReleaseSmall test.

https://github.com/ziglang/zig/blob/7cf2cbb33ef34c1d211135f56d30fe23b6cacd42/lib/std/debug.zig#L2185-L2197

I assume it's triggered because strip is now set to true on ReleaseSmall, thus failing on the builtin strip check.

I haven't investigated further yet so i could be totally wrong, but does it make sense that this test should have been skipped for ReleaseSmall because there is no debug info?

2023-05-18 15:29 UTC, davidgm94 commented
I guess, if I understood correctly, that one could use `@import("builtin").strip_debug_info`  to conditionally execute this test only in situations where the binary was not stripped.

2023-05-18 18:08 UTC, xEgoist commented
I think I have a better understanding of this now. The problem is more specifically because it's stripping the test (addTest in Build.zig). So it depends on the desired behavior of tests. Whether tests should also strip or not.

So there are three options here:
 - Skip this test on strip as specified above.
 - Don't strip tests regardless of release mode.
 - Don't strip the lang/CI tests.

2023-05-19 00:15 UTC, andrewrk requested changes

2023-05-19 00:15 UTC, andrewrk commented on lib/std/Build/Step/Compile.zig
> +        .strip = if (options.optimize == .ReleaseSmall) true else null,
The previous value was correct. The default is decided by the compiler rather than the build system. `null` means to use the compiler's default.

2023-06-03 20:45 UTC, merged