make CompileStep.addRPath preserve relative paths
ziglang/zig pull request #15907
Opened 2023-05-30 10:43 UTC by yujiri8

Closes #15849.

2023-06-13 18:15 UTC, andrewrk requested changes
This will make rpaths relative to the build root (i.e. to the directory containing build.zig). Is that what is desired? I think it should instead be relative to the installation prefix, no?

2023-06-13 18:15 UTC, andrewrk commented on lib/std/Build/Step/Compile.zig
> +        std.debug.print("path is {s}\n", .{rpath.getPathRelative(b, step)});
stray debug print

2023-06-14 20:53 UTC, yujiri8 commented
:shrug: this PR's purpose was only to make `CompileStep.adRPath` consistent with the `-rpath` flag to `build-exe`. I have no idea what behavior is desirable here, but if relative paths are being interpreted relative to the wrong root, isn't that a separate issue?

2023-06-14 20:54 UTC, yujiri8 commented on lib/std/Build/Step/Compile.zig
> +        std.debug.print("path is {s}\n", .{rpath.getPathRelative(b, step)});
Sorry, fixed that.

2023-07-10 19:34 UTC, hazeycode commented
> This will make rpaths relative to the build root (i.e. to the directory containing build.zig). Is that what is desired? I think it should instead be relative to the installation prefix, no?

Possibly not. There is also an issue resolving `$ORIGIN` on linux, I presume that this is what should be used if one wants to use a path relative to the installation dir? There was similar issue (resolving `@executable_path` on Darwin) that was solved by @kubkon here: https://github.com/ziglang/zig/pull/15061

2023-07-10 20:51 UTC, yujiri8 commented
Alright. Well, I'm not going to do any more work on this. Others feel free to add commits or close.

2023-12-07 01:59 UTC, closed without merging