Uri: Don't double-escape escaped query parameters
ziglang/zig pull request #16043
Opened 2023-06-15 04:01 UTC by AnnikaCodes

Zig's HTTP client breaks down when redirected to a URL with escaped query parameters. It seems to be doubly escaping them; this PR simply exempts the `%` character from being escaped in query parameters. I'm not sure if this will have unanticipated effects; we could also try a more complicated fix by looking ahead to see if the % in question is part of an escape sequence (and escaping it only if it's not).

2023-06-15 19:44 UTC, andrewrk requested changes
Thanks for the patch.

This needs unit tests. Lack of unit tests is why this is broken in the first place.

2023-06-16 00:41 UTC, AnnikaCodes commented
I added a unit test. I'm also not 100% confident that this is the correct place to fix the problem — maybe the HTTP client shouldn't be re-escaping URLs provided in redirects in the first place? But this does fix the problem.

2023-07-26 15:34 UTC, dadrian commented
Comparing this PR to mine (#16533):
* I forgot Github doesn't search open PRs when searching issues, so I didn't see this one when I searched for issues around std.Uri and decided to open my own
* I think this PR is a more minimal change to the standard library that unblocks using the built in HTTP client with a bunch of common request patterns. However, I think it's odd behavior for std.Uri, since when given an unescaped query string, `writeEscapedQueryString` can't be correct in all cases.
* My PR punts the whole problem to the caller, but doesn't provide a built-in solution for them to escape a set of K/V pairs, because I was shooting for a small change and I'm not sure if there's a process for proposing larger stdlib changes.

My suggestion is that we merge this PR now, because it makes it possible to use the HTTP library with non-alphanumeric query strings without changing any API signatures. At some point, std.Uri probably needs a more consistent escaping story, but that could be a larger PR that addresses fields besides query, as noted in https://github.com/ziglang/zig/pull/16043#issuecomment-1593911082, and optionally adds something like https://github.com/nektro/zig-UrlValues.

2023-07-27 17:18 UTC, andrewrk commented
Thanks @AnnikaCodes!

2023-07-27 17:18 UTC, merged