linux: do not set stack size hard limit
ziglang/zig pull request #16210
Opened 2023-06-25 19:46 UTC by mikdusan

When expanding stacksize we should only set the soft limit and avoid setting the hard limit, as the latter would clamp any child process from exceeding the soft limit.

2023-06-25 22:40 UTC, matu3ba commented
Sounds like a good idea.

As I understand it, there is a cli option missing to let the user limit the stack size of a run step (only for compile steps its used) which is relevant for limited systems, ie CI systems in container environments to rule out any subprocess exceeding stack limits.

I did also look into what windows offers and [I found nothing to limit the stack size](https://stackoverflow.com/questions/156510/increase-stack-size-on-windows-gcc)

Do you feel like this is relevant or are the environment messages conclusive enough?

2023-07-25 02:40 UTC, andrewrk requested changes
1. Can you try to do it with only 1 syscall? Does it succeed if you pass "unlimited" as max?
2. Please avoid unnecessary use of `var`. Both of these should be `const`.

2023-07-26 01:48 UTC, mikdusan commented
> * Can you try to do it with only 1 syscall? Does it succeed if you pass "unlimited" as max?

TL;DR: nope. I cannot see a way that we can set *only* `.cur` and leave `.max` untouched without first reading it.

`RLIM_INFINITY` is defined as `0xffffffffffffffff` (`maxInt(u64)`) and unfortunately, it has no symbolic meaning. Thus, if I try to set `.max = RLIM_INFINITY` it only works if that is the same value as *already* active. For example, if active .max is 16 MiB, then bumping +1 to `16777217` yields `error.PermissionDenied` because never allowed to increase hard-limit. And `0` has no special meaning.

> * Please avoid unnecessary use of `var`. Both of these should be `const`.

Done. (my initial thoughts were that `2 * var` was better than `2 * const + 1 * tmp` but hey things aren't so simple).

2023-07-27 17:17 UTC, andrewrk commented
Thanks!

2023-07-27 17:17 UTC, merged