Replace @fabs builtin with new @abs builtin
ziglang/zig pull request #16434
Opened 2023-07-18 00:10 UTC by antlilja

Closes #16026

This PR replaces the `@fabs` builtin with a new `@abs` builtin accepts signed integers in addition to floating point types.

I've implemented codegen for the llvm, x86_64, wasm and c backends (no vector integer abs except on llvm). 

As I've implemented it right now the builtin does not accept unsigned integers only signed integers and always outputs unsigned integers. My rationale was that an unsigned integer is never negative and thus `@abs` isn't a valid operation. The other option would be to just nop for `@abs` on an unsigned value.

I've also not implemented any safety yet in case of overflow.

2023-07-18 01:33 UTC, mgord9518 commented
I think not accepting unsigned ints makes more sense than making it a noop

2023-07-18 07:31 UTC, matu3ba commented
> I've also not implemented any safety yet in case of overflow.

IEEE754 floats can not overflow and I dont see `@abs(-inf), @abs(inf), @abs(-0.0), @abs(+0.0), @abs(-Nan), @abs(Nan), @abs(-denormal), @abs(denormal)`. LLVM does not preserve quite and signaling NaN (it uses any NaN) and this is undocumented, so I would not trust it too much regarding float correctness.

2023-07-24 13:53 UTC, matu3ba commented
CI fails with
```
[16/21] Running zig1.wasm to produce /home/ci/actions-runner4/_work/zig/zig/build-debug/zig2.c
FAILED: zig2.c 
cd /home/ci/actions-runner4/_work/zig/zig && /home/ci/actions-runner4/_work/zig/zig/build-debug/zig1 /home/ci/actions-runner4/_work/zig/zig/lib build-exe src/main.zig -ofmt=c -lc -OReleaseSmall --name zig2 -femit-bin="/home/ci/actions-runner4/_work/zig/zig/build-debug/zig2.c" --mod build_options::/home/ci/actions-runner4/_work/zig/zig/build-debug/config.zig --deps build_options -target aarch64-linux
src/codegen/llvm.zig:8449:93: error: member function expected 5 argument(s), found 7
src/codegen/llvm/bindings.zig:655:12: note: function declared here
ninja: build stopped: subcommand failed.
```

bindings points to
```
    pub const buildCall = LLVMBuildCall2;
    extern fn LLVMBuildCall2(
        *Builder,
        *Type,
        Fn: *Value,
        Args: [*]const *Value,
        NumArgs: c_uint,
        Name: [*:0]const u8,
    ) *Value;
```
which has been changed in https://github.com/ziglang/zig/commit/d21d1d4ba25701410b9ae99921326f8bfc8a44dd.

2023-07-28 14:20 UTC, antlilja commented
I seem to be running into the same LLVM bug on x86_64 macos reported here: #12827

2023-07-31 11:19 UTC, antlilja commented
The failing test has been skipped on x86_64-macos because it was due to a bug in LLVM

2023-08-05 21:02 UTC, antlilja commented
I've now also implemented the ```llvm.abs.``` intrinsic for the new LLVM builder API.

2023-08-10 23:08 UTC, andrewrk requested changes
Thanks, nice work.

Before this is merged, it needs `zig fmt` to auto-convert `@fabs` to `@abs`.

Also, the absolute value function is well-defined for positive integers. The absolute value of a positive integer is the same positive integer. Just because `u8` cannot store the value `-10`, does not mean that `abs(10) != 10`.

2023-08-14 11:25 UTC, wooster0 commented on lib/std/math.zig
>  pub inline fn fabs(value: anytype) @TypeOf(value) {
```suggestion
pub inline fn abs(value: anytype) @TypeOf(value) {
```

2023-08-14 11:37 UTC, wooster0 commented on doc/langref.html.in
> +      Returns the absolute value of a floating point or signed integer number. Uses a dedicated hardware instruction
Looking at `Sema`, unsigned integers seem to be supported.
```suggestion
      Returns the absolute value of an integer or a floating point number. Uses a dedicated hardware instruction
```

2023-08-14 11:38 UTC, wooster0 commented on lib/std/math.zig
>  pub inline fn fabs(value: anytype) @TypeOf(value) {
```suggestion
pub inline fn abs(value: anytype) @TypeOf(value) {
```

2023-09-18 08:13 UTC, andrewrk commented
This looked like it was pretty close to being landed, however, it did not get to green CI status (perhaps due to a flaky test in master branch that needs to get disabled?), and it has a few conflicts to be resolved. Since it has not been touched in over 1 month, I'm going to close it. However, please feel free to open a new pull request if you wish to continue these efforts.

2023-09-18 08:13 UTC, closed without merging