std.Uri: Assume query string is already escaped
ziglang/zig pull request #16533
Opened 2023-07-24 19:20 UTC by dadrian

std.Uri.format currently calls writeEscapedQuery when writing out the query string. Unfortunately, this means that it is not possible to specify a query that contains an ampersand or an equals sign, since these are left unescaped by the writeEscapedQuery.

For example, assume you are attempting to pass the value `M&M` as a query variable named `candy`, and the value `=` as the variable `cmp`. Note that the escaped value for `=` is `%3D`, `&` is `%26', and '%' is '%25'.

Consider the possible values for Uri.query attempting to encode the above example:
1. Unescaped: `candy=M&M&cmp==`
2. Escaped: `candy=M%26M&cmp=%3D`

After passing through writeEscapedQuery, (1) encodes to itself, because `=` and `&` are valid characters in a query string. However, the semantic meaning of that string unclear, but at minimum contains the set `{ candy: "M", M: "" }`, and the behavior around `cmp` is dependent on any rules that may or may not exist for interpreting malformed query values.

On the other hand, (2) would end up double-escaped because '%' gets escaped to '%25', resulting in `candy=M%2526M^cmp=%253D`, which is the set `{ candy: "M%26", cmp: "%3D"}`, which is also wrong.

Ultimately, if there's any instances of `=` or `&` in the query variable, not only is writeEscapedQuery incorrect, but there's no way to write a correct function that operates on a combined query string, rather than a set of key/value pairs.

Instead, Uri should assume the query string is already escaped. Callers can use Uri.escapeString and Uri.writeEscapedString to encode their query values individually, and then combine.

This approach is similar to the Go standard library, which uses a URL.RawQuery field to store the encoded query as a string.

2023-07-24 19:25 UTC, dadrian commented
It might be useful to have a function that takes a list of K/V pairs, or a map, and encodes them as a query string, similar to https://pkg.go.dev/net/url#Values. However, I'm not sure what the standard patterns, if any, are in the stdlib for tuples or maps, as they all seem fairly allocation-heavy.

2023-07-24 23:51 UTC, nektro commented
I have https://github.com/nektro/zig-UrlValues, welcome to inspect and take

2023-07-26 23:07 UTC, MasterQ32 commented
If unchanged from my impl, this is intentional.

There is explicit functions to escape query components, same as other url apis do, as query format can be arbitrary, but still needs escaping for certain characters.

if values need to be escaped, this has to be done explicitly beforehand

2023-10-19 03:12 UTC, andrewrk requested changes
@MasterQ32 you seem to be saying the same thing as @dadrian.

Looking at the commit log, I see a bunch of suspicious query string escaping related things. I think perhaps some well meaning contributors have taken the code in a problematic direction.

@dadrian would you be willing to rebase this on master, and then rework the query string escaping to avoid these pitfalls, perhaps enhancing the comments to make the code more resistant to well-meaning but ultimately destructive contributions in the future?

2023-10-19 07:13 UTC, MasterQ32 requested changes

2023-10-19 07:13 UTC, MasterQ32 commented on lib/std/Uri.zig
>          if (uri.query) |q| {
If we do this change, i'd rename `query` to `raw_query` to inform the user that it is actually not containing any escaped data

2023-10-19 07:15 UTC, MasterQ32 commented
Another thing i'd maybe change is making a validate function people can assert on that will check if all URI components will behave in a good manner (so `raw_uri` doesn't contain bad characters and such)

2023-12-05 22:28 UTC, dadrian commented
Apologies for the delay. I'm happy to get this rebased.

2024-03-15 02:03 UTC, andrewrk commented
Closing since this is untouched in 3 months and is not passing CI checks. Please make a bug report first to continue this effort so that we can agree on the expected API and desired unit test behavior.

2024-03-15 02:03 UTC, closed without merging