llvm: fix data layout on ios
ziglang/zig pull request #16556
Opened 2023-07-26 02:17 UTC by jacobly0

Closes #16549

2023-07-26 12:19 UTC, kubkon requested changes

2023-07-26 12:19 UTC, kubkon commented on test/llvm_targets.zig
> +    .{ .cpu_arch = .aarch64, .os_tag = .ios, .abi = .simulator },
Could you also include `x86_64-ios-simulator` which is also a vaild target that we used to support?. In the future, we might want to expand across more Apple platforms, but given that I haven't done any checks on any other platform but `macos` and `ios`, I think it is safe to defer adding those until later.

2023-07-26 17:36 UTC, kubkon requested changes

2023-07-26 17:36 UTC, kubkon commented on test/llvm_targets.zig
> +    .{ .cpu_arch = .x86_64, .os_tag = .ios, .abi = .none },
```suggestion
```

This set is unreachable. Apple only support `x86_64-ios-simulator`.

2023-07-26 17:43 UTC, kubkon approved these changes

2023-07-26 23:49 UTC, merged

2023-07-31 08:20 UTC, andrewrk commented
similar issue: #16616