Build.ConfigHeader: render identifiers
ziglang/zig pull request #16689
Opened 2023-08-05 02:20 UTC by alichraghi

2023-08-05 18:52 UTC, andrewrk requested changes
Please either provide a test, or an explanation for what this change does and how you tested it.

2023-08-05 18:52 UTC, andrewrk commented on lib/std/Build/Step/ConfigHeader.zig
> +                .ident => |ident| {
This looks like the same body as `string`. Couldn't you just do `.string, .ident => |x| {`

2023-08-06 03:49 UTC, alichraghi commented
while adding [`build.zig`](https://github.com/hexops/ogg/blob/b6cc26bd14a5f99f06359f39772efd6e8c90aa3f/build.zig#L16-L21) to libogg, i noticed that this [config header](https://github.com/xiph/ogg/blob/db5c7a49ce7ebda47b15b78471e78fb7f2483e22/include/ogg/config_types.h.in#L19-L24) requires identifier values.
before this PR, identifiers were ignored and rendered as `typedef  ogg_int16_t;` instead of `typedef int16_t ogg_int16_t;`.

2023-08-10 23:17 UTC, merged

2023-08-10 23:18 UTC, andrewrk commented
btw https://github.com/andrewrk/libogg

2023-08-11 06:24 UTC, alichraghi commented
yeah i see that one but somehow opusfile requires `config_types.h`