std.Build: add support for deps .d file in Step.Run
ziglang/zig pull request #16789
Opened 2023-08-12 11:40 UTC by Sahnvour

Closes #16040

Tested with a simple example program that outputs one target in the `.d` file, however I think we don't need to limit to a single target anymore. For example in the case of asset processors, as cited in the issue.

2023-08-12 17:35 UTC, andrewrk requested changes
Thanks for working on this!

2023-08-12 17:35 UTC, andrewrk commented on lib/std/Build/Step/Run.zig
> +}
This should not hard code a "standard" prefix, there is no such standard. The use case for a function named `addDepFileOutputArg` is adding the path to the dep file as a single argument.

2023-08-12 17:35 UTC, andrewrk commented on lib/std/Build/Step/Run.zig
> +    const two_args = !std.mem.endsWith(u8, flag, &.{'='});
Don't do this. It's too late to discover the user's intention. In this function, there is a single argument that is prefixed with `flag` (which should be renamed to `prefix`).

2023-08-12 17:35 UTC, andrewrk commented on lib/std/Build/Step/Run.zig
> +    self.dep_output_file = dep_file;
Please either assert that this value is null here, and document this limitation in the doc comments of the function, or make it handle N dep files.

2023-08-12 17:35 UTC, andrewrk commented on lib/std/Build/Step/Run.zig
> +    return .{ .generated = &dep_file.generated_file };
I don't think this function should return a lazy file. It implies that the user should handle it, which would be an unusual case.

2023-08-12 23:23 UTC, andrewrk requested changes
Thanks for the changes. One more thing- I think that both of these functions should follow the example set by `addOutputFileArg` and `addPrefixedOutputFileArg` in this file, and accept a `basename` parameter rather than hard-coding it to "deps.d". This is a slightly more verbose API but handles the case where the child process depends on a certain filename (or perhaps extension) in order to behave correctly. Plus, it's just nice to have API consistency.

2023-08-13 08:19 UTC, Sahnvour commented
Absolutely, I missed that. Should be good to go now.

2023-08-13 19:15 UTC, merged