de-bitrot the BSDs
ziglang/zig pull request #16824
Opened 2023-08-14 19:45 UTC by mikdusan

Advance the state of various BSDs ports on x86_64 to be able to build stage3 and pass `zig test lib/std/std.zig`:

- netbsd 9.3
- openbsd 7.3
- dragonfly 6.4
- freebsd 13.2 (wasn't broken but tested anyways)

2023-08-15 07:20 UTC, andrewrk requested changes
Thanks! Just one suggestion before this is ready.

2023-08-15 07:20 UTC, andrewrk commented on lib/std/c.zig
>  };
```suggestion
pub extern "c" fn getcontext(ucp: *std.os.ucontext_t) c_int;
```

 * don't fear linker errors
 * std.c should not re-export something from std.os.linux
 * avoid `usingnamespace`

2023-08-15 18:20 UTC, mikdusan commented
> Thanks! Just one suggestion before this is ready.

Done. There were a few consequences in `std.debug` but handled.

If you sign off, before merge, I need to update the commit log and drop the OpenBSD commit (no longer needed).

2023-08-16 19:25 UTC, andrewrk requested changes

2023-08-16 19:25 UTC, andrewrk commented on lib/std/debug.zig
> +};
This function should not exist.

Note that `@import("builtin").omit_frame_pointer` exists.

2023-08-17 19:13 UTC, andrewrk approved these changes
Looks great, I'm happy with where this landed, thanks!

2023-08-17 19:14 UTC, merged