langref: keyword consistency (between keyword list and grammar)
ziglang/zig pull request #16825
Opened 2023-08-14 20:45 UTC by Kiyoshi364

There were some keywords that were in the Grammar, but not in the Keyword List, namely: callconv and opaque.
Also some keywords in Grammar were not sorted in alphabetical order (that the Keyword List appeared to be in),
namely: linksection and nosuspend (or noinline).

I did all that in the browser, so I didn't test/ran anything.
But if something would be broken, I expect that it would be the link to opaque header.

Let me know if something is not ok.

2023-08-17 19:17 UTC, andrewrk requested changes

2023-08-17 19:17 UTC, andrewrk commented on doc/langref.html.in
> +              <li>TODO add documentation for callconv</li>
```suggestion
              <li>Specifies the calling convention in a function type.</li>
```

2023-08-18 16:35 UTC, Kiyoshi364 commented
I (as a zig user) have been looking for a place to understand better how the calling conventions work.
I don't even know all the "possible values" that I can put in there
(until now that I made function with `callconv(.custom)` and the complier said that it is not a `builtin.CallingConvention`).

I was expecting to exist a topic/header in the langref talking about this, maybe inside Functions
(then I took a look and there are some examples there).

If it is not planned to add a topic/header about Calling Conventions, the change is ok by me.

2023-08-19 01:54 UTC, wooster0 commented
To find out the possible values  that you can put in a `callconv(...)` you can reference `std.builtin.CallingConvention` which is found in the standard library documentation instead of the language reference.

2023-09-06 16:10 UTC, merged