wasm: implement more float operations on f80 and f128
ziglang/zig pull request #17081
Opened 2023-09-06 21:52 UTC by Techatrix

follow up to #14668

This should cover the majority of float operations on `f80` and `f128` (excluding vectors).
I always tried to match the code generated by the llvm backend which was mostly compiler-rt calls.
Some of the possible conversions with `@floatFromInt` and `@intFromFloat` are not properly implemented yet, but I don't think that I regressed anything there.
71b15ea28eb308c3344bd097bd46115318e37f73 is technically not related to floats but it makes it possible to call `std.debug.print` on floats.

2023-09-10 06:01 UTC, kubkon requested changes
Nice work! I just have a few questions and suggestions.

2023-09-10 14:07 UTC, Techatrix commented on src/arch/wasm/CodeGen.zig
> +            try func.addMemArg(.i64_load, .{ .offset = 0 + arg.offset(), .alignment = 2 });
I added the `0 + ` to be more consistent with other code in the wasm backend. Some other examples in the codebase: [link1](https://github.com/ziglang/zig/blob/9f187aaadfeee9491027e73d2afd10554b88f775/src/arch/wasm/CodeGen.zig#L2412) [link2](https://github.com/ziglang/zig/blob/9f187aaadfeee9491027e73d2afd10554b88f775/src/arch/wasm/CodeGen.zig#L3642)

2023-09-10 14:07 UTC, Techatrix commented on src/arch/wasm/CodeGen.zig
> +            return func.finishAir(inst, result, &.{});
I think this is because it only concerns the C calling convention and this hat not been covered by behavior test yet. Just a guess...

2023-09-11 05:58 UTC, kubkon commented on src/arch/wasm/CodeGen.zig
> +            try func.addMemArg(.i64_load, .{ .offset = 0 + arg.offset(), .alignment = 2 });
Sounds good!

2023-09-11 05:59 UTC, kubkon approved these changes

2023-09-11 05:59 UTC, merged