Add the ability to customise libcxx compile flags
ziglang/zig pull request #17224
Opened 2023-09-21 16:37 UTC by phildrip

Via environment variable ZIG_LIBCXX_FLAGS.

This enables the use case of cross-compiling for old versions of Windows. Currently, any dlls or exes built for Windows won't run on anything older than 8, since a new function, `GetSystemTimePreciseAsFileTime`, was added in windows 8, and which libcxx will depend on if it is built for Window 8 or above. 

Zig will build libcxx without specifying `_WIN32_WINNT`, which controls the target version, and so libcxx ends up targeting 8+.

This PR provides an escape hatch to enable anyone calling `zig c++` to do, for example:

```
env ZIG_LIBCXX_FLAGS="-D_WIN32_WINNT=0x0601" ~/git/zig/build/stage3/bin/zig c++ -D_WIN32_WINNT=0x0601 -target x86_64-windows-gnu -o main.withflags.exe main.cpp
```

and have it run on win7.

This the first time I've written any zig code, so it may not be idiomatic, etc! 

Thanks.

2023-09-23 19:17 UTC, andrewrk requested changes
Thanks for the patch.

I think using environment variables in this way will lead to more problems down the road than it solves. The compiler already knows which version of windows is being targeted (it has a min/max version OS range), and it should use that information instead to configure how to build libcxx.

2023-09-23 20:10 UTC, mikdusan commented
fwiw I'll copy some discord ramblings here re: using -target...

> I don't see that PR being accepted because:, avoid env vars when possible and the target version mechanism looks ideal imo.
> 
> in macos land, the target version actually passes right through to vendored clang compiler and it sets the right env version vars! and our zld linker picks up on it too.
> 
> unfortunately, for windows that is not the case so the solve is a little harder. However, let's take libcxx.zig as an example. It hard codes -DNDEBUG and other flags. But to add to the complication, we have mingw.zig which does hardcode -D_WIN32_WINNT=0x0f00 .. I have no idea what that value is! (not a windows person). but is it even valid?
> 
> anyways ... from *Compilation one can get target, and when target.os == .windows then target.os.version_range.windows.min is available. I haven't looked in detail, but if std.Target doesn't support going from WindowsVersion 32-bit hex to 16-bit hex defines for _WIN32_WINNT and WINVER, the mask/shift is simple.
> 
> the larger problem becomes... there are 3 different kinds of compilations happening here.. user code, libcxx, mingw (which libcxx depends on). And none are in sync wrt _WIN32_WINNT .
> 
> I can see the the define as mingw is being built (thank you ZIG_VERBOSE_CC=1), but it is certainly not used compiling foo.c or libcxx compilation.
> 
> so where to set those defines? Perhaps the most robust way is to:
> 
> 1. remove -D_WIN32_WINNT from mingw.zig logic.
> 2. add -D_WIN32_WINNT logic to src/main.zig frontend. Essentially clang_argv.append() would be the sweet spot?
> 
> this would ensure all windows compilations (and cImports, preprocessor, etc) have the same _WIN32_WINNT all based on target version.

2023-09-25 14:16 UTC, phildrip commented
Thanks for the comments - I wasn't aware of the target version range mechanism. 

I'll rework the change.

2023-09-25 16:21 UTC, phildrip commented
Ok, reworked!

2023-09-25 16:32 UTC, phildrip commented
I didn't go near mingw.zig, but wonder if that should have the same / similar change.

2023-09-26 01:54 UTC, mikdusan commented
> I didn't go near mingw.zig, but wonder if that should have the same / similar change

I think this PR will kick ass with a universal location to insert the command-line arg(s) as needed.
To that end, I've taken the gist of your patch and:

1. nuked all "-D_WIN32_WINNT" args in `src/`
2. immediately after the place where "-target ..." arg is added, emit the macro

would you mind trying this diff out with `-target native-windows.win7` and see if it solves origin issue?

<details>
<summary>diff</summary>

```diff
diff --git a/src/Compilation.zig b/src/Compilation.zig
index 47d0125ff..c1cfe4613 100644
--- a/src/Compilation.zig
+++ b/src/Compilation.zig
@@ -4880,6 +4880,14 @@ pub fn addCCArgs(
     const llvm_triple = try @import("codegen/llvm.zig").targetTriple(arena, target);
     try argv.appendSlice(&[_][]const u8{ "-target", llvm_triple });
 
+    if (target.os.tag == .windows) switch (ext) {
+        .c, .cpp, .m, .mm, .h, .cu, .rc, .assembly, .assembly_with_cpp => {
+            const minver: u16 = @truncate(@intFromEnum(target.os.getVersionRange().windows.min) >> 16);
+            try argv.append(try std.fmt.allocPrint(argv.allocator, "-D_WIN32_WINNT=0x{x:0>4}", .{minver}));
+        },
+        else => {},
+    };
+
     switch (ext) {
         .c, .cpp, .m, .mm, .h, .cu, .rc => {
             try argv.appendSlice(&[_][]const u8{
diff --git a/src/mingw.zig b/src/mingw.zig
index f4d5ae23e..4d122819d 100644
--- a/src/mingw.zig
+++ b/src/mingw.zig
@@ -89,7 +89,6 @@ pub fn buildCRTFile(comp: *Compilation, crt_file: CRTFile, prog_node: *std.Progr
 
                     "-std=gnu99",
                     "-D_CRTBLD",
-                    "-D_WIN32_WINNT=0x0f00",
                     "-D__MSVCRT_VERSION__=0x700",
                     "-D__USE_MINGW_ANSI_STDIO=0",
                 });
@@ -114,7 +113,6 @@ pub fn buildCRTFile(comp: *Compilation, crt_file: CRTFile, prog_node: *std.Progr
 
                 "-std=gnu99",
                 "-D_CRTBLD",
-                "-D_WIN32_WINNT=0x0f00",
                 "-D__MSVCRT_VERSION__=0x700",
                 "-D__USE_MINGW_ANSI_STDIO=0",
 
@@ -163,7 +161,6 @@ pub fn buildCRTFile(comp: *Compilation, crt_file: CRTFile, prog_node: *std.Progr
 
                 "-std=gnu99",
                 "-D_CRTBLD",
-                "-D_WIN32_WINNT=0x0f00",
                 "-D__MSVCRT_VERSION__=0x700",
                 "-D__USE_MINGW_ANSI_STDIO=0",
 
@@ -226,7 +223,6 @@ pub fn buildCRTFile(comp: *Compilation, crt_file: CRTFile, prog_node: *std.Progr
 
                 "-std=gnu99",
                 "-D_CRTBLD",
-                "-D_WIN32_WINNT=0x0f00",
                 "-D__MSVCRT_VERSION__=0x700",
                 "-D__USE_MINGW_ANSI_STDIO=0",
 
@@ -272,7 +268,6 @@ fn add_cc_args(
     try args.appendSlice(&[_][]const u8{
         "-std=gnu11",
         "-D_CRTBLD",
-        "-D_WIN32_WINNT=0x0f00",
         "-D__MSVCRT_VERSION__=0x700",
         "-D__USE_MINGW_ANSI_STDIO=0",
     });
```

</details>

2023-09-26 11:53 UTC, phildrip commented
thanks! I've done as you suggested. I believe this means that the correct define is specified whenever a minimum version is specified via the target info.

2023-09-26 12:02 UTC, mikdusan commented
> I believe this means that the correct define is specified whenever a minimum version is specified via the target info, so it takes effect for user code, mingw, libcxx and all supporting libs.

small clarification. Even when `-target` does not specify a minver, there is a default minver which for windows is `win8_1`.

2023-09-26 19:25 UTC, merged

2023-09-26 20:39 UTC, squeek502 commented
Nice work @phildrip and @mikdusan!