Fix some frameworks not linking macos
ziglang/zig pull request #17531
Opened 2023-10-15 11:15 UTC by moosichu

Pull request #16888 removed searching for libraries with no extensions when linking frameworks... this adds that feature back.

This fixes #17294.

2023-10-15 11:39 UTC, moosichu commented
For context, in the loop iterating over extensions was changed when that logic was moved to the frontend:

[Removed](https://github.com/ziglang/zig/pull/16888/files#diff-fec40ee24d981f2bd0ded9f221b211ffed98cf41a66cf86d48c5369c14d9c4e3):
```zig
for (&[_][]const u8{ ".tbd", ".dylib", "" }) |ext| {
    if (try MachO.resolveFramework(arena, dir, f_name, ext)) |full_path| {
        const info = options.frameworks.get(f_name).?;
        try libs.put(full_path, .{
            .needed = info.needed,
            .weak = info.weak,
            .path = full_path,
        });
        continue :outer;
    }
}
```

[Added](https://github.com/ziglang/zig/pull/16888/files#diff-d924ca21d81d7d5a59eb9e10d3e2689c4c58a7e28e6ecce6a064701666f5a730):

```zig
for (&[_][]const u8{ "tbd", "dylib" }) |ext| {
    test_path.clearRetainingCapacity();
    try test_path.writer().print("{s}" ++ sep ++ "{s}.framework" ++ sep ++ "{s}.{s}", .{
        framework_dir_path,
        framework_name,
        framework_name,
        ext,
    });
    try checked_paths.writer().print("\n {s}", .{test_path.items});
    fs.cwd().access(test_path.items, .{}) catch |err| switch (err) {
        error.FileNotFound => continue,
        else => |e| fatal("unable to search for {s} framework '{s}': {s}", .{
            ext, test_path.items, @errorName(e),
        }),
    };
    return true;
}
```

This change restores the previous behavior in main.zig.

2023-10-15 15:41 UTC, kubkon requested changes
Nice, thanks! I think we may need the same treatment in the code responsible for resolving dylib dependencies: https://github.com/ziglang/zig/blob/a241cf90d66ee0a47fafc49dc65fe32871557a01/src/link/MachO.zig#L679

cc @mikdusan

2023-10-15 16:16 UTC, moosichu commented
I'm not entirely sure the full context of how things are supposed to work when linking MachO, but hopefully I applied the changes in the right way! (if the changes to `accessLibPath` aren't desired then just merge the first commit 😅 ).

2023-10-15 19:07 UTC, mikdusan commented
Framework primary artifacts are _usually_ named as follows:

1. `Foo.framework/Version/Current/Foo`
2. `Foo.framework/Version/Current/Foo.tbd`

Do we have any concrete examples of macOS SDK (new and old) with this pattern?

3. `Foo.framework/Version/Current/Foo.dylib`

2023-10-15 21:06 UTC, moosichu commented
So should this change remove the .dylib path also? TBH I've not dived into enough frameworks to know! (and it's obviously very hard to prove the non-existence of something, especially if it's just very rare!).

2023-10-15 21:17 UTC, moosichu commented
https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPFrameworks/Concepts/FrameworkAnatomy.html

This only mentions the primary artifacts having no extension, so is definetely good to go. I presume the .tbd extension is newer than this documentation? (Which was last updated in 2013 - so I presume that very well may be the case!).

So `.dylib` in the case for frameworks may never need to be handled then?

@kubkon in light of this - what changes would you like to see this PR contain? (what is `accessLibPath`  - is the change I made in the additional commit still sensible in light of this? Had a look at the contexts it is used briefly but personally don't feel confident enough on this one in particular). I am sure that a minimum, the change in `main.zig` will fix a known issue.

2023-10-15 22:07 UTC, nogira commented
these are all the folders containing files with .dylib extensions in Frameworks folders in latest xcode. looks like there aren't any directly in `Foo.framework/Versions/Current` like `Foo.framework/Versions/Current/Foo.tbd`
(note: folder `A` from below = folder alias `Current`)

```shell
find /Applications/Xcode.app/Contents -name "*.dylib" -type f -exec dirname {} \; | grep Framework

/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/SDKs/AppleTVSimulator.sdk/System/Library/Frameworks/OpenGLES.framework
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/OpenGLES.framework
/Applications/Xcode.app/Contents/SharedFrameworks/SwiftPM.framework/Versions/A/SharedSupport/PluginAPI
/Applications/Xcode.app/Contents/SharedFrameworks/SwiftPM.framework/Versions/A/SharedSupport/PluginAPI
/Applications/Xcode.app/Contents/SharedFrameworks/SwiftPM.framework/Versions/A/SharedSupport/ManifestAPI
/Applications/Xcode.app/Contents/SharedFrameworks/SwiftPM.framework/Versions/A/SharedSupport/ManifestAPI
/Applications/Xcode.app/Contents/SharedFrameworks/SwiftPM.framework/Versions/A/SharedSupport/ManifestAPI
/Applications/Xcode.app/Contents/SharedFrameworks/SourceKit.framework/Versions/A/XPCServices/com.apple.dt.SKAgent.xpc/Contents/Frameworks
/Applications/Xcode.app/Contents/SharedFrameworks/SourceKit.framework/Versions/A/XPCServices/com.apple.dt.SKAgent.xpc/Contents/Frameworks
/Applications/Xcode.app/Contents/SharedFrameworks/SourceKit.framework/Versions/A/XPCServices/com.apple.dt.SKAgent.xpc/Contents/Frameworks
/Applications/Xcode.app/Contents/SharedFrameworks/SourceKit.framework/Versions/A/XPCServices/com.apple.dt.SKAgent.xpc/Contents/Frameworks
/Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Versions/A/Libraries/usr/lib/swift/host
/Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Versions/A/Libraries/usr/lib/swift/host
/Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Versions/A/Libraries/usr/lib/swift/host
/Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Versions/A/Libraries/usr/lib/swift/host
/Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Versions/A/Libraries/usr/lib/swift/host
/Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Versions/A/Libraries/usr/lib/swift/host
/Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Versions/A/Libraries/usr/lib/swift/host
/Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Versions/A/Libraries/usr/lib/swift/host
/Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Versions/A/Libraries/usr/lib/swift/host
/Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Versions/A/Libraries/usr/lib/swift/host
/Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Versions/A/Libraries/usr/lib/swift/host
/Applications/Xcode.app/Contents/SharedFrameworks/DVTInstrumentsFoundation.framework/Versions/A/Resources
/Applications/Xcode.app/Contents/SharedFrameworks/DVTInstrumentsFoundation.framework/Versions/A/Resources
/Applications/Xcode.app/Contents/SharedFrameworks/AppIntentsSupport.framework/Versions/A/Resources
/Applications/Xcode.app/Contents/SharedFrameworks
/Applications/Xcode.app/Contents/SharedFrameworks/CoreSymbolicationDT.framework/Versions/A/Resources
/Applications/Xcode.app/Contents/SharedFrameworks/CoreSymbolicationDT.framework/Versions/A/Resources/libatos/libs
/Applications/Xcode.app/Contents/Frameworks
/Applications/Xcode.app/Contents/Frameworks
```

2023-10-15 22:20 UTC, mikdusan commented
> what changes would you like to see this PR contain? (what is `accessLibPath` - is the change I made in the additional commit still sensible in light of this? Had a look at the contexts it is used briefly but personally don't feel confident enough on this one in particular). I am sure that a minimum, the change in `main.zig` will fix a known issue.

```diff
diff --git a/src/main.zig b/src/main.zig
index 4b8061a52..5d7665356 100644
--- a/src/main.zig
+++ b/src/main.zig
@@ -6929,7 +6929,7 @@ fn accessFrameworkPath(
 ) !bool {
     const sep = fs.path.sep_str;
 
-    for (&[_][]const u8{ ".tbd", ".dylib", "" }) |ext| {
+    for (&[_][]const u8{ ".tbd", "" }) |ext| {
         test_path.clearRetainingCapacity();
         try test_path.writer().print("{s}" ++ sep ++ "{s}.framework" ++ sep ++ "{s}{s}", .{
             framework_dir_path,
```

... for Macho's `accessLibPath()` it doesn't look like _any_ patches are required for it. Could you re-try the motivating libSDL case without patching `Macho.zig` ?

2023-10-15 22:32 UTC, mikdusan commented
> these are all the folders containing files with `.dylib` extensions in Frameworks folders in latest xcode. looks like there aren't any `.dylib` files directly in `Foo.framework/Versions/Current` like `Foo.framework/Versions/Current/Foo.dylib` (note: folder `A` from below = folder alias `Current`)

yup and seems to be consistent with SDKs all the way back to 10.3.9 .

2023-10-15 22:46 UTC, kubkon commented
I want all three extensions handled including `.dylib`. While Apple might not ship them, don't forget users can create and ship their own frameworks too.

2023-10-15 22:58 UTC, mikdusan commented
> I want all three extensions handled including `.dylib`. While Apple might not ship them, don't forget users can create and ship their own frameworks too.

What about `.a` ?

2023-10-16 05:37 UTC, kubkon commented
> > I want all three extensions handled including `.dylib`. While Apple might not ship them, don't forget users can create and ship their own frameworks too.
> 
> What about `.a` ?
> 
> So, { `".tbd"`, `".dylib"`, `".a"`, `""` } ?

That one needs more thought - does search strategy impact search here? I would like to leave that one be for the moment until we actually thoroughly investigate static frameworks.

2023-10-16 08:12 UTC, moosichu commented
> > what changes would you like to see this PR contain? (what is `accessLibPath` - is the change I made in the additional commit still sensible in light of this? Had a look at the contexts it is used briefly but personally don't feel confident enough on this one in particular). I am sure that a minimum, the change in `main.zig` will fix a known issue.
> 
> 
> 
> ```diff
> 
> diff --git a/src/main.zig b/src/main.zig
> 
> index 4b8061a52..5d7665356 100644
> 
> --- a/src/main.zig
> 
> +++ b/src/main.zig
> 
> @@ -6929,7 +6929,7 @@ fn accessFrameworkPath(
> 
>  ) !bool {
> 
>      const sep = fs.path.sep_str;
> 
>  
> 
> -    for (&[_][]const u8{ ".tbd", ".dylib", "" }) |ext| {
> 
> +    for (&[_][]const u8{ ".tbd", "" }) |ext| {
> 
>          test_path.clearRetainingCapacity();
> 
>          try test_path.writer().print("{s}" ++ sep ++ "{s}.framework" ++ sep ++ "{s}{s}", .{
> 
>              framework_dir_path,
> 
> ```
> 
> 
> 
> ... for `MachO.accessLibPath()` it doesn't look like _any_ patches are required for it. Could you re-try the motivating libSDL case without patching `MachO.zig` ?
> 
> 
> 
> also I'd like to add the reason why I am scrutinizing `.dylib` for frameworks is because, although rare, frameworks may be static, and I found no examples of `.a` either except for some very poorly named stub libraries in Tcl and Tk frameworks. Basically, if we want to search for `.dylib` we also should search for `.a`, but searching for neither looks to be the right behavior!

Yeah so I already tested with just patching main.zig and that fixed the motivating use case for me.

2023-10-16 11:15 UTC, moosichu commented
So I want to confirm, in terms of this PR, we want this commit:
https://github.com/ziglang/zig/pull/17531/commits/8870ead9b257c1b02f668075c3c53e70b204832f
but not this:
https://github.com/ziglang/zig/pull/17531/commits/023d1ac6bf25c941510509ddbb659c73947ec39b

So I should go ahead and remove that second one? Is that the correct takeaway from this conversation @kubkon @mikdusan?

I did validate that the first one was all that I needed to get SDL linking again.

2023-10-16 18:44 UTC, kubkon approved these changes
Looks great, thanks!

2023-10-16 18:45 UTC, merged