Sema: disallow @intFromPtr to accept comptime-only types
ziglang/zig pull request #17540
Opened 2023-10-15 18:31 UTC by wrongnull

It would make a lot more sense if we prevented it from accepting pointers to comptime-only types. For instance the following 
```zig
pub fn main() void {
    const x = 0;
    const y = @intFromPtr(&x);
    @import("std").debug.print("{d}\n", .{y});
```
prints a ridiculously large number

2023-10-15 22:11 UTC, wrongnull commented
It looks like anytype parameters are treated as comptime-only under any conditions. @Vexu , is it a bug? If so, I could open an issue and try to fix one.

2023-10-16 05:04 UTC, Vexu commented
No, this just has the same bug that you fixed for `@extern` in #17509. Also @SpexGuy was against this change when I previously tried to implement it in https://github.com/ziglang/zig/pull/11734#issuecomment-1139132094.

2023-10-16 12:39 UTC, mlugg commented
> Also @SpexGuy was against this change when I previously tried to implement it in [#11734 (comment)](https://github.com/ziglang/zig/pull/11734#issuecomment-1139132094).

AFAICT that's about something else. `@intFromPtr` on pointers to comptime memory *where the child type is not comptime-only* could, in theory, be implemented in a semi-sane way using lazy values or something (although I still don't think that's a worthwhile idea). However, this is about `@intFromPtr` on an actual comptime-only type, where having a concrete address is just a nonsensical concept - it's not like you could ever perform meaningful arithmetic on that address, since the value doesn't have a size.

Currently, it seems backends (or at least LLVM) just lower these values as references to zero-bit types (so give them an arbitrary "fake address"), which is an entirely useless and unintuitive behavior.

2023-10-17 04:07 UTC, andrewrk requested changes
Thanks! After a minor rewording of the error message, this is ready to land.

2023-10-17 07:22 UTC, wrongnull commented on src/Sema.zig
> +            const msg = try sema.errMsg(block, ptr_src, "cannot accept pointer to comptime-only type '{}'", .{pointee_ty.fmt(mod)});
+

2023-10-17 07:32 UTC, wrongnull commented on src/Sema.zig
> +            const msg = try sema.errMsg(block, ptr_src, "cannot accept pointer to comptime-only type '{}'", .{pointee_ty.fmt(mod)});
@andrewrk Is it worth mentioning this in the langref?

2023-10-17 20:05 UTC, merged