llvm: set PIE only for executables
ziglang/zig pull request #17597
Opened 2023-10-18 19:56 UTC by mikdusan

closes #17575

2023-10-18 20:17 UTC, andrewrk commented
Shouldn't `options.pie` be set to false earlier in the frontend?

2023-10-18 23:40 UTC, andrewrk requested changes
missing error when the user specifies `-fpie` for an executable

2023-10-18 23:45 UTC, mikdusan commented
> missing error when the user specifies `-fpie` for a non-executable

ha I actually had that done and took it out.

Do we also want to error for `-fno-PIE` for non-executables?

2023-10-18 23:48 UTC, andrewrk commented
no

2023-10-19 00:35 UTC, andrewrk requested changes
keep it simple:

```zig
const pie: bool = pie: {
    if (options.output_mode != .Exe) {
        if (options.want_pie == true) return error.OutputModeForbidsPie;
        break :pie false;
    }
    if (target_util.requiresPIE(options.target)) {
        if (options.want_pie == false) return error.TargetRequiresPie;
        break :pie true;
    }
    if (tsan) {
        if (options.want_pie == false) return error.TsanRequiresPie;
        break :pie true;
    }
    if (options.want_pie) |want_pie| {
        break :pie want_pie;
    }
    break :pie false;
};
```

2023-10-19 00:35 UTC, andrewrk commented on src/Compilation.zig
> +                if (options.want_pie) |explicit| if (explicit) return error.PIERequiresExe;
```suggestion
                if (options.want_pie == true) return error.PIERequiresExe;
```

2023-10-19 02:58 UTC, andrewrk commented
Looks good, thanks!

2023-10-20 05:59 UTC, merged

2023-10-20 14:47 UTC, IntegratedQuantum commented
This change appears to break the thread sanitizer even further:
I was just attempting to look into repairing the thread sanitizer, when I got
`error: unable to build TSAN library: OutputModeForbidsPie`
It appears that the thread sanitizer builds as a lib, but also requires PIE.

2023-10-21 13:35 UTC, mikdusan commented
> This change appears to break the thread sanitizer even further: I was just attempting to look into repairing the thread sanitizer, when I got `error: unable to build TSAN library: OutputModeForbidsPie` It appears that the thread sanitizer builds as a lib, but also requires PIE.

#17653 should fix it