std.zig.system.NativeTargetInfo: small cleanup, de-duplicate code with std.elf
ziglang/zig pull request #17724
Opened 2023-10-26 06:57 UTC by BratishkaErik

2023-10-28 07:40 UTC, BratishkaErik commented
Rebased on master.

2023-10-28 20:49 UTC, BratishkaErik commented
x86_64-linux-release failure seems unrelated?

2023-10-29 06:49 UTC, BratishkaErik commented
Rebased on master, failure is gone.

2023-12-24 09:40 UTC, BratishkaErik commented
Rebased on master.

2024-01-04 22:58 UTC, andrewrk requested changes
It looks like there is a bug fix here buried among "cleanup" commits. It is unclear to me how the new code is better than the old code.

I have 2 requests for you:
1. Can you submit the bug fix independently?
2. Can you explain what is improved in the other commits without using the word "clean"?

2024-01-04 22:58 UTC, andrewrk commented on lib/std/zig/system.zig
> +                const p_filesz = program_header.p_filesz;
The code that you are replacing here is designed to make as few syscalls as possible. Can you share how the new code fared against the old code?

2024-01-04 22:58 UTC, andrewrk commented on lib/std/zig/system.zig
> +            const file = cwd.openFile(file_name, .{ .mode = .read_only }) catch |err| switch (err) {
`openFileAbsolute` is correct when the file path is an absolute path, as it is with `/usr/bin/env` as well as any shebang line encountered.

2024-01-04 22:58 UTC, andrewrk commented on lib/std/elf.zig
> +pub const SectionHeader = struct {
Opinionated code like this should not go into std.elf but somewhere else such as std.zig.elf perhaps. However, why is this even needed? It's redundant with Elf64_Shdr.

2024-01-27 10:06 UTC, closed without merging