mingw: Use aro instead of clang for preprocessing import libs
ziglang/zig pull request #17771
Opened 2023-10-29 05:25 UTC by ehaas

Based on manual testing, this produces the same output for `kernel32.def` when compared to clang, other than minor whitespace differences (clang puts a newline at the beginning, and a trailing space on one line which aro does not)

Testing steps:
1. Clear zig cache
2. Create empty `test.c`
3. With status-quo zig: `zig build-lib -target x86_64-windows-gnu -lkernel32 --verbose-cc test.c` 
a. This will print a `zig clang` line to stderr; the output path is the final argument
4. With this branch: `./zig-out/bin/zig build-lib -target x86_64-windows-gnu -lkernel32 --verbose-cc test.c`
a. This will print `output path: <ZIG_CACHE_PATH>/o/<SOME HASH>/kernel32.def`
5. Diff the two files 
6. Available targets are `x86_64-windows-gnu`, `x86-windows-gnu`, `arm-windows-gnu`, `aarch64-windows-gnu`

I manually tested error handling by editing `kernel32.def.in` to have an invalid preprocessing directive and got the following:
```
zig-out/lib/zig/libc/mingw/lib-common/kernel32.def.in:1:1: error: invalid preprocessing directive
#foo
^
1 error generated.
error: unable to generate DLL import .lib file for kernel32: AroPreprocessorFailed
```

Closes #17753

2023-10-29 07:50 UTC, andrewrk commented
I suggest to put a check for `build_options.only_core_functionality` to prevent Aro from being compiled into zig1.wasm or zig2.c during the bootstrap process. This will also fix the current CI failures.

2023-10-30 06:46 UTC, ehaas commented
Is there a way to test this locally if I don't have access to a windows machine? I don't want to spam the CI with attempts, since I'm not totally sure where the check should go. It seems like the function is being used, since we're hitting that panic - does that mean that if `build_options.only_core_functionality` is true, we should use the existing `zig clang` solution, and otherwise use the new aro one?

2023-10-30 07:55 UTC, andrewrk commented
Yes, here is a way to test it:

1. put  `@compileError()` somewhere inside aro
2. `zig build -Donly-c`

If you get the compile error, it's incorrectly including aro in the build.

The check goes at the top of `buildImportLib`:

```zig
if (build_options.only_core_functionality) @panic("building import libs not included in core functionality");
```

2023-10-31 17:46 UTC, andrewrk commented
Oops, I gave you some bad advice. It should be checking `only_c` instead of `only_core_functionality`.

We don't want the logic to be part of zig1.wasm, however we do want the logic to be part of zig2.c.

The use case for `only_core_functionality` is for example package fetching. We certainly do not need zig2 to have the package manager logic inside of it.

2023-10-31 17:50 UTC, ehaas commented
Ok, if I add that I assume it means it's also safe for me to remove the `if (builtin.zig_backend == .stage2_c) @panic("the CBE cannot compile Aro yet!");` from later in the function, right before I import aro?

2023-10-31 17:51 UTC, andrewrk requested changes

2023-10-31 17:51 UTC, andrewrk commented on src/mingw.zig
> +    cache.hash.addBytes("aro");
No need, already covered by `build_options.version`.

2023-10-31 18:01 UTC, andrewrk commented on src/mingw.zig
> +    if (!build_options.have_llvm) return error.ZigCompilerNotBuiltWithLLVMExtensions;
#17807

2023-10-31 18:10 UTC, ehaas commented on src/mingw.zig
> +    if (builtin.zig_backend == .stage2_c) @panic("the CBE cannot compile Aro yet!");
I get a bunch of errors when compiling zig2.c - the first few:

```
/Users/ehaas/source/zig/build/zig2.c:799577:1154: error: call to undeclared function 'zig_make_big'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
/Users/ehaas/source/zig/build/zig2.c:799577:1183: error: call to undeclared function 'zig_shl_big'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
/Users/ehaas/source/zig/build/zig2.c:799577:1183: note: did you mean 'zig_shl_i8'?
/Users/ehaas/source/zig/stage1/zig.h:534:1: note: 'zig_shl_i8' declared here
zig_int_helpers(8)
^
/Users/ehaas/source/zig/stage1/zig.h:464:5: note: expanded from macro 'zig_int_helpers'
    zig_shift_operator( int##w##_t, shl_i##w, <<) \
    ^
/Users/ehaas/source/zig/stage1/zig.h:455:5: note: expanded from macro 'zig_shift_operator'
    zig_operator(Type, uint8_t, operation, operator)
    ^
/Users/ehaas/source/zig/stage1/zig.h:449:24: note: expanded from macro 'zig_operator'
    static inline Type zig_##operation(Type lhs, RhsType rhs) { \
                       ^
<scratch space>:93:1: note: expanded from here
zig_shl_i8
^
/Users/ehaas/source/zig/build/zig2.c:799577:1236: error: too few arguments to function call, expected 5, have 2
/Users/ehaas/source/zig/stage1/zig.h:1996:20: note: 'zig_or_big' declared here
static inline void zig_or_big(void *res, const void *lhs, const void *rhs, bool is_signed, uint16_t bits) {
                   ^
/Users/ehaas/source/zig/build/zig2.c:800411:30: error: call to undeclared function 'zig_lo_big'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   t4 = zig_wrap_u8((uint8_t)zig_lo_big(zig_shr_big(t9, UINT16_C(236))), UINT8_C(4));
                             ^
```

2023-11-02 22:14 UTC, ehaas commented
@Vexu I will need your help integrating the arocc's `GenerateDef` changes with zig's `build.zig` - I'm not sure how to add the def files to the aro module.

2023-11-02 23:02 UTC, Vexu commented
I don't think there's going to be an easy way to do so because of the bootstrapping process. I'd just copy the generated files from the cache and replace the def files.

2023-11-02 23:23 UTC, Vexu commented
One possible option would be to add a stubbed def file and then in CMake add that as the module for the def files for the purpose of bootstrapping. For building them regularly it should be easy enough to copy some parts from Aro's `build.zig`.

A stub would look something like this:
```zig
pub fn with(comptime _: type) type {
    return struct {
        pub const max_param_count = 0;
        pub const longest_name = 0;
        pub const data = [_]@This(){.{}};
        pub fn fromName(_: []const u8) ?@This() {
            return null;
        }
        pub fn nameFromUniqueIndex(_: u16, _: []u8) []u8 {
            return "";
        }
        pub fn uniqueIndex(_: []const u8) ?u16 {
            return null;
        }
        pub const Tag = enum(u16) { _ };
        pub fn nameFromTag(_: Tag) NameBuf {}
        pub fn tagFromName(name: []const u8) ?Tag {
            return @enumFromInt(name.len);
        }
        pub const NameBuf = struct {
            pub fn span(_: *const NameBuf) []const u8 {
                return "";
            }
        };
    };
}

```

2023-11-03 17:33 UTC, Vexu approved these changes
I forgot about the "file exists in multiple modules" error again and made the stub work for both. It could be simplified for them individually but this works too.

2023-11-03 19:08 UTC, ehaas commented
The issue I was seeing was that stage3 was unable to build the zig compiler due to not finding the def files. I fixed it with the following diff:

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index dcbddc476..d5fd9b4b1 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -647,8 +647,11 @@ set(ZIG_STAGE2_SOURCES
     "${CMAKE_SOURCE_DIR}/src/windows_sdk.zig"
     "${CMAKE_SOURCE_DIR}/src/stubs/aro_builtins.zig"
     "${CMAKE_SOURCE_DIR}/src/stubs/aro_attributes.zig"
+    "${CMAKE_SOURCE_DIR}/deps/aro/Attribute/names.def"
+    "${CMAKE_SOURCE_DIR}/deps/aro/Builtins/Builtin.def"
 )

+
 if(MSVC)
     set(MSVC_DIA_SDK_DIR "$ENV{VSINSTALLDIR}DIA SDK")
     if(IS_DIRECTORY ${MSVC_DIA_SDK_DIR})
@@ -947,3 +950,10 @@ install(CODE "set(ZIG_BUILD_ARGS \"${ZIG_BUILD_ARGS}\")")
 install(CODE "set(CMAKE_INSTALL_PREFIX \"${CMAKE_INSTALL_PREFIX}\")")
 install(CODE "set(CMAKE_SOURCE_DIR \"${CMAKE_SOURCE_DIR}\")")
 install(SCRIPT "${CMAKE_SOURCE_DIR}/cmake/install.cmake")
+
+
+file(COPY ${CMAKE_CURRENT_SOURCE_DIR}/deps/aro/Attribute/names.def
+     DESTINATION ${CMAKE_CURRENT_BINARY_DIR}/deps/aro/Attribute)
+
+file(COPY ${CMAKE_CURRENT_SOURCE_DIR}/deps/aro/Builtins/Builtin.def
+     DESTINATION ${CMAKE_CURRENT_BINARY_DIR}/deps/aro/Builtins)
```

I'm not sure if this is the correct fix; I also did this without your changes to this branch or to aro from today.

2023-11-03 19:10 UTC, andrewrk commented
Please don't add any additional logic to CMakeLists.txt. Zig should depend on Aro only as a set of zig files. I don't want to add any Aro-related build system logic to zig's build process.

2023-11-03 20:20 UTC, Vexu commented
> The issue I was seeing was that stage3 was unable to build the zig compiler due to not finding the def files.

I think the issue was https://github.com/Vexu/arocc/commit/9f4c28ae36b664238ce8e4ac1d0e7fd147d16726

2023-11-03 21:07 UTC, ehaas commented
If we want to completely eliminate the `CMakeLists.txt` changes (so, no stub modules or anything) I have a local patch that does that by replacing the `.def` file contents with the generated versions. It succeeds at the bootstrap + stage4 build. Let me know if that is desired and I can push it.

2023-11-07 19:46 UTC, andrewrk commented
Thanks @ehaas. I think this is fine - passing a few more args to building zig2.c is OK, I just didn't want to add any more steps to the process. For example, to update #17892 after merging this PR, I will only need to adjust a few command line args, but not introduce more logic into bootstrap.c.

2023-11-07 19:47 UTC, merged