io_uring: ring mapped buffers
ziglang/zig pull request #17806
Opened 2023-10-31 17:26 UTC by ianic

Ring mapped buffers are newer implementation of provided buffers, supported since kernel 5.19.
Best described by Jens Axboe in [io_uring and networking in 2023](https://github.com/axboe/liburing/wiki/io_uring-and-networking-in-2023#provided-buffers).  
Newer implementation requires less management, after initial setup, and should be more [efficient](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=c7fb19428d67dd0a2a78a4f237af01d39c78dc5a).

This commit implements low level io_uring_buf_ring functions as mostly direct translation from liburing:
* io_uring_setup_buf_ring
* io_uring_free_buf_ring
* io_uring_buf_ring_init
* io_uring_buf_ring_mask
* io_uring_buf_ring_add
* io_uring_buf_ring_advance

Using this functions is little work-some. Application need first to setup_buf_ring, add buffers with appropriate buffer ID, advance to make buffers visible to the kernel, find buffer for buffer ID from the CQE, repeat cycle of add/advance after application wants to return buffer to the kernel and call free_buf_ring at the end.

So I incorporate this low level functions into developer friendly abstraction: BufferGroup. Didn't named it BufferRing or BufRing as in liburing because ring is already overused word in io_uring.zig file. To avoid confusion I stayed away from ring word.

Application provides to the BufferGroup contiguous block of memory of size `buffers_count` * `buffers_size`. It can then use BufferGroup to submit `recv` operation without providing buffer upfront. Once the operation is ready to receive data, a buffer is picked automatically and the resulting CQE will contain the buffer ID in `cqe.buffer_id()`. Use `get` method to get buffer for buffer ID identified by CQE. Once the application has processed the buffer, it may hand ownership back to the kernel, by calling `put` allowing the cycle to repeat.

Example BufferGroup usage: 
```Zig
     // setup buffer group
     const group_id: u16 = 0;
     const buffers_count: u16 = 256;
     const buffer_size: u32 = 4096;
     const buffers = try allocator.alloc(u8, buffers_count * buffers_size);
     var buf_grp = try BufferGroup.init.ring(&ring, group_id, buffers, buffer_size, buffers_count);

     // prepare recv on fd with buffer picked from group
     _ = try buf_grp.recv(user_data, fd, 0);

     // ... when we have completion for recv operation
     // (assuming cqe.err() == .SUCCESS)
     const buffer_id = try cqe.buffer_id();
     const len = @as(usize, @intCast(cqe.res));
     var buf = buf_grp.get(buffer_id)[0..len];
     // ... use buf
     buf_grp.release(buffer_id);

     // ...
     buf_grp.deinit();
```

2023-11-11 16:29 UTC, ianic commented
A test ("ring mapped buffers multishot recv") was failing in Zig ci. It is fixed now and this PR is again ready to merge.

Failing test traced down to different kernels between my dev env and Zig ci. io_uring multishot recv cancel operation is returning different completion results depending on the Linux kernel. Kernel 6.5 returns expected result, older kernels return slightly different results.

In the test there is active multishot recv operation. When I cancel that operation I got two completions, one for cancel operation cqe_cancel and another for multishot recv operation cqe_recv. According to documentation I expected that cqe_cancel has res = 0 (success) and cqe_recv has res = -124 (canceled). And that is what I get on kernel 6.5.

On older kernels 6.0, 6.1, 6.2, 6.4 I got for cqe_cancel res = -2 (noent) and cqe_recv res = -105 (nobufs).

I'm now handling both cases as successful cancel operation.

2024-03-08 23:30 UTC, andrewrk commented
I'm sorry for letting this bitrot, but if you take the trouble to rebase it I will merge it.

2024-03-12 00:15 UTC, ianic commented
Rebased.

2024-03-12 01:05 UTC, andrewrk requested changes
If I merge your branch locally, and then run `zig std` to look at the documentation, here is what I see:

```
...
std.os.linux.IoUring.unregister_eventfd
std.os.linux.IoUring.register_buffers
std.os.linux.IoUring.unregister_buffers
std.os.linux.IoUring.unregister_files
std.os.linux.IoUring.socket
std.os.linux.IoUring.socket_direct
std.os.linux.IoUring.socket_direct_alloc
std.os.linux.IoUring.SubmissionQueue
std.os.linux.IoUring.CompletionQueue
std.os.linux.IoUring.BufferGroup
std.os.linux.IoUring.io_uring_setup_buf_ring
std.os.linux.IoUring.io_uring_free_buf_ring
std.os.linux.IoUring.io_uring_buf_ring_init
std.os.linux.IoUring.io_uring_buf_ring_advance
std.os.linux.IoUring.io_uring_buf_ring_add
std.os.linux.IoUring.io_uring_buf_ring_mask
std.os.linux.IoUring.CompletionQueue.deinit
std.os.linux.IoUring.BufferGroup.init
std.os.linux.IoUring.BufferGroup.recv
std.os.linux.IoUring.BufferGroup.recv_multishot
std.os.linux.IoUring.BufferGroup.get
std.os.linux.IoUring.BufferGroup.get_cqe
std.os.linux.IoUring.CompletionQueue.init
...
```

Notice how the new functions have a redundant prefix which should be removed.

2024-03-12 01:38 UTC, RossComputerGuy requested changes

2024-03-12 01:38 UTC, RossComputerGuy commented on lib/std/os/linux/IoUring.zig
> +    @atomicStore(u16, &br.tail, tail, .Release);
Please change `.Release` to `.release`.

2024-03-16 02:34 UTC, merged

2024-03-16 02:34 UTC, andrewrk commented
Thanks!