cbe: add a system for avoiding collisions with C compiler intrinsics
ziglang/zig pull request #17824
Opened 2023-11-02 05:51 UTC by kcbanner

Fixes https://github.com/ziglang/zig/issues/17817, and re-enables the MSVC CBE tests.

It's possible for some of the names generated by the macros in zig.h to collide with compiler intrinsics. This change introduces a system for avoiding these collisions, while still allowing the colliding name to be exported.

To avoid compile errors, the colliding names are redefined as `zig_intrin_<name>` in zig.h. If the symbol is exported, then a `zig_export` is generated mapping the mangled name back to the original.

The specific problem that sparked this change was the unfortunate combination of `zig_libc_name_f80(name) __##name##x` with the input `fma`, resulting in `__fmax`, which seems to be a new intrinsic in recent versions of cl.exe. If more of these intrinsic collisions come up in the future, all that has to be done is to add an entry to `colliding_intrinsics` and a `#define` in zig.h in the `Intrinsic Collisions` section.

2023-11-02 06:45 UTC, jacobly0 requested changes
`declIsGlobal` needs to be updated so that the symbols are not additionally exported under the new name.

Also, the `#define` is problematic because it causes external references to try to import the new name which doesn't exist (either because the above issue is fixed or the external library was compiled with a different backend, such as what is done with `compiler_rt`).

I suggest reusing `reserved_idents` instead of creating a new `colliding_intrinsics` thing, because this is exactly the same workaround that is needed in order to export a symbol like `int` or `max`.

2023-11-02 14:16 UTC, kcbanner commented
> `declIsGlobal` needs to be updated so that the symbols are not additionally exported under the new name.

> Also, the `#define` is problematic because it causes external references to try to import the new name which doesn't exist (either because the above issue is fixed or the external library was compiled with a different backend, such as what is done with `compiler_rt`).

I see - the `/alternatename` mechanism fixes this for Windows, by causing the linker to lookup the real name if the mangled name isn't found. 
 
> I suggest reusing `reserved_idents` instead of creating a new `colliding_intrinsics` thing, because this is exactly the same workaround that would be needed in order to export a symbol like `int` or `max`. There's also an extremely non-zero chance that redefining an intrinsic will break some macro from `windows.h` some day.

I considered using the `isReservedIdent` mechanism, but I thought it would bloat the generated source for a lot of simples that don't actually collide (ie. most of compiler_rt `__` prefixed functions), but with the `declIsGlboal` change, the line count should be the same. I can switch it over to this.

The problem then becomes, how do we mangle a name like `__fmax` such that we preserve the weak symbol behaviour, but also allow it to compile under recent MSVC.

- If we `#define` the symbol to a new name: Breaks importing, we'll no longer use the C compiler's compiler_rt version. 
- If we mangle the name via `fmtIdent`: Similar issue - now we are requiring use of our compiler-rt, since it's the only one that's going to provide `zig_e___fmax`. Even with the export change in place such that `__fmax` is exported, how do we hook that up on the import side under this scheme?

2023-11-02 14:59 UTC, jacobly0 commented
> how do we hook that up on the import side under this scheme?

Can't speak for MSVC, but it's easy enough in [normal C](https://godbolt.org/z/Ec8KvWo3M).

2023-11-02 15:19 UTC, Vexu commented
It looks like it might be possible in MSVC too [with pragmas](https://devblogs.microsoft.com/oldnewthing/20200731-00/?p=104024):
```c
#pragma comment(linker, "/alternatename:global_int=int")
int global_int;
```


BTW, if you need a list of all reserved keywords and library symbols Aro already has them.

2023-11-04 06:31 UTC, kcbanner commented
Ok, I think I've found a solution that doesn't require using `#define` to mask the symbols!

Changes:
- Add `isMangledIdent` to determine if `fmtIdent` would make any edits to the identifier
- Any function that has a mangled identifier is referred to using the mangled identifer
  within the current file, but if it is exported the first export will be with the non-mangled name.
- Add `zig_import` to import a symbol under a different name
- Add a level of indirection to float function names. Now, they are referred to as
  `zig_float_fn_<float type>_<operation>`. The definitions in zig.h are wrapped
  with `zig_import` to import the symbol under the real name.

With the above changes in place, compiler_rt can output the following (as an example):

```
static zig_weak_linkage_fn zig_f80 zig_e___fmax(zig_f80, zig_f80, zig_f80);
zig_export(zig_weak_linkage_fn zig_f80 zig_e___fmax(zig_f80, zig_f80, zig_f80), __fmax, "__fmax");
```

Within compiler_rt, `zig_e___fmax` is used to refer to the function, but consumers
will import `__fmax`, which maps to their `zig_float_fn_f80_fma` definition from zig.h.

The only problem left is to get msvc to actually export symbols under a different name. This may require using a .def file, since the /EXPORT pragma does not seem to allow you to rename an export. You can handle this on the import side with /ALTERNATENAME, but ideally we actually export the right names when compiled with msvc.

2023-11-04 23:44 UTC, kcbanner commented
Just pushed a solution to the MSVC export problem.

After trying several combinations of the `/INCLUDE`, `/EXPORT`, and `/ALTERNATENAME` linker flags (via pragmas), the only solution that works to export a symbol under a different name is to use `/ALTERNATENAME` in the exporting file. In the resulting obj, there is only a symbol under the original name, but the `/ALTERNATENAME` directive is included in the linker directive section of the COFF, and consumed by the linker. This has the effect of allowing us to refer to symbols via an alias across obj bounds.

This comes with the caveat that (even if you use `/EXPORT`), symbols won't be exported if they are marked `static`. This is where the new `DeclVisibility` enum comes in. For decls that are global (ie. have an export), but have a mangled name, `zig_extern_mangled` is used. On msvc, this is `zig_extern`, and on non-msvc this is `static`.

This seems to be the only way to accomplish this under MSVC. This does mean that, for example, the compiler-rt .obj has "extra" symbols like `zig_e___fmax` in it. There seems to be no way around this problem given that we can't affect the exported name directly - only redirect uses via `/ALTERNATENAME`.

2023-11-05 03:13 UTC, jacobly0 commented
I somewhat expect msvc to not allow you to get things exactly correct, I was only being critical of non-msvc having the correct imports and exports.

2023-11-11 05:01 UTC, jacobly0 approved these changes

2024-01-01 23:36 UTC, andrewrk commented
Nice work @kcbanner  and thanks for doing the reviews @jacobly0!

2024-01-01 23:36 UTC, merged

2024-01-02 00:55 UTC, andrewrk commented
Unfortunately I had to revert this because it caused a regression in the bootstrap process, presumably from sitting in the merge queue too long and accumulating a sneaky conflict. I apologize for not merging it sooner.

To reproduce the problem:

```
$ stage3/bin/zig build update-zig1
$ rm -rf ../zig-cache/
$ touch ../CMakeLists.txt && time ninja install && time stage3/bin/zig build -p stage4 -Dno-lib -Denable-llvm 
[0/1] Re-running CMake...
-- Configuring zig version 0.12.0-dev.1871+e426ae43a
-- Configuring done
-- Generating done
-- Build files have been written to: /home/andy/Downloads/zig/build-release
[8/9] Linking CXX executable zig2
FAILED: zig2 
: && /nix/store/lcf37pgp3rgww67v9x2990hbfwx96c1w-gcc-wrapper-12.2.0/bin/g++ -O3 -DNDEBUG -Wl,-z,stack-size=0x10000000 CMakeFiles/zig2.dir/zig2.c.o CMakeFiles/zig2.dir/compiler_rt.c.o -o zig2 -L/home/andy/local/llvm17-assert/lib -Wl,-rpath,/home/andy/local/llvm17-assert/lib  zigcpp/libzigcpp.a  /home/andy/local/llvm17-assert/lib/libclangFrontendTool.a  /home/andy/local/llvm17-assert/lib/libclangCodeGen.a  /home/andy/local/llvm17-assert/lib/libclangFrontend.a  /home/andy/local/llvm17-assert/lib/libclangDriver.a  /home/andy/local/llvm17-assert/lib/libclangSerialization.a  /home/andy/local/llvm17-assert/lib/libclangSema.a  /home/andy/local/llvm17-assert/lib/libclangStaticAnalyzerFrontend.a  /home/andy/local/llvm17-assert/lib/libclangStaticAnalyzerCheckers.a  /home/andy/local/llvm17-assert/lib/libclangStaticAnalyzerCore.a  /home/andy/local/llvm17-assert/lib/libclangAnalysis.a  /home/andy/local/llvm17-assert/lib/libclangASTMatchers.a  /home/andy/local/llvm17-assert/lib/libclangAST.a  /home/andy/local/llvm17-assert/lib/libclangParse.a  /home/andy/local/llvm17-assert/lib/libclangSema.a  /home/andy/local/llvm17-assert/lib/libclangStaticAnalyzerFrontend.a  /home/andy/local/llvm17-assert/lib/libclangStaticAnalyzerCheckers.a  /home/andy/local/llvm17-assert/lib/libclangStaticAnalyzerCore.a  /home/andy/local/llvm17-assert/lib/libclangAnalysis.a  /home/andy/local/llvm17-assert/lib/libclangASTMatchers.a  /home/andy/local/llvm17-assert/lib/libclangAST.a  /home/andy/local/llvm17-assert/lib/libclangParse.a  /home/andy/local/llvm17-assert/lib/libclangBasic.a  /home/andy/local/llvm17-assert/lib/libclangEdit.a  /home/andy/local/llvm17-assert/lib/libclangLex.a  /home/andy/local/llvm17-assert/lib/libclangARCMigrate.a  /home/andy/local/llvm17-assert/lib/libclangRewriteFrontend.a  /home/andy/local/llvm17-assert/lib/libclangRewrite.a  /home/andy/local/llvm17-assert/lib/libclangCrossTU.a  /home/andy/local/llvm17-assert/lib/libclangIndex.a  /home/andy/local/llvm17-assert/lib/libclangToolingCore.a  /home/andy/local/llvm17-assert/lib/libclangExtractAPI.a  /home/andy/local/llvm17-assert/lib/libclangSupport.a  /home/andy/local/llvm17-assert/lib/liblldMinGW.a  /home/andy/local/llvm17-assert/lib/liblldELF.a  /home/andy/local/llvm17-assert/lib/liblldCOFF.a  /home/andy/local/llvm17-assert/lib/liblldWasm.a  /home/andy/local/llvm17-assert/lib/liblldMachO.a  /home/andy/local/llvm17-assert/lib/liblldCommon.a  -lLLVMWindowsManifest  -lLLVMXRay  -lLLVMLibDriver  -lLLVMDlltoolDriver  -lLLVMCoverage  -lLLVMLineEditor  -lLLVMXCoreDisassembler  -lLLVMXCoreCodeGen  -lLLVMXCoreDesc  -lLLVMXCoreInfo  -lLLVMX86TargetMCA  -lLLVMX86Disassembler  -lLLVMX86AsmParser  -lLLVMX86CodeGen  -lLLVMX86Desc  -lLLVMX86Info  -lLLVMWebAssemblyDisassembler  -lLLVMWebAssemblyAsmParser  -lLLVMWebAssemblyCodeGen  -lLLVMWebAssemblyUtils  -lLLVMWebAssemblyDesc  -lLLVMWebAssemblyInfo  -lLLVMVEDisassembler  -lLLVMVEAsmParser  -lLLVMVECodeGen  -lLLVMVEDesc  -lLLVMVEInfo  -lLLVMSystemZDisassembler  -lLLVMSystemZAsmParser  -lLLVMSystemZCodeGen  -lLLVMSystemZDesc  -lLLVMSystemZInfo  -lLLVMSparcDisassembler  -lLLVMSparcAsmParser  -lLLVMSparcCodeGen  -lLLVMSparcDesc  -lLLVMSparcInfo  -lLLVMRISCVTargetMCA  -lLLVMRISCVDisassembler  -lLLVMRISCVAsmParser  -lLLVMRISCVCodeGen  -lLLVMRISCVDesc  -lLLVMRISCVInfo  -lLLVMPowerPCDisassembler  -lLLVMPowerPCAsmParser  -lLLVMPowerPCCodeGen  -lLLVMPowerPCDesc  -lLLVMPowerPCInfo  -lLLVMNVPTXCodeGen  -lLLVMNVPTXDesc  -lLLVMNVPTXInfo  -lLLVMMSP430Disassembler  -lLLVMMSP430AsmParser  -lLLVMMSP430CodeGen  -lLLVMMSP430Desc  -lLLVMMSP430Info  -lLLVMMipsDisassembler  -lLLVMMipsAsmParser  -lLLVMMipsCodeGen  -lLLVMMipsDesc  -lLLVMMipsInfo  -lLLVMLoongArchDisassembler  -lLLVMLoongArchAsmParser  -lLLVMLoongArchCodeGen  -lLLVMLoongArchDesc  -lLLVMLoongArchInfo  -lLLVMLanaiDisassembler  -lLLVMLanaiCodeGen  -lLLVMLanaiAsmParser  -lLLVMLanaiDesc  -lLLVMLanaiInfo  -lLLVMHexagonDisassembler  -lLLVMHexagonCodeGen  -lLLVMHexagonAsmParser  -lLLVMHexagonDesc  -lLLVMHexagonInfo  -lLLVMBPFDisassembler  -lLLVMBPFAsmParser  -lLLVMBPFCodeGen  -lLLVMBPFDesc  -lLLVMBPFInfo  -lLLVMAVRDisassembler  -lLLVMAVRAsmParser  -lLLVMAVRCodeGen  -lLLVMAVRDesc  -lLLVMAVRInfo  -lLLVMARMDisassembler  -lLLVMARMAsmParser  -lLLVMARMCodeGen  -lLLVMARMDesc  -lLLVMARMUtils  -lLLVMARMInfo  -lLLVMAMDGPUTargetMCA  -lLLVMAMDGPUDisassembler  -lLLVMAMDGPUAsmParser  -lLLVMAMDGPUCodeGen  -lLLVMAMDGPUDesc  -lLLVMAMDGPUUtils  -lLLVMAMDGPUInfo  -lLLVMAArch64Disassembler  -lLLVMAArch64AsmParser  -lLLVMAArch64CodeGen  -lLLVMAArch64Desc  -lLLVMAArch64Utils  -lLLVMAArch64Info  -lLLVMOrcJIT  -lLLVMWindowsDriver  -lLLVMMCJIT  -lLLVMJITLink  -lLLVMInterpreter  -lLLVMExecutionEngine  -lLLVMRuntimeDyld  -lLLVMOrcTargetProcess  -lLLVMOrcShared  -lLLVMDWP  -lLLVMDebugInfoLogicalView  -lLLVMDebugInfoGSYM  -lLLVMOption  -lLLVMObjectYAML  -lLLVMObjCopy  -lLLVMMCA  -lLLVMMCDisassembler  -lLLVMLTO  -lLLVMPasses  -lLLVMCFGuard  -lLLVMCoroutines  -lLLVMipo  -lLLVMVectorize  -lLLVMLinker  -lLLVMInstrumentation  -lLLVMFrontendOpenMP  -lLLVMFrontendOpenACC  -lLLVMFrontendHLSL  -lLLVMExtensions  -lLLVMDWARFLinkerParallel  -lLLVMDWARFLinker  -lLLVMGlobalISel  -lLLVMMIRParser  -lLLVMAsmPrinter  -lLLVMSelectionDAG  -lLLVMCodeGen  -lLLVMTarget  -lLLVMObjCARCOpts  -lLLVMCodeGenTypes  -lLLVMIRPrinter  -lLLVMInterfaceStub  -lLLVMFileCheck  -lLLVMFuzzMutate  -lLLVMScalarOpts  -lLLVMInstCombine  -lLLVMAggressiveInstCombine  -lLLVMTransformUtils  -lLLVMBitWriter  -lLLVMAnalysis  -lLLVMProfileData  -lLLVMSymbolize  -lLLVMDebugInfoBTF  -lLLVMDebugInfoPDB  -lLLVMDebugInfoMSF  -lLLVMDebugInfoDWARF  -lLLVMObject  -lLLVMTextAPI  -lLLVMMCParser  -lLLVMIRReader  -lLLVMAsmParser  -lLLVMMC  -lLLVMDebugInfoCodeView  -lLLVMBitReader  -lLLVMFuzzerCLI  -lLLVMCore  -lLLVMRemarks  -lLLVMBitstreamReader  -lLLVMBinaryFormat  -lLLVMTargetParser  -lLLVMTableGen  -lLLVMSupport  -lLLVMDemangle  -lrt  -ldl  -lm  -lz && :
/nix/store/zkjq96ik8cbv6ijh1lylnkk2bni9qvas-binutils-2.40/bin/ld: CMakeFiles/zig2.dir/zig2.c.o: in function `zig_truncxfsf':
zig2.c:(.text+0x32ef): undefined reference to `__truncxfsf2'
/nix/store/zkjq96ik8cbv6ijh1lylnkk2bni9qvas-binutils-2.40/bin/ld: CMakeFiles/zig2.dir/zig2.c.o: in function `zig_truncxfdf':
zig2.c:(.text+0x33d4): undefined reference to `__truncxfdf2'
/nix/store/zkjq96ik8cbv6ijh1lylnkk2bni9qvas-binutils-2.40/bin/ld: CMakeFiles/zig2.dir/zig2.c.o: in function `zig_extendsfxf':
zig2.c:(.text+0x34c2): undefined reference to `__extendsfxf2'
/nix/store/zkjq96ik8cbv6ijh1lylnkk2bni9qvas-binutils-2.40/bin/ld: CMakeFiles/zig2.dir/zig2.c.o: in function `zig_extenddfxf':
zig2.c:(.text+0x34fd): undefined reference to `__extenddfxf2'
/nix/store/zkjq96ik8cbv6ijh1lylnkk2bni9qvas-binutils-2.40/bin/ld: CMakeFiles/zig2.dir/zig2.c.o: in function `zig_floatdihf':
zig2.c:(.text+0x380c): undefined reference to `__floatdihf'
/nix/store/zkjq96ik8cbv6ijh1lylnkk2bni9qvas-binutils-2.40/bin/ld: CMakeFiles/zig2.dir/zig2.c.o: in function `zig_div_trunc_f16':
zig2.c:(.text+0x3bab): undefined reference to `__trunch'
/nix/store/zkjq96ik8cbv6ijh1lylnkk2bni9qvas-binutils-2.40/bin/ld: CMakeFiles/zig2.dir/zig2.c.o: in function `zig_div_floor_f16':
zig2.c:(.text+0x3bf0): undefined reference to `__floorh'
/nix/store/zkjq96ik8cbv6ijh1lylnkk2bni9qvas-binutils-2.40/bin/ld: CMakeFiles/zig2.dir/zig2.c.o: in function `zig_floatdisf':
zig2.c:(.text+0x3c7d): undefined re [...]

2024-01-02 06:36 UTC, kcbanner commented
Will take a look at this soon