zig cc: add linker -Map flag
ziglang/zig pull request #18358
Opened 2023-12-23 19:24 UTC by jiridanek

2023-12-23 19:25 UTC, jiridanek commented on src/main.zig
> +                    linker_map_file = arg["-Map=".len..];
This handles `-Map=file` which is enough for me. Should `-Map file` be handled as well?

2023-12-23 19:26 UTC, jiridanek commented on src/Compilation.zig
> +                options.linker_map_file != null)
I'm not sure what I'm actually doing here and whether I should do this.

2023-12-25 18:03 UTC, kubkon requested changes
What is the purpose of this flag in an ELF linker? Additionally, before we consider this for merging, we need a test in `test/link/elf.zig` with `llvm=true` and `lld=true`. Once we move away from lld as the default linker, this will help in narrowing down the missing functionality.

2024-01-04 17:34 UTC, jiridanek commented
@kubkon I could not figure out how to check the `.map` file content from inside of the test. More importantly, i haven't figured out how to run the test I just wrote (or this test _and_ the least amount of other tests) on my machine

```
% stage4/bin/zig test ../test/tests.zig --test-filter  testMapFlag
All 0 tests passed.
stage4/bin/zig test ../test/tests.zig --test-filter testMapFlag  4.76s user 1.58s system 100% cpu 6.333 total
```

Can you or anyone else please suggest how to do both correctly?

2024-01-04 19:02 UTC, andrewrk commented
`zig build test-link`

You can pass `--help` to see more options (the help menu is augmented by the contents of build.zig scripts so it's different in different projects).

2024-01-04 19:08 UTC, andrewrk commented
Please see https://github.com/ziglang/zig/issues/18356#issuecomment-1877618990. @kubkon will be the final word on this, but I think it would be better to not even decide whether to add this functionality until some other things are done. Until then, if you need this feature you will need to use a different toolchain than zig cc. @kubkon please close this pull request if you agree.

2024-01-05 00:16 UTC, kubkon commented
I have to agree with @andrewrk here - this is a new feature request that while may look innocent and easy to implement with LLD in mind, it needs some careful consideration if ported to Zig's linker. Until we decide if we want to accept your proposal, I am closing this PR as not applicable.

2024-01-05 00:16 UTC, closed without merging