lib/std/tar: add missing license file
ziglang/zig pull request #18551
Opened 2024-01-14 09:04 UTC by perillo

f8e42d6 copied tar test data from the Go Language repository, without adding a license file.

Copy the Go LICENSE file to lib/std/tar/testdata.

I'm not sure if this is the right way to add a license file; I followed what was done in the `lib` directory for foreign source code.

2024-01-14 10:42 UTC, perillo commented
How about skipping running checks when no known source files (like `.zig` and `.c`) are detected?

2024-01-14 17:36 UTC, luehmann commented
> How about skipping running checks when no known source files (like `.zig` and `.c`) are detected?

Alternatively you could skip workflows using https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs

2024-01-16 07:06 UTC, andrewrk requested changes
There's going to be a bit of a yak shave on this one. We don't actually ship those files with a zig installation, and so I don't want to ship the go license either, although it does need to live inside the directory with those testdata files.

The build system needs a slightly better way to exclude files from installation other than excluding by extension which we have so far been abusing for all exclusions.

2024-01-16 19:09 UTC, andrewrk commented
An `exclude_directories` option sounds like a good idea to me.

2024-01-16 19:35 UTC, perillo commented
@andrewrk I wrote a patch that adds a new `exclude` option.  It matches directories if the pattern ends with `/` and files otherwise (like in `.gitignore`).
```diff
commit 782cfe42476aaef0b7c19cc16e664ba8bc18e11d
Author: Manlio Perillo <manlio.perillo@gmail.com>
Date:   Tue Jan 16 19:54:12 2024 +0100

    DRAFT

diff --git a/build.zig b/build.zig
index 1d44c249c..5f272325b 100644
--- a/build.zig
+++ b/build.zig
@@ -140,37 +140,12 @@ pub fn build(b: *std.Build) !void {
             .source_dir = .{ .path = "lib" },
             .install_dir = if (flat) .prefix else .lib,
             .install_subdir = if (flat) "lib" else "zig",
-            .exclude_extensions = &[_][]const u8{
-                // exclude files from lib/std/compress/testdata
-                ".gz",
-                ".z.0",
-                ".z.9",
-                ".zstd.3",
-                ".zstd.19",
-                "rfc1951.txt",
-                "rfc1952.txt",
-                "rfc8478.txt",
-                // exclude files from lib/std/compress/deflate/testdata
-                ".expect",
-                ".expect-noinput",
-                ".golden",
-                ".input",
-                "compress-e.txt",
-                "compress-gettysburg.txt",
-                "compress-pi.txt",
-                "rfc1951.txt",
-                // exclude files from lib/std/compress/lzma/testdata
-                ".lzma",
-                // exclude files from lib/std/compress/xz/testdata
-                ".xz",
-                // exclude files from lib/std/tz/
-                ".tzif",
-                // exclude files from lib/std/tar/testdata
-                ".tar",
-                // others
+            .exclude = &.{
+                "testdata/",
+                "tz/",
                 "README.md",
             },
-            .blank_extensions = &[_][]const u8{
+            .blank_extensions = &.{
                 "test.zig",
             },
         });
diff --git a/lib/std/Build/Step/InstallDir.zig b/lib/std/Build/Step/InstallDir.zig
index 7472dba2a..131a6e5c5 100644
--- a/lib/std/Build/Step/InstallDir.zig
+++ b/lib/std/Build/Step/InstallDir.zig
@@ -31,6 +31,8 @@ pub const Options = struct {
     /// However if the files were not present at all, then
     /// `@import("test.zig")` would be a compile error.
     blank_extensions: []const []const u8 = &.{},
+    /// TODO
+    exclude: []const []const u8 = &.{},
 
     fn dupe(self: Options, b: *std.Build) Options {
         return .{
@@ -40,6 +42,7 @@ pub const Options = struct {
             .exclude_extensions = b.dupeStrings(self.exclude_extensions),
             .include_extensions = if (self.include_extensions) |incs| b.dupeStrings(incs) else null,
             .blank_extensions = b.dupeStrings(self.blank_extensions),
+            .exclude = b.dupeStrings(self.exclude),
         };
     }
 };
@@ -78,6 +81,9 @@ fn make(step: *Step, prog_node: *std.Progress.Node) !void {
     var it = try src_dir.walk(arena);
     var all_cached = true;
     next_entry: while (try it.next()) |entry| {
+        for (self.options.exclude) |pattern| {
+            if (match(pattern, entry.name, entry.kind)) continue :next_entry;
+        }
         for (self.options.exclude_extensions) |ext| {
             if (mem.endsWith(u8, entry.path, ext)) {
                 continue :next_entry;
@@ -128,3 +134,23 @@ fn make(step: *Step, prog_node: *std.Progress.Node) !void {
 
     step.result_cached = all_cached;
 }
+
+fn match(pattern: []const u8, name: []const u8, kind: fs.File.Kind) bool {
+    const len = pattern.len;
+    const isdir = if (len > 0 and name[len - 1] == '/') true else false;
+    switch (kind) {
+        .directory => {
+            if (!isdir) return false;
+            const path = pattern[0 .. len - 1];
+            if (mem.eql(path, name)) return true;
+        },
+
+        .file => {
+            if (isdir) return false;
+            if (mem.eql(pattern, name)) return true;
+        },
+        else => unreachable,
+    }
+
+    return false;
+}
```

Unfortunately I can not test it, since on my PC I'm having problems building Zig.

In order to make things simpler, IMHO a `testdata` directory should be created in `lib/std` and the `tz` directory should be moved there.

2024-01-16 19:36 UTC, andrewrk commented
You don't need to compile from source to test changes to the zig build system. You can patch the build system directly and the changes reflect immediately thanks to the caching system.

2024-01-17 09:26 UTC, perillo commented
@andrewrk  I have a working draft, with print debugs.  I have not create a new PR since there are some implementation choices:

  1. The old implementation creates an empty directory when all files inside the directory are matched.  The new implementation does not create empty directories.
  2. Since I added a new `match` function, what about adding more features (*simple to implement*)?
     - A `*` at the start of the pattern matches `basename` using `mem.endsWith`.
     - A `*` at the end of the pattern matches `basename` using `mem.startsWith`.
     - A `**` at the start of the pattern matches `path` using `mem.endsWith`.
     - A `**` at the end of the pattern matches `path` using `mem.startsWith`.
     - Range notation (`[a-zA-Z]`) and `*` or `**` in the middle of the pattern are not supported.
  3. What about `exclude_extensions`?  This feature can be implemented in `exclude`.
  4. What about `include_extensions` and `blank_extensions`?  These fields can be replaced with `include` and `blank` using the new syntax.
  5. Should I add tests?  AFAIK, there are currently no tests.
 
Here is the patch.  I tested the correctness comparing (using `diff -ru`) the `lib` directory of the old and new installation.
I built the compiler using `zig build --zig-lib-dir lib --prefix build/stage4 -Dno-langref -Dno-autodocs` 

```diff
commit 4a9abeb2bdafa688fd475c4992a511b9ea134168
Author: Manlio Perillo <manlio.perillo@gmail.com>
Date:   Tue Jan 16 19:54:12 2024 +0100

    DRAFT

diff --git a/build.zig b/build.zig
index 1d44c249c..5f272325b 100644
--- a/build.zig
+++ b/build.zig
@@ -140,37 +140,12 @@ pub fn build(b: *std.Build) !void {
             .source_dir = .{ .path = "lib" },
             .install_dir = if (flat) .prefix else .lib,
             .install_subdir = if (flat) "lib" else "zig",
-            .exclude_extensions = &[_][]const u8{
-                // exclude files from lib/std/compress/testdata
-                ".gz",
-                ".z.0",
-                ".z.9",
-                ".zstd.3",
-                ".zstd.19",
-                "rfc1951.txt",
-                "rfc1952.txt",
-                "rfc8478.txt",
-                // exclude files from lib/std/compress/deflate/testdata
-                ".expect",
-                ".expect-noinput",
-                ".golden",
-                ".input",
-                "compress-e.txt",
-                "compress-gettysburg.txt",
-                "compress-pi.txt",
-                "rfc1951.txt",
-                // exclude files from lib/std/compress/lzma/testdata
-                ".lzma",
-                // exclude files from lib/std/compress/xz/testdata
-                ".xz",
-                // exclude files from lib/std/tz/
-                ".tzif",
-                // exclude files from lib/std/tar/testdata
-                ".tar",
-                // others
+            .exclude = &.{
+                "testdata/",
+                "tz/",
                 "README.md",
             },
-            .blank_extensions = &[_][]const u8{
+            .blank_extensions = &.{
                 "test.zig",
             },
         });
diff --git a/lib/std/Build/Step/InstallDir.zig b/lib/std/Build/Step/InstallDir.zig
index 7472dba2a..6483e5848 100644
--- a/lib/std/Build/Step/InstallDir.zig
+++ b/lib/std/Build/Step/InstallDir.zig
@@ -18,6 +18,14 @@ pub const Options = struct {
     source_dir: LazyPath,
     install_dir: InstallDir,
     install_subdir: []const u8,
+    /// Paths to be excluded from being installed, using a simple pattern
+    /// matching.
+    ///
+    /// If there is a slash "/" at the end of the pattern then the pattern will
+    /// only match directories, otherwise the pattern can only match files.
+    ///
+    /// Patterns are matched against basename.
+    exclude: []const []const u8 = &.{},
     /// File paths which end in any of these suffixes will be excluded
     /// from being installed.
     exclude_extensions: []const []const u8 = &.{},
@@ -40,6 +48,7 @@ pub const Options = struct {
             .exclude_extensions = b.dupeStrings(self.exclude_extensions),
             .include_extensions = if (self.include_extensions) |incs| b.dupeStrings(incs) else null,
             .blank_extensions = b.dupeStrings(self.blank_extensions),
+            .exclude = b.dupeStrings(self.exclude),
         };
     }
 };
@@ -77,7 +86,25 @@ fn make(step: *Step, prog_node: *std.Progress.Node) !void {
     defer src_dir.close();
     var it = try src_dir.walk(arena);
     var all_cached = true;
+    var skip_directory: ?[]const u8 = null;
     next_entry: while (try it.next()) |entry| {
+        if (skip_directory) |dirpath| {
+            if (mem.eql(u8, fs.path.dirname(entry.path).?, dirpath)) {
+                std.debug.print("skip file: {s}\n", .{entry.path});
+                continue;
+            } else {
+                std.debug.print("exit directory: {s}\n", .{entry.path});
+                skip_directory = null;
+            }
+        }
+        for (self.options.exclude) |pattern| {
+            if (match(pattern, entry.basename, entry.kind)) {
+                std.debug.print("match {s} {s} {}\n", .{ pattern, entry.path, entry.kind });
+                if (entry.kind == .directory) skip_directory = entry.path;
+                if (skip_directory) |dirpath| std.debug.print("enter directory: {s}\n", .{dirpath});
+                continue :next_entry;
+            }
+        }
         for (self.options.exclude_extensions) |ext| {
             if (mem.endsWith(u8, entry.path, ext)) {
                 continue :next_entry;
@@ -128,3 +155,25 @@ fn make(step: *Step, prog_node: *std.Progress.Node) !void {
 
     step.result_cached = all_cached;
 }
+
+fn match(pattern: []const u8, name: []const u8, kind: fs.File.Kind) bool {
+    const len = pattern.len;
+    const isdir = if (len > 0 and pattern[len - 1] == '/') true else false;
+    switch (kind) {
+        .directory => {
+            if (!isdir) return false;
+            if (mem.eql(u8, pattern[0 .. len - 1], name)) {
+                return true;
+            }
+        },
+        .file => {
+            if (isdir) return false;
+            if (mem.eql(u8, pattern, name)) {
+                return true;
+            }
+        },
+        else => unreachable,
+    }
+
+    return false;
+}
```

2024-05-09 23:36 UTC, closed without merging