std.os: add support for socketpair
ziglang/zig pull request #18561
Opened 2024-01-14 22:24 UTC by notcancername

fixes #18417 cc @nektro

with the `AF_UNIX` implementation, the file the socket is bound to is not cleaned up, it might be worth exposing this eventually or abstracting socketpair properly in std.net (related: #6600), comments are appreciated

2024-01-15 00:38 UTC, nektro reviewed
some thoughts in no particular order

- nice!
- if windows doesn't have this behavior I don't think std.os should pretend it does imo.
- additionally it should accept `i32` or `c_int` and not bitCast
- `E.OPNOTSUPP, E.PROTONOSUPPORT` shouldn't be in the same case
- neither should `E.NOBUFS, E.NOMEM`
- there shouldn't be util functions, it should all be in the if statement of `socketpair`
- common style for std.os is `if (windows) { _win_ } _posix_`, this is in the wrong order and shouldn't use an `else`

2024-01-15 01:02 UTC, notcancername commented
> - if windows doesn't have this behavior I don't think std.os should pretend it does imo.

Seems like `std.net` is the preferred layer for this?

> - `E.OPNOTSUPP, E.PROTONOSUPPORT` shouldn't be in the same case
> - neither should `E.NOBUFS, E.NOMEM`

Which errors would be more appropriate?

> there shouldn't be util functions, it should all be in the if statement of socketpair

They're separate functions because `AF_UNIX` may not be available at runtime:
```zig
        error.AddressFamilyNotSupported => return socketpairEmulatedAfInet(),
```

> additionally it should accept i32 or c_int and not bitCast

`std.c.socketpair`  uses `c_uint`, but `std.os.linux.socketpair` uses `i32`. Some amount of casting is unavoidable with the way it is right now. I've changed `std.os.linux.socketpair` to fit `std.os.socket` precedent.

2024-01-15 01:27 UTC, nektro commented
`std.c.socketpair` was wrong. they all should be using `c_int`/`i32`.

https://pubs.opengroup.org/onlinepubs/009696699/functions/socketpair.html
https://www.man7.org/linux/man-pages/man2/socketpair.2.html
https://man.freebsd.org/cgi/man.cgi?query=socketpair(2)

2024-01-15 01:29 UTC, nektro commented
```zig
        .OPNOTSUPP => return error.OperationNotSupported,
        .PROTONOSUPPORT => return error.ProtocolNotSupported,
        .NOBUFS => return error.SystemResources,
        .NOMEM => return error.SystemResources,
```

2024-01-15 01:43 UTC, notcancername commented
done. why are we using separate switch prongs for the same error?

2024-01-15 01:56 UTC, nektro commented
no particular reason afaik. just the style that core team/prs has kept up so far in this case to keep things vertical

2024-01-15 02:01 UTC, notcancername commented
these test failures are looking pretty mysterious:

```
 src/Sema.zig:32601:92: error: no field or member function named 'toValue' in 'InternPool.Index'
src/InternPool.zig:2010:19: note: enum declared here
child process failed
Aborted
Error: Process completed with exit code 134.
```

I don't see how my changes could possibly have caused this

2024-01-15 02:10 UTC, nektro commented
looks like master branch is failing too

2024-01-17 00:32 UTC, andrewrk requested changes

2024-01-17 00:32 UTC, andrewrk commented on lib/std/os/windows/kernel32.zig
> +pub extern "kernel32" fn GetTempPathA(nBufferLength: DWORD, lpBuffer: LPSTR) callconv(WINAPI) DWORD;
no

2024-03-14 10:54 UTC, closed without merging