mingw: add missing CRT sources
ziglang/zig pull request #18596
Opened 2024-01-17 02:27 UTC by ypsvlq

fixes https://github.com/ziglang/zig/issues/9364

2024-01-19 04:41 UTC, andrewrk requested changes
C files in the include directory?

2024-01-19 06:54 UTC, ypsvlq commented
@andrewrk this is the correct location, it can be verified against an existing mingw install and is briefly mentioned in MS docs [here](https://learn.microsoft.com/en-us/windows/win32/api/tsuserex/nn-tsuserex-iadstsuserex) (although that was the only file that seemed to be documented or even mentioned online, so leaving them out probably wouldn't cause any problems)

2024-01-19 22:32 UTC, andrewrk commented on src/mingw.zig
> +    adsiid,
What's the purpose of adding all these additional CRTFile entries? Can't we just toss the source files into mingwex.lib?

2024-01-20 19:27 UTC, andrewrk approved these changes
Nice! Thanks for working with me on this. I'm happy with this. I hope you are too.

2024-01-20 19:34 UTC, ypsvlq commented
Definitely, there's still some things I might look at in future but this gets it to a much better place both for usability and deciding what to add/remove.

2024-01-20 20:01 UTC, andrewrk commented
I verified that running `zig build update-mingw` created an empty diff (copied files in this branch match upstream mingw-w64 exactly).

2024-01-20 20:01 UTC, merged