std.fmt: fix unecessary deref on user-defined format function
ziglang/zig pull request #18636
Opened 2024-01-21 12:05 UTC by iceghost

When formatting a pointer to user type, currently it needs to be dereferenced first, then call `formatType` on the child type.

This fixes the problem by checking for "format" function on not only the type itself, but also the struct it points to.

Fixes #15335.
Supersedes #16367.

2024-01-21 12:06 UTC, iceghost commented
cc @Vexu

2024-01-21 12:13 UTC, N00byEdge commented
Wouldn't this stop printing the address in pointers to structs with a format fn?

2024-01-21 12:22 UTC, iceghost commented
> Wouldn't this stop printing the address in pointers to structs with a format fn?

I think the original behavior is already not printing the address. 

https://github.com/ziglang/zig/blob/3562b74e296a0e88642c51f0a4856282200a7366/lib/std/fmt.zig#L611-L614

`formatType(value.*, ...` will invoke the `format` fn, which should be the same behavior in this PR.

2024-01-21 20:56 UTC, andrewrk requested changes
Hi @iceghost, thank you for sending this patch.

I think that one of two things should happen instead:
1. `std.meta.hasFn` is modified to have this behavior, leaving fmt.zig unchanged, or
2. `std.meta.hasMethod` should be introduced which has this behavior.

I think if you crack open the implementation of that function you will see that it makes sense to put the logic there.

2024-01-22 12:34 UTC, iceghost commented
> Hi @iceghost, thank you for sending this patch.
> 
> I think that one of two things should happen instead:
> 
>     1. `std.meta.hasFn` is modified to have this behavior, leaving fmt.zig unchanged, or
> 
>     2. `std.meta.hasMethod` should be introduced which has this behavior.
> 
> 
> I think if you crack open the implementation of that function you will see that it makes sense to put the logic there.
> 
> (1) is a more disruptive change that might not even be a good idea, while (2) is likely to be a quick merge.

Makes sense to me, I fixed it. The docs for `hasMethod` wording may not be precise though, so let me know if I need to change it.

2024-01-23 02:56 UTC, andrewrk commented
Good enough, thank you!

2024-01-23 09:03 UTC, merged