Compilation: detect and regenerate missing cache artifacts
ziglang/zig pull request #18792
Opened 2024-02-03 05:21 UTC by jacobly0

While it is not clear why artifacts are occasionally missing for which the manifest remains intact, regardless of how it happens, the cache should be at least somewhat resilient to kills, crashes, power loss, etc. affecting compilation processes anyway.

Workaround #18763

2024-02-03 09:43 UTC, andrewrk requested changes
> the cache should be at least somewhat resilient to kills, crashes, power loss, etc.

It is resilient to these things already by writing the manifest file only after all the artifacts are created. This workaround is not desirable because it masks symptoms of a non understood phenomenon. 

I don't want this workaround in the codebase. We need to figure out the true cause and address it.

2024-02-03 15:57 UTC, jacobly0 commented
> It is resilient to these things already by writing the manifest file only after all the artifacts are created.

This makes no sense to me.  The OS is under no obligation to physically perform writes to disk in the same order as they occur in the program.  Its only obligation is to atomically update the filesystem cache in a way consistent with some total ordering of all fs operations, but after a power loss, a journal fs is only consistent with some arbitrary, possibly truncated, alternative ordering of events, where the end result would have been the same only if they were not truncated.

2024-02-04 02:23 UTC, andrewrk commented
I really don't think that's the right tradeoff here. An additional hashing step on every compilation at the end is already a lot, but to additionally check the hash on a cache hit? That's too much to ask.

It's unfortunate that file systems do not expose the primitives that databases need in order to synchronize writes relative to each other. I don't even think fsync is the right approach here. Ultimately, these conditions are too rare and too costly to work around. We lose more than we gain, given the file system primitives available to us.

Does power loss, kills, and crashes even have anything to do with #18763? It looks to me like the latest hypothesis is a cron job to delete the tmp directory racing against the zig cache.

2024-02-04 02:50 UTC, jacobly0 commented
Fixes extracted to #18801

2024-02-04 02:50 UTC, closed without merging

2024-02-04 03:00 UTC, andrewrk commented
> loss, kills, and crashes

I wanted to add: I think it's worth noting that *crashes* are distinct from the other two because they are not subject to the out-of-order possibilities. The atomic weaknesses of the OS you mentioned above don't apply to crashes.