std: do not use inferred errors in dynamic_library
ziglang/zig pull request #18947
Opened 2024-02-15 12:54 UTC by Cloudef

The error unions for WindowsDynLib and ElfDynLib do not contain all the possible errors. So user code that relies on DynLib.Error will fail to compile.

2024-02-15 14:51 UTC, Cloudef commented
I'll send another PR for system library loading for ElfDynLib once this is in

2024-02-16 03:53 UTC, Cloudef commented
Another thing I'm wondering is that should these error unions be standardized so that every platform uses the same error union? I can see this done either by mapping lower level errors to higher level ones, or having giant error union with all the possible errors from all variations.

2024-03-15 14:55 UTC, Vexu requested changes
`DynLib.Error` should contain all the possible errors on all platforms to ensure that it remains cross-platform.

`std.DynLib` should probably be reworked to better match other abstractions in the std lib.

2024-03-15 14:58 UTC, Cloudef commented
>  should probably be reworked to better match other abstractions in the std lib.

what does this mean in practice?

2024-03-15 21:10 UTC, Vexu commented
It means that the `DynLib` should be closer to how [`std.fs.File.Metadata`](https://ziglang.org/documentation/master/std/#std.fs.File.Metadata) is with the platform specific implementations stored in a cross-platform struct. The actual logic probably doesn't need to be touched.

2024-03-18 03:21 UTC, andrewrk commented
cbeab678a50e48ba55f39b391fcfe98823fe3c8c

2024-03-18 03:21 UTC, closed without merging