fix `standalone/empty_env` test
ziglang/zig pull request #18969
Opened 2024-02-17 07:42 UTC by Parzival-3141

Closes #13685
Closes #3168

The problem seems to be ConEmu setting environment variables before executing the test process (the test passes when run in Windows CMD). These variables can differ depending on user configuration too. This PR skips the test if the host environment has the [`ConEmuHWND`](https://conemu.github.io/en/ConEmuEnvironment.html) variable set; i.e. we're running inside a ConEmu terminal session.

2024-02-22 20:50 UTC, nektro commented
yeah doesn't seem like it'd be your fault at first glance but its UB in the compiler causing a crash https://zigbin.io/544ee8

2024-02-28 05:40 UTC, Parzival-3141 commented
@nektro Just to clarify, are you saying this is a separate bug or caused by the test?

2024-02-28 06:12 UTC, nektro commented
I'm not totally sure, was more just documenting the finding to ease anyone else looking into it as well

2024-08-24 05:51 UTC, andrewrk requested changes

2024-08-24 05:51 UTC, andrewrk commented on test/standalone/empty_env/build.zig
> +        std.process.hasEnvVarConstant("ConEmuHWND")))
Please untangle these conditions so that one can be deleted cleanly when it is resolved.

2024-10-08 16:50 UTC, alexrp approved these changes

2024-10-08 21:34 UTC, merged

2024-10-09 01:06 UTC, andrewrk commented
@alexrp please, no rebase commits if it is greater than 1 commit. This should have been a squash. The reasoning behind this is to ensure the ability to use `git bisect`. When there is greater than one commit in a rebase merge, it means there are direct children in master branch which have not passed the CI.

2024-10-09 06:23 UTC, alexrp commented
@andrewrk sorry, I *did* intend for this to be a squash (per your earlier comment), which is why I disabled and re-enabled auto-merge. But apparently I accidentally selected the wrong option? 🤦 I'll keep a closer eye on that from now on.

2024-10-09 06:36 UTC, andrewrk commented
Thanks, appreciated!