std: re-enable most of setrlimit test on macos
ziglang/zig pull request #19051
Opened 2024-02-23 17:10 UTC by mikdusan

- skip only RLIMIT_STACK test on macos

closes #18395

2024-02-24 05:12 UTC, andrewrk requested changes

2024-02-24 05:12 UTC, andrewrk commented on lib/std/os/test.zig
> +        if (comptime builtin.os.tag.isDarwin() and resource == .STACK) {
```suggestion
        if (builtin.os.tag.isDarwin() and resource == .STACK) {
```

2024-02-24 16:07 UTC, mikdusan commented on lib/std/os/test.zig
> +        if (comptime builtin.os.tag.isDarwin() and resource == .STACK) {
done.

2024-02-25 05:31 UTC, merged

2024-02-25 05:31 UTC, andrewrk commented
Thanks