LLVM: Remove deprecated or soon to be deprecated constant expressions
ziglang/zig pull request #19134
Opened 2024-02-29 20:19 UTC by antlilja

This PR removes most constant expression from Builder in preparation for LLVM 18. These constant expression will either be removed in LLVM 18 or are planned to be removed at a later date (some discussion on the subject can be found on the [LLVM discourse](https://discourse.llvm.org/t/rfc-remove-most-constant-expressions/63179/28)). 

Most of the removed expression were unused anyway, the only major change to the backend is to how packed struct and union values are lowered. They are now lowered manually into a single integer instead of a constant expression. Constant expressions have also been converted to instructions in other places (which is what the LLVM auto upgrade system would have done anyway).

These are the remaining constant expressions in Builder:
```
trunc
ptrtoint
inttoptr
bitcast
addrspacecast
add
sub
```

2024-02-29 21:22 UTC, jacobly0 requested changes

2024-02-29 21:22 UTC, jacobly0 commented on src/codegen/llvm.zig
> +                        ) catch unreachable;
This breaks for a big endian target as per the doc comment of `writeToPackedMemory`.

2024-02-29 21:22 UTC, jacobly0 commented on src/codegen/llvm.zig
> +                        });
This breaks when either the host or target is big endian, since `limbs` is a slice of native endian limbs in little endian order.

2024-03-04 00:23 UTC, antlilja commented
There has been a slight change of plan from the original comment. Two constant expressions which will not be removed in LLVM 18 have been restored (xor and shl), as lowering packed structs which contain decl refs without these will require a slightly larger amount of work. This is a problem we'll have to deal with eventually but I thought it would be best to get zig working with LLVM 18 first and then think about solving this more difficult problem.

2024-04-25 20:00 UTC, andrewrk commented
Rebased and force-pushed on your behalf

2024-04-25 20:08 UTC, andrewrk commented
Oh, hi @antlilja, I see you're active. I started working on the LLVM 18 upgrade today.

2024-04-25 20:18 UTC, antlilja commented
> Oh, hi @antlilja, I see you're active. I started working on the LLVM 18 upgrade today.

Nice! I'm fixing this branch to compile on master right now.

2024-04-25 20:19 UTC, andrewrk commented
Ah ok great, in that case I'll start with the other items from the [upgrade process](https://github.com/ziglang/zig/wiki/LLVM-Upgrade-Process).

2024-04-26 05:58 UTC, merged

2024-04-26 06:10 UTC, andrewrk commented
Thanks! I pushed the `llvm18` branch just now.

Still todo:
* [ ] Update `lib/libcxx/`, `lib/libcxxabi`, and `lib/libunwind`
* [ ] Update `tsan`
* [ ] Run `tools/update_clang_options.zig`
* [ ] Update zig-bootstrap and CI tarballs 

Before your changes here:

```
[100%] Building stage3
LLVM Emit Object... error: Value referenced by initializer is an unsupported constant expression of type zext (Producer: 'zig 0.13.0' Reader: 'LLVM 18.1.5')
```

After your changes here:

```
[100%] Building stage3
LLVM Emit Object... 512-bit vector arguments require 'evex512' for AVX512
ptr @math.rotl__anon_22869
512-bit vector arguments require 'evex512' for AVX512
ptr @math.rotl__anon_22870
512-bit vector arguments require 'evex512' for AVX512
ptr @math.rotl__anon_22871
512-bit vector arguments require 'evex512' for AVX512
ptr @math.rotl__anon_22872
LLVM ERROR: Broken module found, compilation aborted!
```

Looks like they decided not to lower vector arguments unless the target CPU features are convenient.