std.Build.Step.ConfigHeader: make header_text optional, no default
ziglang/zig pull request #19277
Opened 2024-03-12 19:31 UTC by g012

The default header_text added as a comment at the top of the generated file assumes C or ASM syntax, whereas we could be generating any type of file. This change makes no header_text the default, and allows users to specify one if they desire, including their own comment syntax as necessary.

https://github.com/ziglang/zig/issues/19272

2024-03-26 11:59 UTC, Vexu approved these changes

2024-05-01 00:54 UTC, andrewrk requested changes
Thanks.

Making it configurable is of course a good idea, however, I disagree with the default, because it's widely accepted as best practice for a generated file to advertise at the top of the file that it is a generated file.

When the comment syntax is unknown, the user should be encouraged to populate this field, and explicitly opt into making the prefix empty if desired.

I suggest these modifications:
* Keep `header_text: ?[]const u8 = null,` as you have it.
* For the flavors where the comment syntax is known, make it continue to default to including the "generated by..." line.
* For the "blank" flavor, make it fail the configure phase (i.e. panic) with a message that tells the user to either specify the header text, or to explicitly set it to the empty string.

Users can then use `.header_text = ""` when they want no header, or `.header_text = "foo\n"` when they want a header. The user should control the newline.

This gives ultimate flexibility to the user, while retaining good defaults that will lead people to not forget to include this line.

2024-05-05 16:24 UTC, g012 commented
> * For the flavors where the comment syntax is known, make it continue to default to including the "generated by..." line.
> * For the "blank" flavor, make it fail the configure phase (i.e. panic) with a message that tells the user to either specify the header text, or to explicitly set it to the empty string.

Actually one can't rely on the Style types / flavors here, as this field mixes two different informations:
 * which syntax to use as variable replacement, if any (autoconf, cmake, or no replacement / blank input)
 * what type of file to output (C for autoconf and cmake, ASM for nasm, anything for blank)

As for me, I am using ConfigHeader with cmake syntax to output a Lua file from a Lua input file containing CMake-style variables. I wouldn't be able to specify this with your solution.

In my opinion we should split the style option into two: syntax, defaulting to none (no replacement), and header_text, compulsory. We could add a third such as output_format, and make header_text optional, and panic if there's neither header_text nor output_format, but it seems a tad convoluted to me.

2024-05-05 21:17 UTC, g012 commented
I think I've added what you suggested. It's working for me with Lua input and specifying a Lua comment in header_text.

2024-08-12 18:13 UTC, andrewrk requested changes
would you mind rebasing and fixing the conflict?

2025-07-17 03:14 UTC, closed without merging