fix(autodoc): include entire code on line in source
ziglang/zig pull request #19301
Opened 2024-03-14 05:48 UTC by sno2

I took the easy route and just add the entire line's contents. This fixes the noted issue:

![image](https://github.com/ziglang/zig/assets/43641633/5b90b386-94ee-47e1-aa14-4abe3b6922b9)

> However, care should be taken to make sure it does not introduce bugs if there is non-whitespace on that same line.

I am unsure if I introduced what you were warning against. Do you want

```zig
const a = 1; fn add(a: u32, b: u32) u32 {
    return a + b;
}
```

to render as itself, or

```zig
fn add(a: u32, b: u32) u32 {
    return a + b;
}
```

or

```zig
             fn add(a: u32, b: u32) u32 {
    return a + b;
}
```

This implementation assume you want the first option.

2024-03-14 05:50 UTC, sno2 commented on lib/docs/wasm/main.zig
> +    file_source_html(decl.file, &string_result, doctest_ast_node, .{
This adds the same behavior to rendering doctests.

2024-03-14 05:56 UTC, nektro commented
imo it should print option 2. just the decl and whitespace trimmed while preserving indentation.

2024-03-15 19:38 UTC, sno2 commented
> imo it should print option 2. just the decl and whitespace trimmed while preserving indentation.

Hmm, I think we disagree on what would be the actual "Source Code." Although, the current setup doesn't show any of the tokens on the last line after the terminator, so it would match that setup if we did option 2.

2024-03-16 02:47 UTC, andrewrk requested changes
Thanks for the patch, @sno2. This discussion has convinced me that simply including the entire line is not good enough, and the original required behavior I specified in #19293 is the required behavior.

#### Case 1

Input:
```zig
    fn add(a: u32, b: u32) u32 {
        return a + b;
    }
```
Expected Output:
```zig
fn add(a: u32, b: u32) u32 {
    return a + b;
}
```

#### Case 2

Input: 
```zig
    const a = 1; fn add(a: u32, b: u32) u32 {
        return a + b;
    }
```
Expected Output:
```zig
fn add(a: u32, b: u32) u32 {
    return a + b;
}
```

#### Case 3

Input: 
```zig
    fn add(a: u32, b: u32) u32 {
return a + b;
    }
```
Expected Output:

```zig
fn add(a: u32, b: u32) u32 {
return a + b;
}
```

#### Case 4


Input: 
```zig
    const a = 1; fn add(a: u32, b: u32) u32 {
return a + b;
    }
```
Expected Output:
```zig
fn add(a: u32, b: u32) u32 {
return a + b;
}
```

2024-03-16 03:11 UTC, nektro commented
imo the existence of zig fmt's api in the stdlib should mean that with:

```zig
    const a = 1; fn add(a: u32, b: u32) u32 {
return a + b;
    }
```

when viewing the source of `add` is still rendered as:

```zig
fn add(a: u32, b: u32) u32 {
    return a + b;
}
```

2024-03-20 23:36 UTC, sno2 commented
If anyone else would like to work on this- be my guest. I have exams to study for until halfway through next week so I will be busy until then. Will re-open next week.

2024-03-20 23:36 UTC, closed without merging