AstGen: avoid intermediate loads during field/array access
ziglang/zig pull request #19347
Opened 2024-03-18 14:32 UTC by Vexu

There should probably be a check that the access chain ends in a symbol since other cases could still use the `_val` versions?

Closes #15685
Closes #15280
Closes #12963

2024-03-18 14:39 UTC, mlugg commented
The AstGen change here causes "local variable is never mutated" errors to not be emitted when they should, because that error is based on when a local variable is never accessed with a ref result location. I'll let you decide how best to handle this - perhaps you could introduce a `.pseudo_ref` result location which acts like `.ref` but exists only as an optimization so doesn't mark a local variable as mutated.

2024-03-20 01:43 UTC, Rexicon226 commented
https://github.com/ziglang/zig/commit/b97ae638fa4b2f425fa560b330fe9e78b06741fe should be documented in langref?

2024-03-20 17:56 UTC, andrewrk requested changes
This change needs to come with benchmarks, an analysis of the differences in ZIR, and an overview explanation.

2024-03-22 06:14 UTC, Vexu commented
> [b97ae63](https://github.com/ziglang/zig/commit/b97ae638fa4b2f425fa560b330fe9e78b06741fe) should be documented in langref?

It should but note that it is just implementing #4765 in a slightly different situation (`&array_ptr.ptr`).

2024-03-23 19:13 UTC, Vexu commented
I can't think of a way to get this to work right now and the latent bugs its uncovering aren't making it any easier.

2024-03-23 19:13 UTC, closed without merging