mingw: support -municode
ziglang/zig pull request #19399
Opened 2024-03-22 21:00 UTC by ypsvlq

fixes #18621

also rename mingwex to mingw32, which feels more appropriate as it contains the basic C runtime code

2024-03-23 02:04 UTC, squeek502 commented
Nice work, thanks for getting this fixed!

This works when using `zig cc`:

```c
#include <windows.h>

int APIENTRY wWinMain(HINSTANCE hInst, HINSTANCE hInstPrev, PWSTR cmdline, int cmdshow) {
    return 0;
}
```

```
zig cc -o test-wwinmain-cc.exe test-wwinmain.c -lc -municode -Wl,--subsystem,windows
```

```
> dumpbin /headers test-wwinmain-cc.exe
...
            1180 entry point (0000000000401180) WinMainCRTStartup
...
               2 subsystem (Windows GUI)
...
```

But is there an intended way to provide `-municode` when using `zig build-exe`?

```
zig build-exe -cflags -municode -- test-wwinmain.c -lc --subsystem windows
```
doesn't seem to work

2024-03-23 08:05 UTC, ypsvlq commented
fixed

2024-03-23 15:38 UTC, squeek502 commented
Great! One last thing to make this maximally usable is integration with `build.zig`. I've added that + a standalone test and submitted it as a PR to your branch here: https://github.com/ypsvlq/zig/pull/1

2024-03-25 23:50 UTC, andrewrk requested changes
Thanks @ypsvlq. One small change needed and then this is ready to land.

I'm confused why #18621 is marked as a regression when the fix requires adding a new feature (the `-municode` flag). How did it used to work?

2024-03-25 23:50 UTC, andrewrk commented on src/clang_options_data.zig
> +},
This file is generated by tools/update_clang_options.zig. This patch will be reverted with the next run of the tool; the tool needs a corresponding change.

2024-03-26 05:24 UTC, squeek502 commented
> I'm confused why https://github.com/ziglang/zig/issues/18621 is marked as a regression when the fix requires adding a new feature (the -municode flag). How did it used to work?

There are two parts to that issue (and this PR):

- The regression is that if `WinMain` was defined, it wouldn't be detected and the linker would fail with `undefined symbol: main`. In particular, [this is a reproduction of *only* the regression](https://github.com/ziglang/zig/issues/18621#issuecomment-1989673384)
- The `-municode` part of this PR is to support `wmain`/`wWinMain` which I don't think has ever been fully supported before (at least I couldn't get `wWinMain` to work with 0.11.0)

@ypsvlq can better clarify which parts of this PR address one or the other.

One thing I'd be interested in is if it's at all feasible to make MinGW recognize `wWinMain`/`wmain` without needing an explicit CLI flag (e.g. this is the case when targeting MSVC--it will use `wWinMain` without any CLI flags needed and without needing `UNICODE` defined AFAICT).

2024-03-26 09:14 UTC, ypsvlq commented
> How did it used to work?

The version of mingw used in 0.11 includes the WinMain startup code in `crtexe.c`, in later versions it has been moved to a separate file which wasn't included in Zig. As far as I can tell `wWinMain` was never supported.

2024-03-26 15:40 UTC, chawyehsu commented
This is great! Thanks @ypsvlq for working on it! And I believe it will also close #9924 , in which unicode entry points support against mingw was reported missing the first time I guess.

2024-03-28 21:16 UTC, merged