autodoc: better indentation handling when rendering source code
ziglang/zig pull request #19422
Opened 2024-03-24 16:13 UTC by HydroH

Closes #19293

2024-03-24 20:49 UTC, mlugg requested changes

2024-03-24 20:49 UTC, mlugg commented on lib/docs/wasm/main.zig
> +    if (std.mem.lastIndexOfAny(u8, ast.source[0..cursor], "\r\n")) |newline_index| {
Canonical Zig style uses LF line endings (`\n`). Using `\n` here is also conveniently compatible with `\r\n`, so replacing this with `"\n"` will handle both line endings in common use today.

2024-03-24 20:49 UTC, mlugg commented on lib/docs/wasm/main.zig
> +    var it = std.mem.splitAny(u8, s, "\r\n");
Same as above.

2024-03-24 23:44 UTC, andrewrk commented
Can you share a screenshot to demonstrate your work?

2024-03-25 05:36 UTC, HydroH commented
> Can you share a screenshot to demonstrate your work?

Sure. This is a comparison between this pr and master branch rendered docs. I chose a function with nested blocks and comments, which should be a good demonstration.
![image](https://github.com/ziglang/zig/assets/14823453/ebfbb47d-bb2a-4b94-96ea-26064df73814)
![image](https://github.com/ziglang/zig/assets/14823453/4f45d55a-23fb-4181-8a1b-857e13af354c)

2024-03-25 05:43 UTC, mlugg approved these changes
Looks good to me!

I know what (AFAICT) this code ought to do, but could you give a screenshot of an example where some of the code has lower indentation than the start of the block? e.g.
```zig
const S = struct {
    const foo = {};
    test foo {
        const x: [2]u8 =
        // zig fmt: off
.{ 10, 20 };
        // zig fmt: on
        _ = x;
    }
};
```

Assuming I'm reading this right, the test should render like this (which I would consider ideal):
```zig
test foo {
    const x: [2]u8 =
    // zig fmt: off
.{ 10, 20 };
    // zig fmt: on
    _ = x;
}
```

2024-03-25 06:26 UTC, HydroH commented
> Looks good to me!
> 
> I know what (AFAICT) this code ought to do, but could you give a screenshot of an example where some of the code has lower indentation than the start of the block? e.g.
> 
> ```zig
> const S = struct {
>     const foo = {};
>     test foo {
>         const x: [2]u8 =
>         // zig fmt: off
> .{ 10, 20 };
>         // zig fmt: on
>         _ = x;
>     }
> };
> ```
> 
> Assuming I'm reading this right, the test should render like this (which I would consider ideal):
> 
> ```zig
> test foo {
>     const x: [2]u8 =
>     // zig fmt: off
> .{ 10, 20 };
>     // zig fmt: on
>     _ = x;
> }
> ```

This is the result for the following code:
```zig
        pub fn testIndent() void {
            const x: [2]u8 =
                // zig fmt: off
.{ 10, 20 };
            // zig fmt: on
            _ = x;
        }
```
![image](https://github.com/ziglang/zig/assets/14823453/6261a66a-d525-4870-b8ce-e4ba8d0d34e1)

2024-03-25 06:28 UTC, mlugg commented
Brilliant, I'm happy with this then - thanks!

2024-03-25 22:20 UTC, merged