Use DWARF debug format option
ziglang/zig pull request #19633
Opened 2024-04-12 18:12 UTC by chrisbodhi

Addresses #19478

2024-04-12 18:19 UTC, chrisbodhi commented on src/Compilation/Config.zig
> +            },
This works as expected with 

```
$ zig build-obj -gdwarf32 -O Debug -target x86_64-linux example.zig

$ /opt/homebrew/opt/binutils/bin/objdump --dwarf=info example.o | head -20

example.o:     file format elf64-x86-64

Contents of the .debug_info section:

  Compilation Unit @ offset 0:
   Length:        0x25f5a (32-bit)
   Version:       4
   Abbrev Offset: 0
   Pointer Size:  8
...
```

and 

```
$ zig build-obj -gdwarf64 -O Debug -target x86_64-linux example.zig

$ /opt/homebrew/opt/binutils/bin/objdump --dwarf=info example.o | head -20

example.o:     file format elf64-x86-64

Contents of the .debug_info section:

  Compilation Unit @ offset 0:
   Length:        0x31232 (64-bit)
   Version:       4
   Abbrev Offset: 0
   Pointer Size:  8
...
```

But, reviewing my code, I'm unsure of what the behavior would be if `debug_format` were empty. I can see that a 32-bit size is used when no flag is added:

```
$ zig build-obj -O Debug -target x86_64-linux example.zig

$ /opt/homebrew/opt/binutils/bin/objdump --dwarf=info example.o | head -20

example.o:     file format elf64-x86-64

Contents of the .debug_info section:

  Compilation Unit @ offset 0:
   Length:        0x25f5a (32-bit)
   Version:       4
   Abbrev Offset: 0
   Pointer Size:  8
...
```

Is this wanted?

2024-04-16 03:53 UTC, geezmolycos commented
I can see in past versions 32-bit format was used, and the `-dwarf64` option was added to resolve a specific problem (https://github.com/ziglang/zig/issues/7962), so default to 32-bit should be good for most situations.

2024-04-16 03:59 UTC, geezmolycos commented
Also, as a further suggestion, it might be straightforward to also support DWARF generation for windows target (COFF object) with these options. As mentioned in [CodeLLDB's wiki page](https://github.com/vadimcn/codelldb/wiki/Windows), LLDB's support for CodeView is incomplete, and GDB currently has no support for Codeview.

Allowing DWARF generation for windows could make it easier to integrate with mingw toolchain (which uses GDB or LLDB) and to [debug zig program in Wine environment](https://werat.dev/blog/debugging-wine-with-lldb-and-vscode/#:~:text=There%E2%80%99s%20one%20caveat,only%20on%20Windows.)

2024-04-23 00:13 UTC, chrisbodhi commented
@geezmolycos I made a pass at adding DWARF support for COFF objects as you suggested, but with my limited time, wasn't able to come up with a good emulation solution for verifying my changes. I'd prefer to add a new issue for adding DWARF support for COFF objects, and get this code reviewed as is. How does that all sound to you?

2024-04-23 03:11 UTC, geezmolycos commented
Okay, the current solution should be fine for the original problem. I know that the COFF thing might need more reviewing and testing. I will look into that and post another issue to find help or try to work with that myself. Anyways, thanks for your contribution

2024-04-23 12:47 UTC, chrisbodhi commented
Thanks for all of your guidance, @geezmolycos, and for writing a detailed & helpful issue -- that made it much easier to contribute. :D

2024-04-28 18:04 UTC, chrisbodhi commented
@kubkon 👋 Pinging for a review, since you've [previously reviewed a different, related PR](https://github.com/ziglang/zig/pull/15193).

2024-06-08 20:13 UTC, andrewrk requested changes
seems like it might work. please rebase your work and fix the issue I pointed out and then I think it could be merged.

2024-06-08 20:13 UTC, andrewrk commented on src/Compilation/Config.zig
> +            .elf, .macho, .wasm => switch (options.debug_format.?.dwarf) {
why are you assuming that options.debug_format is non-null?

2024-07-01 18:10 UTC, andrewrk commented
Closing since my instructions for getting the PR landed were ignored. Bug report still exists to track the issue.

2024-07-01 18:10 UTC, closed without merging

2024-07-01 20:57 UTC, chrisbodhi commented
@andrewrk thanks for the explanation and for working to keep the repo tidy. I tried some fixes to handle the null case, but didn't arrive at a solution that worked for all cases. As a new user to Zig, I tried working it out myself, but could have reached out for assistance sooner. When I have some extra brainspace (and if the bug report is still open), I'll do so and re-open the PR.