std: add std.options.debug_stacktrace_kind
ziglang/zig pull request #19650
Opened 2024-04-14 09:05 UTC by nektro

given the following test file we can run it with the various option values.

```zig
const std = @import("std");

pub const std_options = std.Options{
    .debug_stacktrace_kind = .full,
};

pub fn main() !void {
    foo();
}

fn foo() void {
    bar();
}

fn bar() void {
    qux();
}

fn qux() void {
    lorem();
}

fn lorem() void {
    ipsum();
}

fn ipsum() void {
    @panic("oops!");
}
```

```
thread 182792 panic: oops!
/home/meghan/src/zig/test4.zig:28:5: 0x10762c0 in ipsum (test4)
    @panic("oops!");
    ^
/home/meghan/src/zig/test4.zig:24:10: 0x10687e8 in lorem (test4)
    ipsum();
         ^
/home/meghan/src/zig/test4.zig:20:10: 0x1038158 in qux (test4)
    lorem();
         ^
/home/meghan/src/zig/test4.zig:16:8: 0x1036098 in bar (test4)
    qux();
       ^
/home/meghan/src/zig/test4.zig:12:8: 0x1033938 in foo (test4)
    bar();
       ^
/home/meghan/src/zig/test4.zig:8:8: 0x1033928 in main (test4)
    foo();
       ^
/home/meghan/src/zig/lib/std/start.zig:511:37: 0x1033904 in posixCallMainAndExit (test4)
            const result = root.main() catch |err| {
                                    ^
/home/meghan/src/zig/lib/std/start.zig:253:5: 0x1033441 in _start (test4)
    asm volatile (switch (native_arch) {
    ^
???:?:?: 0x0 in ??? (???)
Aborted (core dumped)
```

```
thread 182911 panic: oops!
/home/meghan/src/zig/test4.zig:28:5: 0x1073880 in ipsum (test4)
/home/meghan/src/zig/test4.zig:24:10: 0x10660e8 in lorem (test4)
/home/meghan/src/zig/test4.zig:20:10: 0x1037a78 in qux (test4)
/home/meghan/src/zig/test4.zig:16:8: 0x10359b8 in bar (test4)
/home/meghan/src/zig/test4.zig:12:8: 0x1033258 in foo (test4)
/home/meghan/src/zig/test4.zig:8:8: 0x1033248 in main (test4)
/home/meghan/src/zig/lib/std/start.zig:511:37: 0x1033224 in posixCallMainAndExit (test4)
/home/meghan/src/zig/lib/std/start.zig:253:5: 0x1032d61 in _start (test4)
???:?:?: 0x0 in ??? (???)
Aborted (core dumped)
```

```
thread 183137 panic: oops!
Aborted (core dumped)
```

beyond stylistic desires, the various options also have performance and binary size ramifications. `.none` exits faster not having to inspect the program's debug info and results in a smaller file. however since this does not require the file to be stripped to get the effect, using an external debugger remains totally possible.

```
-rwxr-xr-x 1 meghan users 2227856 Apr 14 02:01 ./test4-full
-rwxr-xr-x 1 meghan users 2208816 Apr 14 02:03 ./test4-slim
-rwxr-xr-x 1 meghan users 1921440 Apr 14 02:04 ./test4-none
```

2024-05-08 20:34 UTC, Khitiara commented
a version that prints out stack addresses without needing any debug info (so no file, line, or symbol name info) could be useful too

2024-05-08 20:36 UTC, nektro commented
afaik that's already what happens if you use `.full` and strip. it will print out the addresses with the line info replaced with `????`

2024-05-08 21:25 UTC, Khitiara commented
if you strip debug info then dumpStackTrace prints out a warning and returns early, and writeStackTrace returns error.MissingDebugInfo, though printSourceAtAddress does work for what you describe

2024-08-24 05:07 UTC, andrewrk requested changes
Thank you. I think it is a good idea. Happy to merge if you:
* rebase on latest master
* rename "kind" to "mode" (Since "mode" applies in fewer places than "kind" it a better name when it can be used)
* expose the enum inside the `std.Options` namespace
* default to "none" when strip is true
* double check that it still works (test it again) and let me know that you did that

2024-08-24 05:07 UTC, andrewrk commented on lib/std/std.zig
> +    debug_stacktrace_kind: enum { none, slim, full } = .full,
```suggestion
    debug_stacktrace_mode: DebugStacktraceMode = if (builtin.strip) .none else .full,
```

2024-09-23 19:46 UTC, nektro commented
built llvm 19 and rebased branch last night, will address comments and re-test soon

2025-01-30 15:21 UTC, alexrp commented
@nektro want to try getting this into 0.14.0?

2025-01-30 20:58 UTC, nektro commented
thought 22077 might supersede this but read the description and it says it doesn't. yeah i can rebase and address the comments soon

2025-01-31 21:27 UTC, nektro commented
reran the test above with the same file from the OP description

<details>
<summary> full </summary>

```
thread 825998 panic: oops!
/home/meghan/src/zig/test.zig:28:5: 0x1056f6c in ipsum (test)
    @panic("oops!");
    ^
/home/meghan/src/zig/test.zig:24:10: 0x103d088 in lorem (test)
    ipsum();
         ^
/home/meghan/src/zig/test.zig:20:10: 0x103b158 in qux (test)
    lorem();
         ^
/home/meghan/src/zig/test.zig:16:8: 0x103a068 in bar (test)
    qux();
       ^
/home/meghan/src/zig/test.zig:12:8: 0x1038d68 in foo (test)
    bar();
       ^
/home/meghan/src/zig/test.zig:8:8: 0x1038d58 in main (test)
    foo();
       ^
/home/meghan/src/zig/lib/std/start.zig:656:37: 0x1038d22 in posixCallMainAndExit (test)
            const result = root.main() catch |err| {
                                    ^
/home/meghan/src/zig/lib/std/start.zig:271:5: 0x10388fd in _start (test)
    asm volatile (switch (native_arch) {
    ^
???:?:?: 0x0 in ??? (???)
Aborted (core dumped)
```
</details>

<details>
<summary> slim </summary>

```
thread 826329 panic: oops!
/home/meghan/src/zig/test.zig:28:5: 0x105497c in ipsum (test)
/home/meghan/src/zig/test.zig:24:10: 0x103c9b8 in lorem (test)
/home/meghan/src/zig/test.zig:20:10: 0x103aa88 in qux (test)
/home/meghan/src/zig/test.zig:16:8: 0x1039998 in bar (test)
/home/meghan/src/zig/test.zig:12:8: 0x1038698 in foo (test)
/home/meghan/src/zig/test.zig:8:8: 0x1038688 in main (test)
/home/meghan/src/zig/lib/std/start.zig:656:37: 0x1038652 in posixCallMainAndExit (test)
/home/meghan/src/zig/lib/std/start.zig:271:5: 0x103822d in _start (test)
???:?:?: 0x0 in ??? (???)
Aborted (core dumped)
```

</details>

<details>
<summary> none </summary>

```
thread 826606 panic: oops!
Aborted (core dumped)
```

</details>

2025-01-31 21:35 UTC, alexrp commented on lib/std/debug.zig
> +pub const StackTraceMode = enum {
@andrewrk are you fine with this being here? A bit unclear from your comment if you meant for the enum itself to be declared inside `std.Options` too.

2025-02-03 13:52 UTC, xdBronch commented
this should also handle `dumpStackTrace` which is what the default panic handler uses so thatll probably have the largest impact on binary size and compile time in small examples, possibly others too but i didnt look too hard. the amount of different but very similar functions this needs to be done in makes me think this whole stack trace system could be done better, though thats just a thought, i havent familiarized myself with it.

2025-02-23 08:10 UTC, nektro commented
size comparison of the three modes

```
[meghan@nixos:~/src/zig]$ ./build/stage3/bin/zig build-exe -femit-bin=testt ./test.zig && ll ./testt
-rwxr-xr-x 1 meghan users 2664144 Feb 23 00:08 ./testt

[meghan@nixos:~/src/zig]$ ./build/stage3/bin/zig build-exe -femit-bin=testt ./test.zig && ll ./testt
-rwxr-xr-x 1 meghan users 2645304 Feb 23 00:08 ./testt

[meghan@nixos:~/src/zig]$ ./build/stage3/bin/zig build-exe -femit-bin=testt ./test.zig && ll ./testt
-rwxr-xr-x 1 meghan users 1299776 Feb 23 00:09 ./testt

```

2025-08-02 04:37 UTC, xdBronch commented
it would also be nice if this allowed you to force enable stack traces even if `builtin.strip_debug_info` is true. in cases where you use [zig as a library](https://gist.github.com/andrewrk/752a1f4db1a3327ee21f684cc87026e7) to provide debug utility in other programs its not necessary for the zig code itself to have debug info, only the final executable. testing locally, after commenting out the places that check for debug info im able to strip the object file which takes it from 1.3M to 184K while still fully functioning

maybe this could be as simple as removing the all the checks for `strip_debug_info` and simply relying on the value of `options.debug_stacktrace_mode` with a reasonable default

2025-10-04 18:48 UTC, alexrp commented
Is this still needed with #25227?

2026-04-25 07:51 UTC, alexrp commented
> Is this still needed with #25227?

Closing on the assumption that the answer is "no", but if I'm wrong, you're of course welcome to resubmit on Codeberg.

2026-04-25 07:51 UTC, closed without merging