std: add pointer stability locks to array list
ziglang/zig pull request #19676
Opened 2024-04-17 16:07 UTC by emar-kar

Closes #19326

2024-08-12 18:04 UTC, andrewrk requested changes

2024-08-12 18:04 UTC, andrewrk commented on lib/std/array_list.zig
> +            self.pointer_stability.unlock();
```suggestion
            self.pointer_stability.assertUnlocked();
```

2024-09-03 22:12 UTC, vortexofdoom reviewed
This shouldn't require pointers to be unlocked, right? The only allocations are for the newly cloned ArrayList, and the original allocation is unchanged.

2024-09-03 22:12 UTC, vortexofdoom commented on lib/std/array_list.zig
> +            self.pointer_stability.assertUnlocked();
```suggestion
```

2024-09-03 22:12 UTC, vortexofdoom commented on lib/std/array_list.zig
> +            self.pointer_stability.assertUnlocked();
```suggestion
```

2024-09-04 08:59 UTC, emar-kar commented
And I was thinking if `appendSliceAssumeCapacity` should lock the array as well?

2024-09-04 14:09 UTC, vortexofdoom commented
Interesting point. I guess my gut instinct would be to avoid making things that should be trivially possible in non-async settings impossible for the sake of async. In an async setting you can manually lock it before a clone.

Appending, even assuming capacity, could "invalidate" a pointer to the last element or similar, so that seems maybe less objectionable, but I could see the argument for removing it.

Although I guess the argument exists that you won't be locking much in a non-async context, so it may be a non-issue.

2024-09-04 14:20 UTC, emar-kar commented
I see the point for removing assertion from clone. And actually I do support it. It's easy to bring it back in case 

Anyway, the question about `appendSliceAssumeCapacity ` is still open for discussion.

2024-09-04 16:41 UTC, vortexofdoom commented
Looking at it, I think `appendSliceAssumeCapacity` is also better without. There's already an assertion that the items can fit, it's supposed to be the utility function for actually doing the thing under the hood, I think if it requires being unlocked suddenly there's a case for making an even *deeper* function that doesn't require it being unlocked.

The buck has to stop somewhere, and I think it's fine to stop short of functions with `assume` in the name.

2025-02-05 06:00 UTC, alexrp commented
Merge conflicts need to be resolved.

2025-02-23 04:53 UTC, andrewrk commented
3 weeks old, conflicts, failing CI.

2025-02-23 04:53 UTC, closed without merging

2025-02-23 08:32 UTC, emar-kar commented
> 3 weeks old, conflicts

MR was opened 6 months ago. And the last sync with master was when someone came back to have look at it.

> failing CI

CI was failing after master merge with errors unrelated to changes