std.net: use send/recv for streams, support vectorized io on windows
ziglang/zig pull request #19751
Opened 2024-04-23 19:44 UTC by truemedian

The primary goal of this change is to use `send` and `recv` for network streams, this also enables passing per-message flags like `MSG_NOSIGNAL` instead of installing a SIGPIPE handler.

- Alongside using recv and send, windows now uses WSARecvFrom and WSASendTo for readv and writev. This enables vectorized network I/O on windows.

Introduces a mostly platform agnostic iovec as `std.net.iovec` and `std.net.iovec_const`. This provides a singular interface to vectorized network I/O on windows and posix.

- The only problem this introduces is windows using `u32` for lengths and posix using `usize`. This requires any code currently using `usize` to `@intCast` into the length field.

- As part of this change, `std.posix.iovec` and `std.windows.ws2_32.WSABUF` now use `.ptr` and `.len` instead of their posix/windows specific names.

Removes std.os.windows.ws2_32.WSARecvMsg, as it is not present in ws2_32.dll and must be fetched via WSAIoctl.

- The `sendto` and `recvfrom` wrappers around `WSASendTo` and `WSARecvFrom` have been removed from `std.os.windows`. These functions are already provided by `ws2_32` and are not needed.

A os-agnostic IoVec struct (re #7699) would likely be more convienent to use, but I could not design an interface that both works well and is reasonable to interact with.

A potential problem this PR introduces is passing `WSABUF_const` to `WSASendTo` and `WSASend` is that this type doesn't actually exist in windows. Windows makes no guarantees that the buffers will not be modified.

This enables the "general client/server API coverage" test on windows. The comment on the skip claims that the test was never passing, however during my tests the test passed 100% of the time.

2024-04-25 19:09 UTC, andrewrk requested changes

2024-04-25 19:09 UTC, andrewrk commented on lib/compiler/objcopy.zig
> +                    var iovec = [_]std.posix.iovec_const{.{ .ptr = data.data.ptr, .len = data.data.len }};
can you please submit this as a standalone PR?

2024-04-29 02:16 UTC, daurnimator commented
For what it's worth, the `const`-ness for `IoSlice` gets more complicated 
with e.g. `sendmsg` where we need `msghdr` and `msghdr_const`
and then again with e.g. `sendmmsg` where we have e.g. `mmsghdr_const` vs `msghdr_const`

2024-04-29 15:33 UTC, truemedian commented
I decided to avoid writing definitions for msghdr and mmsghdr because nothing in std.net needs them (right now). I'm not sure a cross platform definition of msghdr is even necessary for TCP because WSASend/WSARecv already do vectorized IO and don't enable any extra features. And outside of Windows, `[]IoSlice` can be ptrCast into an `[]iovec` because they're guaranteed to have the same representation

2024-09-10 13:27 UTC, truemedian commented
No idea why `zig build test docs` seems to hang on x86, although it appears to be relatively consistent, it has happened 3 times now.

Could a part of the compiler or docgen be reliant on some behavior that was inadvertantly changed here?

2024-10-01 19:22 UTC, truemedian commented
The last commit seems to have triggered #21457, despite not touching any of those components. Will wait for it to be resolved before resuming.

2025-01-17 22:59 UTC, roig commented
Good work, I hope this lands before 0.14 release.

2025-02-05 05:59 UTC, alexrp commented
This has merge conflicts and related-looking CI failures that need to be resolved.

2025-02-05 20:22 UTC, truemedian commented
I finally got around to rebasing on master and fixing the merge conflict. Changing `writeAll` to no longer call the type-erased and const-qualified `write_cl` seems to have fixed the test failure (CI seems to be very far behind so will have to wait to see if it fixes it everywhere).

If tests start passing it's further support towards #21457 being related to the constCast.

2025-02-23 04:51 UTC, andrewrk commented
I have solved this in [wrangle-writer-buffering branch](https://github.com/ziglang/zig/tree/wrangle-writer-buffering), work will continue on it post 0.14.0 tag.

2025-02-23 04:51 UTC, closed without merging