zig build: add `--pkg-config` option
ziglang/zig pull request #19901
Opened 2024-05-08 19:04 UTC by BratishkaErik

Useful to override path to pkg-config executable, for example when it's name is prepended by target triple for cross-compilation purposes.

2024-05-08 20:31 UTC, nektro commented
standard practice here is to check the `PKG_CONFIG` env var

2024-05-08 21:00 UTC, BratishkaErik commented
> standard practice here is to check the `PKG_CONFIG` env var

I know, it was intentionally omitted. I think it will be easier to merge without it, since there are less lines added and less ehh controversial points (IIRC core team wants to avoid this kind of environment variables, f.e.  https://github.com/ziglang/zig/issues/17585 and https://github.com/ziglang/zig/issues/10754#issuecomment-1519151708), don't want to convince them, just easy merge.

2024-05-09 09:25 UTC, BratishkaErik commented
Fixed merge conflict.

2024-05-12 13:44 UTC, andrewrk requested changes
I don't see how those linked issues are relevant. If `PKG_CONFIG` environment variable is a standard practice then it's desirable to use as the default. The purpose of the pkg-config integration is to integrate with the system. Respecting a standard environment variable would make the system integration more complete.

2024-05-12 14:14 UTC, BratishkaErik commented
> I don't see how those linked issues are relevant. If `PKG_CONFIG` environment variable is a standard practice then it's desirable to use as the default. The purpose of the pkg-config integration is to integrate with the system. Respecting a standard environment variable would make the system integration more complete.

It's even better, will do :)

2024-05-17 13:26 UTC, xnhp0320 commented
you can use below code in the build.zig to achieve the same effect.

```zig
b.graph.env_map.put("PKG_CONFIG_PATH", "XXXX") catch unreachable;
```

2024-07-21 09:32 UTC, merged

2024-07-24 05:52 UTC, BratishkaErik commented
Thanks!