std.crypto: add the ability to explicitly tag a value as secret
ziglang/zig pull request #19907
Opened 2024-05-08 23:41 UTC by jedisct1

It turns out that Valgrind can be a very useful tool to check that secrets are not leaked via side channels involving lookups or conditional jumps.

Valgrind tracks uninitialized data, and memcheck reports operations involving uninitialized values. By permanently or temporarily telling Valgrind that a memory region containing secrets is uninitialized, we can detect common side-channel vulnerabilities.

For example, the following code snippets would immediately report that the result is not computed in constant time:

```zig
classify(&key);
const len = std.mem.indexOfScalar(u8, &key, 0);
```

```zig
classify(&key);
const idx = key[0];
x += idx;
```

```zig
var x: [4]u8 = undefined;
std.crypto.random.bytes(&x);
classify(&x);
if (std.mem.eql(u8, "test", &x)) return;
```

This is not fool-proof, but it can help a lot to detect unwanted compiler optimizations.

Also, right now, this is relying on Valgrind primitives, but these annotations can be used to do more interesting things later, especially with our own code generation backends.

2024-05-09 21:40 UTC, andrewrk requested changes
Cool idea!

No new functions should be added to utils.zig or they will have to be deprecated and moved later. Just put them at the root of std.crypto, i.e. `std.crypto.classify` and `std.crypto.declassify` [API naming guidance](https://ziglang.org/documentation/master/#Avoid-Redundancy-in-Names)

Wouldn't it be great if Valgrind could add support for this kind of thing directly, and then it wouldn't have to be such a hack. Maybe we can convince the project to add something like this.

2024-05-09 21:40 UTC, andrewrk commented on lib/std/crypto/utils.zig
> +    if (@inComptime()) return;
```suggestion
    if (!std.debug.inValgrind()) return;
```

[inValgrind](https://ziglang.org/documentation/master/std/#std.debug.inValgrind)

Also I think this check should be pushed up into `classify` and `declassify`.

2024-05-09 22:47 UTC, jedisct1 commented
Everything in `std.crypto.utils` contains building blocks for constant-time operations. And additional functions we have could be move there (for example all the `ct` namespace from `crypto.ff`).

So, maybe we could keep `classify()`/`declassify()` there and rename `utils` to `ct` instead?

2024-07-21 09:22 UTC, andrewrk commented
> So, maybe we could keep `classify()`/`declassify()` there and rename `utils` to `ct` instead?

Sounds good!

2024-11-20 00:15 UTC, daurnimator commented on lib/std/crypto/timing_safe.zig
> +    if (!std.debug.inValgrind()) return;
This does both a runtime and a compile-time check; where the runtime check is as expensive as just doing the operation anyway.
i.e. no need for this check: the `makeMemUndefined`/`makeMemDefined` compile to no-ops if not running under valgrind
Though perhaps you should add in a check for debug/safe vs release-fast?

2024-11-20 09:46 UTC, jedisct1 commented on lib/std/crypto/timing_safe.zig
> +    if (!std.debug.inValgrind()) return;
> i.e. no need for this check: the makeMemUndefined/makeMemDefined compile to no-ops

Is that true without LTO?

2024-11-20 11:45 UTC, jedisct1 commented on lib/std/crypto/timing_safe.zig
> +    if (!std.debug.inValgrind()) return;
The `std.debug.inValgrind()` checks have been removed.

A check for debug/safe vs release-fast can be useful if `classify()` does a bit more than call valgrind, but this is not the case yet.

2025-02-20 11:32 UTC, merged