std.hash_map: adding a rehash() method
ziglang/zig pull request #19923
Opened 2024-05-10 00:24 UTC by mrjbq7

**Note: this resurrects the recently closed #17890.**

---

This allows a highly fragmented HashMap to have tombstones removed as the values are all rehashed.

It would be nice to make this ``rehash()`` automatically, but that currently presents a challenge where it doesn't work with adapted contexts since the keys are not preserved in the map for re-hashing and the hash value is not stored currently, and the non-adapted contexts require a bit of additional book-keeping to check before calling rehash().

This is a partial fix for #17851, but requires the user to call ``rehash()`` periodically to get the benefit.

2024-05-10 09:44 UTC, linusg requested changes

2024-05-10 09:44 UTC, linusg commented on lib/std/hash_map.zig
> +    var prng = std.rand.DefaultPrng.init(0);
https://github.com/ziglang/zig/blob/841bb0a1fd73f71865ec29027a8f6de8ed0efa74/lib/std/std.zig#L94-L95

2024-05-10 09:44 UTC, linusg commented on lib/std/hash_map.zig
> +    while (i < count) : (i += 1) {
`for (0..count) |i|`

2024-05-10 09:44 UTC, linusg commented on lib/std/hash_map.zig
> +    while (i < count) : (i += 1) {
likewise

2024-05-10 15:30 UTC, mrjbq7 commented
@linusg thanks! fixed those 3 comments, and rebased on master again.

2024-06-06 03:28 UTC, mrjbq7 commented
I'll just keep it rebased on master until @andrewrk tells me he doesn't like this PR.

2024-07-15 22:37 UTC, tau-dev commented
To mirror my comment in #17851: We can remove the user burden of calling rehash manually by requiring any adapter context to have an additional `hashStored` function capable of hashing non-adapted keys, which enables the HashMap to rehash automatically and maintain good performance by default.

2024-07-23 11:05 UTC, tau-dev commented
After this is merged, I'd be happy to fix #7494.

2024-08-08 18:59 UTC, merged