Fix GeneralPurposeAllocator crash when deallocating metadata
ziglang/zig pull request #20000
Opened 2024-05-19 11:55 UTC by Frojdholm

Fixes #19977

This makes the following test not crash

```zig
const std = @import("std");

test "retain metadata and never unmap" {
    var gpa = std.heap.GeneralPurposeAllocator(.{
        .safety = true,
        .never_unmap = true,
        .retain_metadata = true,
    }){};
    defer std.debug.assert(gpa.deinit() == .ok);
    const allocator = gpa.allocator();

    const alloc = try allocator.alloc(u8, 8);
    allocator.free(alloc);

    const alloc2 = try allocator.alloc(u8, 8);
    allocator.free(alloc2);
}
```

However I feel like iterating the `Treap` like this to modify the nodes is a bit of a foot gun since it can very easily invalidate the `Treap`. In this case it's okay since we're doing it to destroy all nodes in the tree.

An alternative implementation, that requires some tree rotations, but doesn't invalidate the tree during removal is
```zig
// free retained metadata for small allocations
while (self.empty_buckets.getMin()) |node| {
    // remove the node before making modifications
    var entry = self.empty_buckets.getEntryForExisting(node);
    entry.set(null);

    var bucket = node.key;
    if (config.never_unmap) {
        // free page that was intentionally leaked by never_unmap
        self.backing_allocator.free(bucket.page[0..page_size]);
    }
    // alloc_cursor was set to slot count when bucket added to empty_buckets
    self.freeBucket(bucket, @divExact(page_size, bucket.alloc_cursor));
    self.bucket_node_pool.destroy(node);
}
self.empty_buckets.root = null;
```

2024-05-20 15:07 UTC, andrewrk requested changes
Nice test case. Can it be added to the file as a unit test?

2024-05-20 16:31 UTC, Frojdholm commented
> Nice test case. Can it be added to the file as a unit test?

Sure, added :+1:

However, I was a bit confused that the "double frees" test wasn't already failing since it's using the same setup, but with a backing allocator of another GPA.

2024-05-21 17:10 UTC, Frojdholm commented
Test failure was a flaky windows test

2024-06-06 01:13 UTC, merged

2024-06-06 01:14 UTC, andrewrk commented
Thanks!