std: Avoid overflowing in the midpoint calculation in upperBound
ziglang/zig pull request #20029
Opened 2024-05-22 01:42 UTC by g2mt

The line that calculates the midpoint in the upperBound function didn't take into account overflows from large arrays like in other binary search functions.

2024-05-22 01:52 UTC, marler8997 commented
Is it possible to add a regression test that would ensure this doesn't break again?

2024-05-22 13:52 UTC, andrewrk requested changes
unit test please

2024-05-22 14:56 UTC, g2mt commented
How should I write the unit test? Triggering an overflow requires the left and right indices add up to greater than max of usize. Allocating a 2 GB array to test it seems feasible for a 32-bit system, but I'm not sure if you can allocate 2^63 bytes on most 64-bit systems.

2024-05-22 15:02 UTC, marler8997 commented
There's `upperBound` unit tests a little further down in the code, you should be able to add your test there.  No need to actually allocate that much memory.

2024-05-23 10:39 UTC, squeek502 commented
> No need to actually allocate that much memory.

Unless I'm missing something, there is.

2024-05-29 00:44 UTC, andrewrk commented
Upon second look, I'm happy to merge this as-is. Thanks @g2mt

2024-05-29 00:44 UTC, merged