Updated initialisation of `Color` values and `std.Progress` nodes to respect environment variable `NO_COLOR` and `native_os`.
ziglang/zig pull request #20141
Opened 2024-05-31 20:55 UTC by amp-59

2024-05-31 23:20 UTC, amp-59 commented
@Vexu Is this patch ready to be merged?

2024-06-01 07:07 UTC, Vexu reviewed
It would be nice having the comment explaining the initializer attached to these other places, maybe by extracting the initializer into a `defaultColor` helper?

2024-06-01 07:07 UTC, Vexu commented on src/main.zig
> +    const color: Color = if (native_os == .wasi or EnvVar.NO_COLOR.isSet()) .off else .auto;
`cmdTranslateC` should get `color` from either `buildOutputType` or `serve`.

2024-06-01 20:02 UTC, amp-59 commented
Is that all okay?

2024-06-02 07:18 UTC, Vexu commented
If you fix the commits then yes. `defaultColor` didn't need to be more verbose but I guess it's fine that way too.

2024-06-02 08:35 UTC, andrewrk requested changes
This diff has a bunch of crap in it that is already in master branch. If you want this reviewed then make it mergeable as-is.

2024-06-02 18:05 UTC, amp-59 commented
>  If you want this reviewed 

No problem.

2024-06-02 18:05 UTC, closed without merging