std.priority_queue: add useful functions from ArrayList API
ziglang/zig pull request #20282
Opened 2024-06-13 14:23 UTC by dweiller

The `ensureTotalCapacityPrecise`, `clearRetainingCapacity` and `clearAndFree` functions from the ArrayList API are also useful for a PriorityQueue.

2025-01-30 14:04 UTC, ifreund requested changes

2025-01-30 14:05 UTC, ifreund commented on lib/std/priority_queue.zig
> +                self.capacity = std.math.maxInt(usize);
Actually I'll just get rid of this branch myself and enable auto-merge. No need to make you make trivial changes to a 6 month old PR :D

2025-01-30 14:07 UTC, ifreund approved these changes
Thanks for the patch!

2025-01-31 00:02 UTC, dweiller commented on lib/std/priority_queue.zig
> +                self.capacity = std.math.maxInt(usize);
Whoops, not sure (well, I can guess but don't remember) how that happened, thanks for fixing it up.

2025-02-01 18:02 UTC, merged