Make 0e.0 and 0xp0 not crash
ziglang/zig pull request #20400
Opened 2024-06-23 12:35 UTC by wooster0

This fixes those sequences of characters crashing.

Fixes #20385

2024-06-24 10:25 UTC, Vexu approved these changes

2024-06-25 09:56 UTC, linusg requested changes

2024-06-27 22:14 UTC, wooster0 commented on lib/std/zig/number_literal.zig
> +                    return .{ .failure = .{ .digit_after_base = {} } };
This kind of thing can be done in a different PR

2024-06-27 23:13 UTC, linusg commented on lib/std/zig/number_literal.zig
> +                    return .{ .failure = .{ .digit_after_base = {} } };
It's new code, why would you want to fix that in a _separate_ PR?

2024-06-30 04:33 UTC, wooster0 commented on lib/std/zig/number_literal.zig
> +                    return .{ .failure = .{ .digit_after_base = {} } };
This is basically just style. I don't see the problem. You're not pointing out a bug or anything. Unless a maintainer wants this I don't feel like rerunning the CI for this

2024-06-30 10:11 UTC, Rexicon226 commented on lib/std/zig/number_literal.zig
> +                    return .{ .failure = .{ .digit_after_base = {} } };
That is silly, there is literally no gain from not fixing this. A subsequent PR will *also* run the CI??

2024-06-30 10:33 UTC, wooster0 commented on lib/std/zig/number_literal.zig
> +                    return .{ .failure = .{ .digit_after_base = {} } };
I don't see anything to fix. This is just style.

2024-06-30 16:16 UTC, linusg commented
For reviewing maintainers: The comment above has mistakenly been marked as resolved, please take a look at it before merging. Thanks!

2024-07-03 06:53 UTC, andrewrk commented
I would have appreciated the suggested cleanup, but thanks for the bug fix regardless.

2024-07-03 06:53 UTC, merged