Some improvements on llvm for BPF platform
ziglang/zig pull request #20479
Opened 2024-07-03 09:10 UTC by tw4452852

2024-07-03 13:06 UTC, jacobly0 requested changes
A departure from the debug info emitted by clang cannot be merged without any stated justification.  At the very least, some way of evaluating whether this change is still necessary in the future is needed.  Also, a change like this needs some manual testing on the affected targets, which is all of them according to the code, and a blank PR description with no mention in commit messages does not suggest that any testing was done.

2024-07-03 14:14 UTC, jacobly0 commented
Here's the relevant code in clang:
https://github.com/llvm/llvm-project/blob/3b5b5c1ec4a3095ab096dd780e84d7ab81f3d7ff/clang/lib/CodeGen/CGDebugInfo.cpp#L4372-L4387
https://github.com/llvm/llvm-project/blob/3b5b5c1ec4a3095ab096dd780e84d7ab81f3d7ff/clang/lib/CodeGen/CGDebugInfo.cpp#L5922-L5927
Which means that this change only applies to the BPF target when optimizations and debug info are enabled.

2024-07-04 01:59 UTC, tw4452852 commented
@jacobly0 Thanks for the review, I think this is just my attempt to fix the issue I mentioned before, moreover this change could be a reference when someone else is trying to implement this feature, and this is just a POC, so I change it to the draft.
The reason I use trail is that the retained node's information isn't available when subprogram is created. It is only available after generating all the airArg instructions. And I leverage the trail's `nextMut` method to override later.

2024-10-15 08:35 UTC, andrewrk commented
draft status, no updates in 30+ days

2024-10-15 08:35 UTC, closed without merging