Fix #19443
ziglang/zig pull request #20543
Opened 2024-07-08 21:29 UTC by tau-dev

Reset the line number to its previous state after genBodyDebugScope, so that instructions between its end and the next dbg_stmt do not leak inside the block. This core fix is very simple, but surfaces a secondary issue: the LLVM codegen generates blocks in a different order than Clang would for the same CFG in C, which ultimately results in GDB skipping the loop header altogether. So we need to reorder some basic blocks too.

2024-07-21 08:38 UTC, andrewrk commented
Is patching Builder really the correct solution here? I think the usage code, if anything should be updated. Also I'm not convinced the order of basic blocks is the problem.

2024-07-21 16:23 UTC, tau-dev commented
> Also I'm not convinced the order of basic blocks is the problem.

No problem! If you move the placeBlock so that we get the same ordering again as we have now:
```patch
--- /tmp/llvm.zig       2024-07-21 18:02:01.645028639 +0200
+++ src/codegen/llvm.zig        2024-07-21 18:01:12.664540800 +0200
@@ -5962,10 +5962,10 @@
             .breaks = &breaks,
         });
         defer assert(self.blocks.remove(inst));
+        try self.wip.placeBlock(parent_bb);

         try self.genBodyDebugScope(maybe_inline_func, body);

-        try self.wip.placeBlock(parent_bb);
         self.wip.cursor = .{ .block = parent_bb };

         // Create a phi node only if the block returns a value.
```

an then, for example, try stepping through a for loop—this is my test code:
```zig
export fn foo() u8 {
    const s = [3]u32{4,5,6};

    var x: u8 = 1;
    for (s) |c| {
        if (c == 5)
            x = 2;
        x = 3;
    }
    return x;
}
```
—then you can see that GDB doesn't stop on the `for (s) |c| {` line anymore after the first iteration. Took me some head-scratching to figure that one out :)

How could I influence the block ordering without touching the Builder?

2024-07-21 17:28 UTC, tau-dev commented
CI failure seems unrelated (to this PR, I'm working on fixing my other one, sorry for that)

2024-07-21 20:05 UTC, andrewrk commented
I think it would be informative to look at it in terms of the LLVM IR that is being generated.

2024-07-21 20:27 UTC, tau-dev commented
The LLVM is the same, differing only in the order of the blocks. Hang on a sec, I can show you too...

2024-07-21 21:06 UTC, tau-dev commented
Updated the details tags in my previous comment.

2025-03-08 05:13 UTC, jacobly0 requested changes
This also doesn't emit equivalent textual llvm IR, which is a sure recipe for disaster later.  Additionally, this increases the size of a finalized function without increasing its information content.  The whole point is to be able to store extra information in `WipFunction` and then simplify the representation so that it doesn't have to be stored anymore in `Function`.

2025-03-08 14:44 UTC, tau-dev commented
If you are referring to the `remapped_index` field, we could get rid of that by doing a remapping scan over all instructions in finish(); would that help?

> doesn't emit equivalent textual llvm IR
Equivalent to what?

2025-11-27 02:30 UTC, andrewrk commented
This pull request is not ready for review because:
* It has conflicts that must be resolved via rebasing against latest origin/master.
* It is not passing the CI tests.
* No response to core team feedback for 30+ days.

2025-11-27 02:30 UTC, closed without merging