Add length range to FuzzInputOptions
ziglang/zig pull request #20914
Opened 2024-08-03 03:16 UTC by AdamGoertz

Closes #20816

Example test case, fuzzing f64 printing.

```zig
const std = @import("std");
const testing = std.testing;

test "fuzz f64 printing" {
    const input_bytes = testing.fuzzInput(.{
        .corpus = &.{std.mem.asBytes(&@as(f64, 32.0))},
        .len_range = .{ .min = 8, .max = 8 },
    });
    var buf: [1024]u8 = undefined;
    _ = try std.fmt.bufPrint(&buf, "{}", .{@as(f64, @bitCast(input_bytes[0..8].*))});
}
```

If the minimum length is greater than 0, the corpus must contain at least 1 entry, so that we can use it for the initial run/smoke test of the fuzzer.

```zig
const std = @import("std");
const testing = std.testing;

test "fuzz f64 printing no corpus" {
    const input_bytes = testing.fuzzInput(.{
        // ERROR: no corpus with len_range.min > 0
        .len_range = .{ .min = 8, .max = 8 },
    });
    var buf: [1024]u8 = undefined;
    _ = try std.fmt.bufPrint(&buf, "{}", .{@as(f64, @bitCast(input_bytes[0..8].*))});
}
```

fails with the error:

```
adam@d436cc4244a0:~/fuzz_test$ ../zig/build/debug/bin/zig build test --fuzz --debug-rt
test
└─ run test failure
fuzz input with minimum length > 0 must provide a corpus
error: while executing test 'root.test.fuzz no corpus', the following command exited with code 1 (expected exited with code 0):
/home/adam/fuzz_test/.zig-cache/o/f0d612cb25ff38743ccda28a305c932c/test --seed=0x5a6aeb46 --listen=-
Build Summary: 1/3 steps succeeded; 1 failed; 1/1 tests passed
test transitive failure
└─ run test failure
error: the following build command failed with exit code 1:
/home/adam/fuzz_test/.zig-cache/o/aa465f37e8f409be163d7a296fb3ce6a/build /home/adam/zig/build/debug/bin/zig /home/adam/zig/lib /home/adam/fuzz_test /home/adam/fuzz_test/.zig-cache /home/adam/.cache/zig --seed 0x5a6aeb46 -Z42915d9275626acf test --fuzz --debug-rt
```

Several invariants are enforced with assertions:

* len_range.min <= len_range.max
* The output of `Fuzzer.next()` is always between the min and max length (inclusive).
* the length of corpus entries is between the min and max range

2024-08-03 19:20 UTC, andrewrk commented
I'll look at this in a couple days - I have a rather large body of work sitting in the `fuzz` branch right now.

2024-08-04 00:01 UTC, AdamGoertz commented
No problem, I figured. As of yesterday looks like the conflicts would be pretty minimal, so hopefully it'll stay easy.

2024-08-07 22:18 UTC, andrewrk commented
Looks like there were indeed a couple of conflicts.

2024-08-08 02:39 UTC, AdamGoertz commented
Conflicts resolved :+1:

2024-08-08 03:38 UTC, andrewrk commented
> If the minimum length is greater than 0, the corpus must contain at least 1 entry, so that we can use it for the initial run/smoke test of the fuzzer.

No need, it can generate random bytes in this case.

2024-08-08 11:48 UTC, AdamGoertz commented
> > If the minimum length is greater than 0, the corpus must contain at least 1 entry, so that we can use it for the initial run/smoke test of the fuzzer.
> 
> 
> 
> No need, it can generate random bytes in this case.

I considered this. The concern I had was with ownership of the memory for holding the input. Since the length range is runtime known we need to allocate it dynamically. Under normal circumstances the fuzzer owns all of the returned memory, but on the initial run it's not clear how to de-allocate the slice returned from fuzzInput. A few options I considered:

* Use a comptime-known length range:
This would force the FuzzInputOptions parameter to be comptime known. Being able to load corpus entries from a file (without '@embedFile') would be nice, which this option would preclude. The length range could also be moved to a second parameter. 

* Reorganize the fuzzer code so it is still able to manage the returned input even when not linked to libfuzzer: This might be the best option, but I haven't explored how difficult it would be. My objective was to minimize changes to the current fuzzing architecture.

* add a 'deinit' function for the fuzzer input: totally possible, just annoying because it would do nothing while actually fuzzing; its only responsibility would be cleaning up this one allocation for the smoke test. 

Does one of these (or something else I haven't considered) seem like a better approach?

2024-08-09 03:18 UTC, AdamGoertz commented
Ok, a pretty easy solution by adding another global variable to track the bytes allocated for the smoke test. I think that should work.

2024-09-10 03:27 UTC, andrewrk requested changes
I think I've addressed your objection in #21370. After those changes, you can use `std.testing.allocator` to allocate the input buffer, and free it after the call to `testOne`.

2024-09-11 20:36 UTC, AdamGoertz commented
Sounds good! Once that lands I'll take another look 👍

2024-09-15 03:31 UTC, AdamGoertz commented
Looks like the updated version is now green 👍🏻

2025-09-19 19:34 UTC, closed without merging

2025-09-19 19:34 UTC, AdamGoertz commented
Going to close this given that #23416 is merged. I think things have changed enough that it will need to be mostly re-implemented.