libfuzzer: Track the rate of fuzzing in cycles/s.
ziglang/zig pull request #21025
Opened 2024-08-11 04:59 UTC by gcoakes

As libfuzzer develops or as users design their own fuzz tests which use libfuzzer, it will be essential to understand the performance impact of changes. This change tracks the rate of execution in terms of cycles per second and updates the UI at most every second.

2024-08-25 18:52 UTC, ProkopRandacek commented
This statistic can be entierly calculated on the webui instead of calculating it in the fuzz process if you make the webserver send periodic updates instead of only on new unique input like it is now.

2024-08-29 22:48 UTC, andrewrk requested changes
Agreed, it should be calculated client side.

2024-09-07 04:35 UTC, gcoakes commented
@andrewrk, I think I've resolved the requested changes. I found a small bug while working on that and fixed it with 75ce2c3. That bug caused changes in `std/build/Fuzz/abi.zig` to be ignored regardless of `--zig-lib-dir` option.

2024-09-10 03:14 UTC, andrewrk requested changes

2024-09-10 03:14 UTC, andrewrk commented on lib/std/Build/Fuzz/WebServer.zig
> +            .cycles_per_second = cycles_per_second,
it should be calculated *client side*.

the only additional thing that needs to be sent by the server is:
 * what time the server thinks it currently is
 * what time according to the server fuzzing started

then the client can do the calculation based on what time it is currently and the number of runs.

2024-09-12 06:41 UTC, closed without merging