add an error for stack allocations in naked functions
ziglang/zig pull request #21082
Opened 2024-08-15 04:24 UTC by Rexicon226

closes #72

2024-08-15 22:45 UTC, andrewrk requested changes
The error message shouldn't mention the stack, only the language rule. Pointing at the type is a bit weird. Pointing at the keyword or name is OK.

2024-08-15 22:45 UTC, andrewrk commented on test/cases/compile_errors/stack_usage_in_naked_function.zig
> +// :23:12: error: no stack frame in naked functions
```suggestion
// :2:5: error: local variable in naked function
// :10:5: error: local variable in naked function
// :23:5: error: local variable in naked function
```

2024-08-15 23:01 UTC, zeroZshadow commented
Will this error also trigger for usage of `var` in an `inline` function that is called inside a `.Naked` function?

2024-08-15 23:44 UTC, andrewrk commented
A good question that should be answered with a few more lines in the test case.

2024-08-16 16:41 UTC, andrewrk commented
Thanks!

2024-08-16 16:41 UTC, merged