Build/Options: fix for struct array/slice and optional struct options
ziglang/zig pull request #21122
Opened 2024-08-18 07:55 UTC by tw4452852

2024-08-18 09:12 UTC, Vexu commented
This looks like it fixes #19656 and #19594, can you confirm?

2024-08-19 00:35 UTC, tw4452852 commented
@Vexu Yes, I confirmed that both of issues can be fixed by this PR.

2024-08-27 03:34 UTC, tw4452852 commented
Any feedback about this PR?

2025-02-10 20:22 UTC, Reokodoku commented
Also, there are optional enums that doesn't work. This patch should work (+ some test):
```diff
diff --git a/lib/std/Build/Step/Options.zig b/lib/std/Build/Step/Options.zig
index 8348d74..e05255c 100644
--- a/lib/std/Build/Step/Options.zig
+++ b/lib/std/Build/Step/Options.zig
@@ -272,12 +272,17 @@ fn printType(options: *Options, out: anytype, comptime T: type, value: T, indent
             try printEnum(options, out, T, info, indent);
 
             if (name) |some| {
-                try out.print("pub const {}: {} = .{p_};\n", .{
+                try out.print("pub const {}: {} = ", .{
                     std.zig.fmtId(some),
                     std.zig.fmtId(@typeName(T)),
-                    std.zig.fmtId(@tagName(value)),
                 });
             }
+
+            if (indent == 0)
+                try out.print(".{p_};\n", .{std.zig.fmtId(@tagName(value))})
+            else
+                try out.print(".{p_},\n", .{std.zig.fmtId(@tagName(value))});
+
             return;
         },
         .@"struct" => |info| {
```

2025-02-22 23:43 UTC, andrewrk requested changes

2025-02-22 23:43 UTC, andrewrk commented on lib/std/Build/Step/Options.zig
> +                if (std.mem.containsAtLeast(u8, type_name, 1, ".")) {
sorry, I won't merge any patch that depends on searching type names for substrings.

2026-01-05 18:38 UTC, closed without merging