doc: clarify build.zig.zon urls should point to immutable data
ziglang/zig pull request #21120
Opened 2024-08-18 01:32 UTC by marler8997

There's been some proliferation of dependency URLs that reference mutable data such as links to git branches that can change.  This has resulted in broken projects, i.e.

* https://github.com/RohanVashisht1234/raylib_rain_train/blob/9eef9de94c511f2eb4fe5db1d6abd574ee245c9b/build.zig.zon
* https://github.com/rcmagic/ZigFightingGame/commit/4b64353e9c69de0fa2eb87fa9c3a3da76a8a3e7b

There's also disagreement about whether it's fine for URL's to point to git branches, i.e.

https://github.com/Not-Nik/raylib-zig/pull/130

This updates the docs to clarify that urls should reference immutable data.

2024-09-29 01:06 UTC, marler8997 commented
Another victim: https://github.com/RaidoAun/TowerDefense-v2/commit/706052510c326da6554870e42a8feec32b6d1651

Oh the humanity...how many more need to suffer till we do something about it? :)

2024-09-29 07:53 UTC, mocompute commented
Just a thought, would it help to clarify whether this is a suggestion or an invariant that will break Zig build? I ask because I frequently follow a branch of a dependent package during development. If Zig build were to somehow stop working in this scenario, it would be extremely inconvenient.

I might suggest this wording instead:

`Best practice is to refer to tags or commit hashes rather than branch names which may change unpredictably depending on when this file is processed.`

2024-09-29 13:53 UTC, marler8997 commented
Hmmm...I wouldn't say the behavior is "unpredictable", it's very predictable.  What do you think of this wording?

> The URL should always result in the same content, avoid URL's that
reference content that can change such as git branch names. If the contents
of a URL change, zig will no longer be able to fetch that package, but,
users who already downloaded the old version matching the hash will continue
to be able to build resulting in differing behavior depending on the state
of the cache.

2024-09-29 22:11 UTC, mocompute commented
How about this: advice, then first-order consequence:

Best practice is to refer to tags or commit hashes, rather than branch names which may change depending on when the URL is fetched.

If the contents of an archive change, the Zig cache will be out of sync, or a hash mismatch will occur when initially fetching. 

I think file comments should be brief, but this is slightly complicated, and still a bit too long in my opinion.

2024-09-30 13:52 UTC, marler8997 commented
> Best practice is to refer to tags or commit hashes, rather than branch names which may change depending on when the URL is fetched.

I don't love this wording as I think "Best practice" gives the wrong impression.  It makes it seems like it's ok to do, just discouraged, but, a zon file that does this is broken.  When the content changes, the dependency will no longer be able to be fetched/resolved.  How about:

The URL must always result in the same content.  Avoid URL's that reference content that can change such as git branch names. If the contents of a URL change, it will no longer match the associated hash and zig will no longer be able to fetch/resolve it.

2024-10-01 00:07 UTC, mocompute commented
Perfect! For grammar, can I just suggest replacing a comma with a semicolon and removing a possessive? Yes I was a grammar nerd sorry :-)

URLs must reference immutable content. Avoid URLs that reference git branches; use commits or tags instead. If the contents of a URL change, it will no longer match the associated hash and zig will no longer be able to fetch it.

2024-10-02 10:49 UTC, marler8997 commented
Cool thanks for the suggestions, final revision is improved IMO.

2024-10-04 22:18 UTC, andrewrk requested changes
Also need to edit lib/init/build.zig.zon

2024-10-04 22:18 UTC, andrewrk commented on doc/build.zig.zon.md
> +it.
Be descriptive not prescriptive. Just explain what happens if a URL changes.

2024-10-04 22:19 UTC, andrewrk commented
> There's also disagreement about whether it's fine for URL's to point to git branches, i.e.

I don't see any disagreement there? it's pretty obvious what you're supposed to do given that it completely doesn't work if you don't do it...

2024-10-05 13:28 UTC, marler8997 commented
> Be descriptive not prescriptive. Just explain what happens if a URL changes.

I like this convention, thanks for the clarification.  I've reworded it to just this:

"If the contents of a URL change this will result in a hash mismatch which will prevent zig from using it."

Also updated `lib/init/build.zig.zon` with the same change.

2024-12-21 20:59 UTC, marler8997 commented
The scourge continues to spread like an infectious disease...just saw a new victim this morning: https://github.com/zadockmaloba/znake

2024-12-21 23:23 UTC, merged

2024-12-21 23:24 UTC, andrewrk commented
How does it spread? It's self-annihilating. Are people getting burned and then continuing to do it?

2024-12-22 06:53 UTC, marler8997 commented
I don't think so. I think it was just spreading because there can be an indefinite delay between being infected and becoming symptomatic. On top of that the code was left for others to copy for many months as well. Fascinating how I ended up see this same issue resurface from the same source in multiple repositories over many months. I hate to see it though as it hurts the zig build brand when things inevitably break.