Dwarf: implement .eh_frame
ziglang/zig pull request #21210
Opened 2024-08-26 20:39 UTC by jacobly0

2024-08-26 21:09 UTC, kubkon requested changes
Perhaps it would make sense to land `elf-incr` branch first in its current state since it cleans up a lot of things in the ELF linker, and then rebase this branch on top? Next, `initSyntheticSections` really should not be used in `initMetadata` - happy to clean that one up if you want. Finally, not a blocker but as it currently stands, `.eh_frame` generated with `ZigObject` will not have its CIEs deduped across all input object files - not a biggie, but something to remember about. I would also like to have it tested with the linker - emit `.eh_frame` section as part of `.o` file and then link it back into an executable.

2024-08-26 21:09 UTC, kubkon commented on src/link/Elf.zig
> +                }.addSectionSymbol;
We already have this logic defined and used in `initMetadata`. Again, we should not call `initSyntheticSections` from `initMetadata`.

2024-08-26 21:09 UTC, kubkon commented on src/link/Elf/relocatable.zig
> +    const target = comp.root_mod.resolved_target.result;
```suggestion
    const target = elf_file.getTarget();
```

2024-08-27 03:57 UTC, jacobly0 commented
> Finally, not a blocker but as it currently stands, `.eh_frame` generated with `ZigObject` will not have its CIEs deduped across all input object files - not a biggie, but something to remember about. I would also like to have it tested with the linker - emit `.eh_frame` section as part of `.o` file and then link it back into an executable.

A CIE is like 24 bytes, so it's definitely not worth deduping the two extra CIE per module in incremental mode (the only use case I'm working towards right now), especially given all the padding that already exists.  The key feature that would be useful is the ability to generate a `.eh_frame_hdr` in non-incremental mode, which I believe would come for free when CIE deduping is integrated.

2024-08-27 09:33 UTC, kubkon approved these changes
Looks great!

2024-08-27 18:55 UTC, mlugg approved these changes

2024-08-27 19:06 UTC, merged