Support stringifying non-exhaustive enum to json
ziglang/zig pull request #21228
Opened 2024-08-28 07:55 UTC by pfgithub

```zig
test "stringify non-exhaustive enum" {
    const E = enum(u8) {
        foo = 0,
        _,
    };
    try testStringify("\"foo\"", E.foo, .{});
    try testStringify("1", @as(E, @enumFromInt(1)), .{});
}
```

It stringifies the named ones to strings and unnamed ones to a number, which parses just fine into an enum already.

I'm not sure if there's a better way to detect if the active field is unnamed - `if` doesn't support both `_` and `else`, and tagName doesn't return an optional for non-exhaustive enums.

2024-08-30 00:05 UTC, thejoshwolfe requested changes
great idea! and thanks for the test! just missing documentation. The other suggestion is optional.

2024-08-30 00:05 UTC, thejoshwolfe commented on lib/std/json/stringify.zig
> +                            return self.valueDone();
there's a precedent to unwrap a type and then recurse for the underlying type like this:
```suggestion
                            return self.write(@intFromEnum(value));
```

2024-09-07 04:30 UTC, pfgithub commented
Added to the documentation comment, switched to recurse instead of writing raw text, and updated for the lowercase std.builtin.Type change

2024-09-07 15:06 UTC, thejoshwolfe approved these changes
thanks!

2024-09-07 15:06 UTC, merged