Add some stage1 tests
ziglang/zig pull request #21340
Opened 2024-09-08 04:41 UTC by RetroDev256

I am trying to learn how the Zig source code is structured. Is this right?

If so, this should close:
#7724
#7841
#7841
#8146
#7370
#7789

2024-09-08 05:09 UTC, Rexicon226 requested changes
Love seeing more testing coverage, just have a couple of nitpicks :). Also please note that `stage1` does not exist anymore. These are tests for `stage2`.

A driving goal in these tests is to reproduce the issue in a succinct fashion that depends on other things workings as little as possible.

(also disclaimer that I'm not a core member, just a motivated contributor)

2024-09-08 05:09 UTC, Rexicon226 commented on test/cases/compile_errors/getting_pointer_to_bit-aligned_field_sized_greater_8191.zig
> +    _ = &ptr;
Don't need `&` here, it's a bit of a smell nowadays.

2024-09-08 05:56 UTC, nektro commented
note the current description as is wouldnt close any of the issues listed 
you have to do `Closes #xxx` for each line

2024-09-08 21:42 UTC, RetroDev256 commented
![image](https://github.com/user-attachments/assets/ad326a6e-d6fc-4d2c-823e-f1114943c817)

How do I write a test which may contain the path of the cache? Is there a way in the test manifest to say that the error should/should not include a string? (but not *be* the string?)

2024-09-08 21:43 UTC, Rexicon226 commented
The problem there isn't that it's in the cache, it's that you're using `example.a` instead of `tmp.a`.

2024-09-09 03:54 UTC, RetroDev256 commented
Ok This is now fully ready for review. All the other stage1 issues (as far as I could see) are not easy to test (they link to an entire project zip, or are dealing with things not directly related to stage1, etc.)

I don't expect to add any more test cases to this, but will keep it rebased (and try to fix issues) until it can be merged.

2024-09-09 17:10 UTC, closed without merging