fix: support error set values with @errorCast
ziglang/zig pull request #21494
Opened 2024-09-23 06:48 UTC by WillLillis

It looks like `zirErrorCast` attempts to complete its cast if the destination operand is an error union, treating the source as an error union even if it's an error set value:

https://github.com/ziglang/zig/blob/d83a3f1746c81026d1cf0244156513c9b5a2a9f6/src/Sema.zig#L23606-L23607

Checking if the source type tag is also an error union avoids this, handling it instead in the check's `else` block:

https://github.com/ziglang/zig/blob/d83a3f1746c81026d1cf0244156513c9b5a2a9f6/src/Sema.zig#L23621-L23625

As far as I can tell, adding this additional `base_operand_ty.zigTypeTag(zcu) == .error_union` condition fixes the issue.

Running `zig build` on  the example from #20169 used to give the following error:

```shell
src/main.zig:21:41: error: expected error union type, found 'error{Foo,Bar}'
    return bar() catch |err| @errorCast(err);
                                        ^~~
```

but now compiles successfully.

Closes #20169

2024-09-23 19:56 UTC, andrewrk requested changes
Could you please also add a test case for when the destination type is an error union with a non-void payload type? It looks like that will not be handled correctly here.

2024-09-25 01:19 UTC, WillLillis commented
> Could you please also add a test case for when the destination type is an error union with a non-void payload type? It looks like that will not be handled correctly here.

You're right! I added the test. I'm a little out of depth here, but I think I found a fix.

2024-10-04 23:23 UTC, WillLillis commented
I've spent an embarrassing number of hours on this without any making any progress or new insights. I'll keep working on it locally, but am going to close down this PR for the time being to avoid wasting any of the maintainers' time.

2024-10-04 23:23 UTC, closed without merging

2024-10-04 23:32 UTC, andrewrk commented
Well, I'm sorry to hear that. Thanks for giving it a try.