build: protect from adding the same dependency multiple times
ziglang/zig pull request #21546
Opened 2024-09-29 14:10 UTC by marler8997

In experimenting with the build system I discovered there were some places where the same step was being added as a dependency multiple times. The implementation currently uses an ArrayList and doesn't prevent the same entry from being added. For the same reason that Zig makes unused variables an error, I've made a change that makes duplicate dependencies an error by default. `Step.dependOn` will now panic if the same dependency is added multiple times. In cases where its unclear if a dependency may have already been added, like `LazyPath.addStepDependencies`, build code can call `Step.dependOnIfNotAlready` to avoid this panic.

2024-09-29 14:48 UTC, mlugg commented
I don't see any value in this change. Could you expand on "for the same reason that Zig makes unused variables an error"?

2024-09-29 15:00 UTC, marler8997 commented
Unused variables are a signal that the code might contain bugs/logic errors.  Same idea, adding the same dependency multiple times is a signal that the build might contain bugs/logic errors.

2024-10-04 22:57 UTC, andrewrk requested changes
I like it. I predict it will help users understand the build system and its API more.

At first I was going to suggest making it non-breaking for 1 release cycle, however, given that doing the upgrade is backwards-compatible, I think it is not necessary. Packages which remove redundant dependency edges will continue to work correctly with older Zig versions.

Let's workshop those names, however. "dependOnIfNotAlready" has too much English grammar in it. I think "dependOnRelaxed" or "dependOnEnsure" would be better. It's nice when related functions like this share the same prefix and only 1 word suffix different.

There also needs to be a `assertAlreadyDependsOn` to go along with this, for when users want to check their assumptions, but not necessarily create a dependency edge. This would be particularly useful for checking that a recursive dependency exists. That does not block this PR.

In the failure message, please make it additionally do the following:
* Explain the 2 options to solve the problem.
* Show the stack trace where the first edge was created.

2024-10-05 14:02 UTC, marler8997 commented
Either name works for me, another similar option that comes to mind is `dependOnConfirm`.

Another option to consider is not adding this function and the `assertAlreadyDependsOn` function, but adding a `dependsOn` function instead.

2025-02-23 07:49 UTC, closed without merging

2025-02-24 15:35 UTC, marler8997 commented
Why was this closed? Was waiting on you or someone to suggest which direction we should go.  Do we want a `dependOnEnsure`/`assertDependsOn`...or do we want to add a `dependsOn`.  Here's how the two usages would differ:

1. Make `a` depend on `b` if not already
```zig
// direction 1
a.dependsOnEnsure(b)

// direction 2 equivalent
if (!a.dependsOn(b)) {
    a.dependOn(ab);
}
```

2. Assert `a` already depends on `b`
```zig
// direction 1
a.assertDependsOn(b);

// direction 2 equivalent
assert(a.dependsOn(b));
```

2025-02-24 20:51 UTC, andrewrk commented
I'm sorry, I didn't realize you were waiting for me to provide guidance. If you reopen it and make the question more clear, I will look again.

2025-02-25 16:13 UTC, marler8997 commented
This PR added a new `dependOnEnsure` function and you suggested we'd also need an `assertDependsOn` function. I proposed that instead of adding these two functions, we could add a single `dependsOn` function which would return a bool indicating whether a step depends on another step.  With this one function you can derive the other two functions like so:

```zig
// dependsOnEnsure equivalent
if (!a.dependsOn(b)) a.dependOn(b);

// assertDependsOn equivalent
assert(a.dependsOn(b));
```

However, now that I'm writing this, I'm thinking you may not have noticed the "s" in the `dependsOn` function I suggested which would have made my suggestion incoherent.  I'm now thinking it would be easy to mistake these two functions for each other so I am withdrawing this suggestion.  I other words, I think you've inadvertently answered my question :)

It looks like GitHub doesn't give me an option to reopen the PR, I can create a new one when I get a chance to finish the changes with your suggestions.