`link.Elf`: Fix page size calculation for more architectures.
ziglang/zig pull request #21612
Opened 2024-10-06 12:08 UTC by alexrp

Sourced from binutils/bfd (`ELF_MAXPAGESIZE`).

[LLD differs on some of these](https://github.com/search?q=repo%3Allvm%2Fllvm-project+path%3Alld%2FELF+defaultMaxPageSize&type=code), and [mold differs further](https://github.com/search?q=repo%3Arui314%2Fmold%20path%3Aelf%20page_size&type=code). I don't really know what to make of that. Following binutils seems safest...?

2024-10-06 19:50 UTC, kubkon requested changes
Looks good. I just have one minor nit: what is a common page size? To the best of knowledge that doesn't exist. There is however the concept of a user-specified max page size tho.

2024-10-06 19:50 UTC, kubkon commented on src/link/Elf.zig
> +    // be confused with the common page size, which is the page size that's used in practice on most
```suggestion
    // be confused with the user-specified max page size.
```

2024-10-06 19:52 UTC, alexrp commented
> Looks good. I just have one minor nit: what is a common page size? To the best of knowledge that doesn't exist. There is however the concept of a user-specified max page size tho.

`-z common-page-size` vs `-z max-page-size` (`ELF_COMMONPAGESIZE` vs `ELF_MAXPAGESIZE`).

2024-10-06 21:07 UTC, kubkon commented
> > Looks good. I just have one minor nit: what is a common page size? To the best of knowledge that doesn't exist. There is however the concept of a user-specified max page size tho.
> 
> 
> 
> `-z common-page-size` vs `-z max-page-size` (`ELF_COMMONPAGESIZE` vs `ELF_MAXPAGESIZE`).

I would trust Rui on this one https://github.com/rui314/mold/blob/3441cbb636d742a632aeb3c1e35b0fbc77ecc846/src/cmdline.cc#L188

2024-10-06 21:14 UTC, alexrp commented
`common-page-size` is parsed and used by both lld and GNU ld, FWIW. I don't really have a strong preference on whether we support it; my reason for adding the comment was that the old sparc64 value that I replaced in this PR was set to what it was exactly because whoever wrote it confused common vs max page size (LLD has common page size for sparc64 set to `0x2000`).

2024-10-06 21:24 UTC, kubkon commented
> `common-page-size` is parsed and used by both lld and GNU ld, FWIW. I don't really have a strong preference on whether we support it; my reason for adding the comment was that the old sparc64 value that I replaced in this PR was set to what it was exactly because whoever wrote it confused common vs max page size (LLD has common page size for sparc64 set to `0x2000`).

How does lld then decide which value is the default in absence of either flag passed explicitly by the user? IMHO max page size dictated by the arch and os should be the default - common page size sounds like a poor attempt at reducing the binary size and hoping the target os has page size set at at least the common value.

2024-10-06 21:45 UTC, alexrp commented
There's this comment:

https://github.com/llvm/llvm-project/blob/7f65377880ce6a0e5eaa4cb2591b86b8c8a24ee6/lld/ELF/Driver.cpp#L3137-L3142

And these actual uses:

https://github.com/llvm/llvm-project/blob/7f65377880ce6a0e5eaa4cb2591b86b8c8a24ee6/lld/ELF/ScriptParser.cpp#L1327-L1345
https://github.com/llvm/llvm-project/blob/7f65377880ce6a0e5eaa4cb2591b86b8c8a24ee6/lld/ELF/LinkerScript.cpp#L1238-L1241

2024-10-07 05:03 UTC, kubkon approved these changes

2024-10-07 05:04 UTC, merged