Sema: implement @splat for arrays
ziglang/zig pull request #21635
Opened 2024-10-08 22:36 UTC by mlugg

Resolves: #20433

2024-10-08 23:22 UTC, Rexicon226 approved these changes

2024-10-08 23:22 UTC, Rexicon226 commented on src/Sema.zig
> +        else => return sema.fail(block, block.nodeOffset(un_node.src_node), "expected vector type, found '{}'", .{vec_ty.fmt(pt)}),
```suggestion
        else => return sema.fail(block, block.nodeOffset(un_node.src_node), "expected array or vector type, found '{}'", .{vec_ty.fmt(pt)}),
```
did you mean?

2024-10-08 23:28 UTC, Rexicon226 commented on src/Sema.zig
> +                        const elems = try sema.arena.alloc(InternPool.Index, len + 1);
```suggestion
                        const elems = try sema.arena.alloc(InternPool.Index, @intCast(len + 1));
```
Maybe `arrayLen` should return `usize`? I've had to intcast the length from it so many times. vectors take a `u32` len fwiw.

2024-10-09 19:48 UTC, Rexicon226 requested changes

2024-10-09 19:48 UTC, Rexicon226 commented on src/Sema.zig
> +                        elems[len] = sentinel.toIntern();
these need to be `@intCast`ed, prob just cast the `const len = `

2024-10-09 19:48 UTC, Rexicon226 commented on src/Sema.zig
> +            @memset(elems[0..len], scalar);
these two will also need to be int casted. ditto above.

2024-10-10 10:22 UTC, merged

2024-10-10 22:29 UTC, andrewrk commented
Release notes please!

2024-10-17 08:40 UTC, mlugg commented
## Release Notes

Zig 0.14.0 expands the `@splat` builtin to apply not only to vectors, but to arrays. This is useful when default-initializing an array to a constant value. For instance, in conjunction with \[Decl Literals\}\(link to relevent release notes section\), we can elegantly initialize an array of "color" values:
```zig
const Rgba = struct {
    r: u8,
    b: u8,
    g: u8,
    a: u8,
    pub const black: Rgba = .{ .r = 0, .g = 0, .b = 0, .a = 255 };
};
var pixels: [width][height]Rgba = @splat(@splat(.black));
```
The operand may be comptime-known or runtime-known. In addition, this builtin can also be used to initialize sentinel-terminated arrays.
```zig
const std = @import("std");
const assert = std.debug.assert;
const expect = std.testing.expect;
test "initialize sentinel-terminated array" {
    // the sentinel does not need to match the value 
    const arr: [2:0]u8 = @splat(10);
    try expect(arr[0] == 10);
    try expect(arr[1] == 10);
    try expect(arr[2] == 0);
}
test "initialize runtime array" {
    var runtime_known: u8 = undefined;
    runtime_known = 123;
    // the operand can be runtime-known, giving a runtime-known array
    const arr: [2]u8 = @splat(runtime_known);
    try expect(arr[0] == 123);
    try expect(arr[1] == 123);
}
test "initialize zero-length sentinel-terminated array" {
    var runtime_known: u8 = undefined;
    runtime_known = 123;
    const arr: [0:10]u8 = @splat(runtime_known);
    // the operand was runtime-known, but since the array length was zero, the result is comptime-known
    comptime assert(arr[0] == 10);
}
```