Compilation: rename totalErrorCount to anyErrors and check again after flush
ziglang/zig pull request #21662
Opened 2024-10-10 20:57 UTC by kubkon

We need to check for linker errors after `flush` in whole cache mode so that we do not commit the cache manifest in case there were any linker errors reported.

Closes #21637

2024-10-10 21:03 UTC, andrewrk requested changes

2024-10-10 21:03 UTC, andrewrk commented on src/Compilation.zig
> +        zcu_has_errors;
by putting this at the end you force the other logic to run when an early return would make more sense

2024-10-10 21:03 UTC, andrewrk commented on src/Compilation.zig
> +        comp.link_error_flags.no_entry_point_found or
should instead bit cast to int and check for nonzero (this would fix the bug here which is not noticing the missing_libc field)

2024-10-10 21:03 UTC, andrewrk commented on src/Compilation.zig
> +            (comp.incremental and zcu.transitive_failed_analysis.values().len > 0);
no need to check comp.incremental

2024-10-10 22:12 UTC, mlugg commented
The implementation of `anyErrors` is wrong under incremental compilation; I expect this PR to fail some of the incremental test cases, in particular `unreferenced_error`. The reason this implementation is incorrect is because `failed_analysis` (and `transitive_failed_analysis`) may contain error messages for `AnalUnit`s which were analyzed on previous updates resulting in compile errors, but which are no longer referenced (i.e. all references to them were removed). To handle these cases, if there are any compile errors, `getAllErrorsAlloc` does a graph traversal starting from roots of analysis to figure out which units are referenced, and ignore the compile errors for those which aren't -- take a look at the calls to `zcu.resolveReferences()` in `getAllErrorsAlloc`.

That's why this function was implemented in terms of `getAllErrorsAlloc`; it needs to allocate anyway for `resolveReferences`, so it made sense to just simplify the implementation.

(Note that currently, the return value of `resolveReferences` isn't memoized between different calls to `getAllErrorsAlloc`; I'm planning to fix that by memoizing it on `Zcu`. I've added that to #21165.)

2024-10-10 22:21 UTC, andrewrk commented
This is the implementation I tossed into #21654 for the time being:
```zig
fn anyErrors(comp: *Compilation) bool {
    return (totalErrorCount(comp) catch return true) != 0;
}
```

2024-10-11 03:15 UTC, kubkon commented
Given what @mlugg said, should we revert back to what it was then? I can also close it in favour of landing it in #21654 too. Thoughts?

2024-10-11 03:37 UTC, andrewrk commented
Sure, I think the commit in #21654 is good enough to close the issue. Thanks for diagnosing the problem though.

2024-10-11 03:37 UTC, closed without merging

2024-10-11 04:56 UTC, kubkon commented
No problem!