Bug fixed. #21668
ziglang/zig pull request #21669
Opened 2024-10-11 05:19 UTC by dravenk

2024-10-11 17:31 UTC, andrewrk commented on lib/std/Target/Query.zig
> +        if (os == .linux and self.abi.?.isAndroid()) return true;
Please avoid `.?` syntax altogether in this case.

2024-10-11 17:50 UTC, dravenk commented on lib/std/Target/Query.zig
> +        if (os == .linux and self.abi.?.isAndroid()) return true;
> Please avoid `.?` syntax altogether in this case.
Refer to system.zig, completely ignore.? syntax.
Reference: https://github.com/ziglang/zig/blob/13fb68c064900cee67583e603d8c2acf41770663/lib/std/zig/system.zig#L976

2024-10-12 09:16 UTC, alexrp approved these changes

2024-10-12 09:20 UTC, andrewrk requested changes

2024-10-12 09:28 UTC, alexrp commented
This isn't strictly related to this PR as it's just restoring existing behavior, but I don't understand why Android actually gets special-cased here. The idea seems to be that you can do `CC=/path/to/android/sdk/cc zig libc -target arm-linux-androideabi` or similar. But why is Android special in this regard? Surely I could just as well do `CC=mips64-linux-gnuabi64-gcc zig libc -target mips64-linux-gnuabi64`? cc @mikdusan

2024-10-12 20:21 UTC, mikdusan commented
@alexrp I added this a while back leaning towards a curated approach of non-native libc detection and so checks were added for the only 2 platforms I tested against: various apple SDKs and android NDK. Also this impl doesn't explicitly allow NDK on macos or windows hosts, and although rare, the NDKs are available.

What I was happy about is that a garbage libc.txt was avoided. But if we take out `canDetectLibC()` (non-native logic), everything just falls through to `LibCInstallation.findNative()` and useless libc.txt is generated, or a very unhelpful error is given such as `LibCRuntimeNotFound` in case of `zig libc -target aarch64-linux-android` when NOT setting CC to the correct NDK pathname. We were getting issues raised against this.

In a better impl, what I'd like to see is some tech where libc.txt paths are fuzzy-validated.

To be clear, I think it is important to support exactly the use case pattern you listed (general cross compiler pathname) and it could very well be the curated approach is at odds with that goal.

2024-10-12 23:15 UTC, merged