`wasm2c`: Add big endian support.
ziglang/zig pull request #21693
Opened 2024-10-14 00:36 UTC by alexrp

I took a slightly unconventional approach to detecting endianness here. We have no compiler/platform-specific preprocessor checks in the stage1 C code today, and I think that's a property worth maintaining. The downside is that the check only gets removed in `-O1` and above (including `-Os`), but as the `wasm2c` output compiled at `-O0` hits an ~instant stack overflow, I don't get the impression that this is a scenario we care about anyway.

With this patch, I'm able to successfully run `./zig-wasm2c ../stage1/zig1.wasm zig1.c && s390x-linux-gnu-gcc -std=c99 -Os zig1.c ../stage1/wasi.c -o zig1 && qemu-s390x ../lib zig1 build-exe -ofmt=c -lc -OReleaseSmall ... -femit-bin=zig2.c`.

2024-10-14 01:52 UTC, andrewrk requested changes
since the same computer will be generating this C code and running it, it would be better to detect endianness and then generate code that does not branch. 

in fact that seems to be how @jacobly0 set you up, all you had to do was one detection and populate a bool... why not just do that?

2024-10-14 02:09 UTC, alexrp commented
It just seemed like a bit of a shame to generate target-specific C code when doing the check in the generated code like this means that the output is target-agnostic.

But if that's a property we don't care about, then sure, I can move the check into the generator.

2024-10-14 08:47 UTC, andrewrk commented
The *only* goal of that code is to bootstrap on the current host, as fast as possible.

2024-10-14 09:10 UTC, alexrp commented
Ok. Any preference for what to do about `wasi.c`? My inclination would be to have it call into the load/store helpers generated by `wasm2c` if we do the detection in the generator.

2024-10-15 17:22 UTC, alexrp commented
Ok, switched the approach to checking in the generator.

> It just seemed like a bit of a shame to generate target-specific C code when doing the check in the generated code like this means that the output is target-agnostic.

One additional, minor point here is that, while hacking on `wasm2c`, it's just convenient to know that it doesn't matter what target the generator itself is built for, as it'll produce usable code for any target. It became a bit more convoluted when I had to build `zig-wasm2c` for s390x and run it under QEMU too.

2024-10-15 18:57 UTC, andrewrk commented
How about making it an overridable preprocessor define?

2024-10-15 19:46 UTC, alexrp commented
> How about making it an overridable preprocessor define?

How about giving `wasm2c` an optional third command line argument to specify endianness? I think that's a tiny bit nicer since it maintains the ability to just invoke `ninja zig-wasm2c` to build it.

2024-10-15 19:49 UTC, andrewrk commented
Seems fine to me. My main protest is that duration of the bootstrap is the top priority.

2024-10-15 20:54 UTC, alexrp commented
Ok, done.

2024-10-28 16:52 UTC, alexrp commented
Going to merge since all concerns should be addressed. If there are any other issues, I'll address them in a follow-up PR.

2024-10-28 16:52 UTC, merged