Add `.unpack = false` and --no-unpack to build.zig.zon and zig fetch
ziglang/zig pull request #22042
Opened 2024-11-21 05:34 UTC by marler8997

closes #17895

Enhances zig with the ability to fetch a dependency of any file type.

2024-11-22 02:23 UTC, marler8997 commented on test/standalone/fetch/example/build.zig
> +        dep.path("example_dep_file.txt"),
I went with the solution that I didn't have to add any code for as the existing code paths already supported `dep.path("file.txt")`, willing to add extra code to support a special mapping if we feel it's advantageous.

2024-11-22 02:25 UTC, marler8997 commented on src/Package/Manifest.zig
> +                if (dep.unpack) return fail(p, main_tokens[field_init], "unpack cannot be set to true, omit it instead", .{});
I think anytime you can decrease the "surface area" of an interface it's a win, failing to do so does more harm than people realize.

2024-11-22 02:26 UTC, marler8997 commented on src/Package/Fetch.zig
> +                f.parent_package_root, path_relative, @errorName(err),
I've pushed a new iteration that uses an absolute file path instead.

2025-02-22 21:57 UTC, andrewrk requested changes
Thanks for working on this. It looks nearly ready to land, however, I have identified an API issue that is worth addressing beforehand.

2025-02-28 16:09 UTC, marler8997 commented
I've updated the API according to the suggestions.  Since we've moved from `.unpack = false` to an optional path, I also renamed the field to `no_unpack` so now we have:
```zig
.no_unpack = "foo/bar.zip",
```
Let me know if you think there's a better name.

2026-09-19 06:47 UTC, alexrp commented
https://codeberg.org/ziglang/zig/pulls/36226

2026-09-19 06:47 UTC, closed without merging