compiler: Implement `@disableIntrinsics()` builtin function.
ziglang/zig pull request #22154
Opened 2024-12-05 15:27 UTC by alexrp

This implements #22110, and in a way that also satisfies the use case for #21833. If accepted, this would therefore supersede #21900.

I won't add any usage of this builtin to compiler-rt and std yet as this will require a `zig1.wasm` update.

Closes #21833.
Closes #22110.

2024-12-06 00:52 UTC, wooster0 commented
Might be nice to add docs for this in the langref as well, along with disableInstrumentation maybe? (#21424)

2024-12-06 00:57 UTC, alexrp commented
Will write docs if/when it's approved.

2025-01-05 17:11 UTC, alexrp commented
Will resolve conflicts if/when this is approved.

2025-02-23 01:27 UTC, andrewrk requested changes
Looks good other than this strange snippet I see here

2025-02-23 01:27 UTC, andrewrk commented on src/InternPool.zig
> +    };
not sure what's going on here, is this a merge conflict?

2025-02-23 01:36 UTC, alexrp commented on src/InternPool.zig
> +    };
Huh, yeah, looks like I messed up a rebase at some point.

2025-02-23 03:10 UTC, alexrp commented
@andrewrk do you have any thoughts on nuking `-fno-builtin` (a rather blunt instrument) in favor of requiring explicit usage of `@disableIntrinsics()` where necessary? (Would be follow-up work since it needs a `zig1.wasm` update.)

2025-02-23 03:23 UTC, andrewrk commented
Yeah I'm in favor

2025-02-23 03:36 UTC, andrewrk commented
> @[alexrp](https://github.com/alexrp) alexrp enabled auto-merge 2 minutes ago

you have the patience of a saint

2025-02-23 04:05 UTC, alexrp commented
:angel:

2025-02-24 07:25 UTC, merged