Add branch hint to unlikely branch of `rem_pio2_large`
ziglang/zig pull request #22268
Opened 2024-12-19 06:23 UTC by LiamSwayne

Adds a `@branchHint` to a 1 in 12 branch of the pi/2 remainder calculation.

2024-12-19 06:39 UTC, andrewrk requested changes
does it generate better code? or are you just guessing? commit message does not say

2024-12-19 06:44 UTC, Rexicon226 commented
The codegen does appear to be better, it's now jumping to the unlikely case,
https://zig.godbolt.org/z/h8Kfab1Tf

2024-12-19 07:43 UTC, LiamSwayne commented
In my asm output it has been moved away (https://zig.godbolt.org/z/8eq4bKrfP, LBB0_94), which was the goal, but I haven't run any benches to verify that it's actually beneficial. I'll include a link or asm output diff going forward.

2024-12-23 19:40 UTC, andrewrk commented
Thanks!

2024-12-23 19:41 UTC, merged