Remove strict verifyContext invocation from hash_map implementation.
ziglang/zig pull request #22370
Opened 2024-12-31 05:01 UTC by cdeler

Fixes #19640

In this PR I'm trying to remove the strict verifyContext  from `lib/std/hash_map.zig`

### How I tested locally

(1) I was able to successfully built the minimal viable test sample from the origin ticket https://github.com/ziglang/zig/issues/19640 :
```
➜  build git:(cdeler_strict_verifyContext_HashTable) ./stage4/bin/zig build-exe cdeler_test/test_minimal.zig
➜  build git:(cdeler_strict_verifyContext_HashTable) echo $?
0
```

(2) but without the change (upstream `zig 0.13.0` from HomeBrew) I still have the error:
```
➜  build git:(cdeler_strict_verifyContext_HashTable) zig version
0.13.0
➜  build git:(cdeler_strict_verifyContext_HashTable) zig build-exe cdeler_test/test_minimal.zig
/opt/homebrew/Cellar/zig/0.13.0/lib/zig/std/hash_map.zig:340:13: error: Problems found with hash context type hash_map.StringContext:
                                                                          hash_map.StringContext.hash must be fn (self, []u8) u64
                                                                            but is actually fn (hash_map.StringContext, []const u8) u64
                                                                            Second parameter must be []u8, but is []const u8
                                                                          hash_map.StringContext.eql must be fn (self, []u8, []const u8) bool
                                                                            but is actually fn (hash_map.StringContext, []const u8, []const u8) bool
                                                                            Second parameter must be []u8, but is []const u8
            @compileError("Problems found with hash context type " ++ @typeName(Context) ++ ":" ++ errors);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/homebrew/Cellar/zig/0.13.0/lib/zig/std/hash_map.zig:1174:35: note: called from here
            comptime verifyContext(@TypeOf(ctx), @TypeOf(key), K, Hash, false);
                     ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/homebrew/Cellar/zig/0.13.0/lib/zig/std/hash_map.zig:1337:48: note: called from here
                    const index = self.getIndex(key, key_ctx) orelse return err;
                                  ~~~~~~~~~~~~~^~~~~~~~~~~~~~
referenced by:
    getOrPutAdapted__anon_1630: /opt/homebrew/Cellar/zig/0.13.0/lib/zig/std/hash_map.zig:501:57
    main: cdeler_test/test_minimal.zig:11:45
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```

(3) std-lib test suite for OS X aarch passed:
```
➜  build git:(cdeler_strict_verifyContext_HashTable) ✗ ./stage4/bin/zig build test-std -Dskip-release -Dskip-non-native
➜  build git:(cdeler_strict_verifyContext_HashTable) ✗ echo $?
0
```

2025-01-05 05:09 UTC, andrewrk requested changes
Nice job, almost perfect.

2025-01-05 05:09 UTC, andrewrk commented on lib/std/hash_map.zig
>              const hash = ctx.hash(key);
This will make the compile error from wrong hash function return type much clearer:

```suggestion
            const hash: Hash = ctx.hash(key);
```

2025-01-06 04:56 UTC, cdeler commented
Current progress on the PR:
* I applied the fix suggested by @andrewrk 
* made similar changes in the other touched code areas
* rebased the PR on the ziglang/zig/master@HEAD
* running the std testing ...

Once it's done, I'll update the PR

2025-01-06 05:18 UTC, andrewrk requested changes
Sorry, I noticed one last thing before merge - the `verifyContext` function should be deleted from the file since it is now dead code. It is technically a breaking change since it is marked `pub`, but I suspect nobody has any direct dependencies on it.

2025-01-06 06:17 UTC, cdeler commented
Removed the function (hadn't done it before your comment, because, as you mentioned, it's a breaking change)

2025-01-06 07:41 UTC, andrewrk commented
Thanks!

2025-01-06 13:37 UTC, merged