Implement @Type for Union
ziglang/zig pull request #6172
Opened 2020-08-26 15:38 UTC by tadeokondrak

I hope I didn't break unions...

2020-08-26 16:27 UTC, tadeokondrak commented
Turns out some things in the standard library use TypeInfo.UnionField.enum_field and I'm running into some compiler bugs replacing them

2020-08-26 19:49 UTC, alexnask approved these changes

2020-08-27 12:23 UTC, Vexu requested changes

2020-08-27 12:23 UTC, Vexu commented on src/ir.cpp
> +            ZigValue *layout_value = get_const_field(ira, source_instr->source_node, payload, "layout", 0);
Missing null check.

2020-08-27 12:23 UTC, Vexu commented on src/ir.cpp
> +            ZigType *tag_type = get_const_field_meta_type_optional(ira, source_instr->source_node, payload, "tag_type", 1);
Missing error check: `tag_type != nullptr && type_is_invalid(tag_type)`.

2020-08-27 12:23 UTC, Vexu commented on src/ir.cpp
> +                    "union tag type must be an enum, not %s", type_id_name(tag_type->id)));
```suggestion
                    "expected enum type, found '%s'", type_id_name(tag_type->id)));
```

2020-08-27 12:23 UTC, Vexu commented on src/analyze.cpp
> +            add_node_error(g, decl_node, buf_sprintf("unions must have 1 or more fields"));
This should also be checked for generated unions. Seems to also be missing from enums.

2020-08-27 12:23 UTC, Vexu commented on src/analyze.cpp
> +                if (field_is_opaque_type) {
This should also be checked for generated unions.

2020-09-07 12:24 UTC, tadeokondrak commented
Rebased to fix conflict

2020-09-14 13:43 UTC, merged