std.meta.TrailerFlags: use @Type to improve API
ziglang/zig pull request #6184
Opened 2020-08-27 21:04 UTC by tadeokondrak

- Use an enum of all field names instead of string literals
- Create a struct type with all fields optional instead of relying on
anonymous struct literals

This should provide better type inference, compile errors, and a
(subjectively) cleaner API.

2020-08-27 21:52 UTC, Vexu requested changes
I don't think this makes too big of a difference since it is all checked at compile time anyways, but I do prefer enum literals to strings so I wouldn't mind the change.

This could also give nice completions in editors sometime in the distant future.

2020-08-27 21:52 UTC, Vexu commented on lib/std/meta/trailer_flags.zig
> +            comptime var fields: []const TypeInfo.EnumField = &[_]TypeInfo.EnumField{};
You know the size, just use an array.

2020-08-27 21:52 UTC, Vexu commented on lib/std/meta/trailer_flags.zig
> +            comptime var fields: []const TypeInfo.StructField = &[_]TypeInfo.StructField{};
Same here.

2020-08-27 21:52 UTC, Vexu commented on lib/std/zig/ast.zig
>                  self.trailer_flags.ptrConst(trailers_start, "name_token"),
Missed this one.

2020-08-30 20:54 UTC, andrewrk commented
I'm actually regretting not adding getters now since this will be the second time we break API of Zig AST. Mind adding those in with this, @tadeokondrak? I did it here

https://github.com/ziglang/zig/blob/1bb30c5e228f4a5ebc42cc23e593ebad3bd6dbbe/lib/std/zig/ast.zig#L2675-L2681

but not here

https://github.com/ziglang/zig/blob/1bb30c5e228f4a5ebc42cc23e593ebad3bd6dbbe/lib/std/zig/ast.zig#L1333-L1347

I think we should go ahead and do the industry standard OOP thing in this one case, and make `getTrailer` / `setTrailer` private, and expose getters/setters for every thing that was previously hidden by `getTrailer` / `setTrailer`.

2020-08-31 05:00 UTC, merged