Implement rest of BPF pseudo instructions
ziglang/zig pull request #6265
Opened 2020-09-06 23:24 UTC by mattnite

The opcodes and instructions are listed here:

https://github.com/iovisor/bpf-docs/blob/master/eBPF.md

There's one minor exception and that's because the document doesn't cover one with enough information so I'm saving that for the kernel dive I'm doing later.

2020-09-06 23:41 UTC, daurnimator requested changes
Looks good :)

2020-09-06 23:41 UTC, daurnimator commented on lib/std/os/linux/bpf.zig
> +const builtin = @import("builtin");
use `std.builtin` instead.

2020-09-07 00:11 UTC, daurnimator approved these changes

2020-09-07 19:39 UTC, andrewrk approved these changes

2020-09-07 19:39 UTC, andrewrk commented on lib/std/os/linux/bpf.zig
> +// endian systems
Don't be afraid to announce these TODOs loud and proud in the doc comments :)

2020-09-07 19:39 UTC, merged