Implements std.meta.ArgsTuple.
ziglang/zig pull request #6415
Opened 2020-09-25 07:17 UTC by MasterQ32

Implements a helper function that is useful for creating generic function calls: `std.meta.ArgsTuple` calculates a tuple type for any given non-generic, non-variadic function type that can be passed into `@call()` to invoke the function.

2020-09-25 16:40 UTC, Rocknest commented
It seems that the code is almost identical to #6416

2020-09-25 16:49 UTC, alexnask commented
This is tripping the same assert as #6416

2020-09-27 18:12 UTC, alexnask requested changes

2020-09-27 18:12 UTC, alexnask commented on lib/std/meta.zig
> +comptime {
Please move these tests in a test block, at the moment these will run every time meta is referenced.

2020-09-29 13:01 UTC, alexnask approved these changes

2020-09-29 13:04 UTC, alexnask commented
Maybe thsi can use std.meta.Tuple instead now?  
Although it would be a bit less efficient.

2020-09-29 13:08 UTC, MasterQ32 commented
I thought about it too, but i think it's good as it is. we don't have to waste more `comptime` time than necessary

2020-09-29 17:28 UTC, merged