Implements std.meta.Tuple(), implements #4607 in userland.
ziglang/zig pull request #6416
Opened 2020-09-25 07:28 UTC by MasterQ32

Implements a function that returns a tuple type for a list of types:
```zig
std.meta.Tuple(.{ u32, f16 }) // returns struct { @"0": u32, @"1": f16 }
```

2020-09-25 16:37 UTC, Rocknest commented
Closes #4335?

2020-09-25 16:39 UTC, tadeokondrak commented
> Closes #4335?

I think creating one with std.meta and with built-in syntax are different usecases.

2020-09-25 16:41 UTC, alexnask approved these changes

2020-09-25 16:41 UTC, Rocknest commented
@tadeokondrak how its different?

2020-09-25 16:44 UTC, alexnask commented
Hm, this seems like it's tripping some assert in `resolve_llvm_types_struct`.  
I will look into this soon.

2020-09-25 16:48 UTC, tadeokondrak commented
@Rocknest 
Built-in syntax doesn't let you take a []type and create a tuple from it.

Any use of the built-in syntax could be replaced with the std.meta function, but that's not itself a justification for it.

The `struct` keyword could be replaced with a `std.meta.Struct(fields: anytype) type`, used like `Struct(.{ a = u32, b = u32 })`, should that be removed?

2020-09-25 18:03 UTC, Rocknest commented
@tadeokondrak Here we go again. Should we remove something if there is another way to achieve the same result? I always say in these kind of discussions - if its used often we should have sugar for that.

2020-09-25 18:06 UTC, tadeokondrak commented
@Rocknest
Being an accepted proposal, I think the better place to discuss is #4335.

2020-09-27 18:11 UTC, alexnask requested changes

2020-09-27 18:11 UTC, alexnask commented on lib/std/meta.zig
> +comptime {
Please move these tests in a test block, at the moment these will run every time meta is referenced.

2020-09-27 18:15 UTC, tadeokondrak commented
Is there a reason this takes `anytype` and not `[]type`?

2020-09-27 18:17 UTC, alexnask commented
@tadeokondrak  
I assume the reason is to support iterable of types (mostly tuples) as well as slices.  
Personally I like this decision.

2020-09-27 18:31 UTC, MasterQ32 commented
> Is there a reason this takes `anytype` and not `[]type`?

Actually because i'm lazy and i don't want to write `&[_]type { … }` when i can write `.{ … }`. What @alexnask said is a nice side effect though

2020-09-29 12:59 UTC, merged

2020-09-29 16:25 UTC, Rocknest commented
The decision to make this api a little more verbose is somewhat arbitrary. Doesn't std.meta exists to assist type introspection and manipulation with minimal verbosity?

2021-03-26 22:12 UTC, cindRoberta commented
```zig
const a: Tuple(&[_]type{ u32, u8 }) = .{ .@"0" = 0, .@"1" = 4 };
print("{any}\n", .{a[0]});
```