stage1: Implement @reduce builtin for vector types
ziglang/zig pull request #6558
Opened 2020-10-04 16:27 UTC by LemonBoy

The builtin folds a Vector(N,T) into a scalar T using a specified operator.

Closes #2698

2020-10-05 01:21 UTC, andrewrk commented
My goodness, we just cannot catch a break with that windows CI

2020-10-05 01:28 UTC, andrewrk requested changes
Nice progress! 1 nitpick and then this is good to land.

BTW why not work towards this in stage2? This is still useful progress because the changes to builtin.zig, behavior tests, and zig_llvm.{h,cpp} will persist, but I have a feeling you would enjoy the work more on stage2, and once we get far enough on that, the current plan is to delete the stage1 codebase (#6378).

Also I'm happy to do the nitpick myself in the merge process if you want, just say the word.

2020-10-05 01:28 UTC, andrewrk commented on lib/std/builtin.zig
> +    Max,
[lower case tag names](https://ziglang.org/documentation/master/#Style-Guide) for new enums please. I normally don't want to care about style stuff but I also don't want to have to make unnecessary breaking changes later.

2020-10-05 07:39 UTC, LemonBoy commented
> BTW why not work towards this in stage2? 

Because I was playing with SIMD rather than with the compiler :^)
When the LLVM backend for stage2 is kickstarted I'll definitely move to the Zig side of the moon.

> Also I'm happy to do the nitpick myself in the merge process if you want, just say the word.

Yeah go ahead, didn't know about the lowercase rule for enum members.

2020-10-05 08:51 UTC, andrewrk commented
Oh, hmm. Gonna change my mind on this one. Capitalized enum tag names in this case works around the conflicts with the language keywords. :shrug:

2020-10-05 08:51 UTC, merged

2020-10-05 08:53 UTC, andrewrk commented
>  When the LLVM backend for stage2 is kickstarted I'll definitely move to the Zig side of the moon.

Alright well that's certainly motivating for me or someone else to get started on  #6541 :-)

2020-10-27 21:52 UTC, LemonBoy commented
> Can you implement .Add and .Mul, please?

Sure, I didn't implement those because I wasn't sure about the names to use (nor I had any need for those ops).
Since the add/sub/mul provided by LLVM are wrapping I'd go for `Wrapping{Add,Mul}`.

2020-11-01 12:11 UTC, data-man commented
@LemonBoy 
> Sure

Before 0.7.0 release? :)

But I thought about integer/float overflow for `.Add` and `.Mul`. :(
E.g. if a vector is `float32` type, can `@reduce` return `float64`?