std: openDirAbsolute and accessAbsolute
ziglang/zig pull request #7082
Opened 2020-11-11 21:21 UTC by g-w1

This is from a use case in zigup: [here](https://github.com/marler8997/zigup/blob/74aa0ca36886d3a2c2c0fdb3a2da6475dc0b1286/zigup.zig#L450).

2020-11-14 01:24 UTC, g-w1 commented
I also added a minor documentation fix.

2020-11-16 04:59 UTC, daurnimator approved these changes
nit: typo in commit message.


Could you add tests for these new functions?
Without them they're likely to break when we e.g. fix `access` flags argument; and they won't show up in std library docs.

2020-11-16 08:00 UTC, kubkon requested changes

2020-11-16 12:27 UTC, g-w1 commented on lib/std/fs.zig
> +/// Test accessing `path`.
I am not sure what you mean about WTF16 encoding? Do you mean a function that takes utf16, or the actual source code is in utf16?

2020-11-16 12:45 UTC, g-w1 commented on lib/std/fs.zig
> +/// Test accessing `path`.
Ah, I see, like createFileAbsoluteW.

2020-11-16 13:04 UTC, g-w1 commented on lib/std/fs.zig
> +    assert(path.isAbsolute(absolute_path));
I think it is good to have these absolutes because they also assert that the path is absolute, which could save some time in debugging.

2020-11-16 17:36 UTC, g-w1 commented
Could someone take a look at why the ci is failing. I have no clue?
![image](https://user-images.githubusercontent.com/58830309/99287311-14dfe900-2808-11eb-897a-be3d947d59d0.png)
Maybe my tests uncovered some bug because of lazy code eval.

2020-11-16 17:55 UTC, kubkon requested changes

2020-11-16 17:55 UTC, kubkon commented on lib/std/fs/test.zig
> +    var tmp = tmpDir(.{});
You need to specifically exclude tests that rely on absolute paths from being tested on WASI target. WASI doesn't have a concept of an absolute path after all.

2020-11-16 17:55 UTC, kubkon commented on lib/std/fs/test.zig
> +    var tmp = tmpDir(.{});
Ditto.

2020-11-16 17:55 UTC, kubkon commented on lib/std/fs/test.zig
> +    var tmp = tmpDir(.{});
This will also make the tests pass again.

2020-11-16 18:00 UTC, g-w1 commented on lib/std/fs/test.zig
> +    var tmp = tmpDir(.{});
Ah, that makes sense. Thanks!

2020-11-16 18:05 UTC, g-w1 commented on lib/std/fs.zig
> +    assert(path.isAbsolute(absolute_path));
For the wasi compile error, what should it say? "WASI doesn't have the concept of an absolute directory; use openDir instead for wasi." is this good?

2020-11-18 07:42 UTC, kubkon approved these changes
Great stuff, thanks @g-w1!

2020-11-18 07:42 UTC, merged

2021-06-11 01:42 UTC, g-w1 commented on lib/std/os.zig
> +    if (file_path.len >= MAX_PATH_BYTES) return error.NameTooLong;
Reasoning for this, WASI does not have a PATH_MAX. This has caused problems for others.