Stop passing --cache-dir and --global-cache-dir to build.zig exe through zig build.
ziglang/zig pull request #7270
Opened 2020-12-01 16:07 UTC by antlilja

Passing --cache-dir or --global-cache-dir to zig build causes the error: "Unknown argument: --cache-dir/--global-cache-dir" in build_runner.zig. This is because zig build passes these through to the build exe but they are not expected.

2020-12-03 00:41 UTC, andrewrk requested changes
Instead, build_runner.zig should be improved to accept these parameters and pass them to every zig invocation.

2020-12-03 12:05 UTC, antlilja commented
build_runner.zig already takes the local cache dir as a mandatory argument see [build_runner.zig:40](https://github.com/ziglang/zig/blob/master/lib/std/special/build_runner.zig#L40), it was just being passed twice. But I'll handle the global cache as well.

2020-12-04 00:43 UTC, antlilja commented
The global cache directory is now a mandatory argument to build_runner.zig (same as local cache).

2020-12-10 23:06 UTC, merged

2020-12-10 23:06 UTC, andrewrk commented
Thanks for the follow-up!

2020-12-10 23:06 UTC, andrewrk commented
cc @alexnask I believe this will require an update to ZLS's custom build_runner

2020-12-10 23:23 UTC, antlilja commented
No problem 👍

2020-12-10 23:41 UTC, antlilja commented
> cc @alexnask I believe this will require an update to ZLS's custom build_runner

I created a PR in the zls repo to address this: https://github.com/zigtools/zls/pull/203