Improve README: show intro logo card box
ziglang/zig pull request #7470
Opened 2020-12-17 01:41 UTC by BaseMax

Hi there,

Just a small PR to improve `README.md` and make this more beautiful.

**Summary:**
Improve README: show intro logo card box

Regards,

2020-12-17 01:55 UTC, BaseMax commented
GitHub Dark theme:
![dark-theme](https://user-images.githubusercontent.com/2658040/102431235-45de5400-4028-11eb-8f80-cd61c5f3b695.png)

GitHub Light theme:
![light-theme](https://user-images.githubusercontent.com/2658040/102431260-470f8100-4028-11eb-87ef-8e9568bad6dd.png)

2020-12-17 01:57 UTC, BaseMax commented
So now the logo has no problem in both themes and looks beautiful. :heart:  (Dark and Light)

https://github.blog/2020-12-08-new-from-universe-2020-dark-mode-github-sponsors-for-companies-and-more/#dark-mode

2020-12-17 03:29 UTC, jayschwa commented
FYI, there is a standalone repository for the logo: https://github.com/ziglang/logo

2020-12-17 05:00 UTC, BaseMax commented
Thank you Jay.
This does not just include changing the logo, There are other changes in the **readme** file.

We are waiting for the follow-up for the new logo file to be completed. https://github.com/ziglang/logo/pull/12

After that, we continue this PR.

Thanks

2020-12-19 03:14 UTC, andrewrk requested changes
Thanks for your efforts however I don't think this will work, at least not as is.

2020-12-19 03:14 UTC, andrewrk commented on README.md
> +<div align="center">
No html in readme.md please, this is also a plain text document

2020-12-19 03:14 UTC, andrewrk commented on README.md
> +    <img src="https://raw.githubusercontent.com/MaxFork/zig/e7c86677d0754fc884c4242c897a28b7c324f541/logo.svg" alt="ZIG" style="max-width:100%; margin: 0 auto;" width="200">
this link is to a fork

2020-12-19 03:14 UTC, andrewrk commented on logo.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 400 140">
I'd like to keep the logo external to this repository, we have a dedicated repository for logo and other images

2021-01-12 00:51 UTC, closed without merging