stage2: wasm - "Hello world"
ziglang/zig pull request #8439
Opened 2021-04-04 18:37 UTC by Luukdegram

Note: conflicts with https://github.com/ziglang/zig/pull/8416. Will rebase after merge.

This PR implements arrays and the 'data' and 'mem' sections of wasm, allowing
for the following to work (including incremental compilation):
```zig
extern fn print(s: [*:0]const u8, len: i32) void;

pub export fn helloWorld() void {
    print("Hello, world!", 13);
}
```
Using the following JS:
```js
const fs = require('fs');
const source = fs.readFileSync("./test.wasm");
const typedArray = new Uint8Array(source);
var buffer = null;

WebAssembly.instantiate(typedArray, {
  env: {
    print: (offset, len) => {
        
        let s = "";
        for (let i = offset; i < offset + len; i++)
        	s += String.fromCharCode(buffer[i]);
        console.log(`The result is ${s}`); }

  }}).then(result => {
  	buffer = new Uint8Array(result.instance.exports.memory.buffer);
  	const helloWorld = result.instance.exports.helloWorld;
  	helloWorld();
});
```
Results in the following:
```sh
> node test test.js
> The result is Hello, world!
```

2021-04-05 00:03 UTC, andrewrk requested changes
Nice work!

I left you some suggestions to improve it, and I think we should also have a chat and plan out some of these bigger picture items such as how to organize the linker code with regards to incremental compilation.

2021-04-05 00:03 UTC, andrewrk commented on src/link/Wasm.zig
> +fn calcDataLen(self: *Wasm, typed_value: TypedValue) u32 {
Let's chat about this too - I don't quite understand why this mechanism is needed.

2021-04-05 00:03 UTC, andrewrk commented on src/link/Wasm.zig
> +        } else unreachable; // offset() called on declaration that does not live inside 'data' section
Let's chat about this. I think there is a better solution than linear scan across all decls for this.

2021-04-09 07:25 UTC, Luukdegram commented
Ok, should be all ready now!

2021-04-09 17:08 UTC, merged

2021-04-09 17:08 UTC, andrewrk commented
Great work! I guess the next thing to do will be to work towards WASI hello world so we can add a test case :grin: