std: Better handing of POLLHUP in ChildProcess
ziglang/zig pull request #8988
Opened 2021-06-04 10:43 UTC by LemonBoy

It's still possible to read the remaining data from the file descriptor
after a POLLHUP is received, check that flag together with POLLIN to
make sure we're not prematurely closing the fd and lose data.

Closes #8969

cc @leroycep Please try this patch, it fixes the problem on my system.

2021-06-04 16:44 UTC, mikdusan requested changes
This breaks the dragonfly-workaround path. We'll need to adjust the workaround to unset POLLIN when EOF is detected.

<details>
<summary>diff</summary>
```diff
iff --git a/lib/std/child_process.zig b/lib/std/child_process.zig
index 5a1cd9057..0012a70a3 100644
--- a/lib/std/child_process.zig
+++ b/lib/std/child_process.zig
@@ -223,8 +223,10 @@ pub const ChildProcess = struct {
                 stdout.items.len += nread;

                 // insert POLLHUP event because dragonfly fails to do so
-                if (dragonfly_workaround and nread == 0)
+                if (dragonfly_workaround and nread == 0) {
+                    poll_fds[0].revents &= ~@as(@TypeOf(poll_fds[0].revents), os.POLLIN);
                     poll_fds[0].revents |= os.POLLHUP;
+                }
             }
             if (poll_fds[1].revents & os.POLLIN != 0) {
                 // stderr is ready.
@@ -236,8 +238,10 @@ pub const ChildProcess = struct {
                 stderr.items.len += nread;

                 // insert POLLHUP event because dragonfly fails to do so
-                if (dragonfly_workaround and nread == 0)
+                if (dragonfly_workaround and nread == 0) {
+                    poll_fds[1].revents &= ~@as(@TypeOf(poll_fds[1].revents), os.POLLIN);
                     poll_fds[1].revents |= os.POLLHUP;
+                }
             }

             // Exclude the fds that signaled an error.
```
</details>

2021-06-04 17:46 UTC, mikdusan approved these changes

2021-06-04 20:30 UTC, leroycep commented
This fixes it on my system. :+1:

2021-06-04 21:07 UTC, LemonBoy commented
Given the ci builds hanging there's some subtle difference in how the poll events are delivered on macos and freebsd. @mikdusan can you confirm?

2021-06-04 22:15 UTC, mikdusan commented
@LemonBoy,

Difficult to reproduce. I think the logic has a weakness so here's my stab at it. This diff is based on the idea:

- it's not guaranteed that subsequent poll() is meaningful after receiving POLLHUP event
- check for POLLHUP inside POLLIN handlers and if detected, loop reading until EOF
- a read is always checked for EOF

```diff
diff --git a/lib/std/child_process.zig b/lib/std/child_process.zig
index 56f3e9b1d..66827b341 100644
--- a/lib/std/child_process.zig
+++ b/lib/std/child_process.zig
@@ -215,27 +215,41 @@ pub const ChildProcess = struct {
             // conditions.
             if (poll_fds[0].revents & os.POLLIN != 0) {
                 // stdout is ready.
-                const new_capacity = std.math.min(stdout.items.len + bump_amt, max_output_bytes);
-                try stdout.ensureCapacity(new_capacity);
-                const buf = stdout.unusedCapacitySlice();
-                if (buf.len == 0) return error.StdoutStreamTooLong;
-                const nread = try os.read(poll_fds[0].fd, buf);
-                stdout.items.len += nread;
-
-                // insert POLLHUP event because dragonfly fails to do so
-                if (dragonfly_workaround and nread == 0) poll_fds[0].revents |= os.POLLHUP;
+                while (true) {
+                    const new_capacity = std.math.min(stdout.items.len + bump_amt, max_output_bytes);
+                    try stdout.ensureCapacity(new_capacity);
+                    const buf = stdout.unusedCapacitySlice();
+                    if (buf.len == 0) return error.StdoutStreamTooLong;
+                    const nread = try os.read(poll_fds[0].fd, buf);
+                    if (nread == 0) {
+                        // insert POLLHUP event because dragonfly fails to do so
+                        if (dragonfly_workaround)
+                            poll_fds[0].revents |= os.POLLHUP;
+                        break;
+                    }
+                    stdout.items.len += nread;
+                    if (poll_fds[0].revents & os.POLLHUP == 0)
+                        break;
+                }
             }
             if (poll_fds[1].revents & os.POLLIN != 0) {
                 // stderr is ready.
-                const new_capacity = std.math.min(stderr.items.len + bump_amt, max_output_bytes);
-                try stderr.ensureCapacity(new_capacity);
-                const buf = stderr.unusedCapacitySlice();
-                if (buf.len == 0) return error.StderrStreamTooLong;
-                const nread = try os.read(poll_fds[1].fd, buf);
-                stderr.items.len += nread;
-
-                // insert POLLHUP event because dragonfly fails to do so
-                if (dragonfly_workaround and nread == 0) poll_fds[1].revents |= os.POLLHUP;
+                while (true) {
+                    const new_capacity = std.math.min(stderr.items.len + bump_amt, max_output_bytes);
+                    try stderr.ensureCapacity(new_capacity);
+                    const buf = stderr.unusedCapacitySlice();
+                    if (buf.len == 0) return error.StderrStreamTooLong;
+                    const nread = try os.read(poll_fds[1].fd, buf);
+                    if (nread == 0) {
+                        // insert POLLHUP event because dragonfly fails to do so
+                        if (dragonfly_workaround)
+                            poll_fds[1].revents |= os.POLLHUP;
+                        break;
+                    }
+                    stderr.items.len += nread;
+                    if (poll_fds[1].revents & os.POLLHUP == 0)
+                        break;
+                }
             }
 
             // Exclude the fds that signaled an error.
```

2021-06-05 08:24 UTC, LemonBoy commented
Can you report the results given by [this program](https://www.greenend.org.uk/rjk/tech/poll.c) when run on macos and freebsd? We're hitting some [underspecified](https://www.greenend.org.uk/rjk/tech/poll.html) corner of the poll specification that every implementer is interpreting differently.

> it's not guaranteed that subsequent poll() is meaningful after receiving POLLHUP event

That (and calling `read()`) should be pretty safe to do, the EOF condition makes the read return 0.

> check for POLLHUP inside POLLIN handlers and if detected, loop reading until EOF

Adding a loop kinda defeats the whole point of adding a polling loop, I'm trying hard to avoid adding one to prevent one stream from starving the other.

> a read is always checked for EOF

This is a good idea, I'll push an updated patch that seems to work both on Linux and FreeBSD.

2021-06-05 15:50 UTC, mikdusan commented
> Can you report the results given by...

```
Linux archlinux 5.12.9-arch1-1 #1 SMP PREEMPT Thu, 03 Jun 2021 11:36:13 +0000 x86_64 GNU/Linux
pipe: POLLHUP
socketpair: POLLIN|POLLHUP
SHUT_WR socketpair: POLLIN
SHUT_RD socketpair: POLLIN
regular: POLLIN

Darwin tiberius 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64 i386 iMac19,1 Darwin
pipe: POLLIN|POLLHUP
socketpair: POLLIN|POLLHUP
SHUT_WR socketpair: POLLIN|POLLHUP
SHUT_RD socketpair: POLLIN|POLLHUP
regular: POLLIN

FreeBSD freebsd130 13.0-RELEASE FreeBSD 13.0-RELEASE #0 releng/13.0-n244733-ea31abc261f: Fri Apr  9 04:24:09 UTC 2021     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/amd64.amd64/sys/GENERIC  amd64
pipe: POLLIN|POLLHUP
socketpair: POLLIN|POLLHUP
SHUT_WR socketpair: POLLIN
SHUT_RD socketpair: POLLIN
regular: POLLIN

NetBSD netbsd91-amd64.Home 9.1 NetBSD 9.1 (GENERIC) #0: Sun Oct 18 19:24:30 UTC 2020  mkrepro@mkrepro.NetBSD.org:/usr/src/sys/arch/amd64/compile/GENERIC amd64
pipe: POLLIN|POLLHUP
socketpair: POLLIN
SHUT_WR socketpair: POLLIN
SHUT_RD socketpair: POLLIN
regular: POLLIN

DragonFly dragonfly60 6.0-RELEASE DragonFly v6.0.0-RELEASE #1: Tue May 11 03:22:45 EDT 2021     root@dragonfly60:/usr/obj/usr/src/sys/X86_64_POLLHUP  x86_64
pipe: POLLIN|POLLHUP
socketpair: POLLIN|POLLHUP
SHUT_WR socketpair: POLLIN
SHUT_RD socketpair: POLLIN
regular: POLLIN

OpenBSD openbsd69 6.9 GENERIC.MP#473 amd64
pipe: POLLIN|POLLHUP
socketpair: POLLIN|POLLHUP
SHUT_WR socketpair: POLLIN
SHUT_RD socketpair: POLLIN
regular: POLLIN
```

2021-06-05 18:26 UTC, merged