fix tool/update_clang_options.zig for ArrayHashMap's Separated Key/Va…
ziglang/zig pull request #9022
Opened 2021-06-07 01:41 UTC by redj

…lue Storage breaking change.

2021-06-07 01:41 UTC, redj commented
Is this the proper fix? I did run the tool and it generated an identical src/clang_options_data.zig file.

2021-06-07 15:17 UTC, kubkon approved these changes
LGTM!

2021-06-07 15:29 UTC, kubkon requested changes
Actually, on second thought, explicit dereferencing when accessing members or union variants are not needed - the pointer will get dereferenced automatically.

2021-06-07 15:29 UTC, kubkon commented on tools/update_clang_options.zig
> +            if (kv.key_ptr.*.len == 0) continue;
```suggestion
            if (kv.key_ptr.len == 0) continue;
```

2021-06-07 15:29 UTC, kubkon commented on tools/update_clang_options.zig
> +            if (!kv.value_ptr.*.Object.contains("NumArgs")) continue;
```suggestion
            if (!kv.value_ptr.Object.contains("NumArgs")) continue;
```

2021-06-07 15:29 UTC, kubkon commented on tools/update_clang_options.zig
> +            if (!kv.value_ptr.*.Object.contains("Name")) continue;
```suggestion
            if (!kv.value_ptr.Object.contains("Name")) continue;
```

2021-06-07 15:29 UTC, kubkon commented on tools/update_clang_options.zig
> +            if (kv.value_ptr.*.Object.get("Name").?.String.len == 0) continue;
```suggestion
            if (kv.value_ptr.Object.get("Name").?.String.len == 0) continue;
```

2021-06-07 15:29 UTC, kubkon commented on tools/update_clang_options.zig
> +            try all_objects.append(&kv.value_ptr.*.Object);
```suggestion
            try all_objects.append(&kv.value_ptr.Object);
```

2021-06-07 21:12 UTC, redj commented
@kubkon, thanks for the review. I think I got them all. I amended and force pushed. should be good to merge.

2021-06-08 04:24 UTC, kubkon approved these changes

2021-06-08 04:26 UTC, merged