stage2: bringup plan9 target and linker
ziglang/zig pull request #9105
Opened 2021-06-13 15:40 UTC by g-w1

* [x] sucessful `pub fn main() void {}`
* [ ] Convert to use a global offset table
* [ ] sucessful hello world (This may be harder as the pwrite syscall needs arguments on the stack, so I might have to implement more inline asm which may be out of scope).
* [ ] use correct code for 64 bit targets (not `@intCast`) to u32
* [ ] remove some panics
![scrot](https://user-images.githubusercontent.com/58830309/121813864-f4f89280-cc3b-11eb-8d13-9a49d548e067.png)

2021-06-15 15:17 UTC, kubkon commented
How much is left (is it viable) for having plan9 autotested in stage2 tests?

2021-06-15 15:35 UTC, g-w1 commented
Very good question! Sourcehut has support for plan9 on ci https://sourcehut.org/blog/2020-05-11-sourcehut-plus-plan-9/, so we could probably use that, but maybe not until its self-hosting or we can generate the binaries on a different platform, then run them on the plan9 ci.
Russ Cox also made a thing, kind of like wine, that can run plan9 user programs on some unixes. https://swtch.com/9vx/ Maybe we could use this on the ci? (I haven't used it yet, I'll try it soon)

2021-06-15 20:05 UTC, kubkon commented
> Very good question! Sourcehut has support for plan9 on ci https://sourcehut.org/blog/2020-05-11-sourcehut-plus-plan-9/, so we could probably use that, but maybe not until its self-hosting or we can generate the binaries on a different platform, then run them on the plan9 ci.
> Russ Cox also made a thing, kind of like wine, that can run plan9 user programs on some unixes. https://swtch.com/9vx/ Maybe we could use this on the ci? (I haven't used it yet, I'll try it soon)
> Edit: Someone on irc also said that you could just boot plan9 in qemu and run the program in it.

Hmm, I guess srht would be our best bet since rolling out wine-like emulation or QEMU might be a tough thing to do inside another VM (i.e., the CI). Perhaps it could be done though?

2021-06-21 17:12 UTC, g-w1 commented
Successful hello world!!!: 
![image](https://user-images.githubusercontent.com/58830309/122801575-4df6a500-d292-11eb-9ff9-5251c065e978.png)

2021-06-26 20:13 UTC, g-w1 commented
For reviewers: here is the link to the man page used for reference http://git.9front.org/plan9front/plan9front/819bec22ccf01927c8d31e9bbcddca91b5ed41ee/sys/man/6/a.out/f.html

2021-07-08 18:50 UTC, andrewrk requested changes
I have only cosmetic changes requested on this. Impressive work!

2021-07-08 18:50 UTC, andrewrk commented on lib/std/zig.zig
> +fn archToPlan9Char(arch: std.Target.Cpu.Arch) ?u8 {
```suggestion
fn archToPlan9Char(arch: std.Target.Cpu.Arch) u8 {
```

2021-07-08 18:50 UTC, andrewrk commented on src/link.zig
> +            .plan9 => @panic("PLAN 9 DEBUG INFO"),
```suggestion
            .plan9 => @panic("TODO: implement updateDeclLineNumber for plan9"),
```

2021-07-08 18:50 UTC, andrewrk commented on src/link/Plan9.zig
> +// TODO use incremental compilation
```suggestion
//! This implementation does all the linking work in flush(). A future improvement
//! would be to add incremental linking in a similar way as ELF does.
```

2021-07-08 18:50 UTC, andrewrk commented on src/link/plan9/a.out.zig
> +// SOFTWARE.
this zig code is not copyright-owned by plan 9 foundation; you can and should omit this copyright notice.

2021-07-08 21:30 UTC, merged