Add support for the NO_COLOR environment variable
ziglang/zig pull request #9156
Opened 2021-06-18 18:16 UTC by SpexGuy

This PR adds checks for the [widely supported](http://no-color.org/) `NO_COLOR` environment variable.  If this variable exists, the default is changed from tty detection to no color.  Command line arguments will still take precedence over this environment variable.

2021-06-21 03:09 UTC, g-w1 requested changes
Could you also add it here?https://github.com/ziglang/zig/blob/fc1feebdc0ffd4730c724780265d4ef6a9515dc8/lib/std/debug.zig#L88-L103 and https://github.com/ziglang/zig/blob/fc1feebdc0ffd4730c724780265d4ef6a9515dc8/src/stage1/errmsg.cpp#L20
There may be other places in the codebase where this is needed.

2021-06-21 18:16 UTC, SpexGuy commented
@g-w1 good find, I'll update those too.  I don't see an existing way to get env vars in stage 1.  Should I add that to os.cpp or am I missing something?

2021-06-21 18:17 UTC, g-w1 commented
I implemented something similar but worse in this pr, https://github.com/ziglang/zig/pull/7932/files
```cpp
bool os_is_dumb_term(void) {
    char* term = getenv("TERM");
    if (term == nullptr) return false;
    return strcmp(term, "dumb") == 0;
}
```

2021-06-21 18:41 UTC, SpexGuy commented
uh, what

...did this just get merged?

Oh fuck

2021-06-21 18:41 UTC, g-w1 commented
I think you just closed it.

2021-06-21 18:42 UTC, andrewrk commented
If you accidentally deleted git commits, check your `git reflog` and the data is likely still there

2021-06-21 18:43 UTC, SpexGuy commented
Nothing's been deleted, my branch still exists, but I don't know what happened.  Doesn't look like it got merged into the zig repo, which is good.  The repoen button is greyed out, so I can't click that.  I guess I'll make a new PR?

2021-06-21 18:49 UTC, SpexGuy commented
I accidentally force pushed before committing, which apparently causes github to auto-close the PR since there are no changes.  Oops xD

2021-06-24 19:35 UTC, SpexGuy commented
Rebased to fix merge conflicts

2021-07-01 20:06 UTC, Vexu approved these changes

2021-07-08 18:30 UTC, merged