Skip over CRs at the end of multiline literals
ziglang/zig pull request #9274
Opened 2021-07-01 11:04 UTC by jmc-88

Fixes #9257.
This is needed when tokenizing input containing DOS line endings, i.e.
the CRLF sequence.

2021-07-01 13:55 UTC, ifreund reviewed
This seems wrong, aren't windows line endings supposed to be CRLF? That, CR and then LF, or `"\r\n"`.

2021-07-01 19:27 UTC, Vexu requested changes
Seems to me like `\r` should be handled with `\t` as is done elsewhere.

2021-07-01 22:55 UTC, jmc-88 commented
Yes, you're quite right, though applying that change miraculously breaks a bunch of other code paths. I will look into it more as soon as I get the time.

2021-07-04 14:02 UTC, jmc-88 commented
Mostly note to self: a complete `zig build -Dskip-release test-std` run shows that the only failure triggered by moving the `'\r'` to the same branch as `'\t'` is the ["writev/fsync/readv" test from /lib/std/os/linux/io_uring.zig](https://github.com/ziglang/zig/blob/8a863381d11adcdcb4e0509611af93c61fc89804/lib/std/os/linux/io_uring.zig#L1063-L1129) (specifically [line 1105](https://github.com/ziglang/zig/blob/8a863381d11adcdcb4e0509611af93c61fc89804/lib/std/os/linux/io_uring.zig#L1105)).

2021-07-06 20:01 UTC, Vexu commented
What does your error return trace look like? I've also been experiencing some failures with that test on both my Arch Linux desktop and laptop. Try running `zig test lib/std/os/linux/io_uring.zig --zig-lib-dir lib` a few times and see if that works. For me it fails on clean cache about half the time but the second run always succeeds.

2021-07-06 20:40 UTC, jmc-88 commented
Oh, interesting, it didn't occur to me to try running it on a different system -- this laptop is also currently running Arch Linux... I tried it on a Debian host and it passed cleanly. ¯\\\_(ツ)_/¯

This is the failure log I got on Arch Linux: https://gist.github.com/jmc-88/54997867ae0e38cb6cd6f7331fce4142
Interestingly, if I don't pipe it somewhere, the error trace seems to get stuck in an infinite loop and I have to kill `zig` manually. That may or may not be a second issue.

Given the above, I pushed an updated version of this change, since the failure appears to be unrelated. PTAL.

2021-07-07 17:03 UTC, merged

2021-07-07 17:13 UTC, Vexu commented
Mine also used to loop until I tried it yesterday.

@jorangreef do you have any idea what could be happening here? It has happened to me on multiple 5.x kernels on Arch Linux. If you are interested in taking a look, I can provide an executable that can reproduce the failure but the debug info in it seems to always be corrupt.