std.json: stringily enum based on tag name
ziglang/zig pull request #9450
Opened 2021-07-25 14:26 UTC by haze

2021-07-25 14:28 UTC, char commented
i like this

2021-07-25 14:29 UTC, Luukdegram commented
Duplicate of https://github.com/ziglang/zig/pull/8661

2021-07-26 00:50 UTC, daurnimator requested changes
Lets go via the proposal process first (#9451) as noted via the duplicate mentioned, this has been rejected before.

2021-07-26 00:50 UTC, daurnimator commented on lib/std/json.zig
> +                return stringify(@tagName(value), options, out_stream);
`@tagName` on non-exhaustive enums can be illegal behaviour.

2021-08-02 06:09 UTC, closed without merging