Add @blend
ziglang/zig pull request #9459
Opened 2021-07-26 01:16 UTC by Snektron

```zig
@blend(
    comptime T: type,
    pred: std.meta.Vector(len, bool),
    a: std.meta.Vector(len, T),
    b: std.meta.Vector(len, T)
) std.meta.Vector(len, T)
```

Constructs a vector from a & b, based on the values in the predicate vector. For indices where the predicate value is true, the corresponding element from the a vector is selected, and otherwise from.

See also #903

2021-07-26 09:00 UTC, zigazeljko commented
Why the name `@blend`? Both LLVM and WebAssembly call this operation `select`, since it just *selects* elements from the two vectors. `@blend` makes it sound like it interpolates (aka *blends*) between elements, like the [`mix`](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/mix.xhtml) function in GLSL.

2021-07-26 12:50 UTC, Snektron commented
This is the name x86_64 uses. I picked blend initially because there is an existing proposal for async which would introduce a `select` keyword, and so didnt want to cause possible confusion between the two.

I dont have a strong opinion on the name though, im fine with renaming it to `@select`.

2021-07-26 19:44 UTC, nektro commented
https://gobyexample.com/select
https://tour.golang.org/concurrency/5

https://llvm.org/docs/LangRef.html#select-instruction
https://webassembly.github.io/spec/core/syntax/instructions.html#syntax-instr-parametric

2021-07-26 23:20 UTC, andrewrk requested changes
I'd like to request the name to be `@select` despite the fact that we have another accepted proposal for select syntax (#5263).

Other than that, this looks ready to merge. Nice work and thank you.

2021-07-26 23:20 UTC, andrewrk commented on test/behavior/blend.zig
> +test "@shuffle" {
don't forget to rename this

2021-07-27 00:03 UTC, andrewrk approved these changes

2021-07-27 00:05 UTC, merged