fs.Dir.walk: Do not close the initial dir during/after walking it
ziglang/zig pull request #9560
Opened 2021-08-14 00:03 UTC by squeek502

Closing the initial directory was unexpected to me, and does not mesh very well with how the rest of the Dir API works.

Fixes #9556

2021-08-14 21:44 UTC, squeek502 commented
Updated now that #9559 has been merged. This should be good to go.

2021-08-19 11:11 UTC, Vexu requested changes

2021-08-19 11:11 UTC, Vexu commented on lib/std/fs.zig
> +                    if (item.dirname_len != 0) {
```suggestion
                    if (self.stack.len != 0) {
```
Both have the same effect but this conveys what property we're really interested in.

2021-08-19 11:11 UTC, Vexu commented on lib/std/fs.zig
> +                if (item.dirname_len != 0) {
Same here.

2021-08-20 07:02 UTC, merged

2021-09-01 16:32 UTC, ominitay commented
Apologies for this oversight! Perhaps the `` `self` will not be closed after walking it. `` comment is unnecessary, as it *is* expected behaviour. Again, sorry I didn't see this sooner; GitHub notifications failed me lol

2021-09-01 19:25 UTC, squeek502 commented
> Apologies for this oversight! Perhaps the `` `self` will not be closed after walking it. `` comment is unnecessary, as it _is_ expected behaviour.

No worries. I also wasn't sure about adding that doc comment but I think it's probably better to be explicit for now for anyone updating their code from the closing version or the old non-Dir version. That part of the doc comment can always be removed later.