stage2: only initialize the llvm backend for the target we are building
ziglang/zig pull request #9659
Opened 2021-08-30 22:12 UTC by nektro

Fixes #9596

2021-08-30 22:15 UTC, andrewrk requested changes
Implementation looks good but please put `initializeLLVMTarget` in codegen/llvm.zig rather than in the bindings file. The reason `LLVMInitializeAllTargetInfos` was in the bindings file was that it was translated from an inline function in an .h file.

2021-08-30 22:16 UTC, andrewrk commented on src/codegen/llvm/bindings.zig
> +        else => {},
list all the targets exhaustively please

2021-08-30 22:46 UTC, nektro commented
Should I make all the `LLVMInitialize` functions public then?

2021-08-31 02:31 UTC, andrewrk requested changes
Thanks - almost there

2021-08-31 02:31 UTC, andrewrk commented on src/codegen/llvm.zig
> +            // llvm.LLVMInitializeXCoreAsmParser();
```suggestion
            // There is no LLVMInitializeXCoreAsmParser function.
```

2021-08-31 02:31 UTC, andrewrk commented on src/codegen/llvm/bindings.zig
> +const std = @import("std");
unused import

2021-08-31 02:31 UTC, andrewrk commented on src/codegen/llvm.zig
> +pub fn initializeLLVMTarget(arch: std.Target.Cpu.Arch) void {
```suggestion
fn initializeLLVMTarget(arch: std.Target.Cpu.Arch) void {
```

2021-08-31 02:57 UTC, andrewrk approved these changes

2021-08-31 17:50 UTC, merged

2021-08-31 19:01 UTC, marler8997 commented
Out of curiosity, what was the performance difference?

2021-08-31 19:07 UTC, nektro commented
`773,734 ns` to `90,751 ns` on my `AMD Ryzen 5 4500U (6) @ 2.375GHz`