sat-arithmetic: add operator support
ziglang/zig pull request #9679
Opened 2021-09-02 20:57 UTC by travisstaloch

- adds initial support for the operators +|, -|, *|, <<|, +|=, -|=, *|=, <<|=
- uses operators in addition to builtins in behavior test
- adds binOpExt() and assignBinOpExt() to AstGen.zig. these need to be audited

2021-09-02 20:59 UTC, travisstaloch commented
TODOS
- update langref
- c backend support
- zig fmt support - currently deleting '|' from '<<|='
- zls support

I'm not sure what needs to be done to add support to zig fmt or zls.  Any advice appreciated.

2021-09-07 19:48 UTC, andrewrk commented
Here's some advice to get you going-

> * c backend support

You can add any functions you need to src/link/C/zig.h, and then in codegen/c.zig you can emit calls to them. This part is pretty fun! I recommend to play with godbolt to test out your saturating arithmetic implementations and see how optimizable they are (the goal would be that most C compilers would be able to optimize them into machine code instructions when available).

> * zig fmt support - currently deleting '|' from '<<|='

Double check your edits to tokenizer.zig. Perhaps try adding some test cases at the bottom of tokenizer.zig (there are a few examples already there you can look at). Something to keep in mind is that tokenizer.zig and tokenizer.cpp are intentionally nearly identical implementations, so your edits to each file should look almost the same.

> * zls support

Not needed for this PR to be merged :)

2021-09-08 23:23 UTC, travisstaloch commented on src/Sema.zig
>      block: *Scope.Block,
I'm reusing analyzeArithmetic() by adding an `opt_extended` param here.  Is this a bad idea?

Also, I can't figure out where the check that rhs of <<| is a Log2T is happening (and how to disable it).  It needs to accept T, but currently doesn't.

2021-09-09 04:41 UTC, travisstaloch commented
> This part is pretty fun! I recommend to play with godbolt to test out your saturating arithmetic implementations and see how optimizable they are (the goal would be that most C compilers would be able to optimize them into machine code instructions when available).

I looked at them on godbolt with [clang](https://godbolt.org/z/rx4o8xTMj) and [gcc](https://godbolt.org/z/r4cWcfvYW), both with -O1.  They were all branchless using cmovs except for gcc signed mul with 64 bits has one jump instruction.  I'm not super confident in the signed shl impl.  

> Double check your edits to tokenizer.zig. Perhaps try adding some test cases at the bottom of tokenizer.zig

This worked well. I was updating the result instead of the state when in the `<<` transition.  

Thank you for the guildance!  Please let me know if you get a chance to look at this again.  I've left some TODOs and FIXMEs.

2021-09-09 20:29 UTC, matu3ba reviewed
Some tests and simplification with using maxInt from math.zig.

Changing the behavior to allowing types on right hand side that are not Log2(left hand side) sounds to me inconsistent to the other `<<` operations and (from my perspective) can hide logical bugs without crashing/overflowing in tests if one is not cautious.

2021-09-09 21:08 UTC, travisstaloch commented on src/codegen/c.zig
> +            const val = std.math.pow(u65, 2, pow_bits) - 1;
maxInt requires a type while this uses bitcount. a type is not available here at comptime.

2021-09-09 21:09 UTC, travisstaloch commented on src/codegen/c.zig
> +                const val = -1 * std.math.pow(i65, 2, @intCast(i65, bits - 1));
minInt requires a type which is not available here. i've added a comment locally. will push soon.

2021-09-09 21:19 UTC, travisstaloch commented on lib/std/zig/tokenizer.zig
> +    try testTokenize("<<|=", &.{.angle_bracket_angle_bracket_left_pipe_equal});
just pushed a commit with updates to langref including precedence.  also added additional tokenization tests.

2021-09-09 21:23 UTC, travisstaloch commented
> Why do you think requiring an @intcast for the left-shift is a bad idea?

@matu3ba I was just trying to match the behavior of @shlWithSaturation which doesn't require Log2T, but accepts T.

2021-09-09 21:29 UTC, travisstaloch commented on src/Sema.zig
>      block: *Scope.Block,
> Why do you think requiring an @intcast for the left-shift is a bad idea?

@matu3ba I was just trying to match the behavior of @shlWithSaturation which doesn't require Log2T, but accepts T.

2021-09-09 21:39 UTC, travisstaloch commented
> Changing the behavior to allowing types on right hand side that are not Log2(left hand side) sounds to me inconsistent to the other `<<` operations and (from my perspective) can hide logical bugs without crashing/overflowing in tests if one is not cautious.

This is how [@shlWithSaturation](https://ziglang.org/documentation/master/#shlWithSaturation) is defined: 

> Unlike other @shl builtins, shift_amt doesn't need to be a Log2T as saturated overshifting is well defined.

2021-09-09 22:13 UTC, travisstaloch commented on src/Sema.zig
>      block: *Scope.Block,
also, this is how the [llvm intrinsics](https://llvm.org/docs/LangRef.html#llvm-sshl-sat-intrinsics) are defined

2021-09-10 23:15 UTC, travisstaloch commented
looks like i messed up during rebase. working on it.

2021-09-13 04:09 UTC, andrewrk requested changes
I have not fully looked at the review but I am about to go do something else so I wanted to give you something to work with in the meantime-

2021-09-13 04:09 UTC, andrewrk commented on src/AstGen.zig
> +        .bit_shift_left_sat => return binOpExt(gz, scope, rl, node, node_datas[node].lhs, node_datas[node].rhs, .shl_with_saturation, Zir.Inst.SaturatingArithmetic),
This does not look like it belongs here; it should go with other calls to `binOpExt`.

2021-09-13 04:09 UTC, andrewrk commented on test/behavior/saturating_arithmetic.zig
> +            .shl => @shlWithSaturation(a, b),
Don't forget to delete these now that we have actual syntax!

2021-09-15 01:59 UTC, travisstaloch commented on src/Sema.zig
> +    opt_extended: ?Zir.Inst.Extended.InstData,
> This does not happen for @shlWithSaturation. So I'm not sure why you are observing any such behavior.

I should have noted that I was only seeing this Log2T requirement with stage2 when testing my cbe code.  I don't think this is a requirement anymore. 

> I suggest to not try to re-use analyzeArithmetic. Case in point, the switch on zir_tag is missing the handling for the new extended ops, and if implemented will branch unnecessarily.

I have created an alternative code path: `Sema.analyzeSatArithmetic()`.  It is incomplete (lacking support for pointers and comptime arithmetic) but seems to be working.

I also feel better about the cbe shl methods.  I've tested that they return the same values as we do using `<<|` for the types i8, u8, i16, u16, i32, u32, i64, u64 in ReleaseFast (limiting shift amounts to Log2T).  Test files [here](https://zigbin.io/ddb34a)

2021-09-15 07:08 UTC, travisstaloch commented
[CI failure](https://dev.azure.com/ziglang/zig/_build/results?buildId=16815&view=logs&j=3e8797c7-5b0a-5f2c-07a4-1bc5e60a122e&t=e20ebee5-9d72-5103-f7c4-43227f669eab)

> del : Cannot remove item D:\a\1\s\sfx.exe: The process cannot access the file 'D:\a\1\s\sfx.exe' because it is being used by another process.

I'm confident this was just a glitch.  Last few commits have passed CI

2021-09-29 02:21 UTC, merged