Lang ref: Explain Zig Test and Containers
ziglang/zig pull request #9737
Opened 2021-09-11 11:54 UTC by paulespinosa

This commit updates the Language Reference to explain Zig's testing capabilities and the meaning of containers.

The result is located at the following URLs. They are the two main sections that are new.
https://paulespinosa.github.io/zig-langref/explain-zig-test-and-containers-01.html#Zig-Test
https://paulespinosa.github.io/zig-langref/explain-zig-test-and-containers-01.html#Containers

2021-09-12 05:45 UTC, paulespinosa commented
For the Zig Test section, I focus more on the language aspects of testing. However, since there aren't separate pages for more comprehensive documentation for each tool in Zig's toolchain, I can add more information and examples for the test specific command line arguments.

2021-09-15 07:52 UTC, paulespinosa commented
In the Zig Test section, I included information about the default test runner. There will be updates to the zig test tool and the Zig Test section can be updated when those changes are made (#6621, #5738, #1356).

2021-09-24 22:13 UTC, matu3ba requested changes
This is too long to review and has quite some redundant information that should better be links to the other sections.
Below are some essentials after taking quite abit time to read.

Given that tests use containers and containers are often used (without definition) in section "Variables", I would propose moving "Zig Test" after "Values". "Containers" should probably go before "Zig Test" leading to the following structure:

- Introduction
- Zig Standard Library
- Hello World
- Comments
- Values
- Containers
- Zig Test
- Variables

Also testing memory leaks belongs into the allocator section
Personally I think explaining each builtin is not feasible and "Detecting Test Build" takes alot space with explaining only a 1-line information.

Test Tool Documentation also has a typo for the command, which should be written as `zig test --help`.

2021-09-25 02:23 UTC, paulespinosa commented
Thank you @matu3ba! I had similar ideas about section re-organization. But, let's try your idea! I'll move this back to a draft pull request, work on the changes, then ping you when the changes are made.

2021-09-25 02:51 UTC, paulespinosa commented
I forgot to mention that some of the repetition is meant to help maintain focus and support learning. Linking too much might detract new learners focus from the section being read and ultimately lose the reader. So, I try (will try) to highlight the main point of the linked section. This also is done to support the reader's understanding of the linked section if it was already read. 

However, the repetition was noticed which means the balance was off. Again, thank you!

2021-09-25 09:47 UTC, matu3ba commented
> Thank you @matu3ba! I had similar ideas about section re-organization. But, let's try your idea! I'll move this back to a draft pull request, work on the changes, then ping you when the changes are made.

Its probably easier to create a new branch for this stuff, so that the review history is not cluttered.

2021-09-25 09:52 UTC, matu3ba commented
> I forgot to mention that some of the repetition is meant to help maintain focus and support learning.

The langref main goal is to work as quick reference for each section. The "hello world" is the exception, if you compare it to the rest of the reference.

From my perspective to learn (practically) ziglings and ziglearn should be used [as referenced in the language website](https://ziglang.org/learn/).

2021-09-29 09:29 UTC, paulespinosa commented
Change of plan: this pull request is being closed. A new pull request #9858 was created to focus on issue #8221. A new issue was created to request the container information to be added to the language reference #9857.

2021-09-29 09:29 UTC, closed without merging