Add Linux ioctl creation utilities
ziglang/zig pull request #9748
Opened 2021-09-12 21:02 UTC by Aransentin

Shamelessly stolen from @mattnite 's now closed #6443 pull request, this adds some utilities for constructing modern IOCTLs, and also uses them in `linux.zig` for some constants that were previously broken on mips, powerpc, and sparc.

From the ioctl manpages: 

> Ioctl command values are 32-bit constants.  In principle these constants are completely arbitrary, but people have tried to build some structure into them.

Therefore I have kept them as u32 values, and not as packed `Request` structures. There previous PR had also messed up the flags a little: `write` is 1 and `read` is 2, not the inverse.

2021-09-12 21:59 UTC, MasterQ32 commented
This is very nice, i needed this in the past quite often already.

2021-09-16 18:02 UTC, Vexu requested changes

2021-09-16 18:02 UTC, Vexu commented on lib/std/os/linux/ioctl.zig
> +const bits = switch (std.Target.current.cpu.arch) {
```suggestion
const bits = switch (@import("builtin").cpu.arch) {
```
`std.Target.current.cpu.arch` is deprecated #9321.

2021-09-16 18:02 UTC, Vexu commented on lib/std/os/linux/ioctl.zig
> +}
```suggestion
comptime {
    std.debug.assert(@bitSizeOf(Request) == 32);
}
```

2021-09-17 08:25 UTC, zigazeljko commented on lib/std/os/linux.zig
> +    pub const IOCGDEV = IOCTL.IOW('T', 0x32, c_uint);
```suggestion
    pub const IOCGDEV = IOCTL.IOR('T', 0x32, c_uint);
```

2021-09-18 06:56 UTC, merged