link: windows-gnu: look for Unix-style library names
ziglang/zig pull request #9771
Opened 2021-09-15 11:20 UTC by Kha

Zig already looks for MinGW-style import library names `lib${name}.dll.a`, so this feels only consistent and simplifies porting existing MinGW projects.

2021-09-15 14:46 UTC, rohlem commented
IIUC (and I might be uninformed), when both static library `.a` and dynamic import library `.dll.a` are present, this change will prioritize the static library, changing current behaviour.

Is that intentional/desirable? From the little I know, some licenses are more strict when statically linking.
Also unintentional dynamic linking (-> missing DLL) seems easier to spot than unintentional static linking (-> DLL shipped but unused).

2021-09-15 14:50 UTC, Kha commented
Well, I'd be happy to swap the two. But the current behavior is that first Windows-style `.lib` static libraries are search, which could reasonably be either "true" static libraries or import libraries, so the search order isn't clear to begin with.

2022-05-10 21:39 UTC, andrewrk requested changes
Needs a test.

Note also this relevant commit: ba127058d1fcf3ca042794244eee052915998b1a

These are supposed to be dynamic libraries in this for loop, not static libraries.

2022-05-10 21:40 UTC, andrewrk commented
Thanks for the patch. I am sorry I did not get around to reviewing it for many months.

I am closing this because it is not merge-ready and it is very old. However, you are welcome to open a new PR if you wish to continue this effort. I think you should first start with an issue to track the use case this is trying to address. This way if the PR is not merged (as in this one) the issue will persist.

2022-05-10 21:40 UTC, closed without merging