stage2: implement cImport
ziglang/zig pull request #9797
Opened 2021-09-19 09:03 UTC by Vexu

I have no idea if any of this works since I can't build stage2 with LLVM.

2021-09-19 13:25 UTC, g-w1 requested changes
If you want to build stage2 with llvm,
`make` or `ninja` should be sufficient to test this.

2021-09-19 13:25 UTC, g-w1 commented on src/Sema.zig
> +        const value = try sema.resolveConstString(block, src, extra.lhs);
```suggestion
        const value = try sema.resolveConstString(block, src, extra.rhs);
```

2021-09-19 17:06 UTC, g-w1 commented
cDefine("THING") does not work as it has 2 params here
https://github.com/ziglang/zig/blob/2a0c44fff3506cdc072d67374e7ffca495cebdc7/src/BuiltinFn.zig#L260-L264
It may need to be special cased in astgen

2021-09-19 17:18 UTC, Vexu commented
> cDefine("THING") does not work as it has 2 params here


It doesn't work in stage1 either:
https://github.com/ziglang/zig/blob/2a0c44fff3506cdc072d67374e7ffca495cebdc7/src/stage1/codegen.cpp#L9047

2021-09-19 19:48 UTC, g-w1 commented
Oh, sorry I was mistaken, I read the code wrong :(

2021-09-21 03:58 UTC, andrewrk commented
Got this error when running the behavior tests:

```
[nix-shell:~/dev/zig/build-release]$ ./zig-out/bin/zig test ../test/behavior.zig -fLLVM 
Segmentation fault at address 0x0
???:?:?: 0x7fa38740863d in ??? (???)
/home/andy/dev/zig/src/Module.zig:1586:17: 0x29315ae in Module.ErrorMsg.deinit (zig)
        gpa.free(err_msg.msg);
                ^
/home/andy/dev/zig/src/Module.zig:1583:24: 0x2931561 in Module.ErrorMsg.deinit (zig)
            note.deinit(gpa);
                       ^
/home/andy/dev/zig/src/Module.zig:1565:23: 0x2850cbc in Module.ErrorMsg.destroy (zig)
        err_msg.deinit(gpa);
                      ^
/home/andy/dev/zig/src/Module.zig:2331:22: 0x283d212 in Module.deinit (zig)
        value.destroy(gpa);
                     ^
/home/andy/dev/zig/src/Compilation.zig:1617:48: 0x2806b5b in Compilation.destroy (zig)
    if (optional_module) |module| module.deinit();
                                               ^
/home/andy/dev/zig/src/main.zig:2130:44: 0x2797732 in buildOutputType (zig)
    defer if (!comp_destroyed) comp.destroy();
                                           ^
/home/andy/dev/zig/src/main.zig:209:31: 0x2780286 in mainArgs (zig)
        return buildOutputType(gpa, arena, args, .zig_test);
                              ^
/home/andy/dev/zig/src/main.zig:158:20: 0x277f035 in main (zig)
    return mainArgs(gpa, arena, args);
                   ^
/home/andy/dev/zig/lib/std/start.zig:515:37: 0x2bd9a87 in std.start.callMain (zig)
            const result = root.main() catch |err| {
                                    ^
/home/andy/dev/zig/lib/std/start.zig:457:12: 0x2781ce7 in std.start.callMainWithArgs (zig)
    return @call(.{ .modifier = .always_inline }, callMain, .{});
           ^
/home/andy/dev/zig/lib/std/start.zig:422:12: 0x2781a92 in std.start.main (zig)
    return @call(.{ .modifier = .always_inline }, callMainWithArgs, .{ @intCast(usize, c_argc), c_argv, envp });
           ^
Aborted (core dumped)
```

I pushed a commit to the branch before merging to solve this (followed the pattern set by other messages with error notes).

2021-09-21 04:01 UTC, merged

2021-09-21 04:02 UTC, andrewrk commented
great work! so many new test cases passing :star2: 

> Still can't build stage2 with LLVM

hmmmmm do we need to get the C backend up to all behavior tests passing so that you can build stage2 and test the frontend without llvm? :)