FIX resize() for non u8 element types.
ziglang/zig pull request #9806
Opened 2021-09-20 18:09 UTC by colemanbroad

Looks like a simple typo that breaks `resize()` on slices of non u8 types?

Fixes, e.g. 

```zig
  var pts = try gpa.allocator.alloc(f32,100);
  pts = try gpa.allocator.resize(pts, pts.len+1);
```

2021-09-20 18:22 UTC, Vexu requested changes
Nice catch but needs a test so it doesn't regress again, `mem.zig` would probably be a good place to add one to.

2021-09-20 20:50 UTC, colemanbroad commented
OK, cool. Thanks for the review. I'll use `testing.allocator` I guess?

2021-09-21 16:29 UTC, colemanbroad commented
So the ziglang.zig check fails on Linux only. The log appears to show a problem with `zig fmt --check`. I tried with running code through `zig fmt`, but that doesn't seem to solve it. Now I'm stuck ;)

2021-09-21 18:47 UTC, colemanbroad commented
OK, That's probably the issue. I'm using `0.8.1`. Is there an easy way to format with latest? Or should I bite the bullet and build from source?

2021-09-22 09:09 UTC, merged