Stage1: Add Visibility field to ExportOptions.
ziglang/zig pull request #9831
Opened 2021-09-24 02:47 UTC by mathetake

Part of https://github.com/ziglang/zig/issues/9762. This PR adds `Visibility` field to `builtin.ExportOptions` in order to allow users to control the visibility of exports.

At least this is already verified to work in my local, and will do the follow up on; 1) change the default visibility of compiler_rt and libc symbols, 2) add a flag for controlling the default visibility (just like `-fvisibility` flag), and 3) support in stage 2.

Signed-off-by: Takeshi Yoneda <takeshi@tetrate.io>

2021-09-24 04:56 UTC, Vexu commented on lib/std/builtin.zig
> +    Default,
New enums should be `snake_case`.

2022-02-14 12:12 UTC, Vexu approved these changes

2022-05-10 23:32 UTC, andrewrk requested changes
```
$ valgrind ./zig test ../test/behavior.zig -target powerpc-linux-musl -lc -I../test
==2828778== Invalid read of size 1
==2828778==    at 0x6EA0265: LLVMSetVisibility (in /home/andy/Downloads/zig/build/zig)
==2828778==    by 0x1BCE60B: do_code_gen(CodeGen*) (codegen.cpp:9031)
==2828778==    by 0x1BD51E2: codegen_build_object(CodeGen*) (codegen.cpp:10610)
==2828778==    by 0x1BA5C17: zig_stage1_build_object (stage1.cpp:132)
==2828778==    by 0xE61E24: Module.build_object (stage1.zig:149)
==2828778==    by 0xC3D4CE: Compilation.updateStage1Module (Compilation.zig:5025)
==2828778==    by 0xC3117E: Compilation.performAllTheWork (Compilation.zig:2691)
==2828778==    by 0xC2A3ED: Compilation.update (Compilation.zig:2098)
==2828778==    by 0xBB9D1F: main.updateModule (main.zig:3104)
==2828778==    by 0xB16B75: main.buildOutputType (main.zig:2793)
==2828778==    by 0xAD0526: main.mainArgs (main.zig:225)
==2828778==    by 0xACFCB9: main (stage1.zig:48)
```

2022-05-11 02:04 UTC, merged

2022-05-11 02:26 UTC, mathetake commented
@andrewrk thank you so much for taking this over... (completely forgot about it...)! 🙇

2022-05-11 02:39 UTC, andrewrk commented
No problem. In case you missed it, I had to back out the stage1 changes due to the unsolved memory error above. However the self-hosted compiler still contains the improvement, and the self-hosted compiler is what we will ship with the upcoming Zig release (0.10.0).

2022-05-11 02:43 UTC, mathetake commented
>  the self-hosted compiler is what we will ship with the upcoming Zig release (0.10.0).

ah i see... sounds nice!