stage2: implement ** at runtime
ziglang/zig pull request #9876
Opened 2021-10-01 02:26 UTC by g-w1

2021-10-03 00:01 UTC, g-w1 commented on src/Sema.zig
> +    const ptr_to_rhs = if (!is_pointer) try sema.analyzeRef(block, rhs_src, rhs) else rhs;
Do I have to copy one of these into sema.arena if it is comptime known?
I get invalid int values inside the air array.
![image](https://user-images.githubusercontent.com/58830309/135734813-c8767636-5fd4-4ca5-a68f-d67b2fe865d2.png)

2021-10-03 00:30 UTC, g-w1 commented on src/Sema.zig
> +    const ptr_to_rhs = if (!is_pointer) try sema.analyzeRef(block, rhs_src, rhs) else rhs;
I put in some code to handle it, and its still there ...

2021-10-03 02:05 UTC, andrewrk requested changes
In your crash screenshot, the Value object that has a bad memory reference is coming from a Decl's Value. Check the Decl name in a debugger and figure out why that Decl's Value is invalid.

2021-10-03 13:25 UTC, g-w1 commented
I stubbed the case that causes the uaf out as a TODO for now as it is confusing me.

2021-10-23 00:29 UTC, g-w1 commented
Ok, marking as draft as memset with bitcast is being weird in llvm backend.

2022-01-08 06:23 UTC, andrewrk commented
30+ days old draft; closing.

2022-01-08 06:23 UTC, closed without merging